-- agentic-labs/erp-bench scenario 2243: Car Frame Platform 4000kg
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5D4587CA6_c01','Nexus Studios North','customer',0,185267.15,NULL,NULL,'orders@nexusstudiosnorth.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5D4587CA6_c02','Grove Publishing','customer',0,126377.48,NULL,NULL,'orders@grovepublishing.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5D4587CA6_c03','Matrix Creative','customer',0,130149.56,NULL,NULL,'orders@matrixcreative.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5D4587CA6_c04','Vertex Arena','customer',0,127313.07,NULL,NULL,'orders@vertexarena.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5D4587CA6_c05','Axis Pavilion','customer',0,134264.36,NULL,NULL,'orders@axispavilion.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5D4587CA6_c06','Pinnacle Works','customer',0,117507.35,NULL,NULL,'orders@pinnacleworks.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5D4587CA6_c07','Thornton Studios East','customer',0,214245.06,NULL,NULL,'orders@thorntonstudioseast.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5D4587CA6_c08','Alloy Practice','customer',0,158559.91,NULL,NULL,'orders@alloypractice.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5D4587CA6_c09','Copper Conservatory','customer',0,191768.26,NULL,NULL,'orders@copperconservatory.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p01','Millbrook Services Site Logistics','customer',0,NULL,NULL,NULL,'contact@millbrookservices.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p02','Spire Operations HQ Procurement','customer',0,NULL,NULL,NULL,'contact@spireoperations.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p03','Pivot Operations Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@pivotoperations.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p04','Indigo Manufacturing HQ Procurement','customer',0,NULL,NULL,NULL,'contact@indigomanufacturing.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p05','Noble Services Quality Lab','customer',0,NULL,NULL,NULL,'contact@nobleservices.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p06','Circuit Services Test Facility','customer',0,NULL,NULL,NULL,'contact@circuitservices.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p07','Cascade Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@cascadeassembly.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p08','Baseline Production Tooling Center','customer',0,NULL,NULL,NULL,'contact@baselineproduction.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p09','Baltic Operations Test Facility','customer',0,NULL,NULL,NULL,'contact@balticoperations.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p10','Marble Fabrication Quality Lab','customer',0,NULL,NULL,NULL,'contact@marblefabrication.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p11','Quartz Fabrication Test Facility','customer',0,NULL,NULL,NULL,'contact@quartzfabrication.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p12','Lakewood Operations Field Ops','customer',0,NULL,NULL,NULL,'contact@lakewoodoperations.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p13','Onyx Solutions Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@onyxsolutions.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p14','Spark Manufacturing Tooling Center','customer',0,NULL,NULL,NULL,'contact@sparkmanufacturing.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p15','Osprey Engineering Quality Lab','customer',0,NULL,NULL,NULL,'contact@ospreyengineering.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p16','Orbital Production Tooling Center','customer',0,NULL,NULL,NULL,'contact@orbitalproduction.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p17','Skyline Engineering Field Ops','customer',0,NULL,NULL,NULL,'contact@skylineengineering.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p18','Sentinel Assembly HQ Procurement','customer',0,NULL,NULL,NULL,'contact@sentinelassembly.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p19','Cosmo Production Prototype Shop','customer',0,NULL,NULL,NULL,'contact@cosmoproduction.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p20','Westfield Industries Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@westfieldindustries.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p21','Gateway Operations HQ Procurement','customer',0,NULL,NULL,NULL,'contact@gatewayoperations.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p22','Hartland Solutions Prototype Shop','customer',0,NULL,NULL,NULL,'contact@hartlandsolutions.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p23','Stonewall Services Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@stonewallservices.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p24','Lumen Technologies R&D Workshop','customer',0,NULL,NULL,NULL,'contact@lumentechnologies.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p25','Catalyst Engineering Site Logistics','customer',0,NULL,NULL,NULL,'contact@catalystengineering.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p26','Trellis Operations Prototype Shop','customer',0,NULL,NULL,NULL,'contact@trellisoperations.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p27','Helix Solutions Prototype Shop','customer',0,NULL,NULL,NULL,'contact@helixsolutions.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p28','Keystone Services Tooling Center','customer',0,NULL,NULL,NULL,'contact@keystoneservices.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p29','Conduit Services Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@conduitservices.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p30','Ridgeline Industries Site Logistics','customer',0,NULL,NULL,NULL,'contact@ridgelineindustries.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p31','Opal Technologies R&D Workshop','customer',0,NULL,NULL,NULL,'contact@opaltechnologies.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p32','Jade Production Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@jadeproduction.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p33','Redstone Industries R&D Workshop','customer',0,NULL,NULL,NULL,'contact@redstoneindustries.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p34','Aegis Technologies R&D Workshop','customer',0,NULL,NULL,NULL,'contact@aegistechnologies.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p35','Canton Technologies HQ Procurement','customer',0,NULL,NULL,NULL,'contact@cantontechnologies.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p36','Anvil Services HQ Procurement','customer',0,NULL,NULL,NULL,'contact@anvilservices.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p37','Raven Solutions Prototype Shop','customer',0,NULL,NULL,NULL,'contact@ravensolutions.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p38','Lance Technologies Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@lancetechnologies.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p39','Apex Industries Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@apexindustries.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p40','Peak Solutions Prototype Shop','customer',0,NULL,NULL,NULL,'contact@peaksolutions.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p41','Bronze Assembly Field Ops','customer',0,NULL,NULL,NULL,'contact@bronzeassembly.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p42','Borough Manufacturing Site Logistics','customer',0,NULL,NULL,NULL,'contact@boroughmanufacturing.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p43','Cobalt Solutions Site Logistics','customer',0,NULL,NULL,NULL,'contact@cobaltsolutions.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p44','Cardinal Fabrication Site Logistics','customer',0,NULL,NULL,NULL,'contact@cardinalfabrication.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p45','Sapphire Engineering Site Logistics','customer',0,NULL,NULL,NULL,'contact@sapphireengineering.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p46','Ember Production Field Ops','customer',0,NULL,NULL,NULL,'contact@emberproduction.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p47','Arc Manufacturing Site Logistics','customer',0,NULL,NULL,NULL,'contact@arcmanufacturing.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p48','Eclipse Services Field Ops','customer',0,NULL,NULL,NULL,'contact@eclipseservices.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p49','Flux Fabrication Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@fluxfabrication.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rD3F8D563B4_p50','Haven Manufacturing R&D Workshop','customer',0,NULL,NULL,NULL,'contact@havenmanufacturing.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5D4587CA6_q01','Ironside Distributors','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5D4587CA6_q02','Oxide Shipping','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5D4587CA6_q03','Sterling Holdings','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5D4587CA6_q04','Quantum Networks','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5D4587CA6_q05','Citadel Logistics','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5D4587CA6_q06','Prism Conveyance','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5D4587CA6_q07','Silverline Sourcing','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5D4587CA6_q08','Riverdale Forwarders','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5D4587CA6_q09','Oakmont Materials','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5D4587CA6_q10','Ledger Microfactory','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5D4587CA6_q11','Brookfield Solutions','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5D4587CA6_q12','Crest Wholesalers','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5D4587CA6_q13','Coral Components','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5D4587CA6_q14','Mosaic Transit','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5D4587CA6_q15','Beacon Partners','vendor',15,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5D4587CA6_q16','Ivory Resources','vendor',16,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5D4587CA6_q17','Aether Packagers','vendor',17,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5D4587CA6_q18','Monarch Warehousing','vendor',18,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5D4587CA6_q19','Northbridge Carriers','vendor',19,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q01','Stratos Resources','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q02','Titan Supply','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q03','Bridgeway Procurement','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q04','Nimbus Supply','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q05','Sierra Networks','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q06','Garnet Resources','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q07','Echo Resources','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q08','Metro Networks','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q09','Clearwater Supply','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q10','Aurora Materials','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q11','Bayshore Supply','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q12','Evergreen Components','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q13','Iron Networks','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q14','Cipher Components','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q15','Polar Parts Co','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q16','Trident Distribution','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q17','Ridge Resources','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q18','Slate Distribution','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q19','Chrome Resources','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q20','Crestview Components','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q21','Ironwood Components','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q22','Horizon Components','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q23','Solace Freight','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q24','Globe Wholesale','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q25','Flint Carriers','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q26','Ashford Components','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q27','Arbor Logistics','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q28','Forge Freight','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q29','Zenith Transit','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q30','Comet Transit','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q31','Vantage Supply','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q32','Granite Freight','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q33','Summit Materials','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q34','Arrow Transit','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q35','Dune Procurement','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q36','Cedar Distribution','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q37','Pacific Supply','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q38','Element Networks','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q39','Drift Supply','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q40','Compass Sourcing','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q41','Alpine Components','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q42','Scion Networks','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q43','Terra Sourcing','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q44','Meridian Transit','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q45','Atlas Procurement','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q46','Equinox Logistics','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q47','Fairview Freight','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q48','Blaze Carriers','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q49','Spectra Logistics','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rD3F8D563B4_q50','Crown Logistics','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5D4587CA6-ELV-CFP-400','Car Frame Platform 4000kg','Building Systems','consu',8053.3,4910.45,'buy,manufacture',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'PE5D4587CA6-ELV-CFP-400','rE5D4587CA6_q01','Priority Shuttle lane (9d transit, 6-6 units)',9,6.0,6.0,4757.93);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'PE5D4587CA6-ELV-CFP-400','rE5D4587CA6_q02','Express Air lane (7d transit, 2-2 units)',7,2.0,2.0,7574.8);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'PE5D4587CA6-ELV-CFP-400','rE5D4587CA6_q03','Bulk Container lane (22d transit, 81-81 units)',22,81.0,81.0,2846.17);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'PE5D4587CA6-ELV-CFP-400','rE5D4587CA6_q04','Hybrid Expedite lane (9d transit, 4-4 units)',9,4.0,4.0,6424.18);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'PE5D4587CA6-ELV-CFP-400','rE5D4587CA6_q05','Bulk Container lane (25d transit, 81-81 units)',25,81.0,81.0,2479.81);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5D4587CA6-SUB-02','Car Frame Platform 4000kg Subassembly','Building Systems','consu',2254.92,1483.32,'manufacture',NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5D4587CA6-ELV-COP-021','Car Operating Panel Faceplate','Building Systems','consu',462.12,283.64,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'PE5D4587CA6-ELV-COP-021','rE5D4587CA6_q06','Rapid Works (3d)',3,4.0,7.0,321.8);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'PE5D4587CA6-ELV-COP-021','rE5D4587CA6_q07','Domestic Supply (6d)',6,13.0,80.0,283.64);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'PE5D4587CA6-ELV-COP-021','rE5D4587CA6_q08','Hybrid Fabricators (6d)',6,13.0,78.0,288.89);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5D4587CA6-ELV-SIL-024','Landing Sill Threshold Plate','Building Systems','consu',127.55,59.26,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'PE5D4587CA6-ELV-SIL-024','rE5D4587CA6_q09','Rapid Works (2d)',2,5.0,18.0,92.69);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'PE5D4587CA6-ELV-SIL-024','rE5D4587CA6_q10','Hybrid Fabricators (6d)',6,18.0,71.0,79.89);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'PE5D4587CA6-ELV-SIL-024','rE5D4587CA6_q11','Import Consolidator (6d)',6,24.0,59.0,59.26);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'PE5D4587CA6-ELV-SIL-024','rE5D4587CA6_q12','Domestic Supply (6d)',6,14.0,28.0,73.67);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5D4587CA6-ELV-BUF-016','Pit Buffer Spring Assembly','Building Systems','consu',335.97,193.44,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'PE5D4587CA6-ELV-BUF-016','rE5D4587CA6_q13','Rapid Works (4d)',4,8.0,12.0,241.72);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'PE5D4587CA6-ELV-BUF-016','rE5D4587CA6_q14','Import Consolidator (4d)',4,36.0,74.0,193.44);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'PE5D4587CA6-ELV-BUF-016','rE5D4587CA6_q15','Domestic Supply (4d)',4,21.0,148.0,204.64);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5D4587CA6-ELV-PCB-018','Main Controller PCB Board','Building Systems','consu',1728.13,928.2,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'PE5D4587CA6-ELV-PCB-018','rE5D4587CA6_q16','Rapid Works (2d)',2,9.0,46.0,1293.21);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'PE5D4587CA6-ELV-PCB-018','rE5D4587CA6_q17','Domestic Supply (4d)',4,23.0,66.0,1025.13);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'PE5D4587CA6-ELV-PCB-018','rE5D4587CA6_q18','Hybrid Fabricators (4d)',4,9.0,24.0,1033.52);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'PE5D4587CA6-ELV-PCB-018','rE5D4587CA6_q19','Import Consolidator (4d)',4,29.0,49.0,928.2);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A001','High-Performance Governor Assembly','Seals and Gaskets','consu',215.38,139.23,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'PD3F8D563B4-A001','rD3F8D563B4_q01','Express route',4,1.0,24.0,136.64);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A002','Self-Lubricating Electromagnetic Guide Shoe','Power Transmission','consu',297.2,196.05,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'PD3F8D563B4-A002','rD3F8D563B4_q02','Cross-dock',8,1.0,24.0,193.4);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A003','Dual-Stage Drive Kit','Power Transmission','consu',298.72,191.76,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'PD3F8D563B4-A003','rD3F8D563B4_q03','Warehouse direct',8,1.0,24.0,191.05);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A004','UV-Stable Governor Assembly','Industrial Spare Parts','consu',314.31,169.61,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'PD3F8D563B4-A004','rD3F8D563B4_q04','Local pickup',6,1.0,24.0,173.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A005','Powder-Coated Governor Assembly','Replacement Parts','consu',354.8,236.08,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'PD3F8D563B4-A005','rD3F8D563B4_q05','Scheduled freight',4,1.0,24.0,228.17);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A006','Stainless Overspeed Governor Assembly','Fasteners and Fixings','consu',257.22,151.31,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'PD3F8D563B4-A006','rD3F8D563B4_q06','Express route',8,1.0,24.0,161.93);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A007','Adjustable Deflector Sheave Assembly','Replacement Parts','consu',237.59,132.56,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'PD3F8D563B4-A007','rD3F8D563B4_q07','Warehouse direct',7,1.0,24.0,136.44);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A008','Wide-Body Door Panel Stainless','Seals and Gaskets','consu',256.28,144.6,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'PD3F8D563B4-A008','rD3F8D563B4_q08','Bulk shipment',4,1.0,24.0,142.56);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A009','Hardened Push Button Module','Pneumatic Components','consu',359.31,211.23,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'PD3F8D563B4-A009','rD3F8D563B4_q09','Cross-dock',6,1.0,24.0,205.16);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A010','Quick-Release Governor Assembly','Replacement Parts','consu',330.82,184.68,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'PD3F8D563B4-A010','rD3F8D563B4_q10','Bulk shipment',6,1.0,24.0,195.12);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A011','Pressure-Balanced Traction Motor','Mechanical Components','consu',202.97,121.12,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'PD3F8D563B4-A011','rD3F8D563B4_q11','Regional lane',4,1.0,24.0,128.36);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A012','Low-Profile Rope Set 12mm','Maintenance Supplies','consu',390.68,244.58,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'PD3F8D563B4-A012','rD3F8D563B4_q12','Bulk shipment',6,1.0,24.0,241.63);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A013','Low-Temp Button Module','Industrial Spare Parts','consu',299.44,162.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'PD3F8D563B4-A013','rD3F8D563B4_q13','Warehouse direct',4,1.0,24.0,168.08);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A014','High-Temp Gearless Traction Motor','Replacement Parts','consu',241.4,141.34,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'PD3F8D563B4-A014','rD3F8D563B4_q14','Local pickup',7,1.0,24.0,138.86);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A015','Economy Panel Stainless','Maintenance Supplies','consu',361.07,246.91,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'PD3F8D563B4-A015','rD3F8D563B4_q15','Cross-dock',3,1.0,24.0,243.95);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A016','Low-Noise Inspection Box','Replacement Parts','consu',389.05,233.29,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'PD3F8D563B4-A016','rD3F8D563B4_q16','Bulk shipment',3,1.0,24.0,228.7);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A017','Compact LED Ceiling Panel','Seals and Gaskets','consu',300.9,199.57,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'PD3F8D563B4-A017','rD3F8D563B4_q17','Scheduled freight',3,1.0,24.0,210.5);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A018','Anodized Rope Set 12mm','Fasteners and Fixings','consu',330.41,211.94,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'PD3F8D563B4-A018','rD3F8D563B4_q18','Local pickup',4,1.0,24.0,228.12);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A019','Extended-Life Panel Stainless','Seals and Gaskets','consu',376.68,197.0,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'PD3F8D563B4-A019','rD3F8D563B4_q19','Local pickup',8,1.0,24.0,211.94);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A020','Sealed Deflector Sheave Assembly','Seals and Gaskets','consu',366.8,212.29,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'PD3F8D563B4-A020','rD3F8D563B4_q20','Scheduled freight',5,1.0,24.0,205.79);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A021','Medical-Grade Rope Set 12mm','Seals and Gaskets','consu',290.23,202.93,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'PD3F8D563B4-A021','rD3F8D563B4_q21','Scheduled freight',4,1.0,24.0,206.16);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A022','Commercial Top Inspection Box','Hardware Accessories','consu',186.8,98.75,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'PD3F8D563B4-A022','rD3F8D563B4_q22','Warehouse direct',5,1.0,24.0,104.08);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A023','Heat-Treated Drive Kit','Industrial Spare Parts','consu',264.07,179.62,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'PD3F8D563B4-A023','rD3F8D563B4_q23','Local pickup',4,1.0,24.0,193.78);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A024','Universal Gearless Traction Motor','Power Transmission','consu',414.52,269.41,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'PD3F8D563B4-A024','rD3F8D563B4_q24','Scheduled freight',3,1.0,24.0,278.53);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A025','Reinforced Top Inspection Box','Replacement Parts','consu',348.22,218.49,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'PD3F8D563B4-A025','rD3F8D563B4_q25','Warehouse direct',8,1.0,24.0,232.87);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A026','Flanged Push Button Module','Hardware Accessories','consu',272.92,177.77,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'PD3F8D563B4-A026','rD3F8D563B4_q26','Local pickup',8,1.0,24.0,185.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A027','Lightweight Rope Set 12mm','Replacement Parts','consu',415.74,298.92,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'PD3F8D563B4-A027','rD3F8D563B4_q27','Express route',4,1.0,24.0,290.51);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A028','Low-Flow Electromagnetic Guide Shoe','Maintenance Supplies','consu',263.26,183.6,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'PD3F8D563B4-A028','rD3F8D563B4_q28','Cross-dock',8,1.0,24.0,193.69);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A029','High-Torque Rope Set 12mm','Electrical Components','consu',320.79,175.75,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'PD3F8D563B4-A029','rD3F8D563B4_q29','Regional lane',6,1.0,24.0,178.74);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A030','Modular Gear Set','Fasteners and Fixings','consu',316.05,167.43,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'PD3F8D563B4-A030','rD3F8D563B4_q30','Regional lane',4,1.0,24.0,177.21);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A031','High-Flow Top Inspection Box','Fasteners and Fixings','consu',396.0,275.2,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'PD3F8D563B4-A031','rD3F8D563B4_q31','Regional lane',8,1.0,24.0,296.78);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A032','Industrial Overspeed Governor Assembly','Mechanical Components','consu',287.93,155.5,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'PD3F8D563B4-A032','rD3F8D563B4_q32','Bulk shipment',5,1.0,24.0,151.26);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A033','Snap-Fit Button Module','Mechanical Components','consu',327.92,224.8,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'PD3F8D563B4-A033','rD3F8D563B4_q33','Bulk shipment',8,1.0,24.0,218.04);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A034','Tapered Electromagnetic Guide Shoe','Electrical Components','consu',215.07,116.89,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'PD3F8D563B4-A034','rD3F8D563B4_q34','Scheduled freight',7,1.0,24.0,120.27);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A035','Standard Electromagnetic Guide Shoe','Fasteners and Fixings','consu',304.23,210.45,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'PD3F8D563B4-A035','rD3F8D563B4_q35','Warehouse direct',8,1.0,24.0,225.12);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A036','Premium Drive Kit','Hardware Accessories','consu',360.93,189.51,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'PD3F8D563B4-A036','rD3F8D563B4_q36','Standard delivery',5,1.0,24.0,189.15);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A037','Impact-Rated Guide Shoe','Replacement Parts','consu',381.18,251.55,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'PD3F8D563B4-A037','rD3F8D563B4_q37','Regional lane',6,1.0,24.0,254.34);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A038','Metric Governor Assembly','Hardware Accessories','consu',262.6,156.0,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(57,'PD3F8D563B4-A038','rD3F8D563B4_q38','Express route',4,1.0,24.0,162.6);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A039','Thermal-Guard Traction Motor','Fasteners and Fixings','consu',332.2,223.25,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(58,'PD3F8D563B4-A039','rD3F8D563B4_q39','Regional lane',6,1.0,24.0,236.3);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A040','Low-Friction Rope Set 12mm','Replacement Parts','consu',378.76,237.63,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(59,'PD3F8D563B4-A040','rD3F8D563B4_q40','Bulk shipment',5,1.0,24.0,244.29);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A041','Double-Row Belt Drive Kit','Pneumatic Components','consu',387.41,205.79,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(60,'PD3F8D563B4-A041','rD3F8D563B4_q41','Regional lane',3,1.0,24.0,213.89);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A042','Cleanroom Sheave Assembly','Replacement Parts','consu',312.51,212.27,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(61,'PD3F8D563B4-A042','rD3F8D563B4_q42','Warehouse direct',5,1.0,24.0,226.61);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A043','Single-Stage Belt Drive Kit','Maintenance Supplies','consu',242.47,150.08,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(62,'PD3F8D563B4-A043','rD3F8D563B4_q43','Warehouse direct',6,1.0,24.0,147.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A044','Cold-Rolled Panel Stainless','Hardware Accessories','consu',290.71,197.82,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(63,'PD3F8D563B4-A044','rD3F8D563B4_q44','Warehouse direct',7,1.0,24.0,206.04);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A045','High-Cycle Sheave Assembly','Industrial Spare Parts','consu',325.12,186.33,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(64,'PD3F8D563B4-A045','rD3F8D563B4_q45','Cross-dock',7,1.0,24.0,200.78);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A046','Precision Rope Set 12mm','Mechanical Components','consu',361.27,227.17,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(65,'PD3F8D563B4-A046','rD3F8D563B4_q46','Scheduled freight',6,1.0,24.0,237.94);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A047','Zero-Backlash Door Panel Stainless','Hardware Accessories','consu',377.95,249.87,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(66,'PD3F8D563B4-A047','rD3F8D563B4_q47','Regional lane',3,1.0,24.0,250.91);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A048','Non-Magnetic Governor Assembly','Mechanical Components','consu',315.24,169.94,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(67,'PD3F8D563B4-A048','rD3F8D563B4_q48','Regional lane',5,1.0,24.0,180.89);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A049','Narrow-Body Deflector Sheave Assembly','Power Transmission','consu',397.23,212.02,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(68,'PD3F8D563B4-A049','rD3F8D563B4_q49','Cross-dock',3,1.0,24.0,205.78);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PD3F8D563B4-A050','Anti-Vibration Shaft Encoder','Power Transmission','consu',304.74,164.34,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(69,'PD3F8D563B4-A050','rD3F8D563B4_q50','Local pickup',8,1.0,24.0,156.9);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'PE5D4587CA6-SUB-02','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PE5D4587CA6-ELV-BUF-016',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PE5D4587CA6-ELV-PCB-018',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'PE5D4587CA6-ELV-CFP-400','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PE5D4587CA6-SUB-02',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PE5D4587CA6-ELV-COP-021',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PE5D4587CA6-ELV-SIL-024',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'PD3F8D563B4-A014','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'PD3F8D563B4-A006',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'PD3F8D563B4-A041','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'PD3F8D563B4-A019',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'PD3F8D563B4-A013',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'PD3F8D563B4-A006','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'PD3F8D563B4-A043',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'PD3F8D563B4-A003',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'PD3F8D563B4-A046','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'PD3F8D563B4-A019',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'PD3F8D563B4-A015','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'PD3F8D563B4-A031',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'PD3F8D563B4-A003',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'PD3F8D563B4-A047','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'PD3F8D563B4-A026',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'PD3F8D563B4-A028',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'PD3F8D563B4-A035','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'PD3F8D563B4-A045',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'PD3F8D563B4-A008','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'PD3F8D563B4-A043',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(11,'PD3F8D563B4-A020','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'PD3F8D563B4-A028',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(12,'PD3F8D563B4-A040','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(12,'PD3F8D563B4-A044',3.0);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PE5D4587CA6-WC02','Fabrication Cell 2',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PE5D4587CA6-WC03','Precision Bench 3',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PE5D4587CA6-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PE5D4587CA6-WC03','Precision Bench 3',0,0,NULL,NULL);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5D4587CA6-ELV-BUF-016',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5D4587CA6-ELV-CFP-400',NULL,70.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5D4587CA6-ELV-COP-021',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5D4587CA6-ELV-PCB-018',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5D4587CA6-ELV-SIL-024',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A001',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A002',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A003',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A004',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A005',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A006',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A007',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A008',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A009',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A010',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A011',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A012',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A013',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A014',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A015',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A016',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A017',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A018',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A019',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A020',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A021',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A022',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A023',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A024',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A025',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A026',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A027',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A028',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A029',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A030',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A031',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A032',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A033',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A034',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A035',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A036',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A037',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A038',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A039',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A040',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A041',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A042',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A043',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A044',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A045',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A046',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A047',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A048',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A049',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PD3F8D563B4-A050',NULL,8.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'rE5D4587CA6_c01','PE5D4587CA6-ELV-CFP-400',22,8,185267.15,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'rE5D4587CA6_c02','PE5D4587CA6-ELV-CFP-400',15,8,126377.48,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'rE5D4587CA6_c03','PE5D4587CA6-ELV-CFP-400',15,9,130149.56,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'rE5D4587CA6_c04','PE5D4587CA6-ELV-CFP-400',15,9,127313.07,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'rE5D4587CA6_c05','PE5D4587CA6-ELV-CFP-400',16,10,134264.36,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'rE5D4587CA6_c06','PE5D4587CA6-ELV-CFP-400',14,10,117507.35,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'rE5D4587CA6_c07','PE5D4587CA6-ELV-CFP-400',24,11,214245.06,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'rE5D4587CA6_c08','PE5D4587CA6-ELV-CFP-400',19,11,158559.91,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(9,'rE5D4587CA6_c09','PE5D4587CA6-ELV-CFP-400',22,13,191768.26,NULL);
