-- agentic-labs/erp-bench scenario 2223: Laser Safety Curtain System
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r83DC4C8D23_c01','Prism Solutions Group','customer',0,43893.63,NULL,NULL,'orders@prismsolutionsgroup.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r83DC4C8D23_c02','Helix Practice','customer',0,49005.94,NULL,NULL,'orders@helixpractice.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r83DC4C8D23_c03','Coral Productions','customer',0,53782.39,NULL,NULL,'orders@coralproductions.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r83DC4C8D23_c04','Alpine Fabricators','customer',0,43734.14,NULL,NULL,'orders@alpinefabricators.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r83DC4C8D23_c05','Orbital Guild','customer',0,43488.55,NULL,NULL,'orders@orbitalguild.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r83DC4C8D23_c06','Blaze Academy','customer',0,57621.58,NULL,NULL,'orders@blazeacademy.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r83DC4C8D23_c07','Globe Studios South','customer',0,55256.71,NULL,NULL,'orders@globestudiossouth.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r83DC4C8D23_c08','Pacific Conservatory','customer',0,76090.95,NULL,NULL,'orders@pacificconservatory.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p01','Chrome Manufacturing Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@chromemanufacturing.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p02','Cascade Assembly Site Logistics','customer',0,NULL,NULL,NULL,'contact@cascadeassembly.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p03','Stonewall Engineering HQ Procurement','customer',0,NULL,NULL,NULL,'contact@stonewallengineering.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p04','Lattice Services Site Logistics','customer',0,NULL,NULL,NULL,'contact@latticeservices.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p05','Element Solutions Tooling Center','customer',0,NULL,NULL,NULL,'contact@elementsolutions.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p06','Lakewood Production Test Facility','customer',0,NULL,NULL,NULL,'contact@lakewoodproduction.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p07','Lumen Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@lumenassembly.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p08','Dune Industries Test Facility','customer',0,NULL,NULL,NULL,'contact@duneindustries.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p09','Pinnacle Manufacturing Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@pinnaclemanufacturing.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p10','Spark Assembly HQ Procurement','customer',0,NULL,NULL,NULL,'contact@sparkassembly.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p11','Alloy Engineering Field Ops','customer',0,NULL,NULL,NULL,'contact@alloyengineering.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p12','Forge Fabrication Quality Lab','customer',0,NULL,NULL,NULL,'contact@forgefabrication.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p13','Polar Technologies Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@polartechnologies.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p14','Anvil Manufacturing Quality Lab','customer',0,NULL,NULL,NULL,'contact@anvilmanufacturing.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p15','Catalyst Operations Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@catalystoperations.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p16','Thornton Technologies Site Logistics','customer',0,NULL,NULL,NULL,'contact@thorntontechnologies.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p17','Meridian Solutions Site Logistics','customer',0,NULL,NULL,NULL,'contact@meridiansolutions.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p18','Aegis Solutions Test Facility','customer',0,NULL,NULL,NULL,'contact@aegissolutions.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p19','Borough Manufacturing Prototype Shop','customer',0,NULL,NULL,NULL,'contact@boroughmanufacturing.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p20','Sapphire Assembly Tooling Center','customer',0,NULL,NULL,NULL,'contact@sapphireassembly.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p21','Nimbus Solutions Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@nimbussolutions.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p22','Summit Engineering HQ Procurement','customer',0,NULL,NULL,NULL,'contact@summitengineering.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p23','Millbrook Engineering Field Ops','customer',0,NULL,NULL,NULL,'contact@millbrookengineering.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p24','Onyx Production Test Facility','customer',0,NULL,NULL,NULL,'contact@onyxproduction.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p25','Spire Manufacturing R&D Workshop','customer',0,NULL,NULL,NULL,'contact@spiremanufacturing.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p26','Raven Manufacturing Field Ops','customer',0,NULL,NULL,NULL,'contact@ravenmanufacturing.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p27','Cedar Manufacturing Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@cedarmanufacturing.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p28','Garnet Services R&D Workshop','customer',0,NULL,NULL,NULL,'contact@garnetservices.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p29','Haven Operations Prototype Shop','customer',0,NULL,NULL,NULL,'contact@havenoperations.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p30','Evergreen Production Test Facility','customer',0,NULL,NULL,NULL,'contact@evergreenproduction.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p31','Fairview Engineering R&D Workshop','customer',0,NULL,NULL,NULL,'contact@fairviewengineering.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p32','Ivory Manufacturing HQ Procurement','customer',0,NULL,NULL,NULL,'contact@ivorymanufacturing.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p33','Iron Fabrication Tooling Center','customer',0,NULL,NULL,NULL,'contact@ironfabrication.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p34','Axis Industries Tooling Center','customer',0,NULL,NULL,NULL,'contact@axisindustries.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p35','Nexus Technologies Quality Lab','customer',0,NULL,NULL,NULL,'contact@nexustechnologies.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p36','Stratos Operations Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@stratosoperations.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p37','Crestview Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@crestviewassembly.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p38','Noble Engineering Quality Lab','customer',0,NULL,NULL,NULL,'contact@nobleengineering.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p39','Aether Engineering Test Facility','customer',0,NULL,NULL,NULL,'contact@aetherengineering.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p40','Apex Assembly Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@apexassembly.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p41','Comet Engineering Quality Lab','customer',0,NULL,NULL,NULL,'contact@cometengineering.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p42','Slate Technologies Prototype Shop','customer',0,NULL,NULL,NULL,'contact@slatetechnologies.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p43','Indigo Engineering Field Ops','customer',0,NULL,NULL,NULL,'contact@indigoengineering.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p44','Ironside Solutions Quality Lab','customer',0,NULL,NULL,NULL,'contact@ironsidesolutions.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p45','Brookfield Operations HQ Procurement','customer',0,NULL,NULL,NULL,'contact@brookfieldoperations.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p46','Grove Solutions Test Facility','customer',0,NULL,NULL,NULL,'contact@grovesolutions.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p47','Adjacent Customer 1 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer001.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p48','Adjacent Customer 2 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer002.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p49','Adjacent Customer 3 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer003.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r52226D78FE_p50','Adjacent Customer 4 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer004.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q01','Westfield Industries','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q02','Spectra Distributors','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q03','Matrix Importers','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q04','Arrow Solutions','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q05','Riverdale Movers','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q06','Clearwater Transport','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q07','Ironwood Commodities','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q08','Quartz Distribution','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q09','Keystone Forwarders','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q10','Cardinal Freight','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q11','Scion Networks','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q12','Baltic Carriers','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q13','Vantage Consolidators','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q14','Marble Logistics','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q15','Lance Exporters','vendor',15,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q16','Opal Resources','vendor',16,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q17','Flux Components','vendor',17,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q18','Trellis Merchants','vendor',18,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q19','Arbor Partners','vendor',19,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q20','Quantum Warehousing','vendor',20,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q21','Osprey Supply','vendor',21,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q22','Ledger Warehouse','vendor',22,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q23','Velocity Conveyance','vendor',23,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q24','Echo Provisions','vendor',24,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q25','Beacon Shipping','vendor',25,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q26','Gateway Operations','vendor',26,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r83DC4C8D23_q27','Eclipse Assemblies','vendor',27,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q01','Granite Sourcing','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q02','Zenith Wholesale','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q03','Northbridge Resources','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q04','Copper Logistics','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q05','Cobalt Resources','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q06','Pivot Resources','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q07','Conduit Logistics','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q08','Equinox Materials','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q09','Steel Resources','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q10','Trident Resources','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q11','Sterling Wholesale','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q12','Silverline Carriers','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q13','Monarch Materials','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q14','Skyline Supply','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q15','Mosaic Materials','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q16','Sierra Resources','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q17','Sentinel Resources','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q18','Redstone Sourcing','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q19','Arc Wholesale','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q20','Cosmo Parts Co','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q21','Bayshore Distribution','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q22','Baseline Logistics','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q23','Peak Sourcing','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q24','Horizon Resources','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q25','Bronze Networks','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q26','Canton Carriers','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q27','Bridgeway Carriers','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q28','Jade Trading','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q29','Vertex Sourcing','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q30','Citadel Supply','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q31','Ridge Wholesale','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q32','Oxide Wholesale','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q33','Compass Components','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q34','Oakmont Parts Co','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q35','Flint Freight','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q36','Ember Carriers','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q37','Ridgeline Sourcing','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q38','Atlas Parts Co','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q39','Cipher Resources','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q40','Circuit Resources','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q41','Solace Distribution','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q42','Crown Freight','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q43','Terra Transit','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q44','Aurora Sourcing','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q45','Crest Trading','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q46','Ashford Components','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q47','Titan Components','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q48','Hartland Distribution','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q49','Metro Networks','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r52226D78FE_q50','Drift Procurement','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P83DC4C8D23-SAF-LSC-006','Laser Safety Curtain System','Industrial Equipment','consu',2804.83,1604.66,'buy,manufacture',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'P83DC4C8D23-SAF-LSC-006','r83DC4C8D23_q01','Priority Shuttle lane (10d transit, 10-12 units)',10,10.0,12.0,1699.45);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'P83DC4C8D23-SAF-LSC-006','r83DC4C8D23_q02','Express Air lane (6d transit, 5-22 units)',6,5.0,22.0,2060.54);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'P83DC4C8D23-SAF-LSC-006','r83DC4C8D23_q03','Bulk Container lane (21d transit, 72-77 units)',21,72.0,77.0,1096.04);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'P83DC4C8D23-SAF-LSC-006','r83DC4C8D23_q04','Scheduled Freight lane (18d transit, 6-8 units)',18,6.0,8.0,1573.47);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'P83DC4C8D23-SAF-LSC-006','r83DC4C8D23_q05','Regional Cross-Dock lane (15d transit, 7-7 units)',15,7.0,7.0,1632.15);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'P83DC4C8D23-SAF-LSC-006','r83DC4C8D23_q06','Bulk Container lane (21d transit, 72-74 units)',21,72.0,74.0,1031.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P83DC4C8D23-SAF-SIS-103','Safety Interlock Switch Module','Industrial Equipment','consu',147.99,64.41,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'P83DC4C8D23-SAF-SIS-103','r83DC4C8D23_q07','Rapid Works (2d)',2,4.0,51.0,83.02);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'P83DC4C8D23-SAF-SIS-103','r83DC4C8D23_q08','Domestic Supply (3d)',3,25.0,117.0,81.09);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'P83DC4C8D23-SAF-SIS-103','r83DC4C8D23_q09','Import Consolidator (3d)',3,36.0,56.0,64.41);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P83DC4C8D23-SAF-WSS-114','Welding Screen PVC Strip Set','Industrial Equipment','consu',43.45,15.79,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'P83DC4C8D23-SAF-WSS-114','r83DC4C8D23_q10','Rapid Works (3d)',3,8.0,63.0,20.76);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'P83DC4C8D23-SAF-WSS-114','r83DC4C8D23_q11','Import Consolidator (3d)',3,42.0,190.0,15.79);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'P83DC4C8D23-SAF-WSS-114','r83DC4C8D23_q12','Domestic Supply (3d)',3,28.0,34.0,20.39);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P83DC4C8D23-SAF-AFL-122','Acoustic Foam Lining Panel','Industrial Equipment','consu',58.05,22.15,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'P83DC4C8D23-SAF-AFL-122','r83DC4C8D23_q13','Rapid Works (2d)',2,9.0,83.0,29.24);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'P83DC4C8D23-SAF-AFL-122','r83DC4C8D23_q14','Import Consolidator (3d)',3,39.0,93.0,23.63);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'P83DC4C8D23-SAF-AFL-122','r83DC4C8D23_q15','Hybrid Fabricators (3d)',3,16.0,23.0,28.17);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'P83DC4C8D23-SAF-AFL-122','r83DC4C8D23_q16','Domestic Supply (3d)',3,27.0,85.0,22.15);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P83DC4C8D23-SAF-FRS-123','Fire-Rated Seal Strip','Industrial Equipment','consu',35.69,14.38,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'P83DC4C8D23-SAF-FRS-123','r83DC4C8D23_q17','Rapid Works (3d)',3,8.0,135.0,19.28);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'P83DC4C8D23-SAF-FRS-123','r83DC4C8D23_q18','Hybrid Fabricators (3d)',3,9.0,59.0,16.63);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'P83DC4C8D23-SAF-FRS-123','r83DC4C8D23_q19','Import Consolidator (3d)',3,24.0,32.0,14.38);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'P83DC4C8D23-SAF-FRS-123','r83DC4C8D23_q20','Domestic Supply (3d)',3,18.0,25.0,14.43);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P83DC4C8D23-SAF-PSM-128','Pressure-Sensitive Safety Mat','Industrial Equipment','consu',205.73,108.84,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'P83DC4C8D23-SAF-PSM-128','r83DC4C8D23_q21','Rapid Works (3d)',3,7.0,16.0,149.47);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'P83DC4C8D23-SAF-PSM-128','r83DC4C8D23_q22','Domestic Supply (3d)',3,28.0,79.0,120.93);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'P83DC4C8D23-SAF-PSM-128','r83DC4C8D23_q23','Import Consolidator (3d)',3,29.0,35.0,108.84);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'P83DC4C8D23-SAF-PSM-128','r83DC4C8D23_q24','Hybrid Fabricators (3d)',3,18.0,45.0,124.95);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P83DC4C8D23-SAF-MSB-130','Muting Sensor Bracket Kit','Industrial Equipment','consu',95.78,38.28,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'P83DC4C8D23-SAF-MSB-130','r83DC4C8D23_q25','Rapid Works (2d)',2,10.0,46.0,55.29);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'P83DC4C8D23-SAF-MSB-130','r83DC4C8D23_q26','Hybrid Fabricators (3d)',3,9.0,66.0,50.69);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'P83DC4C8D23-SAF-MSB-130','r83DC4C8D23_q27','Import Consolidator (3d)',3,44.0,69.0,38.28);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A001','Corrosion-Resistant Polycarbonate Vision Panel','Power Transmission','consu',417.19,280.57,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'P52226D78FE-A001','r52226D78FE_q01','Cross-dock',5,1.0,24.0,273.05);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A002','Economy Clamp Connector Set','Fasteners and Fixings','consu',184.23,130.65,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'P52226D78FE-A002','r52226D78FE_q02','Regional lane',8,1.0,24.0,135.29);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A003','Low-Flow Lock Assembly','Maintenance Supplies','consu',257.88,135.3,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'P52226D78FE-A003','r52226D78FE_q03','Regional lane',8,1.0,24.0,131.17);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A004','Stainless Light Beacon Module','Replacement Parts','consu',281.24,150.28,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'P52226D78FE-A004','r52226D78FE_q04','Bulk shipment',3,1.0,24.0,155.22);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A005','Low-Noise Vision Panel','Seals and Gaskets','consu',374.63,229.2,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'P52226D78FE-A005','r52226D78FE_q05','Regional lane',3,1.0,24.0,237.6);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A006','Lightweight Gate Frame Assembly','Industrial Spare Parts','consu',339.27,224.17,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'P52226D78FE-A006','r52226D78FE_q06','Warehouse direct',7,1.0,24.0,213.0);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A007','Industrial Solenoid Lock Assembly','Fasteners and Fixings','consu',376.77,228.57,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'P52226D78FE-A007','r52226D78FE_q07','Bulk shipment',6,1.0,24.0,222.63);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A008','Modular Key Interlock System','Hardware Accessories','consu',269.68,185.22,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'P52226D78FE-A008','r52226D78FE_q08','Local pickup',6,1.0,24.0,191.42);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A009','Hardened Door Latch Assembly','Hardware Accessories','consu',374.77,264.82,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'P52226D78FE-A009','r52226D78FE_q09','Local pickup',3,1.0,24.0,255.73);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A010','High-Temp Mesh Panel 4x8ft','Replacement Parts','consu',183.23,128.96,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'P52226D78FE-A010','r52226D78FE_q10','Local pickup',4,1.0,24.0,124.31);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A011','UV-Stable Key Interlock System','Electrical Components','consu',408.13,268.35,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'P52226D78FE-A011','r52226D78FE_q11','Cross-dock',8,1.0,24.0,285.8);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A012','Single-Stage Anchor Bolt Kit','Mechanical Components','consu',415.94,220.81,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'P52226D78FE-A012','r52226D78FE_q12','Regional lane',6,1.0,24.0,224.31);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A013','Cold-Rolled Lock Assembly','Fasteners and Fixings','consu',217.88,146.5,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'P52226D78FE-A013','r52226D78FE_q13','Warehouse direct',4,1.0,24.0,144.96);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A014','Dual-Stage Vision Panel','Industrial Spare Parts','consu',315.25,178.18,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'P52226D78FE-A014','r52226D78FE_q14','Scheduled freight',8,1.0,24.0,178.51);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A015','Adjustable Pull Switch','Hardware Accessories','consu',355.91,194.38,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'P52226D78FE-A015','r52226D78FE_q15','Standard delivery',4,1.0,24.0,203.54);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A016','High-Performance Solenoid Lock Assembly','Power Transmission','consu',236.5,166.66,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'P52226D78FE-A016','r52226D78FE_q16','Warehouse direct',5,1.0,24.0,162.99);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A017','Non-Magnetic Gate Frame Assembly','Power Transmission','consu',192.96,102.12,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'P52226D78FE-A017','r52226D78FE_q17','Regional lane',5,1.0,24.0,109.74);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A018','Extended-Life Key Interlock System','Maintenance Supplies','consu',336.86,221.25,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'P52226D78FE-A018','r52226D78FE_q18','Local pickup',5,1.0,24.0,229.81);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A019','Metric Clamp Connector Set','Power Transmission','consu',215.35,140.43,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'P52226D78FE-A019','r52226D78FE_q19','Cross-dock',8,1.0,24.0,149.29);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A020','Thermal-Guard Beacon Module','Replacement Parts','consu',315.81,170.1,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'P52226D78FE-A020','r52226D78FE_q20','Scheduled freight',3,1.0,24.0,173.89);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A021','Weatherproof Panel 4x8ft','Seals and Gaskets','consu',384.58,260.05,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'P52226D78FE-A021','r52226D78FE_q21','Scheduled freight',8,1.0,24.0,277.67);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A022','Reinforced Lock Assembly','Maintenance Supplies','consu',233.84,146.5,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'P52226D78FE-A022','r52226D78FE_q22','Warehouse direct',3,1.0,24.0,157.55);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A023','Standard Panel 4x8ft','Power Transmission','consu',324.73,217.84,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'P52226D78FE-A023','r52226D78FE_q23','Scheduled freight',3,1.0,24.0,226.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A024','Double-Row Clamp Connector Set','Fasteners and Fixings','consu',346.49,202.22,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'P52226D78FE-A024','r52226D78FE_q24','Standard delivery',5,1.0,24.0,212.68);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A025','Threaded Base Plate','Pneumatic Components','consu',281.01,150.25,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'P52226D78FE-A025','r52226D78FE_q25','Express route',7,1.0,24.0,146.34);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A026','Wide-Body Lock Assembly','Mechanical Components','consu',279.65,155.8,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'P52226D78FE-A026','r52226D78FE_q26','Regional lane',6,1.0,24.0,155.29);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A027','Tapered Lock Assembly','Mechanical Components','consu',306.61,199.56,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'P52226D78FE-A027','r52226D78FE_q27','Bulk shipment',6,1.0,24.0,192.57);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A028','Premium Pull Switch','Industrial Spare Parts','consu',201.42,113.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'P52226D78FE-A028','r52226D78FE_q28','Scheduled freight',8,1.0,24.0,120.38);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A029','Food-Grade Frame Assembly','Pneumatic Components','consu',387.35,255.03,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'P52226D78FE-A029','r52226D78FE_q29','Scheduled freight',7,1.0,24.0,242.36);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A030','Zero-Backlash Gate Frame Assembly','Seals and Gaskets','consu',405.68,224.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(57,'P52226D78FE-A030','r52226D78FE_q30','Standard delivery',3,1.0,24.0,218.3);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A031','Heavy-Duty Interlock System','Hardware Accessories','consu',184.24,96.8,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(58,'P52226D78FE-A031','r52226D78FE_q31','Regional lane',5,1.0,24.0,99.83);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A032','Rapid-Lock Solenoid Lock Assembly','Seals and Gaskets','consu',221.37,148.04,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(59,'P52226D78FE-A032','r52226D78FE_q32','Local pickup',7,1.0,24.0,149.07);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A033','Commercial Polycarbonate Vision Panel','Industrial Spare Parts','consu',402.87,225.3,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(60,'P52226D78FE-A033','r52226D78FE_q33','Standard delivery',5,1.0,24.0,235.44);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A034','Low-Friction Interlock Switch Module','Seals and Gaskets','consu',305.32,209.88,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(61,'P52226D78FE-A034','r52226D78FE_q34','Express route',6,1.0,24.0,206.51);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A035','High-Torque Clamp Connector Set','Fasteners and Fixings','consu',192.41,135.74,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(62,'P52226D78FE-A035','r52226D78FE_q35','Local pickup',4,1.0,24.0,138.17);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A036','Powder-Coated Mesh Panel 4x8ft','Maintenance Supplies','consu',210.65,115.29,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(63,'P52226D78FE-A036','r52226D78FE_q36','Cross-dock',5,1.0,24.0,118.16);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A037','Low-Profile Beacon Module','Hardware Accessories','consu',329.45,236.14,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(64,'P52226D78FE-A037','r52226D78FE_q37','Bulk shipment',5,1.0,24.0,246.84);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A038','Heat-Treated Bolt Kit','Seals and Gaskets','consu',356.19,248.88,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(65,'P52226D78FE-A038','r52226D78FE_q38','Express route',3,1.0,24.0,258.53);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A039','Narrow-Body Light Beacon Module','Maintenance Supplies','consu',385.71,235.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(66,'P52226D78FE-A039','r52226D78FE_q39','Express route',3,1.0,24.0,243.56);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A040','Self-Lubricating Lock Assembly','Mechanical Components','consu',359.18,214.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(67,'P52226D78FE-A040','r52226D78FE_q40','Bulk shipment',7,1.0,24.0,212.11);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A041','Cleanroom Polycarbonate Vision Panel','Power Transmission','consu',188.18,117.3,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(68,'P52226D78FE-A041','r52226D78FE_q41','Local pickup',5,1.0,24.0,113.22);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A042','Flanged Mesh Panel 4x8ft','Fasteners and Fixings','consu',182.46,102.15,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(69,'P52226D78FE-A042','r52226D78FE_q42','Bulk shipment',4,1.0,24.0,97.42);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A043','Impact-Rated Interlock Switch Module','Pneumatic Components','consu',314.97,222.72,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(70,'P52226D78FE-A043','r52226D78FE_q43','Express route',5,1.0,24.0,231.99);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A044','Precision Polycarbonate Vision Panel','Replacement Parts','consu',354.5,223.58,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(71,'P52226D78FE-A044','r52226D78FE_q44','Warehouse direct',8,1.0,24.0,215.13);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A045','Anti-Vibration Mesh Panel 4x8ft','Replacement Parts','consu',296.01,181.24,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(72,'P52226D78FE-A045','r52226D78FE_q45','Warehouse direct',6,1.0,24.0,188.15);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A046','Anodized Vision Panel','Fasteners and Fixings','consu',275.46,185.34,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(73,'P52226D78FE-A046','r52226D78FE_q46','Local pickup',7,1.0,24.0,186.38);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A047','High-Cycle Light Beacon Module','Maintenance Supplies','consu',221.49,155.6,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(74,'P52226D78FE-A047','r52226D78FE_q47','Express route',5,1.0,24.0,163.24);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A048','Compact Vision Panel','Maintenance Supplies','consu',394.43,247.64,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(75,'P52226D78FE-A048','r52226D78FE_q48','Cross-dock',7,1.0,24.0,261.54);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A049','Sealed Door Latch Assembly','Pneumatic Components','consu',333.46,199.41,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(76,'P52226D78FE-A049','r52226D78FE_q49','Regional lane',4,1.0,24.0,206.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P52226D78FE-A050','Pressure-Balanced Bolt Kit','Maintenance Supplies','consu',377.6,235.17,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(77,'P52226D78FE-A050','r52226D78FE_q50','Standard delivery',8,1.0,24.0,229.21);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'P83DC4C8D23-SAF-LSC-006','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P83DC4C8D23-SAF-SIS-103',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P83DC4C8D23-SAF-WSS-114',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P83DC4C8D23-SAF-AFL-122',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P83DC4C8D23-SAF-FRS-123',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P83DC4C8D23-SAF-PSM-128',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P83DC4C8D23-SAF-MSB-130',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'P52226D78FE-A045','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P52226D78FE-A040',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'P52226D78FE-A008','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P52226D78FE-A031',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'P52226D78FE-A050','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'P52226D78FE-A042',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'P52226D78FE-A015',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'P52226D78FE-A027','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P52226D78FE-A036',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'P52226D78FE-A043','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P52226D78FE-A004',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P52226D78FE-A015',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'P52226D78FE-A013','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'P52226D78FE-A006',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'P52226D78FE-A032',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'P52226D78FE-A025','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P52226D78FE-A002',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P52226D78FE-A040',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'P52226D78FE-A016','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P52226D78FE-A026',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P52226D78FE-A020',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'P52226D78FE-A022','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P52226D78FE-A025',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P52226D78FE-A044',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(11,'P52226D78FE-A031','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'P52226D78FE-A012',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'P52226D78FE-A048',1.0);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P83DC4C8D23-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P83DC4C8D23-WC02','Fabrication Cell 2',0,0,NULL,NULL);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P83DC4C8D23-SAF-AFL-122',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P83DC4C8D23-SAF-FRS-123',NULL,25.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P83DC4C8D23-SAF-LSC-006',NULL,66.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P83DC4C8D23-SAF-MSB-130',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P83DC4C8D23-SAF-PSM-128',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P83DC4C8D23-SAF-SIS-103',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P83DC4C8D23-SAF-WSS-114',NULL,24.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A001',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A002',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A003',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A004',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A005',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A006',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A007',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A008',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A009',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A010',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A011',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A012',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A013',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A014',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A015',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A016',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A017',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A018',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A019',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A020',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A021',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A022',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A023',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A024',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A025',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A026',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A027',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A028',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A029',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A030',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A031',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A032',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A033',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A034',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A035',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A036',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A037',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A038',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A039',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A040',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A041',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A042',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A043',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A044',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A045',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A046',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A047',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A048',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A049',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P52226D78FE-A050',NULL,15.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'r83DC4C8D23_c01','P83DC4C8D23-SAF-LSC-006',14,9,43893.63,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'r83DC4C8D23_c02','P83DC4C8D23-SAF-LSC-006',17,10,49005.94,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'r83DC4C8D23_c03','P83DC4C8D23-SAF-LSC-006',18,11,53782.39,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'r83DC4C8D23_c04','P83DC4C8D23-SAF-LSC-006',15,11,43734.14,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'r83DC4C8D23_c05','P83DC4C8D23-SAF-LSC-006',15,12,43488.55,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'r83DC4C8D23_c06','P83DC4C8D23-SAF-LSC-006',20,14,57621.58,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'r83DC4C8D23_c07','P83DC4C8D23-SAF-LSC-006',19,14,55256.71,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'r83DC4C8D23_c08','P83DC4C8D23-SAF-LSC-006',26,14,76090.95,NULL);
