-- agentic-labs/erp-bench scenario 2124: Deionization Polishing Unit
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE7BE7302C8_c01','Opal Trust','customer',0,95037.71,NULL,NULL,'orders@opaltrust.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE7BE7302C8_c02','Brookfield Office','customer',0,70418.48,NULL,NULL,'orders@brookfieldoffice.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE7BE7302C8_c03','Zenith Advisory','customer',0,90629.67,NULL,NULL,'orders@zenithadvisory.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE7BE7302C8_c04','Aurora Archive','customer',0,75454.6,NULL,NULL,'orders@auroraarchive.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE7BE7302C8_c05','Apex Society','customer',0,77803.91,NULL,NULL,'orders@apexsociety.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE7BE7302C8_c06','Grove Greenhouse','customer',0,71921.76,NULL,NULL,'orders@grovegreenhouse.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE7BE7302C8_c07','Beacon Systems','customer',0,77265.94,NULL,NULL,'orders@beaconsystems.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE7BE7302C8_c08','Atlas Media','customer',0,107818.74,NULL,NULL,'orders@atlasmedia.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p01','Raven Operations Field Ops','customer',0,NULL,NULL,NULL,'contact@ravenoperations.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p02','Chrome Operations Quality Lab','customer',0,NULL,NULL,NULL,'contact@chromeoperations.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p03','Arbor Fabrication Tooling Center','customer',0,NULL,NULL,NULL,'contact@arborfabrication.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p04','Pivot Fabrication Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@pivotfabrication.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p05','Forge Solutions Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@forgesolutions.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p06','Vantage Assembly R&D Workshop','customer',0,NULL,NULL,NULL,'contact@vantageassembly.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p07','Arrow Engineering HQ Procurement','customer',0,NULL,NULL,NULL,'contact@arrowengineering.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p08','Millbrook Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@millbrookassembly.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p09','Silverline Assembly Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@silverlineassembly.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p10','Cascade Manufacturing Prototype Shop','customer',0,NULL,NULL,NULL,'contact@cascademanufacturing.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p11','Flux Industries R&D Workshop','customer',0,NULL,NULL,NULL,'contact@fluxindustries.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p12','Conduit Assembly Test Facility','customer',0,NULL,NULL,NULL,'contact@conduitassembly.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p13','Crown Production Quality Lab','customer',0,NULL,NULL,NULL,'contact@crownproduction.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p14','Alloy Technologies Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@alloytechnologies.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p15','Noble Engineering HQ Procurement','customer',0,NULL,NULL,NULL,'contact@nobleengineering.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p16','Drift Production Test Facility','customer',0,NULL,NULL,NULL,'contact@driftproduction.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p17','Peak Engineering Prototype Shop','customer',0,NULL,NULL,NULL,'contact@peakengineering.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p18','Dune Engineering Site Logistics','customer',0,NULL,NULL,NULL,'contact@duneengineering.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p19','Compass Assembly R&D Workshop','customer',0,NULL,NULL,NULL,'contact@compassassembly.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p20','Vertex Operations Prototype Shop','customer',0,NULL,NULL,NULL,'contact@vertexoperations.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p21','Ridge Operations Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@ridgeoperations.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p22','Cardinal Services Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@cardinalservices.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p23','Trident Fabrication Quality Lab','customer',0,NULL,NULL,NULL,'contact@tridentfabrication.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p24','Sentinel Fabrication R&D Workshop','customer',0,NULL,NULL,NULL,'contact@sentinelfabrication.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p25','Oxide Operations Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@oxideoperations.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p26','Ironside Operations Tooling Center','customer',0,NULL,NULL,NULL,'contact@ironsideoperations.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p27','Nimbus Services HQ Procurement','customer',0,NULL,NULL,NULL,'contact@nimbusservices.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p28','Borough Industries R&D Workshop','customer',0,NULL,NULL,NULL,'contact@boroughindustries.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p29','Equinox Assembly Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@equinoxassembly.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p30','Citadel Technologies Test Facility','customer',0,NULL,NULL,NULL,'contact@citadeltechnologies.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p31','Metro Services R&D Workshop','customer',0,NULL,NULL,NULL,'contact@metroservices.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p32','Lakewood Solutions HQ Procurement','customer',0,NULL,NULL,NULL,'contact@lakewoodsolutions.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p33','Spectra Manufacturing Quality Lab','customer',0,NULL,NULL,NULL,'contact@spectramanufacturing.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p34','Bridgeway Fabrication Test Facility','customer',0,NULL,NULL,NULL,'contact@bridgewayfabrication.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p35','Velocity Services Test Facility','customer',0,NULL,NULL,NULL,'contact@velocityservices.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p36','Bayshore Manufacturing Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@bayshoremanufacturing.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p37','Axis Engineering Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@axisengineering.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p38','Blaze Services R&D Workshop','customer',0,NULL,NULL,NULL,'contact@blazeservices.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p39','Mosaic Manufacturing Test Facility','customer',0,NULL,NULL,NULL,'contact@mosaicmanufacturing.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p40','Scion Manufacturing Site Logistics','customer',0,NULL,NULL,NULL,'contact@scionmanufacturing.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p41','Garnet Solutions HQ Procurement','customer',0,NULL,NULL,NULL,'contact@garnetsolutions.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p42','Quartz Production Test Facility','customer',0,NULL,NULL,NULL,'contact@quartzproduction.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p43','Globe Production Test Facility','customer',0,NULL,NULL,NULL,'contact@globeproduction.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p44','Fairview Engineering Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@fairviewengineering.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p45','Helix Assembly R&D Workshop','customer',0,NULL,NULL,NULL,'contact@helixassembly.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p46','Osprey Services Prototype Shop','customer',0,NULL,NULL,NULL,'contact@ospreyservices.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p47','Cobalt Solutions Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@cobaltsolutions.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p48','Ivory Manufacturing Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@ivorymanufacturing.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p49','Pacific Technologies Test Facility','customer',0,NULL,NULL,NULL,'contact@pacifictechnologies.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF63ACD5FA8_p50','Ridgeline Technologies R&D Workshop','customer',0,NULL,NULL,NULL,'contact@ridgelinetechnologies.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q01','Bronze Carriers','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q02','Iron Industries','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q03','Steel Components','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q04','Clearwater Integrators','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q05','Haven Shipping','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q06','Arc Distributors','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q07','Canton Assemblies','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q08','Ledger Merchants','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q09','Oakmont Exporters','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q10','Onyx Packagers','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q11','Baltic Transport','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q12','Flint Consolidators','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q13','Summit Manufacturing','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q14','Lumen Sourcing','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q15','Lance Networks','vendor',15,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q16','Skyline Holdings','vendor',16,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q17','Anvil Wholesalers','vendor',17,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q18','Ironwood Forwarders','vendor',18,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q19','Ashford Logistics','vendor',19,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q20','Circuit Conveyance','vendor',20,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q21','Sapphire Transit','vendor',21,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE7BE7302C8_q22','Keystone Operations','vendor',22,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q01','Echo Logistics','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q02','Catalyst Networks','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q03','Crestview Sourcing','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q04','Horizon Materials','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q05','Thornton Wholesale','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q06','Alpine Procurement','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q07','Solace Materials','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q08','Westfield Carriers','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q09','Gateway Carriers','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q10','Trellis Procurement','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q11','Evergreen Distribution','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q12','Granite Networks','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q13','Northbridge Components','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q14','Meridian Procurement','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q15','Indigo Parts Co','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q16','Aether Components','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q17','Quantum Distribution','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q18','Sierra Parts Co','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q19','Nexus Trading','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q20','Orbital Supply','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q21','Stratos Wholesale','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q22','Aegis Materials','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q23','Marble Components','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q24','Jade Networks','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q25','Sterling Components','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q26','Crest Components','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q27','Terra Freight','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q28','Pinnacle Materials','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q29','Riverdale Components','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q30','Matrix Networks','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q31','Baseline Materials','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q32','Slate Components','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q33','Comet Procurement','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q34','Cosmo Sourcing','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q35','Stonewall Networks','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q36','Cedar Trading','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q37','Eclipse Wholesale','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q38','Spark Logistics','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q39','Prism Resources','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q40','Hartland Procurement','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q41','Polar Trading','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q42','Spire Supply','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q43','Cipher Trading','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q44','Lattice Supply','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q45','Ember Components','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q46','Titan Wholesale','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q47','Element Procurement','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q48','Copper Trading','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q49','Monarch Materials','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF63ACD5FA8_q50','Coral Materials','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE7BE7302C8-WTR-DPU-006','Deionization Polishing Unit','Utility Equipment','consu',4331.64,2318.25,'buy,manufacture',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'PE7BE7302C8-WTR-DPU-006','rE7BE7302C8_q01','Priority Shuttle lane (9d transit, 14-44 units)',9,14.0,44.0,2385.69);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'PE7BE7302C8-WTR-DPU-006','rE7BE7302C8_q02','Express Air lane (6d transit, 3-3 units)',6,3.0,3.0,2998.17);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'PE7BE7302C8-WTR-DPU-006','rE7BE7302C8_q03','Bulk Container lane (21d transit, 72-72 units)',21,72.0,72.0,1566.31);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'PE7BE7302C8-WTR-DPU-006','rE7BE7302C8_q04','Hybrid Expedite lane (10d transit, 8-62 units)',10,8.0,62.0,2889.96);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'PE7BE7302C8-WTR-DPU-006','rE7BE7302C8_q05','Scheduled Freight lane (19d transit, 6-6 units)',19,6.0,6.0,2113.95);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'PE7BE7302C8-WTR-DPU-006','rE7BE7302C8_q06','Microfactory Build-to-Order lane (7d transit, 6-20 units)',7,6.0,20.0,3272.28);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE7BE7302C8-SUB-02','Deionization Polishing Unit Subassembly','Utility Equipment','consu',1212.86,83.91,'manufacture',NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE7BE7302C8-WTR-DRC-118','DI Resin Cartridge Mixed Bed','Utility Equipment','consu',78.57,37.05,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'PE7BE7302C8-WTR-DRC-118','rE7BE7302C8_q07','Rapid Works (4d)',4,4.0,64.0,42.51);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'PE7BE7302C8-WTR-DRC-118','rE7BE7302C8_q08','Domestic Supply (4d)',4,13.0,13.0,41.21);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'PE7BE7302C8-WTR-DRC-118','rE7BE7302C8_q09','Import Consolidator (6d)',6,26.0,58.0,37.05);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'PE7BE7302C8-WTR-DRC-118','rE7BE7302C8_q10','Hybrid Fabricators (5d)',5,20.0,25.0,47.29);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE7BE7302C8-WTR-PSA-121','Pressure Switch Assembly','Utility Equipment','consu',41.67,15.23,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'PE7BE7302C8-WTR-PSA-121','rE7BE7302C8_q11','Rapid Works (3d)',3,11.0,21.0,21.56);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'PE7BE7302C8-WTR-PSA-121','rE7BE7302C8_q12','Import Consolidator (6d)',6,33.0,77.0,15.23);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'PE7BE7302C8-WTR-PSA-121','rE7BE7302C8_q13','Domestic Supply (4d)',4,28.0,46.0,18.15);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'PE7BE7302C8-WTR-PSA-121','rE7BE7302C8_q14','Hybrid Fabricators (5d)',5,16.0,17.0,20.46);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE7BE7302C8-WTR-ACC-105','Activated Carbon Cartridge 20in','Utility Equipment','consu',45.65,18.03,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'PE7BE7302C8-WTR-ACC-105','rE7BE7302C8_q15','Rapid Works (4d)',4,11.0,74.0,22.74);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'PE7BE7302C8-WTR-ACC-105','rE7BE7302C8_q16','Import Consolidator (4d)',4,26.0,227.0,18.03);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'PE7BE7302C8-WTR-ACC-105','rE7BE7302C8_q17','Hybrid Fabricators (4d)',4,10.0,31.0,24.07);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'PE7BE7302C8-WTR-ACC-105','rE7BE7302C8_q18','Domestic Supply (4d)',4,16.0,23.0,21.19);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE7BE7302C8-WTR-FHB-110','Filter Housing Bracket Set','Utility Equipment','consu',29.34,11.22,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'PE7BE7302C8-WTR-FHB-110','rE7BE7302C8_q19','Rapid Works (4d)',4,5.0,42.0,15.73);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'PE7BE7302C8-WTR-FHB-110','rE7BE7302C8_q20','Domestic Supply (4d)',4,23.0,121.0,11.84);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'PE7BE7302C8-WTR-FHB-110','rE7BE7302C8_q21','Hybrid Fabricators (4d)',4,8.0,212.0,13.41);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'PE7BE7302C8-WTR-FHB-110','rE7BE7302C8_q22','Import Consolidator (4d)',4,31.0,92.0,11.22);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A001','Cold-Rolled Element 4x40','Power Transmission','consu',201.77,111.46,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'PF63ACD5FA8-A001','rF63ACD5FA8_q01','Express route',6,1.0,24.0,114.74);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A002','Pressure-Balanced Housing FRP','Electrical Components','consu',189.19,108.21,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'PF63ACD5FA8-A002','rF63ACD5FA8_q02','Express route',4,1.0,24.0,112.86);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A003','Food-Grade Metering Pump','Hardware Accessories','consu',240.71,155.47,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'PF63ACD5FA8-A003','rF63ACD5FA8_q03','Cross-dock',4,1.0,24.0,160.67);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A004','Dual-Stage Pressure Pump Assembly','Seals and Gaskets','consu',337.7,229.09,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'PF63ACD5FA8-A004','rF63ACD5FA8_q04','Regional lane',7,1.0,24.0,224.38);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A005','High-Temp Cartridge 20in','Replacement Parts','consu',267.48,170.34,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'PF63ACD5FA8-A005','rF63ACD5FA8_q05','Warehouse direct',6,1.0,24.0,180.57);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A006','Low-Temp Membrane Element 4x40','Fasteners and Fixings','consu',393.93,271.98,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'PF63ACD5FA8-A006','rF63ACD5FA8_q06','Express route',6,1.0,24.0,277.76);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A007','Flanged Housing FRP','Replacement Parts','consu',307.39,161.93,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'PF63ACD5FA8-A007','rF63ACD5FA8_q07','Warehouse direct',6,1.0,24.0,173.79);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A008','High-Performance 0 100PSI','Industrial Spare Parts','consu',191.49,135.22,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'PF63ACD5FA8-A008','rF63ACD5FA8_q08','Warehouse direct',8,1.0,24.0,130.68);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A009','Self-Lubricating Membrane Element 4x40','Replacement Parts','consu',304.29,193.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'PF63ACD5FA8-A009','rF63ACD5FA8_q09','Warehouse direct',7,1.0,24.0,190.31);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A010','Narrow-Body Chemical Metering Pump','Industrial Spare Parts','consu',345.0,183.09,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'PF63ACD5FA8-A010','rF63ACD5FA8_q10','Regional lane',8,1.0,24.0,191.89);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A011','Stainless Element 4x40','Power Transmission','consu',349.96,229.95,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'PF63ACD5FA8-A011','rF63ACD5FA8_q11','Bulk shipment',7,1.0,24.0,226.51);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A012','Double-Row Cartridge 20in','Power Transmission','consu',371.97,200.85,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'PF63ACD5FA8-A012','rF63ACD5FA8_q12','Cross-dock',6,1.0,24.0,213.96);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A013','High-Cycle Sleeve Set','Pneumatic Components','consu',413.25,223.76,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'PF63ACD5FA8-A013','rF63ACD5FA8_q13','Local pickup',5,1.0,24.0,238.79);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A014','Low-Profile Valve Assembly','Industrial Spare Parts','consu',285.14,197.86,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'PF63ACD5FA8-A014','rF63ACD5FA8_q14','Bulk shipment',4,1.0,24.0,196.84);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A015','Low-Flow Membrane Element 4x40','Replacement Parts','consu',185.37,100.34,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'PF63ACD5FA8-A015','rF63ACD5FA8_q15','Regional lane',3,1.0,24.0,100.67);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A016','Powder-Coated Filter Cartridge 5um','Mechanical Components','consu',259.55,182.71,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'PF63ACD5FA8-A016','rF63ACD5FA8_q16','Local pickup',4,1.0,24.0,188.93);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A017','High-Torque Housing Bracket Set','Power Transmission','consu',415.91,227.71,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'PF63ACD5FA8-A017','rF63ACD5FA8_q17','Local pickup',5,1.0,24.0,230.89);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A018','Threaded Housing Bracket Set','Replacement Parts','consu',192.49,107.68,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'PF63ACD5FA8-A018','rF63ACD5FA8_q18','Cross-dock',6,1.0,24.0,115.6);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A019','Tapered Membrane Element 4x40','Pneumatic Components','consu',260.91,161.29,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'PF63ACD5FA8-A019','rF63ACD5FA8_q19','Scheduled freight',6,1.0,24.0,173.72);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A020','Cleanroom Solenoid Valve Assembly','Pneumatic Components','consu',265.74,140.72,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'PF63ACD5FA8-A020','rF63ACD5FA8_q20','Regional lane',5,1.0,24.0,139.81);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A021','Rapid-Lock Meter Sensor Module','Hardware Accessories','consu',278.7,175.08,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'PF63ACD5FA8-A021','rF63ACD5FA8_q21','Express route',4,1.0,24.0,172.49);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A022','Thermal-Guard Gauge 0 100PSI','Maintenance Supplies','consu',398.15,242.89,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'PF63ACD5FA8-A022','rF63ACD5FA8_q22','Bulk shipment',5,1.0,24.0,261.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A023','Sealed Pump Assembly','Fasteners and Fixings','consu',301.03,180.2,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'PF63ACD5FA8-A023','rF63ACD5FA8_q23','Bulk shipment',8,1.0,24.0,176.67);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A024','Premium Quartz Sleeve Set','Maintenance Supplies','consu',375.53,199.22,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'PF63ACD5FA8-A024','rF63ACD5FA8_q24','Local pickup',6,1.0,24.0,202.23);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A025','Adjustable Sleeve Set','Industrial Spare Parts','consu',212.87,136.76,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'PF63ACD5FA8-A025','rF63ACD5FA8_q25','Bulk shipment',7,1.0,24.0,134.26);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A026','Zero-Backlash Sensor Module','Industrial Spare Parts','consu',205.02,128.66,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'PF63ACD5FA8-A026','rF63ACD5FA8_q26','Regional lane',3,1.0,24.0,130.51);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A027','Wide-Body Membrane Element 4x40','Industrial Spare Parts','consu',217.97,123.43,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'PF63ACD5FA8-A027','rF63ACD5FA8_q27','Cross-dock',4,1.0,24.0,126.13);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A028','Medical-Grade Bracket Set','Power Transmission','consu',192.08,109.32,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'PF63ACD5FA8-A028','rF63ACD5FA8_q28','Cross-dock',3,1.0,24.0,116.84);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A029','Impact-Rated Cartridge 5um','Hardware Accessories','consu',301.05,197.12,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'PF63ACD5FA8-A029','rF63ACD5FA8_q29','Regional lane',6,1.0,24.0,192.95);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A030','Low-Friction Bracket Set','Seals and Gaskets','consu',416.23,230.22,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'PF63ACD5FA8-A030','rF63ACD5FA8_q30','Regional lane',7,1.0,24.0,235.9);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A031','Hardened Pressure Pump Assembly','Industrial Spare Parts','consu',313.61,193.84,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'PF63ACD5FA8-A031','rF63ACD5FA8_q31','Cross-dock',4,1.0,24.0,184.55);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A032','Low-Noise Gauge 0 100PSI','Seals and Gaskets','consu',369.96,259.52,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'PF63ACD5FA8-A032','rF63ACD5FA8_q32','Scheduled freight',3,1.0,24.0,274.1);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A033','High-Flow Pump Assembly','Seals and Gaskets','consu',277.89,199.99,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'PF63ACD5FA8-A033','rF63ACD5FA8_q33','Bulk shipment',4,1.0,24.0,197.11);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A034','Spring-Loaded Filter Cartridge 5um','Maintenance Supplies','consu',377.33,241.1,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'PF63ACD5FA8-A034','rF63ACD5FA8_q34','Warehouse direct',6,1.0,24.0,235.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A035','Anti-Vibration Vessel Housing FRP','Pneumatic Components','consu',225.14,130.04,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(57,'PF63ACD5FA8-A035','rF63ACD5FA8_q35','Express route',6,1.0,24.0,130.78);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A036','Quick-Release Metering Pump','Hardware Accessories','consu',256.87,139.61,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(58,'PF63ACD5FA8-A036','rF63ACD5FA8_q36','Local pickup',7,1.0,24.0,145.4);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A037','Heat-Treated Sleeve Set','Seals and Gaskets','consu',226.98,133.63,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(59,'PF63ACD5FA8-A037','rF63ACD5FA8_q37','Local pickup',7,1.0,24.0,136.03);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A038','Modular Meter Sensor Module','Mechanical Components','consu',402.35,249.14,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(60,'PF63ACD5FA8-A038','rF63ACD5FA8_q38','Local pickup',6,1.0,24.0,244.33);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A039','Universal Pressure Pump Assembly','Seals and Gaskets','consu',276.65,181.5,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(61,'PF63ACD5FA8-A039','rF63ACD5FA8_q39','Local pickup',4,1.0,24.0,193.16);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A040','Anodized Metering Pump','Industrial Spare Parts','consu',267.43,170.96,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(62,'PF63ACD5FA8-A040','rF63ACD5FA8_q40','Cross-dock',3,1.0,24.0,179.78);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A041','Industrial Element 4x40','Power Transmission','consu',388.03,249.79,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(63,'PF63ACD5FA8-A041','rF63ACD5FA8_q41','Cross-dock',8,1.0,24.0,246.34);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A042','Heavy-Duty Meter Sensor Module','Power Transmission','consu',346.12,248.62,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(64,'PF63ACD5FA8-A042','rF63ACD5FA8_q42','Cross-dock',8,1.0,24.0,247.37);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A043','Lightweight Membrane Element 4x40','Mechanical Components','consu',281.84,193.82,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(65,'PF63ACD5FA8-A043','rF63ACD5FA8_q43','Local pickup',3,1.0,24.0,194.43);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A044','Reinforced Housing FRP','Seals and Gaskets','consu',251.49,165.66,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(66,'PF63ACD5FA8-A044','rF63ACD5FA8_q44','Cross-dock',6,1.0,24.0,169.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A045','Compact TDS Conductivity Sensor','Seals and Gaskets','consu',207.62,120.78,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(67,'PF63ACD5FA8-A045','rF63ACD5FA8_q45','Bulk shipment',5,1.0,24.0,122.87);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A046','Standard Housing Bracket Set','Hardware Accessories','consu',280.32,163.01,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(68,'PF63ACD5FA8-A046','rF63ACD5FA8_q46','Regional lane',4,1.0,24.0,160.59);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A047','Non-Magnetic Filter Cartridge 5um','Seals and Gaskets','consu',390.54,214.67,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(69,'PF63ACD5FA8-A047','rF63ACD5FA8_q47','Warehouse direct',4,1.0,24.0,214.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A048','Corrosion-Resistant Meter Sensor Module','Seals and Gaskets','consu',351.91,202.44,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(70,'PF63ACD5FA8-A048','rF63ACD5FA8_q48','Express route',6,1.0,24.0,217.68);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A049','Snap-Fit Carbon Cartridge 20in','Power Transmission','consu',382.8,222.57,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(71,'PF63ACD5FA8-A049','rF63ACD5FA8_q49','Regional lane',4,1.0,24.0,222.66);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF63ACD5FA8-A050','Single-Stage Pump Assembly','Power Transmission','consu',358.68,232.41,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(72,'PF63ACD5FA8-A050','rF63ACD5FA8_q50','Local pickup',4,1.0,24.0,236.55);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'PE7BE7302C8-SUB-02','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PE7BE7302C8-WTR-ACC-105',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PE7BE7302C8-WTR-FHB-110',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'PE7BE7302C8-WTR-DPU-006','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PE7BE7302C8-SUB-02',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PE7BE7302C8-WTR-DRC-118',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PE7BE7302C8-WTR-PSA-121',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'PF63ACD5FA8-A027','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'PF63ACD5FA8-A008',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'PF63ACD5FA8-A041','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'PF63ACD5FA8-A029',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'PF63ACD5FA8-A003','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'PF63ACD5FA8-A029',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'PF63ACD5FA8-A020','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'PF63ACD5FA8-A004',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'PF63ACD5FA8-A017','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'PF63ACD5FA8-A033',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'PF63ACD5FA8-A028',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'PF63ACD5FA8-A044','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'PF63ACD5FA8-A048',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'PF63ACD5FA8-A024','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'PF63ACD5FA8-A037',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'PF63ACD5FA8-A020',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'PF63ACD5FA8-A011','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'PF63ACD5FA8-A019',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(11,'PF63ACD5FA8-A034','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'PF63ACD5FA8-A008',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(12,'PF63ACD5FA8-A040','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(12,'PF63ACD5FA8-A035',3.0);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PE7BE7302C8-WC02','Fabrication Cell 2',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PE7BE7302C8-WC03','Precision Bench 3',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PE7BE7302C8-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE7BE7302C8-WTR-ACC-105',NULL,22.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE7BE7302C8-WTR-DPU-006',NULL,75.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE7BE7302C8-WTR-DRC-118',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE7BE7302C8-WTR-FHB-110',NULL,25.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE7BE7302C8-WTR-PSA-121',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A001',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A002',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A003',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A004',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A005',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A006',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A007',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A008',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A009',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A010',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A011',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A012',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A013',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A014',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A015',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A016',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A017',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A018',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A019',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A020',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A021',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A022',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A023',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A024',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A025',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A026',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A027',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A028',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A029',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A030',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A031',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A032',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A033',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A034',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A035',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A036',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A037',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A038',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A039',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A040',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A041',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A042',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A043',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A044',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A045',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A046',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A047',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A048',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A049',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF63ACD5FA8-A050',NULL,14.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'rE7BE7302C8_c01','PE7BE7302C8-WTR-DPU-006',21,8,95037.71,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'rE7BE7302C8_c02','PE7BE7302C8-WTR-DPU-006',15,8,70418.48,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'rE7BE7302C8_c03','PE7BE7302C8-WTR-DPU-006',20,9,90629.67,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'rE7BE7302C8_c04','PE7BE7302C8-WTR-DPU-006',16,9,75454.6,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'rE7BE7302C8_c05','PE7BE7302C8-WTR-DPU-006',17,11,77803.91,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'rE7BE7302C8_c06','PE7BE7302C8-WTR-DPU-006',15,12,71921.76,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'rE7BE7302C8_c07','PE7BE7302C8-WTR-DPU-006',17,13,77265.94,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'rE7BE7302C8_c08','PE7BE7302C8-WTR-DPU-006',23,14,107818.74,NULL);
