-- agentic-labs/erp-bench scenario 2035: Mobile Lab Cart Workstation
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r7B561D27DB_c01','Ashford Reserve','customer',0,12820.96,NULL,NULL,'orders@ashfordreserve.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r7B561D27DB_c02','Prism Conservatory','customer',0,29597.32,NULL,NULL,'orders@prismconservatory.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r7B561D27DB_c03','Forge Outfitters','customer',0,18132.07,NULL,NULL,'orders@forgeoutfitters.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r7B561D27DB_c04','Alloy Greenhouse','customer',0,17084.65,NULL,NULL,'orders@alloygreenhouse.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r7B561D27DB_c05','Trident Studios East','customer',0,21918.17,NULL,NULL,'orders@tridentstudioseast.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r7B561D27DB_c06','Zenith Ventures','customer',0,18909.32,NULL,NULL,'orders@zenithventures.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r7B561D27DB_c07','Atlas Technologies','customer',0,22557.07,NULL,NULL,'orders@atlastechnologies.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r7B561D27DB_c08','Beacon Theater','customer',0,15754.61,NULL,NULL,'orders@beacontheater.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r7B561D27DB_c09','Haven Innovations','customer',0,21967.67,NULL,NULL,'orders@haveninnovations.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r7B561D27DB_c10','Alpine Solutions Group','customer',0,29074.16,NULL,NULL,'orders@alpinesolutionsgroup.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p01','Sierra Engineering Field Ops','customer',0,NULL,NULL,NULL,'contact@sierraengineering.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p02','Aurora Manufacturing Tooling Center','customer',0,NULL,NULL,NULL,'contact@auroramanufacturing.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p03','Bronze Manufacturing Field Ops','customer',0,NULL,NULL,NULL,'contact@bronzemanufacturing.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p04','Drift Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@driftassembly.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p05','Echo Solutions Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@echosolutions.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p06','Chrome Industries Test Facility','customer',0,NULL,NULL,NULL,'contact@chromeindustries.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p07','Hartland Manufacturing Test Facility','customer',0,NULL,NULL,NULL,'contact@hartlandmanufacturing.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p08','Scion Production Tooling Center','customer',0,NULL,NULL,NULL,'contact@scionproduction.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p09','Millbrook Technologies Quality Lab','customer',0,NULL,NULL,NULL,'contact@millbrooktechnologies.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p10','Nimbus Solutions Test Facility','customer',0,NULL,NULL,NULL,'contact@nimbussolutions.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p11','Riverdale Production Quality Lab','customer',0,NULL,NULL,NULL,'contact@riverdaleproduction.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p12','Onyx Industries R&D Workshop','customer',0,NULL,NULL,NULL,'contact@onyxindustries.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p13','Noble Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@nobleassembly.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p14','Flint Engineering Prototype Shop','customer',0,NULL,NULL,NULL,'contact@flintengineering.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p15','Comet Technologies R&D Workshop','customer',0,NULL,NULL,NULL,'contact@comettechnologies.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p16','Spark Solutions HQ Procurement','customer',0,NULL,NULL,NULL,'contact@sparksolutions.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p17','Stonewall Manufacturing Tooling Center','customer',0,NULL,NULL,NULL,'contact@stonewallmanufacturing.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p18','Flux Engineering Test Facility','customer',0,NULL,NULL,NULL,'contact@fluxengineering.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p19','Meridian Manufacturing Tooling Center','customer',0,NULL,NULL,NULL,'contact@meridianmanufacturing.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p20','Ironwood Production Site Logistics','customer',0,NULL,NULL,NULL,'contact@ironwoodproduction.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p21','Ivory Production Field Ops','customer',0,NULL,NULL,NULL,'contact@ivoryproduction.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p22','Borough Manufacturing R&D Workshop','customer',0,NULL,NULL,NULL,'contact@boroughmanufacturing.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p23','Horizon Assembly Site Logistics','customer',0,NULL,NULL,NULL,'contact@horizonassembly.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p24','Copper Services HQ Procurement','customer',0,NULL,NULL,NULL,'contact@copperservices.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p25','Fairview Engineering Site Logistics','customer',0,NULL,NULL,NULL,'contact@fairviewengineering.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p26','Cascade Manufacturing Quality Lab','customer',0,NULL,NULL,NULL,'contact@cascademanufacturing.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p27','Crown Solutions HQ Procurement','customer',0,NULL,NULL,NULL,'contact@crownsolutions.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p28','Metro Engineering Prototype Shop','customer',0,NULL,NULL,NULL,'contact@metroengineering.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p29','Ember Fabrication Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@emberfabrication.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p30','Arbor Solutions Field Ops','customer',0,NULL,NULL,NULL,'contact@arborsolutions.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p31','Cardinal Industries Site Logistics','customer',0,NULL,NULL,NULL,'contact@cardinalindustries.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p32','Equinox Engineering Quality Lab','customer',0,NULL,NULL,NULL,'contact@equinoxengineering.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p33','Keystone Engineering R&D Workshop','customer',0,NULL,NULL,NULL,'contact@keystoneengineering.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p34','Stratos Solutions Quality Lab','customer',0,NULL,NULL,NULL,'contact@stratossolutions.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p35','Peak Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@peakassembly.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p36','Arc Operations Tooling Center','customer',0,NULL,NULL,NULL,'contact@arcoperations.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p37','Iron Assembly Site Logistics','customer',0,NULL,NULL,NULL,'contact@ironassembly.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p38','Pacific Technologies Prototype Shop','customer',0,NULL,NULL,NULL,'contact@pacifictechnologies.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p39','Vantage Operations Tooling Center','customer',0,NULL,NULL,NULL,'contact@vantageoperations.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p40','Pivot Operations Test Facility','customer',0,NULL,NULL,NULL,'contact@pivotoperations.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p41','Marble Manufacturing Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@marblemanufacturing.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p42','Eclipse Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@eclipseassembly.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p43','Pinnacle Operations Field Ops','customer',0,NULL,NULL,NULL,'contact@pinnacleoperations.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p44','Sentinel Production Tooling Center','customer',0,NULL,NULL,NULL,'contact@sentinelproduction.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p45','Granite Fabrication Site Logistics','customer',0,NULL,NULL,NULL,'contact@granitefabrication.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p46','Helix Production Prototype Shop','customer',0,NULL,NULL,NULL,'contact@helixproduction.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p47','Northbridge Technologies Quality Lab','customer',0,NULL,NULL,NULL,'contact@northbridgetechnologies.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p48','Arrow Solutions Site Logistics','customer',0,NULL,NULL,NULL,'contact@arrowsolutions.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p49','Spire Solutions Quality Lab','customer',0,NULL,NULL,NULL,'contact@spiresolutions.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0E66EA3C3C_p50','Globe Fabrication Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@globefabrication.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r7B561D27DB_q01','Opal Industries','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r7B561D27DB_q02','Garnet Exporters','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r7B561D27DB_q03','Baseline Transport','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r7B561D27DB_q04','Summit Solutions','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r7B561D27DB_q05','Jade Procurement','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r7B561D27DB_q06','Apex Materials','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q01','Element Logistics','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q02','Cipher Trading','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q03','Titan Parts Co','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q04','Raven Sourcing','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q05','Slate Networks','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q06','Clearwater Networks','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q07','Brookfield Transit','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q08','Blaze Sourcing','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q09','Quartz Sourcing','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q10','Quantum Carriers','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q11','Polar Supply','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q12','Westfield Parts Co','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q13','Axis Carriers','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q14','Solace Resources','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q15','Compass Carriers','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q16','Oakmont Procurement','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q17','Lumen Networks','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q18','Anvil Logistics','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q19','Thornton Trading','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q20','Baltic Supply','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q21','Dune Logistics','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q22','Ridge Distribution','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q23','Citadel Parts Co','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q24','Aether Carriers','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q25','Sterling Procurement','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q26','Matrix Trading','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q27','Coral Components','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q28','Circuit Logistics','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q29','Sapphire Resources','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q30','Cobalt Procurement','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q31','Terra Wholesale','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q32','Conduit Networks','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q33','Cedar Transit','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q34','Orbital Procurement','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q35','Crest Distribution','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q36','Lance Wholesale','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q37','Canton Materials','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q38','Evergreen Resources','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q39','Lakewood Distribution','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q40','Aegis Wholesale','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q41','Lattice Procurement','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q42','Velocity Networks','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q43','Silverline Wholesale','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q44','Vertex Materials','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q45','Ridgeline Parts Co','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q46','Redstone Parts Co','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q47','Trellis Materials','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q48','Indigo Distribution','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q49','Ironside Transit','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0E66EA3C3C_q50','Ledger Wholesale','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P7B561D27DB-LAB-MLC-004','Mobile Lab Cart Workstation','Laboratory Equipment','consu',1019.86,517.82,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'P7B561D27DB-LAB-MLC-004','r7B561D27DB_q01','Priority Shuttle lane (9d transit, 14-31 units)',9,14.0,31.0,588.45);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'P7B561D27DB-LAB-MLC-004','r7B561D27DB_q02','Express Air lane (7d transit, 5-78 units)',7,5.0,78.0,744.05);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'P7B561D27DB-LAB-MLC-004','r7B561D27DB_q03','Bulk Container lane (25d transit, 95-96 units)',25,95.0,96.0,373.39);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'P7B561D27DB-LAB-MLC-004','r7B561D27DB_q04','Regional Cross-Dock lane (14d transit, 6-25 units)',14,6.0,25.0,537.98);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'P7B561D27DB-LAB-MLC-004','r7B561D27DB_q05','Economy Ocean lane (23d transit, 11-32 units)',23,11.0,32.0,416.68);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'P7B561D27DB-LAB-MLC-004','r7B561D27DB_q06','Bulk Container lane (25d transit, 95-95 units)',25,95.0,95.0,426.2);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A001','Single-Stage Containment Tray','Replacement Parts','consu',283.75,188.72,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'P0E66EA3C3C-A001','r0E66EA3C3C_q01','Bulk shipment',4,1.0,24.0,183.48);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A002','Commercial Valve Assembly','Pneumatic Components','consu',257.2,169.78,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'P0E66EA3C3C-A002','r0E66EA3C3C_q02','Cross-dock',5,1.0,24.0,178.64);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A003','Narrow-Body Support Frame','Electrical Components','consu',181.76,128.52,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'P0E66EA3C3C-A003','r0E66EA3C3C_q03','Regional lane',5,1.0,24.0,123.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A004','Modular Reagent Shelf Unit','Fasteners and Fixings','consu',356.19,256.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'P0E66EA3C3C-A004','r0E66EA3C3C_q04','Regional lane',5,1.0,24.0,245.48);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A005','Food-Grade Resin Worktop Panel','Mechanical Components','consu',404.48,216.16,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'P0E66EA3C3C-A005','r0E66EA3C3C_q05','Express route',6,1.0,24.0,210.34);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A006','Self-Lubricating Utility Channel Kit','Electrical Components','consu',216.89,115.89,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'P0E66EA3C3C-A006','r0E66EA3C3C_q06','Scheduled freight',5,1.0,24.0,113.98);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A007','Heat-Treated Spill Containment Tray','Maintenance Supplies','consu',415.27,218.66,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'P0E66EA3C3C-A007','r0E66EA3C3C_q07','Local pickup',6,1.0,24.0,221.56);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A008','UV-Stable Slide Mechanism','Industrial Spare Parts','consu',275.82,165.54,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'P0E66EA3C3C-A008','r0E66EA3C3C_q08','Warehouse direct',3,1.0,24.0,171.76);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A009','High-Performance with Drain Fitting','Maintenance Supplies','consu',225.11,134.15,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'P0E66EA3C3C-A009','r0E66EA3C3C_q09','Warehouse direct',6,1.0,24.0,132.39);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A010','Corrosion-Resistant Sink Basin Insert','Replacement Parts','consu',283.66,181.81,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'P0E66EA3C3C-A010','r0E66EA3C3C_q10','Cross-dock',7,1.0,24.0,191.88);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A011','Pressure-Balanced Valve Assembly','Hardware Accessories','consu',296.63,207.16,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'P0E66EA3C3C-A011','r0E66EA3C3C_q11','Warehouse direct',8,1.0,24.0,216.48);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A012','Heavy-Duty Slide Mechanism','Mechanical Components','consu',206.77,123.73,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'P0E66EA3C3C-A012','r0E66EA3C3C_q12','Local pickup',4,1.0,24.0,130.52);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A013','Double-Row Containment Tray','Replacement Parts','consu',183.28,108.02,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'P0E66EA3C3C-A013','r0E66EA3C3C_q13','Bulk shipment',3,1.0,24.0,103.51);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A014','Extended-Life Channel Kit','Maintenance Supplies','consu',326.05,207.54,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'P0E66EA3C3C-A014','r0E66EA3C3C_q14','Regional lane',5,1.0,24.0,223.5);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A015','Metric Containment Tray','Mechanical Components','consu',328.41,190.35,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'P0E66EA3C3C-A015','r0E66EA3C3C_q15','Scheduled freight',3,1.0,24.0,202.7);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A016','Spring-Loaded Reagent Shelf Unit','Industrial Spare Parts','consu',208.0,118.62,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'P0E66EA3C3C-A016','r0E66EA3C3C_q16','Local pickup',5,1.0,24.0,122.94);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A017','Wide-Body with Drain Fitting','Maintenance Supplies','consu',225.65,132.2,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'P0E66EA3C3C-A017','r0E66EA3C3C_q17','Cross-dock',3,1.0,24.0,135.5);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A018','Compact Steel Support Frame','Maintenance Supplies','consu',225.6,156.3,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'P0E66EA3C3C-A018','r0E66EA3C3C_q18','Regional lane',8,1.0,24.0,150.42);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A019','High-Torque Accessory Panel','Industrial Spare Parts','consu',377.35,261.26,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'P0E66EA3C3C-A019','r0E66EA3C3C_q19','Cross-dock',4,1.0,24.0,259.9);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A020','High-Temp Reagent Shelf Unit','Electrical Components','consu',380.71,253.66,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'P0E66EA3C3C-A020','r0E66EA3C3C_q20','Scheduled freight',3,1.0,24.0,257.47);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A021','Non-Magnetic Pegboard Accessory Panel','Electrical Components','consu',230.18,158.29,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'P0E66EA3C3C-A021','r0E66EA3C3C_q21','Scheduled freight',7,1.0,24.0,159.78);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A022','Tapered Drawer Slide Mechanism','Fasteners and Fixings','consu',310.63,217.12,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'P0E66EA3C3C-A022','r0E66EA3C3C_q22','Standard delivery',4,1.0,24.0,222.81);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A023','Premium Static Mat','Maintenance Supplies','consu',181.46,106.39,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'P0E66EA3C3C-A023','r0E66EA3C3C_q23','Bulk shipment',8,1.0,24.0,109.38);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A024','Adjustable Channel Kit','Pneumatic Components','consu',399.55,231.58,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'P0E66EA3C3C-A024','r0E66EA3C3C_q24','Local pickup',3,1.0,24.0,233.27);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A025','Cold-Rolled Slide Mechanism','Seals and Gaskets','consu',291.0,154.21,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'P0E66EA3C3C-A025','r0E66EA3C3C_q25','Standard delivery',5,1.0,24.0,160.14);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A026','Hardened Sink Basin Insert','Hardware Accessories','consu',272.6,182.02,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'P0E66EA3C3C-A026','r0E66EA3C3C_q26','Standard delivery',7,1.0,24.0,190.69);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A027','Zero-Backlash Slide Mechanism','Hardware Accessories','consu',415.74,279.39,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'P0E66EA3C3C-A027','r0E66EA3C3C_q27','Scheduled freight',5,1.0,24.0,267.94);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A028','Stainless Valve Assembly','Replacement Parts','consu',364.66,194.61,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'P0E66EA3C3C-A028','r0E66EA3C3C_q28','Scheduled freight',3,1.0,24.0,190.71);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A029','Low-Friction Chemical Resistant Top','Mechanical Components','consu',364.06,248.96,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'P0E66EA3C3C-A029','r0E66EA3C3C_q29','Bulk shipment',5,1.0,24.0,243.5);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A030','Threaded Accessory Panel','Maintenance Supplies','consu',402.69,211.06,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'P0E66EA3C3C-A030','r0E66EA3C3C_q30','Express route',5,1.0,24.0,208.08);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A031','Anodized Static Mat','Hardware Accessories','consu',395.34,216.29,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'P0E66EA3C3C-A031','r0E66EA3C3C_q31','Standard delivery',3,1.0,24.0,209.46);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A032','Lightweight Steel Support Frame','Maintenance Supplies','consu',190.94,107.19,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'P0E66EA3C3C-A032','r0E66EA3C3C_q32','Express route',6,1.0,24.0,114.8);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A033','Low-Noise Reagent Shelf Unit','Replacement Parts','consu',266.35,159.02,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'P0E66EA3C3C-A033','r0E66EA3C3C_q33','Local pickup',6,1.0,24.0,151.57);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A034','High-Flow Valve Assembly','Industrial Spare Parts','consu',183.09,102.08,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'P0E66EA3C3C-A034','r0E66EA3C3C_q34','Bulk shipment',7,1.0,24.0,98.63);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A035','Cleanroom Anti Static Mat','Industrial Spare Parts','consu',263.02,156.62,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'P0E66EA3C3C-A035','r0E66EA3C3C_q35','Warehouse direct',4,1.0,24.0,154.13);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A036','Impact-Rated Steel Support Frame','Replacement Parts','consu',325.29,212.13,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'P0E66EA3C3C-A036','r0E66EA3C3C_q36','Local pickup',7,1.0,24.0,203.11);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A037','Snap-Fit Basin Insert','Power Transmission','consu',299.44,160.93,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'P0E66EA3C3C-A037','r0E66EA3C3C_q37','Regional lane',4,1.0,24.0,171.35);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A038','Low-Profile Support Frame','Electrical Components','consu',311.22,182.75,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'P0E66EA3C3C-A038','r0E66EA3C3C_q38','Local pickup',8,1.0,24.0,193.66);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A039','Medical-Grade Pegboard Accessory Panel','Seals and Gaskets','consu',200.58,113.62,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'P0E66EA3C3C-A039','r0E66EA3C3C_q39','Local pickup',4,1.0,24.0,115.33);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A040','Weatherproof Steel Support Frame','Power Transmission','consu',195.09,124.24,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'P0E66EA3C3C-A040','r0E66EA3C3C_q40','Standard delivery',3,1.0,24.0,119.21);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A041','Standard Reagent Shelf Unit','Hardware Accessories','consu',202.61,125.18,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'P0E66EA3C3C-A041','r0E66EA3C3C_q41','Local pickup',8,1.0,24.0,129.58);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A042','Dual-Stage Slide Mechanism','Fasteners and Fixings','consu',253.95,157.03,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'P0E66EA3C3C-A042','r0E66EA3C3C_q42','Cross-dock',5,1.0,24.0,149.68);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A043','Thermal-Guard Channel Kit','Power Transmission','consu',287.5,180.11,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'P0E66EA3C3C-A043','r0E66EA3C3C_q43','Local pickup',4,1.0,24.0,187.38);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A044','Reinforced Chemical Resistant Top','Industrial Spare Parts','consu',385.33,267.62,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'P0E66EA3C3C-A044','r0E66EA3C3C_q44','Cross-dock',7,1.0,24.0,258.44);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A045','Rapid-Lock Utility Channel Kit','Mechanical Components','consu',198.54,112.21,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'P0E66EA3C3C-A045','r0E66EA3C3C_q45','Express route',3,1.0,24.0,120.94);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A046','Economy Slide Mechanism','Power Transmission','consu',372.14,241.38,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'P0E66EA3C3C-A046','r0E66EA3C3C_q46','Local pickup',8,1.0,24.0,248.67);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A047','Quick-Release Drawer Slide Mechanism','Fasteners and Fixings','consu',324.13,207.27,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'P0E66EA3C3C-A047','r0E66EA3C3C_q47','Regional lane',6,1.0,24.0,202.99);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A048','Powder-Coated Anti Static Mat','Mechanical Components','consu',300.21,167.88,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'P0E66EA3C3C-A048','r0E66EA3C3C_q48','Local pickup',4,1.0,24.0,177.21);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A049','High-Cycle Slide Mechanism','Mechanical Components','consu',207.35,116.71,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'P0E66EA3C3C-A049','r0E66EA3C3C_q49','Local pickup',5,1.0,24.0,120.54);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0E66EA3C3C-A050','Low-Temp Resin Worktop Panel','Pneumatic Components','consu',207.56,142.39,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'P0E66EA3C3C-A050','r0E66EA3C3C_q50','Standard delivery',6,1.0,24.0,137.94);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'P0E66EA3C3C-A045','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P0E66EA3C3C-A002',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'P0E66EA3C3C-A001','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P0E66EA3C3C-A022',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P0E66EA3C3C-A045',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'P0E66EA3C3C-A017','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P0E66EA3C3C-A026',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P0E66EA3C3C-A029',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'P0E66EA3C3C-A037','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'P0E66EA3C3C-A013',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'P0E66EA3C3C-A042','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P0E66EA3C3C-A012',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P0E66EA3C3C-A018',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'P0E66EA3C3C-A004','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P0E66EA3C3C-A041',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'P0E66EA3C3C-A022','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'P0E66EA3C3C-A021',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'P0E66EA3C3C-A011',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'P0E66EA3C3C-A048','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P0E66EA3C3C-A017',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P0E66EA3C3C-A003',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'P0E66EA3C3C-A021','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P0E66EA3C3C-A035',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P0E66EA3C3C-A050',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'P0E66EA3C3C-A030','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P0E66EA3C3C-A016',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P0E66EA3C3C-A018',1.0);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P7B561D27DB-LAB-MLC-004',NULL,89.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A001',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A002',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A003',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A004',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A005',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A006',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A007',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A008',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A009',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A010',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A011',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A012',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A013',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A014',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A015',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A016',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A017',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A018',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A019',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A020',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A021',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A022',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A023',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A024',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A025',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A026',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A027',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A028',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A029',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A030',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A031',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A032',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A033',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A034',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A035',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A036',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A037',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A038',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A039',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A040',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A041',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A042',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A043',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A044',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A045',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A046',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A047',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A048',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A049',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0E66EA3C3C-A050',NULL,10.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'r7B561D27DB_c01','P7B561D27DB-LAB-MLC-004',14,8,12820.96,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'r7B561D27DB_c02','P7B561D27DB-LAB-MLC-004',26,8,29597.32,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'r7B561D27DB_c03','P7B561D27DB-LAB-MLC-004',16,9,18132.07,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'r7B561D27DB_c04','P7B561D27DB-LAB-MLC-004',16,9,17084.65,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'r7B561D27DB_c05','P7B561D27DB-LAB-MLC-004',21,10,21918.17,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'r7B561D27DB_c06','P7B561D27DB-LAB-MLC-004',17,12,18909.32,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'r7B561D27DB_c07','P7B561D27DB-LAB-MLC-004',20,12,22557.07,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'r7B561D27DB_c08','P7B561D27DB-LAB-MLC-004',14,12,15754.61,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(9,'r7B561D27DB_c09','P7B561D27DB-LAB-MLC-004',20,13,21967.67,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(10,'r7B561D27DB_c10','P7B561D27DB-LAB-MLC-004',26,13,29074.16,'draft');
