-- agentic-labs/erp-bench scenario 2092: Dust Containment Enclosure
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r443DA412E3_c01','Canton Robotics','customer',0,57759.83,NULL,NULL,'orders@cantonrobotics.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r443DA412E3_c02','Lakewood Research','customer',0,68022.9,NULL,NULL,'orders@lakewoodresearch.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r443DA412E3_c03','Metro Studios North','customer',0,44118.45,NULL,NULL,'orders@metrostudiosnorth.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r443DA412E3_c04','Mosaic Workspaces','customer',0,47030.5,NULL,NULL,'orders@mosaicworkspaces.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r443DA412E3_c05','Garnet Supply Co','customer',0,80760.23,NULL,NULL,'orders@garnetsupplyco.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r443DA412E3_c06','Aegis Society','customer',0,53325.52,NULL,NULL,'orders@aegissociety.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r443DA412E3_c07','Pinnacle Atelier','customer',0,47888.0,NULL,NULL,'orders@pinnacleatelier.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r443DA412E3_c08','Oakmont Media','customer',0,53721.98,NULL,NULL,'orders@oakmontmedia.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r443DA412E3_c09','Ember Trading Co','customer',0,45029.62,NULL,NULL,'orders@embertradingco.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r443DA412E3_c10','Axis Engineering','customer',0,61089.49,NULL,NULL,'orders@axisengineering.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p01','Helix Operations Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@helixoperations.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p02','Slate Production Test Facility','customer',0,NULL,NULL,NULL,'contact@slateproduction.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p03','Baseline Fabrication Field Ops','customer',0,NULL,NULL,NULL,'contact@baselinefabrication.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p04','Opal Technologies Field Ops','customer',0,NULL,NULL,NULL,'contact@opaltechnologies.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p05','Silverline Manufacturing Quality Lab','customer',0,NULL,NULL,NULL,'contact@silverlinemanufacturing.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p06','Bridgeway Assembly Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@bridgewayassembly.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p07','Monarch Operations Test Facility','customer',0,NULL,NULL,NULL,'contact@monarchoperations.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p08','Catalyst Manufacturing HQ Procurement','customer',0,NULL,NULL,NULL,'contact@catalystmanufacturing.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p09','Millbrook Services Quality Lab','customer',0,NULL,NULL,NULL,'contact@millbrookservices.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p10','Flint Industries Tooling Center','customer',0,NULL,NULL,NULL,'contact@flintindustries.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p11','Citadel Engineering Quality Lab','customer',0,NULL,NULL,NULL,'contact@citadelengineering.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p12','Orbital Production R&D Workshop','customer',0,NULL,NULL,NULL,'contact@orbitalproduction.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p13','Sierra Fabrication Field Ops','customer',0,NULL,NULL,NULL,'contact@sierrafabrication.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p14','Sentinel Solutions Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@sentinelsolutions.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p15','Aether Manufacturing Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@aethermanufacturing.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p16','Clearwater Engineering Test Facility','customer',0,NULL,NULL,NULL,'contact@clearwaterengineering.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p17','Copper Operations Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@copperoperations.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p18','Sterling Fabrication Quality Lab','customer',0,NULL,NULL,NULL,'contact@sterlingfabrication.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p19','Ridge Production Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@ridgeproduction.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p20','Crest Technologies Prototype Shop','customer',0,NULL,NULL,NULL,'contact@cresttechnologies.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p21','Crown Solutions Field Ops','customer',0,NULL,NULL,NULL,'contact@crownsolutions.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p22','Meridian Technologies Field Ops','customer',0,NULL,NULL,NULL,'contact@meridiantechnologies.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p23','Circuit Production Test Facility','customer',0,NULL,NULL,NULL,'contact@circuitproduction.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p24','Thornton Industries Quality Lab','customer',0,NULL,NULL,NULL,'contact@thorntonindustries.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p25','Lance Production Quality Lab','customer',0,NULL,NULL,NULL,'contact@lanceproduction.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p26','Nimbus Technologies Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@nimbustechnologies.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p27','Echo Production Field Ops','customer',0,NULL,NULL,NULL,'contact@echoproduction.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p28','Ridgeline Technologies Quality Lab','customer',0,NULL,NULL,NULL,'contact@ridgelinetechnologies.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p29','Drift Fabrication Tooling Center','customer',0,NULL,NULL,NULL,'contact@driftfabrication.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p30','Westfield Operations Site Logistics','customer',0,NULL,NULL,NULL,'contact@westfieldoperations.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p31','Trident Assembly Tooling Center','customer',0,NULL,NULL,NULL,'contact@tridentassembly.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p32','Ivory Technologies Quality Lab','customer',0,NULL,NULL,NULL,'contact@ivorytechnologies.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p33','Polar Fabrication Tooling Center','customer',0,NULL,NULL,NULL,'contact@polarfabrication.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p34','Titan Industries HQ Procurement','customer',0,NULL,NULL,NULL,'contact@titanindustries.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p35','Vertex Technologies HQ Procurement','customer',0,NULL,NULL,NULL,'contact@vertextechnologies.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p36','Dune Manufacturing Quality Lab','customer',0,NULL,NULL,NULL,'contact@dunemanufacturing.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p37','Jade Fabrication Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@jadefabrication.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p38','Indigo Engineering Tooling Center','customer',0,NULL,NULL,NULL,'contact@indigoengineering.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p39','Iron Manufacturing HQ Procurement','customer',0,NULL,NULL,NULL,'contact@ironmanufacturing.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p40','Bayshore Fabrication Field Ops','customer',0,NULL,NULL,NULL,'contact@bayshorefabrication.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p41','Borough Operations Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@boroughoperations.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p42','Zenith Industries Test Facility','customer',0,NULL,NULL,NULL,'contact@zenithindustries.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p43','Solace Engineering Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@solaceengineering.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p44','Adjacent Customer 1 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer001.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p45','Adjacent Customer 2 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer002.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p46','Adjacent Customer 3 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer003.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p47','Adjacent Customer 4 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer004.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p48','Adjacent Customer 5 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer005.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p49','Adjacent Customer 6 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer006.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC71DC8D370_p50','Adjacent Customer 7 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer007.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q01','Ironside Commodities','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q02','Cedar Packagers','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q03','Scion Haulage','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q04','Oxide Distribution','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q05','Peak Warehouse','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q06','Pivot Wholesalers','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q07','Blaze Integrators','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q08','Stonewall Transport','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q09','Steel Exporters','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q10','Spectra Movers','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q11','Hartland Assemblies','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q12','Alloy Provisions','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q13','Osprey Forwarders','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q14','Stratos Fulfillment','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q15','Vantage Conveyance','vendor',15,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q16','Terra Warehousing','vendor',16,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q17','Cascade Partners','vendor',17,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q18','Riverdale Logistics','vendor',18,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q19','Apex Shipping','vendor',19,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q20','Grove Fabrication','vendor',20,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q21','Ashford Materials','vendor',21,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q22','Globe Operations','vendor',22,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q23','Matrix Importers','vendor',23,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q24','Sapphire Merchants','vendor',24,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q25','Skyline Procurement','vendor',25,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q26','Crestview Components','vendor',26,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q27','Pacific Transit','vendor',27,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r443DA412E3_q28','Marble Depot','vendor',28,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q01','Spire Transit','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q02','Nexus Distribution','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q03','Gateway Networks','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q04','Summit Components','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q05','Alpine Parts Co','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q06','Onyx Procurement','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q07','Element Materials','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q08','Equinox Transit','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q09','Arc Procurement','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q10','Fairview Carriers','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q11','Cosmo Carriers','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q12','Trellis Sourcing','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q13','Atlas Trading','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q14','Anvil Transit','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q15','Lattice Supply','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q16','Velocity Wholesale','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q17','Northbridge Logistics','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q18','Comet Sourcing','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q19','Baltic Components','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q20','Conduit Procurement','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q21','Quantum Wholesale','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q22','Bronze Parts Co','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q23','Quartz Resources','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q24','Granite Networks','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q25','Brookfield Freight','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q26','Haven Parts Co','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q27','Keystone Networks','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q28','Prism Wholesale','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q29','Redstone Transit','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q30','Cardinal Carriers','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q31','Chrome Materials','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q32','Beacon Wholesale','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q33','Forge Materials','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q34','Raven Trading','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q35','Ironwood Distribution','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q36','Eclipse Distribution','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q37','Flux Carriers','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q38','Cobalt Transit','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q39','Ledger Supply','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q40','Spark Freight','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q41','Arrow Resources','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q42','Evergreen Materials','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q43','Coral Resources','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q44','Noble Parts Co','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q45','Aurora Distribution','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q46','Arbor Procurement','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q47','Cipher Networks','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q48','Compass Networks','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q49','Lumen Trading','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC71DC8D370_q50','Horizon Resources','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P443DA412E3-SAF-DCE-009','Dust Containment Enclosure','Industrial Equipment','consu',3055.06,1975.99,'buy,manufacture',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'P443DA412E3-SAF-DCE-009','r443DA412E3_q01','Priority Shuttle lane (9d transit, 7-70 units)',9,7.0,70.0,2153.27);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'P443DA412E3-SAF-DCE-009','r443DA412E3_q02','Express Air lane (8d transit, 5-25 units)',8,5.0,25.0,2557.39);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'P443DA412E3-SAF-DCE-009','r443DA412E3_q03','Bulk Container lane (23d transit, 85-95 units)',23,85.0,95.0,1037.11);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'P443DA412E3-SAF-DCE-009','r443DA412E3_q04','Regional Cross-Dock lane (15d transit, 6-7 units)',15,6.0,7.0,2157.35);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'P443DA412E3-SAF-DCE-009','r443DA412E3_q05','Economy Ocean lane (23d transit, 7-72 units)',23,7.0,72.0,1676.58);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'P443DA412E3-SAF-DCE-009','r443DA412E3_q06','Microfactory Build-to-Order lane (7d transit, 5-38 units)',7,5.0,38.0,2604.55);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P443DA412E3-SAF-PCB-102','Post Column with Base Plate','Industrial Equipment','consu',130.57,50.74,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'P443DA412E3-SAF-PCB-102','r443DA412E3_q07','Rapid Works (3d)',3,5.0,56.0,76.5);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'P443DA412E3-SAF-PCB-102','r443DA412E3_q08','Domestic Supply (3d)',3,17.0,138.0,54.11);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'P443DA412E3-SAF-PCB-102','r443DA412E3_q09','Import Consolidator (3d)',3,29.0,63.0,50.74);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'P443DA412E3-SAF-PCB-102','r443DA412E3_q10','Hybrid Fabricators (3d)',3,15.0,31.0,81.91);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P443DA412E3-SAF-SLA-112','Solenoid Lock Assembly','Industrial Equipment','consu',190.48,82.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'P443DA412E3-SAF-SLA-112','r443DA412E3_q11','Rapid Works (3d)',3,8.0,19.0,129.36);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'P443DA412E3-SAF-SLA-112','r443DA412E3_q12','Domestic Supply (3d)',3,19.0,68.0,96.68);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'P443DA412E3-SAF-SLA-112','r443DA412E3_q13','Hybrid Fabricators (3d)',3,18.0,40.0,115.93);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'P443DA412E3-SAF-SLA-112','r443DA412E3_q14','Import Consolidator (3d)',3,35.0,59.0,82.42);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P443DA412E3-SAF-CEG-121','Cable Entry Gland Plate','Industrial Equipment','consu',41.92,13.48,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'P443DA412E3-SAF-CEG-121','r443DA412E3_q15','Rapid Works (3d)',3,7.0,45.0,22.13);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'P443DA412E3-SAF-CEG-121','r443DA412E3_q16','Hybrid Fabricators (3d)',3,20.0,34.0,20.84);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'P443DA412E3-SAF-CEG-121','r443DA412E3_q17','Import Consolidator (3d)',3,33.0,101.0,13.48);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'P443DA412E3-SAF-CEG-121','r443DA412E3_q18','Domestic Supply (3d)',3,13.0,15.0,15.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P443DA412E3-SAF-AFL-122','Acoustic Foam Lining Panel','Industrial Equipment','consu',55.46,17.25,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'P443DA412E3-SAF-AFL-122','r443DA412E3_q19','Rapid Works (3d)',3,8.0,11.0,31.13);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'P443DA412E3-SAF-AFL-122','r443DA412E3_q20','Import Consolidator (3d)',3,35.0,95.0,17.25);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'P443DA412E3-SAF-AFL-122','r443DA412E3_q21','Hybrid Fabricators (3d)',3,20.0,50.0,27.7);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'P443DA412E3-SAF-AFL-122','r443DA412E3_q22','Domestic Supply (3d)',3,10.0,83.0,23.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P443DA412E3-SAF-TEB-125','Touch-Edge Safety Bumper Strip','Industrial Equipment','consu',46.94,20.85,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'P443DA412E3-SAF-TEB-125','r443DA412E3_q23','Rapid Works (2d)',2,11.0,85.0,22.52);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'P443DA412E3-SAF-TEB-125','r443DA412E3_q24','Hybrid Fabricators (3d)',3,9.0,190.0,21.21);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'P443DA412E3-SAF-TEB-125','r443DA412E3_q25','Domestic Supply (3d)',3,27.0,388.0,20.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P443DA412E3-SAF-TCR-129','Perimeter Guard Top Cap Rail','Industrial Equipment','consu',22.63,9.64,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'P443DA412E3-SAF-TCR-129','r443DA412E3_q26','Rapid Works (3d)',3,4.0,115.0,11.09);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'P443DA412E3-SAF-TCR-129','r443DA412E3_q27','Domestic Supply (3d)',3,22.0,98.0,9.64);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'P443DA412E3-SAF-TCR-129','r443DA412E3_q28','Hybrid Fabricators (3d)',3,17.0,65.0,10.68);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A001','Weatherproof Mesh Panel 4x8ft','Replacement Parts','consu',289.81,157.63,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'PC71DC8D370-A001','rC71DC8D370_q01','Scheduled freight',3,1.0,24.0,169.87);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A002','Low-Temp Panel 4x8ft','Replacement Parts','consu',182.92,107.07,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'PC71DC8D370-A002','rC71DC8D370_q02','Cross-dock',7,1.0,24.0,102.83);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A003','Impact-Rated Base Plate','Maintenance Supplies','consu',259.77,168.65,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'PC71DC8D370-A003','rC71DC8D370_q03','Bulk shipment',5,1.0,24.0,162.81);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A004','Cleanroom Switch Module','Power Transmission','consu',306.77,189.26,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'PC71DC8D370-A004','rC71DC8D370_q04','Express route',7,1.0,24.0,199.44);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A005','Sealed Bolt Kit','Pneumatic Components','consu',383.17,268.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'PC71DC8D370-A005','rC71DC8D370_q05','Express route',8,1.0,24.0,266.78);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A006','Thermal-Guard Vision Panel','Pneumatic Components','consu',329.12,196.18,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'PC71DC8D370-A006','rC71DC8D370_q06','Bulk shipment',4,1.0,24.0,198.34);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A007','Medical-Grade Latch Assembly','Replacement Parts','consu',387.11,228.7,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'PC71DC8D370-A007','rC71DC8D370_q07','Scheduled freight',3,1.0,24.0,228.31);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A008','Metric Bolt Kit','Maintenance Supplies','consu',297.45,210.62,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'PC71DC8D370-A008','rC71DC8D370_q08','Standard delivery',6,1.0,24.0,207.24);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A009','Powder-Coated Anchor Bolt Kit','Industrial Spare Parts','consu',202.72,138.32,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'PC71DC8D370-A009','rC71DC8D370_q09','Cross-dock',8,1.0,24.0,131.82);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A010','Dual-Stage Clamp Connector Set','Industrial Spare Parts','consu',384.64,209.76,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'PC71DC8D370-A010','rC71DC8D370_q10','Cross-dock',4,1.0,24.0,203.82);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A011','Stainless Gate Frame Assembly','Pneumatic Components','consu',403.95,253.02,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'PC71DC8D370-A011','rC71DC8D370_q11','Standard delivery',4,1.0,24.0,253.3);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A012','Hardened Base Plate','Pneumatic Components','consu',292.0,187.32,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'PC71DC8D370-A012','rC71DC8D370_q12','Scheduled freight',5,1.0,24.0,189.1);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A013','Double-Row Beacon Module','Industrial Spare Parts','consu',364.78,190.72,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'PC71DC8D370-A013','rC71DC8D370_q13','Cross-dock',3,1.0,24.0,195.94);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A014','Quick-Release Frame Assembly','Replacement Parts','consu',241.19,154.34,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'PC71DC8D370-A014','rC71DC8D370_q14','Express route',8,1.0,24.0,147.04);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A015','UV-Stable Interlock System','Fasteners and Fixings','consu',185.72,108.3,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'PC71DC8D370-A015','rC71DC8D370_q15','Local pickup',7,1.0,24.0,116.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A016','Zero-Backlash Bolt Kit','Electrical Components','consu',270.59,194.64,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'PC71DC8D370-A016','rC71DC8D370_q16','Express route',5,1.0,24.0,208.14);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A017','Flanged Clamp Connector Set','Mechanical Components','consu',331.65,203.07,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'PC71DC8D370-A017','rC71DC8D370_q17','Local pickup',8,1.0,24.0,212.28);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A018','Commercial Clamp Connector Set','Pneumatic Components','consu',389.63,260.62,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'PC71DC8D370-A018','rC71DC8D370_q18','Scheduled freight',4,1.0,24.0,279.98);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A019','Premium Bolt Kit','Replacement Parts','consu',205.62,121.51,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'PC71DC8D370-A019','rC71DC8D370_q19','Express route',6,1.0,24.0,126.21);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A020','Low-Profile Base Plate','Mechanical Components','consu',235.85,152.38,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'PC71DC8D370-A020','rC71DC8D370_q20','Bulk shipment',4,1.0,24.0,163.01);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A021','Compact Bolt Kit','Replacement Parts','consu',295.85,189.46,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'PC71DC8D370-A021','rC71DC8D370_q21','Local pickup',4,1.0,24.0,202.37);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A022','Tapered Panel 4x8ft','Electrical Components','consu',288.99,165.62,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'PC71DC8D370-A022','rC71DC8D370_q22','Express route',6,1.0,24.0,168.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A023','Snap-Fit Polycarbonate Vision Panel','Pneumatic Components','consu',298.02,156.08,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'PC71DC8D370-A023','rC71DC8D370_q23','Scheduled freight',3,1.0,24.0,151.54);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A024','Anodized Vision Panel','Pneumatic Components','consu',220.09,156.78,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'PC71DC8D370-A024','rC71DC8D370_q24','Standard delivery',8,1.0,24.0,165.05);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A025','Adjustable Key Interlock System','Fasteners and Fixings','consu',324.9,218.2,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'PC71DC8D370-A025','rC71DC8D370_q25','Local pickup',3,1.0,24.0,209.3);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A026','Wide-Body Interlock System','Hardware Accessories','consu',361.46,229.51,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'PC71DC8D370-A026','rC71DC8D370_q26','Scheduled freight',4,1.0,24.0,224.07);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A027','Standard Vision Panel','Mechanical Components','consu',292.38,192.94,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'PC71DC8D370-A027','rC71DC8D370_q27','Standard delivery',5,1.0,24.0,198.88);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A028','Universal Interlock Switch Module','Electrical Components','consu',192.32,131.67,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'PC71DC8D370-A028','rC71DC8D370_q28','Scheduled freight',6,1.0,24.0,130.29);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A029','Extended-Life Lock Assembly','Electrical Components','consu',282.94,200.83,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(57,'PC71DC8D370-A029','rC71DC8D370_q29','Local pickup',3,1.0,24.0,194.33);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A030','Precision Switch Module','Industrial Spare Parts','consu',358.13,226.35,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(58,'PC71DC8D370-A030','rC71DC8D370_q30','Bulk shipment',7,1.0,24.0,238.71);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A031','High-Temp Latch Assembly','Fasteners and Fixings','consu',312.47,201.59,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(59,'PC71DC8D370-A031','rC71DC8D370_q31','Express route',5,1.0,24.0,197.27);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A032','Anti-Vibration Light Beacon Module','Seals and Gaskets','consu',246.79,138.06,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(60,'PC71DC8D370-A032','rC71DC8D370_q32','Regional lane',8,1.0,24.0,141.35);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A033','Rapid-Lock Pull Switch','Seals and Gaskets','consu',224.2,126.56,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(61,'PC71DC8D370-A033','rC71DC8D370_q33','Bulk shipment',7,1.0,24.0,129.83);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A034','Single-Stage Lock Assembly','Industrial Spare Parts','consu',406.12,272.8,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(62,'PC71DC8D370-A034','rC71DC8D370_q34','Local pickup',8,1.0,24.0,261.08);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A035','Cold-Rolled Pull Switch','Hardware Accessories','consu',357.56,243.76,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(63,'PC71DC8D370-A035','rC71DC8D370_q35','Warehouse direct',3,1.0,24.0,257.03);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A036','Corrosion-Resistant Anchor Bolt Kit','Electrical Components','consu',192.41,106.71,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(64,'PC71DC8D370-A036','rC71DC8D370_q36','Local pickup',4,1.0,24.0,102.4);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A037','High-Performance Switch Module','Maintenance Supplies','consu',256.32,138.23,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(65,'PC71DC8D370-A037','rC71DC8D370_q37','Bulk shipment',3,1.0,24.0,140.78);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A038','Food-Grade Mesh Panel 4x8ft','Mechanical Components','consu',370.78,219.85,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(66,'PC71DC8D370-A038','rC71DC8D370_q38','Regional lane',3,1.0,24.0,210.87);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A039','Heat-Treated Door Latch Assembly','Mechanical Components','consu',201.43,122.48,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(67,'PC71DC8D370-A039','rC71DC8D370_q39','Bulk shipment',7,1.0,24.0,130.03);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A040','Low-Noise Clamp Connector Set','Seals and Gaskets','consu',369.82,230.84,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(68,'PC71DC8D370-A040','rC71DC8D370_q40','Warehouse direct',3,1.0,24.0,239.73);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A041','Economy with Base Plate','Fasteners and Fixings','consu',217.31,129.8,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(69,'PC71DC8D370-A041','rC71DC8D370_q41','Bulk shipment',7,1.0,24.0,136.2);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A042','Low-Friction Interlock System','Fasteners and Fixings','consu',242.67,131.02,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(70,'PC71DC8D370-A042','rC71DC8D370_q42','Local pickup',6,1.0,24.0,133.96);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A043','Narrow-Body Panel 4x8ft','Pneumatic Components','consu',414.23,294.24,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(71,'PC71DC8D370-A043','rC71DC8D370_q43','Scheduled freight',3,1.0,24.0,316.72);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A044','High-Torque Gate Frame Assembly','Electrical Components','consu',204.56,112.54,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(72,'PC71DC8D370-A044','rC71DC8D370_q44','Standard delivery',3,1.0,24.0,113.56);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A045','Industrial Switch Module','Power Transmission','consu',246.34,153.75,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(73,'PC71DC8D370-A045','rC71DC8D370_q45','Express route',3,1.0,24.0,147.48);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A046','Low-Flow Rope Pull Switch','Seals and Gaskets','consu',330.97,236.05,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(74,'PC71DC8D370-A046','rC71DC8D370_q46','Standard delivery',5,1.0,24.0,252.72);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A047','Modular Gate Frame Assembly','Maintenance Supplies','consu',237.52,134.83,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(75,'PC71DC8D370-A047','rC71DC8D370_q47','Cross-dock',6,1.0,24.0,130.79);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A048','High-Cycle Interlock Switch Module','Industrial Spare Parts','consu',411.24,293.77,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(76,'PC71DC8D370-A048','rC71DC8D370_q48','Express route',4,1.0,24.0,293.47);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A049','Non-Magnetic Door Latch Assembly','Replacement Parts','consu',180.33,99.36,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(77,'PC71DC8D370-A049','rC71DC8D370_q49','Express route',3,1.0,24.0,96.78);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC71DC8D370-A050','Spring-Loaded Connector Set','Mechanical Components','consu',411.43,293.34,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(78,'PC71DC8D370-A050','rC71DC8D370_q50','Scheduled freight',8,1.0,24.0,305.21);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'P443DA412E3-SAF-DCE-009','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P443DA412E3-SAF-PCB-102',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P443DA412E3-SAF-SLA-112',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P443DA412E3-SAF-CEG-121',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P443DA412E3-SAF-AFL-122',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P443DA412E3-SAF-TEB-125',4.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P443DA412E3-SAF-TCR-129',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'PC71DC8D370-A007','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PC71DC8D370-A034',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PC71DC8D370-A049',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'PC71DC8D370-A041','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'PC71DC8D370-A018',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'PC71DC8D370-A040',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'PC71DC8D370-A021','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'PC71DC8D370-A027',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'PC71DC8D370-A029',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'PC71DC8D370-A042','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'PC71DC8D370-A033',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'PC71DC8D370-A048','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'PC71DC8D370-A033',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'PC71DC8D370-A028','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'PC71DC8D370-A011',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'PC71DC8D370-A007',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'PC71DC8D370-A004','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'PC71DC8D370-A037',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'PC71DC8D370-A014','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'PC71DC8D370-A008',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'PC71DC8D370-A004',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'PC71DC8D370-A015','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'PC71DC8D370-A036',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(11,'PC71DC8D370-A001','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'PC71DC8D370-A024',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'PC71DC8D370-A014',1.0);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P443DA412E3-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P443DA412E3-WC02','Fabrication Cell 2',0,0,NULL,NULL);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P443DA412E3-SAF-AFL-122',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P443DA412E3-SAF-CEG-121',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P443DA412E3-SAF-DCE-009',NULL,80.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P443DA412E3-SAF-PCB-102',NULL,17.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P443DA412E3-SAF-SLA-112',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P443DA412E3-SAF-TCR-129',NULL,25.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P443DA412E3-SAF-TEB-125',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A001',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A002',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A003',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A004',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A005',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A006',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A007',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A008',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A009',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A010',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A011',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A012',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A013',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A014',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A015',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A016',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A017',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A018',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A019',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A020',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A021',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A022',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A023',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A024',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A025',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A026',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A027',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A028',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A029',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A030',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A031',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A032',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A033',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A034',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A035',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A036',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A037',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A038',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A039',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A040',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A041',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A042',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A043',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A044',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A045',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A046',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A047',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A048',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A049',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC71DC8D370-A050',NULL,8.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'r443DA412E3_c01','P443DA412E3-SAF-DCE-009',17,9,57759.83,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'r443DA412E3_c02','P443DA412E3-SAF-DCE-009',21,9,68022.9,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'r443DA412E3_c03','P443DA412E3-SAF-DCE-009',14,9,44118.45,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'r443DA412E3_c04','P443DA412E3-SAF-DCE-009',14,11,47030.5,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'r443DA412E3_c05','P443DA412E3-SAF-DCE-009',24,11,80760.23,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'r443DA412E3_c06','P443DA412E3-SAF-DCE-009',17,12,53325.52,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'r443DA412E3_c07','P443DA412E3-SAF-DCE-009',14,12,47888.0,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'r443DA412E3_c08','P443DA412E3-SAF-DCE-009',17,13,53721.98,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(9,'r443DA412E3_c09','P443DA412E3-SAF-DCE-009',14,13,45029.62,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(10,'r443DA412E3_c10','P443DA412E3-SAF-DCE-009',18,13,61089.49,NULL);
