-- agentic-labs/erp-bench scenario 2005: Sound Privacy Panels
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6AB3E815F3_c01','Stonewall Labs','customer',0,3794.35,NULL,NULL,'orders@stonewalllabs.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6AB3E815F3_c02','Garnet Atelier','customer',0,5830.25,NULL,NULL,'orders@garnetatelier.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6AB3E815F3_c03','Baltic Publishing','customer',0,5601.24,NULL,NULL,'orders@balticpublishing.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6AB3E815F3_c04','Cosmo Consortium','customer',0,5620.74,NULL,NULL,'orders@cosmoconsortium.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p01','Jade Solutions Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@jadesolutions.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p02','Lumen Operations Tooling Center','customer',0,NULL,NULL,NULL,'contact@lumenoperations.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p03','Polar Manufacturing Prototype Shop','customer',0,NULL,NULL,NULL,'contact@polarmanufacturing.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p04','Noble Solutions Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@noblesolutions.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p05','Sierra Fabrication Prototype Shop','customer',0,NULL,NULL,NULL,'contact@sierrafabrication.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p06','Terra Technologies Quality Lab','customer',0,NULL,NULL,NULL,'contact@terratechnologies.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p07','Cascade Industries Site Logistics','customer',0,NULL,NULL,NULL,'contact@cascadeindustries.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p08','Aurora Production Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@auroraproduction.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p09','Dune Production Quality Lab','customer',0,NULL,NULL,NULL,'contact@duneproduction.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p10','Forge Fabrication Prototype Shop','customer',0,NULL,NULL,NULL,'contact@forgefabrication.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p11','Ivory Assembly Test Facility','customer',0,NULL,NULL,NULL,'contact@ivoryassembly.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p12','Mosaic Operations Prototype Shop','customer',0,NULL,NULL,NULL,'contact@mosaicoperations.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p13','Evergreen Manufacturing R&D Workshop','customer',0,NULL,NULL,NULL,'contact@evergreenmanufacturing.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p14','Nexus Fabrication Prototype Shop','customer',0,NULL,NULL,NULL,'contact@nexusfabrication.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p15','Clearwater Services Test Facility','customer',0,NULL,NULL,NULL,'contact@clearwaterservices.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p16','Onyx Fabrication HQ Procurement','customer',0,NULL,NULL,NULL,'contact@onyxfabrication.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p17','Ridgeline Fabrication HQ Procurement','customer',0,NULL,NULL,NULL,'contact@ridgelinefabrication.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p18','Borough Solutions Prototype Shop','customer',0,NULL,NULL,NULL,'contact@boroughsolutions.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p19','Slate Operations Tooling Center','customer',0,NULL,NULL,NULL,'contact@slateoperations.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p20','Indigo Fabrication R&D Workshop','customer',0,NULL,NULL,NULL,'contact@indigofabrication.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p21','Conduit Manufacturing R&D Workshop','customer',0,NULL,NULL,NULL,'contact@conduitmanufacturing.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p22','Vantage Engineering Quality Lab','customer',0,NULL,NULL,NULL,'contact@vantageengineering.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p23','Bridgeway Solutions Tooling Center','customer',0,NULL,NULL,NULL,'contact@bridgewaysolutions.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p24','Pacific Industries Tooling Center','customer',0,NULL,NULL,NULL,'contact@pacificindustries.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p25','Citadel Operations Quality Lab','customer',0,NULL,NULL,NULL,'contact@citadeloperations.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p26','Matrix Fabrication R&D Workshop','customer',0,NULL,NULL,NULL,'contact@matrixfabrication.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p27','Northbridge Engineering R&D Workshop','customer',0,NULL,NULL,NULL,'contact@northbridgeengineering.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p28','Arc Assembly Field Ops','customer',0,NULL,NULL,NULL,'contact@arcassembly.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p29','Redstone Assembly Field Ops','customer',0,NULL,NULL,NULL,'contact@redstoneassembly.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p30','Aegis Solutions Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@aegissolutions.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p31','Silverline Engineering Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@silverlineengineering.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p32','Opal Manufacturing Prototype Shop','customer',0,NULL,NULL,NULL,'contact@opalmanufacturing.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p33','Flux Operations Site Logistics','customer',0,NULL,NULL,NULL,'contact@fluxoperations.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p34','Orbital Technologies R&D Workshop','customer',0,NULL,NULL,NULL,'contact@orbitaltechnologies.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p35','Ridge Solutions Site Logistics','customer',0,NULL,NULL,NULL,'contact@ridgesolutions.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p36','Horizon Industries Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@horizonindustries.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p37','Crown Production Prototype Shop','customer',0,NULL,NULL,NULL,'contact@crownproduction.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p38','Cedar Solutions Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@cedarsolutions.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p39','Peak Operations Quality Lab','customer',0,NULL,NULL,NULL,'contact@peakoperations.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p40','Sentinel Production Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@sentinelproduction.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p41','Solace Industries Tooling Center','customer',0,NULL,NULL,NULL,'contact@solaceindustries.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p42','Spire Manufacturing Test Facility','customer',0,NULL,NULL,NULL,'contact@spiremanufacturing.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p43','Thornton Technologies Prototype Shop','customer',0,NULL,NULL,NULL,'contact@thorntontechnologies.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p44','Lattice Operations Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@latticeoperations.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p45','Westfield Solutions HQ Procurement','customer',0,NULL,NULL,NULL,'contact@westfieldsolutions.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p46','Spark Solutions Test Facility','customer',0,NULL,NULL,NULL,'contact@sparksolutions.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p47','Velocity Industries Prototype Shop','customer',0,NULL,NULL,NULL,'contact@velocityindustries.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p48','Zenith Assembly Tooling Center','customer',0,NULL,NULL,NULL,'contact@zenithassembly.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p49','Pinnacle Solutions Tooling Center','customer',0,NULL,NULL,NULL,'contact@pinnaclesolutions.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r86E8590A46_p50','Crest Engineering Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@crestengineering.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6AB3E815F3_q01','Chrome Consolidators','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6AB3E815F3_q02','Titan Provisions','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6AB3E815F3_q03','Cardinal Freight','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6AB3E815F3_q04','Raven Materials','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q01','Oakmont Wholesale','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q02','Flint Procurement','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q03','Quartz Carriers','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q04','Haven Procurement','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q05','Riverdale Trading','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q06','Canton Parts Co','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q07','Copper Logistics','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q08','Catalyst Parts Co','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q09','Blaze Carriers','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q10','Lakewood Materials','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q11','Sterling Freight','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q12','Anvil Wholesale','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q13','Alloy Parts Co','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q14','Echo Sourcing','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q15','Summit Networks','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q16','Ashford Materials','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q17','Grove Networks','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q18','Granite Networks','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q19','Gateway Transit','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q20','Lance Transit','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q21','Compass Resources','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q22','Bronze Networks','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q23','Arrow Materials','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q24','Keystone Resources','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q25','Skyline Transit','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q26','Ledger Procurement','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q27','Equinox Wholesale','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q28','Metro Transit','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q29','Globe Sourcing','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q30','Bayshore Sourcing','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q31','Quantum Procurement','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q32','Ironwood Procurement','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q33','Axis Networks','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q34','Hartland Supply','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q35','Crestview Trading','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q36','Coral Parts Co','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q37','Ember Distribution','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q38','Fairview Wholesale','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q39','Oxide Wholesale','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q40','Iron Components','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q41','Beacon Materials','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q42','Alpine Distribution','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q43','Aether Components','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q44','Vertex Sourcing','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q45','Circuit Freight','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q46','Marble Networks','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q47','Sapphire Transit','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q48','Comet Components','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q49','Trident Logistics','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r86E8590A46_q50','Brookfield Sourcing','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6AB3E815F3-SPP-001','Sound Privacy Panels','Office Systems','consu',457.09,306.18,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'P6AB3E815F3-SPP-001','r6AB3E815F3_q01','Priority Shuttle lane (6d transit, 11-41 units)',6,11.0,41.0,320.22);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'P6AB3E815F3-SPP-001','r6AB3E815F3_q02','Express Air lane (2d transit, 1-41 units)',2,1.0,41.0,452.41);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'P6AB3E815F3-SPP-001','r6AB3E815F3_q03','Bulk Container lane (20d transit, 23-42 units)',20,23.0,42.0,161.12);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'P6AB3E815F3-SPP-001','r6AB3E815F3_q04','Hybrid Expedite lane (7d transit, 6-11 units)',7,6.0,11.0,341.01);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A001','High-Cycle Seal Strip','Seals and Gaskets','consu',401.91,236.13,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'P86E8590A46-A001','r86E8590A46_q01','Scheduled freight',5,1.0,24.0,225.78);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A002','Compact Hardware Fastener Pack','Hardware Accessories','consu',234.93,164.2,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'P86E8590A46-A002','r86E8590A46_q02','Bulk shipment',3,1.0,24.0,157.88);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A003','Low-Noise Fabric Bolt','Electrical Components','consu',311.95,170.92,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'P86E8590A46-A003','r86E8590A46_q03','Bulk shipment',8,1.0,24.0,165.25);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A004','Heavy-Duty Isolator Pad','Maintenance Supplies','consu',302.02,178.06,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'P86E8590A46-A004','r86E8590A46_q04','Standard delivery',4,1.0,24.0,181.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A005','Premium Sound Dampening Core','Replacement Parts','consu',358.14,222.62,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'P86E8590A46-A005','r86E8590A46_q05','Standard delivery',8,1.0,24.0,212.26);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A006','Tapered Acoustic Fabric Bolt','Mechanical Components','consu',220.3,138.86,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'P86E8590A46-A006','r86E8590A46_q06','Scheduled freight',8,1.0,24.0,134.8);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A007','Thermal-Guard Aluminum Frame Kit','Electrical Components','consu',196.06,140.05,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'P86E8590A46-A007','r86E8590A46_q07','Regional lane',5,1.0,24.0,146.56);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A008','Self-Lubricating Corner Bracket Set','Fasteners and Fixings','consu',367.23,246.44,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'P86E8590A46-A008','r86E8590A46_q08','Bulk shipment',3,1.0,24.0,235.14);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A009','Precision Frame Kit','Pneumatic Components','consu',246.09,152.58,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'P86E8590A46-A009','r86E8590A46_q09','Regional lane',5,1.0,24.0,152.07);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A010','Reinforced Fastener Pack','Replacement Parts','consu',327.61,184.55,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'P86E8590A46-A010','r86E8590A46_q10','Regional lane',8,1.0,24.0,182.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A011','Stainless Fiber Fill Panel','Electrical Components','consu',261.36,172.85,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'P86E8590A46-A011','r86E8590A46_q11','Warehouse direct',5,1.0,24.0,169.42);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A012','Non-Magnetic Sound Dampening Core','Power Transmission','consu',201.93,122.3,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'P86E8590A46-A012','r86E8590A46_q12','Standard delivery',5,1.0,24.0,124.52);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A013','Anti-Vibration Sealant Tube','Mechanical Components','consu',409.0,236.97,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'P86E8590A46-A013','r86E8590A46_q13','Standard delivery',4,1.0,24.0,238.09);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A014','UV-Stable Edge Seal Strip','Hardware Accessories','consu',369.79,194.12,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'P86E8590A46-A014','r86E8590A46_q14','Express route',6,1.0,24.0,207.69);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A015','Zero-Backlash Fiber Fill Panel','Replacement Parts','consu',412.93,226.97,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'P86E8590A46-A015','r86E8590A46_q15','Cross-dock',3,1.0,24.0,223.47);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A016','Impact-Rated Fill Panel','Seals and Gaskets','consu',398.45,235.09,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'P86E8590A46-A016','r86E8590A46_q16','Regional lane',5,1.0,24.0,250.8);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A017','Threaded Fastener Pack','Pneumatic Components','consu',222.36,159.12,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'P86E8590A46-A017','r86E8590A46_q17','Standard delivery',7,1.0,24.0,164.16);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A018','Corrosion-Resistant Dampening Core','Hardware Accessories','consu',193.39,137.48,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'P86E8590A46-A018','r86E8590A46_q18','Express route',5,1.0,24.0,135.55);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A019','Dual-Stage Sealant Tube','Fasteners and Fixings','consu',344.59,208.35,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'P86E8590A46-A019','r86E8590A46_q19','Bulk shipment',7,1.0,24.0,210.63);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A020','Rapid-Lock Fastener Pack','Electrical Components','consu',281.95,182.3,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'P86E8590A46-A020','r86E8590A46_q20','Standard delivery',5,1.0,24.0,183.2);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A021','Modular Acoustic Sealant Tube','Industrial Spare Parts','consu',345.73,200.73,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'P86E8590A46-A021','r86E8590A46_q21','Local pickup',5,1.0,24.0,216.01);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A022','Spring-Loaded Dampening Core','Power Transmission','consu',416.09,258.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'P86E8590A46-A022','r86E8590A46_q22','Cross-dock',8,1.0,24.0,265.87);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A023','Double-Row Board Panel','Seals and Gaskets','consu',396.74,209.56,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'P86E8590A46-A023','r86E8590A46_q23','Warehouse direct',3,1.0,24.0,206.41);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A024','Flanged Acoustic Fabric Bolt','Maintenance Supplies','consu',333.05,184.56,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'P86E8590A46-A024','r86E8590A46_q24','Warehouse direct',5,1.0,24.0,187.06);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A025','Economy Fastener Pack','Power Transmission','consu',400.45,246.15,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'P86E8590A46-A025','r86E8590A46_q25','Warehouse direct',6,1.0,24.0,263.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A026','Anodized Frame Kit','Industrial Spare Parts','consu',336.56,218.7,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'P86E8590A46-A026','r86E8590A46_q26','Scheduled freight',4,1.0,24.0,225.59);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A027','Food-Grade Isolator Pad','Fasteners and Fixings','consu',284.57,149.02,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'P86E8590A46-A027','r86E8590A46_q27','Cross-dock',8,1.0,24.0,153.26);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A028','High-Torque Backing Board Panel','Seals and Gaskets','consu',247.77,155.4,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'P86E8590A46-A028','r86E8590A46_q28','Standard delivery',8,1.0,24.0,156.27);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A029','Single-Stage Clip Assembly','Fasteners and Fixings','consu',263.19,177.13,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'P86E8590A46-A029','r86E8590A46_q29','Express route',6,1.0,24.0,190.95);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A030','Heat-Treated Dampening Core','Mechanical Components','consu',201.79,134.98,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'P86E8590A46-A030','r86E8590A46_q30','Bulk shipment',8,1.0,24.0,139.57);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A031','Adjustable Vinyl Sheet','Maintenance Supplies','consu',280.37,180.09,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'P86E8590A46-A031','r86E8590A46_q31','Standard delivery',8,1.0,24.0,192.49);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A032','Lightweight Corner Bracket Set','Power Transmission','consu',216.54,130.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'P86E8590A46-A032','r86E8590A46_q32','Regional lane',5,1.0,24.0,138.76);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A033','Low-Profile Fabric Bolt','Fasteners and Fixings','consu',231.53,166.39,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'P86E8590A46-A033','r86E8590A46_q33','Scheduled freight',4,1.0,24.0,162.89);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A034','High-Temp Fill Panel','Electrical Components','consu',300.73,170.12,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'P86E8590A46-A034','r86E8590A46_q34','Scheduled freight',7,1.0,24.0,163.62);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A035','Medical-Grade Board Panel','Replacement Parts','consu',394.81,238.86,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'P86E8590A46-A035','r86E8590A46_q35','Bulk shipment',4,1.0,24.0,233.17);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A036','Powder-Coated Bracket Set','Pneumatic Components','consu',306.69,187.91,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'P86E8590A46-A036','r86E8590A46_q36','Bulk shipment',7,1.0,24.0,199.9);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A037','Low-Temp Aluminum Frame Kit','Seals and Gaskets','consu',354.02,190.66,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'P86E8590A46-A037','r86E8590A46_q37','Cross-dock',6,1.0,24.0,205.51);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A038','Wide-Body Hardware Fastener Pack','Seals and Gaskets','consu',353.22,244.59,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'P86E8590A46-A038','r86E8590A46_q38','Warehouse direct',4,1.0,24.0,242.71);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A039','Low-Flow Mounting Clip Assembly','Seals and Gaskets','consu',186.82,119.91,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'P86E8590A46-A039','r86E8590A46_q39','Warehouse direct',7,1.0,24.0,126.77);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A040','Sealed Dampening Core','Maintenance Supplies','consu',239.61,155.66,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'P86E8590A46-A040','r86E8590A46_q40','Bulk shipment',6,1.0,24.0,159.95);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A041','Commercial Hardware Fastener Pack','Fasteners and Fixings','consu',316.35,180.81,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'P86E8590A46-A041','r86E8590A46_q41','Warehouse direct',8,1.0,24.0,194.7);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A042','Pressure-Balanced Backing Board Panel','Replacement Parts','consu',243.39,169.16,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'P86E8590A46-A042','r86E8590A46_q42','Standard delivery',8,1.0,24.0,167.96);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A043','High-Flow Fastener Pack','Mechanical Components','consu',200.59,125.6,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'P86E8590A46-A043','r86E8590A46_q43','Cross-dock',8,1.0,24.0,132.05);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A044','Snap-Fit Fastener Pack','Fasteners and Fixings','consu',358.07,245.96,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'P86E8590A46-A044','r86E8590A46_q44','Regional lane',4,1.0,24.0,254.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A045','Cold-Rolled Mounting Clip Assembly','Pneumatic Components','consu',344.48,187.92,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'P86E8590A46-A045','r86E8590A46_q45','Bulk shipment',4,1.0,24.0,187.82);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A046','Cleanroom Corner Bracket Set','Maintenance Supplies','consu',185.02,112.33,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'P86E8590A46-A046','r86E8590A46_q46','Cross-dock',7,1.0,24.0,108.01);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A047','Metric Isolator Pad','Fasteners and Fixings','consu',274.76,154.93,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'P86E8590A46-A047','r86E8590A46_q47','Express route',8,1.0,24.0,167.05);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A048','Weatherproof Fastener Pack','Industrial Spare Parts','consu',378.78,259.14,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'P86E8590A46-A048','r86E8590A46_q48','Standard delivery',4,1.0,24.0,270.07);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A049','Universal Fill Panel','Seals and Gaskets','consu',199.25,122.13,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'P86E8590A46-A049','r86E8590A46_q49','Express route',5,1.0,24.0,125.86);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P86E8590A46-A050','Standard Vinyl Sheet','Hardware Accessories','consu',414.69,277.38,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'P86E8590A46-A050','r86E8590A46_q50','Warehouse direct',4,1.0,24.0,265.99);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'P86E8590A46-A035','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P86E8590A46-A002',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P86E8590A46-A023',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'P86E8590A46-A016','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P86E8590A46-A041',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P86E8590A46-A020',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'P86E8590A46-A036','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P86E8590A46-A017',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'P86E8590A46-A018','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'P86E8590A46-A003',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'P86E8590A46-A043','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P86E8590A46-A002',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P86E8590A46-A005',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'P86E8590A46-A006','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P86E8590A46-A033',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P86E8590A46-A034',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'P86E8590A46-A017','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'P86E8590A46-A045',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'P86E8590A46-A013','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P86E8590A46-A010',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P86E8590A46-A024',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'P86E8590A46-A010','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P86E8590A46-A024',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'P86E8590A46-A004','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P86E8590A46-A045',3.0);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6AB3E815F3-SPP-001',NULL,39.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A001',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A002',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A003',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A004',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A005',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A006',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A007',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A008',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A009',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A010',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A011',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A012',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A013',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A014',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A015',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A016',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A017',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A018',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A019',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A020',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A021',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A022',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A023',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A024',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A025',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A026',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A027',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A028',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A029',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A030',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A031',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A032',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A033',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A034',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A035',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A036',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A037',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A038',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A039',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A040',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A041',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A042',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A043',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A044',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A045',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A046',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A047',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A048',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A049',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P86E8590A46-A050',NULL,12.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'r6AB3E815F3_c01','P6AB3E815F3-SPP-001',8,5,3794.35,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'r6AB3E815F3_c02','P6AB3E815F3-SPP-001',12,6,5830.25,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'r6AB3E815F3_c03','P6AB3E815F3-SPP-001',12,7,5601.24,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'r6AB3E815F3_c04','P6AB3E815F3-SPP-001',12,8,5620.74,NULL);
