-- agentic-labs/erp-bench scenario 2144: Portable Power Station 3kWh
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c01','Marble Observatory','customer',0,58129.6,NULL,NULL,'orders@marbleobservatory.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c02','Forge Dynamics','customer',0,57405.92,NULL,NULL,'orders@forgedynamics.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c03','Aurora Collective East','customer',0,54431.01,NULL,NULL,'orders@auroracollectiveeast.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c04','Ember Arena','customer',0,55689.54,NULL,NULL,'orders@emberarena.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c05','Crown Works','customer',0,65302.81,NULL,NULL,'orders@crownworks.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c06','Hartland Theater','customer',0,55781.67,NULL,NULL,'orders@hartlandtheater.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c07','Haven Productions','customer',0,57964.95,NULL,NULL,'orders@havenproductions.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c08','Monarch Reserve','customer',0,60246.27,NULL,NULL,'orders@monarchreserve.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c09','Metro Atelier','customer',0,76407.03,NULL,NULL,'orders@metroatelier.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c10','Meridian Publishing','customer',0,52526.63,NULL,NULL,'orders@meridianpublishing.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c11','Summit Advisory','customer',0,63637.8,NULL,NULL,'orders@summitadvisory.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c12','Oxide Studios North','customer',0,55106.7,NULL,NULL,'orders@oxidestudiosnorth.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c13','Oakmont Workshop','customer',0,67454.26,NULL,NULL,'orders@oakmontworkshop.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c14','Flint Solutions Group','customer',0,64080.34,NULL,NULL,'orders@flintsolutionsgroup.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c15','Helix Studios West','customer',0,79359.29,NULL,NULL,'orders@helixstudioswest.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c16','Sterling Pavilion','customer',0,56080.08,NULL,NULL,'orders@sterlingpavilion.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c17','Quantum Architects','customer',0,54496.45,NULL,NULL,'orders@quantumarchitects.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c18','Cardinal Trading Co','customer',0,53629.11,NULL,NULL,'orders@cardinaltradingco.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c19','Aegis Society','customer',0,68839.83,NULL,NULL,'orders@aegissociety.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c20','Ironside Alliance','customer',0,63100.92,NULL,NULL,'orders@ironsidealliance.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c21','Northbridge Manufactory','customer',0,64477.99,NULL,NULL,'orders@northbridgemanufactory.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c22','Crest Sciences','customer',0,54838.39,NULL,NULL,'orders@crestsciences.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c23','Baltic Consortium','customer',0,67443.19,NULL,NULL,'orders@balticconsortium.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c24','Trident Technologies','customer',0,62643.21,NULL,NULL,'orders@tridenttechnologies.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c25','Axis Partners','customer',0,57175.02,NULL,NULL,'orders@axispartners.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r38B062B902_c26','Scion Museum','customer',0,56782.27,NULL,NULL,'orders@scionmuseum.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p01','Peak Engineering Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@peakengineering.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p02','Cascade Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@cascadeassembly.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p03','Cedar Operations R&D Workshop','customer',0,NULL,NULL,NULL,'contact@cedaroperations.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p04','Bronze Manufacturing Test Facility','customer',0,NULL,NULL,NULL,'contact@bronzemanufacturing.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p05','Onyx Manufacturing Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@onyxmanufacturing.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p06','Ironwood Manufacturing HQ Procurement','customer',0,NULL,NULL,NULL,'contact@ironwoodmanufacturing.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p07','Fairview Assembly Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@fairviewassembly.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p08','Citadel Solutions Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@citadelsolutions.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p09','Vantage Production Site Logistics','customer',0,NULL,NULL,NULL,'contact@vantageproduction.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p10','Opal Manufacturing Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@opalmanufacturing.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p11','Borough Assembly Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@boroughassembly.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p12','Terra Engineering HQ Procurement','customer',0,NULL,NULL,NULL,'contact@terraengineering.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p13','Lattice Solutions HQ Procurement','customer',0,NULL,NULL,NULL,'contact@latticesolutions.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p14','Cosmo Assembly Field Ops','customer',0,NULL,NULL,NULL,'contact@cosmoassembly.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p15','Mosaic Fabrication R&D Workshop','customer',0,NULL,NULL,NULL,'contact@mosaicfabrication.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p16','Quartz Production HQ Procurement','customer',0,NULL,NULL,NULL,'contact@quartzproduction.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p17','Arbor Solutions Site Logistics','customer',0,NULL,NULL,NULL,'contact@arborsolutions.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p18','Indigo Fabrication Quality Lab','customer',0,NULL,NULL,NULL,'contact@indigofabrication.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p19','Titan Technologies Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@titantechnologies.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p20','Riverdale Operations Field Ops','customer',0,NULL,NULL,NULL,'contact@riverdaleoperations.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p21','Garnet Manufacturing Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@garnetmanufacturing.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p22','Lakewood Production Prototype Shop','customer',0,NULL,NULL,NULL,'contact@lakewoodproduction.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p23','Westfield Solutions Prototype Shop','customer',0,NULL,NULL,NULL,'contact@westfieldsolutions.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p24','Brookfield Services Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@brookfieldservices.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p25','Compass Fabrication Test Facility','customer',0,NULL,NULL,NULL,'contact@compassfabrication.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p26','Dune Production Field Ops','customer',0,NULL,NULL,NULL,'contact@duneproduction.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p27','Ashford Engineering Quality Lab','customer',0,NULL,NULL,NULL,'contact@ashfordengineering.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p28','Ridgeline Fabrication Site Logistics','customer',0,NULL,NULL,NULL,'contact@ridgelinefabrication.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p29','Keystone Fabrication Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@keystonefabrication.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p30','Adjacent Customer 1 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer001.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p31','Adjacent Customer 2 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer002.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p32','Adjacent Customer 3 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer003.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p33','Adjacent Customer 4 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer004.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p34','Adjacent Customer 5 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer005.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p35','Adjacent Customer 6 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer006.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p36','Adjacent Customer 7 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer007.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p37','Adjacent Customer 8 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer008.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p38','Adjacent Customer 9 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer009.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p39','Adjacent Customer 10 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer010.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p40','Adjacent Customer 11 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer011.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p41','Adjacent Customer 12 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer012.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p42','Adjacent Customer 13 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer013.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p43','Adjacent Customer 14 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer014.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p44','Adjacent Customer 15 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer015.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p45','Adjacent Customer 16 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer016.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p46','Adjacent Customer 17 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer017.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p47','Adjacent Customer 18 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer018.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p48','Adjacent Customer 19 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer019.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p49','Adjacent Customer 20 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer020.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rE5A2F6D3D3_p50','Adjacent Customer 21 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer021.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q01','Cobalt Fabrication','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q02','Osprey Forwarders','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q03','Zenith Importers','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q04','Anvil Commodities','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q05','Velocity Carriers','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q06','Aether Fulfillment','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q07','Evergreen Transport','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q08','Prism Sourcing','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q09','Globe Manufacturing','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q10','Raven Movers','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q11','Nexus Consolidators','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q12','Pinnacle Operations','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q13','Element Components','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q14','Horizon Procurement','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q15','Jade Exporters','vendor',15,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q16','Crestview Partners','vendor',16,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q17','Redstone Networks','vendor',17,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q18','Lance Conveyance','vendor',18,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q19','Sentinel Materials','vendor',19,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q20','Spire Haulage','vendor',20,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q21','Drift Depot','vendor',21,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q22','Gateway Warehousing','vendor',22,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q23','Pacific Distributors','vendor',23,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q24','Chrome Packagers','vendor',24,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q25','Catalyst Distribution','vendor',25,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r38B062B902_q26','Millbrook Logistics','vendor',26,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q01','Sapphire Distribution','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q02','Echo Trading','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q03','Cipher Networks','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q04','Equinox Supply','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q05','Canton Parts Co','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q06','Arc Networks','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q07','Solace Logistics','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q08','Copper Logistics','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q09','Spark Wholesale','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q10','Ledger Resources','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q11','Flux Parts Co','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q12','Arrow Carriers','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q13','Iron Procurement','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q14','Slate Carriers','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q15','Skyline Networks','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q16','Circuit Sourcing','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q17','Steel Carriers','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q18','Eclipse Components','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q19','Ivory Wholesale','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q20','Conduit Resources','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q21','Trellis Carriers','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q22','Beacon Distribution','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q23','Lumen Parts Co','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q24','Baseline Networks','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q25','Nimbus Freight','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q26','Atlas Transit','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q27','Matrix Procurement','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q28','Alpine Parts Co','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q29','Granite Transit','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q30','Coral Procurement','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q31','Bayshore Procurement','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q32','Noble Parts Co','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q33','Spectra Parts Co','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q34','Grove Parts Co','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q35','Apex Trading','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q36','Pivot Carriers','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q37','Thornton Distribution','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q38','Stratos Materials','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q39','Polar Resources','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q40','Vertex Procurement','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q41','Ridge Transit','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q42','Stonewall Wholesale','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q43','Silverline Networks','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q44','Bridgeway Materials','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q45','Comet Wholesale','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q46','Alloy Resources','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q47','Sierra Materials','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q48','Orbital Procurement','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q49','Blaze Logistics','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rE5A2F6D3D3_q50','Clearwater Transit','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P38B062B902-BAT-PPS-010','Portable Power Station 3kWh','Power Equipment','consu',2860.79,1502.46,'buy,manufacture',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'P38B062B902-BAT-PPS-010','r38B062B902_q01','Priority Shuttle lane (8d transit, 11-71 units)',8,11.0,71.0,1681.32);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'P38B062B902-BAT-PPS-010','r38B062B902_q02','Express Air lane (5d transit, 3-47 units)',5,3.0,47.0,2600.45);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'P38B062B902-BAT-PPS-010','r38B062B902_q03','Bulk Container lane (22d transit, 260-268 units)',22,260.0,268.0,1063.17);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'P38B062B902-BAT-PPS-010','r38B062B902_q04','Scheduled Freight lane (19d transit, 10-17 units)',19,10.0,17.0,1612.26);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'P38B062B902-BAT-PPS-010','r38B062B902_q05','Regional Cross-Dock lane (12d transit, 8-9 units)',12,8.0,9.0,1907.85);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'P38B062B902-BAT-PPS-010','r38B062B902_q06','Air Charter lane (5d transit, 1-31 units)',5,1.0,31.0,2923.07);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'P38B062B902-BAT-PPS-010','r38B062B902_q07','Microfactory Build-to-Order lane (8d transit, 6-18 units)',8,6.0,18.0,2411.72);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P38B062B902-SUBA-02','Portable Power Station 3kWh Subassembly A','Power Equipment','consu',801.02,171.69,'manufacture',NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P38B062B902-SUBB-02','Portable Power Station 3kWh Subassembly B','Power Equipment','consu',801.02,160.51,'manufacture',NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P38B062B902-BAT-CBR-111','Cell Balancing Resistor Board','Power Equipment','consu',41.14,13.76,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'P38B062B902-BAT-CBR-111','r38B062B902_q08','Rapid Works (2d)',2,7.0,9.0,25.09);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'P38B062B902-BAT-CBR-111','r38B062B902_q09','Domestic Supply (5d)',5,22.0,147.0,16.42);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'P38B062B902-BAT-CBR-111','r38B062B902_q10','Hybrid Fabricators (6d)',6,19.0,19.0,24.64);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'P38B062B902-BAT-CBR-111','r38B062B902_q11','Import Consolidator (6d)',6,37.0,79.0,13.76);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P38B062B902-BAT-CYL-102','Cylindrical Cell 21700 5Ah','Power Equipment','consu',5.08,1.89,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'P38B062B902-BAT-CYL-102','r38B062B902_q12','Rapid Works (3d)',3,4.0,1065.0,2.93);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'P38B062B902-BAT-CYL-102','r38B062B902_q13','Import Consolidator (4d)',4,40.0,202.0,1.89);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'P38B062B902-BAT-CYL-102','r38B062B902_q14','Domestic Supply (4d)',4,12.0,725.0,2.73);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P38B062B902-BAT-CIB-104','Cell Interconnect Busbar Set','Power Equipment','consu',43.15,14.44,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'P38B062B902-BAT-CIB-104','r38B062B902_q15','Rapid Works (4d)',4,5.0,490.0,21.04);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'P38B062B902-BAT-CIB-104','r38B062B902_q16','Hybrid Fabricators (4d)',4,10.0,72.0,21.23);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'P38B062B902-BAT-CIB-104','r38B062B902_q17','Import Consolidator (4d)',4,47.0,1072.0,14.44);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'P38B062B902-BAT-CIB-104','r38B062B902_q18','Domestic Supply (4d)',4,20.0,1167.0,16.55);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P38B062B902-BAT-HVC-107','High-Voltage Contactor Assembly','Power Equipment','consu',151.62,57.32,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'P38B062B902-BAT-HVC-107','r38B062B902_q19','Rapid Works (3d)',3,11.0,15.0,84.7);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'P38B062B902-BAT-HVC-107','r38B062B902_q20','Hybrid Fabricators (4d)',4,12.0,23.0,80.0);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'P38B062B902-BAT-HVC-107','r38B062B902_q21','Import Consolidator (4d)',4,27.0,147.0,57.32);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'P38B062B902-BAT-HVC-107','r38B062B902_q22','Domestic Supply (4d)',4,18.0,294.0,75.11);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P38B062B902-BAT-PCR-109','Pre-Charge Resistor Module','Power Equipment','consu',26.91,11.84,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'P38B062B902-BAT-PCR-109','r38B062B902_q23','Rapid Works (4d)',4,7.0,62.0,15.51);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'P38B062B902-BAT-PCR-109','r38B062B902_q24','Import Consolidator (4d)',4,39.0,114.0,11.84);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'P38B062B902-BAT-PCR-109','r38B062B902_q25','Domestic Supply (4d)',4,28.0,72.0,12.69);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'P38B062B902-BAT-PCR-109','r38B062B902_q26','Hybrid Fabricators (4d)',4,20.0,56.0,14.29);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A001','Industrial Circuit Breaker 100A','Replacement Parts','consu',332.77,235.35,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'PE5A2F6D3D3-A001','rE5A2F6D3D3_q01','Regional lane',5,1.0,24.0,233.3);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A002','Weatherproof 21700 5Ah','Pneumatic Components','consu',368.08,259.22,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'PE5A2F6D3D3-A002','rE5A2F6D3D3_q02','Scheduled freight',4,1.0,24.0,278.61);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A003','Universal Aluminum Enclosure Housing','Maintenance Supplies','consu',261.22,171.72,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'PE5A2F6D3D3-A003','rE5A2F6D3D3_q03','Express route',3,1.0,24.0,177.83);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A004','Single-Stage 21700 5Ah','Hardware Accessories','consu',251.96,158.59,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'PE5A2F6D3D3-A004','rE5A2F6D3D3_q04','Local pickup',7,1.0,24.0,151.97);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A005','Anodized Contactor Assembly','Maintenance Supplies','consu',201.14,125.73,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'PE5A2F6D3D3-A005','rE5A2F6D3D3_q05','Cross-dock',5,1.0,24.0,120.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A006','Medical-Grade NTC Probe','Mechanical Components','consu',338.11,232.34,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'PE5A2F6D3D3-A006','rE5A2F6D3D3_q06','Warehouse direct',7,1.0,24.0,245.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A007','Premium Aluminum Enclosure Housing','Fasteners and Fixings','consu',403.48,259.14,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'PE5A2F6D3D3-A007','rE5A2F6D3D3_q07','Standard delivery',4,1.0,24.0,268.99);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A008','Hardened Interconnect Busbar Set','Industrial Spare Parts','consu',333.81,228.69,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'PE5A2F6D3D3-A008','rE5A2F6D3D3_q08','Express route',6,1.0,24.0,232.62);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A009','Self-Lubricating Resistor Board','Maintenance Supplies','consu',308.9,200.75,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'PE5A2F6D3D3-A009','rE5A2F6D3D3_q09','Cross-dock',7,1.0,24.0,195.61);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A010','High-Temp NTC Probe','Maintenance Supplies','consu',367.13,226.88,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'PE5A2F6D3D3-A010','rE5A2F6D3D3_q10','Regional lane',4,1.0,24.0,223.52);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A011','Lightweight Pad Insulation Sheet','Seals and Gaskets','consu',304.31,201.81,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'PE5A2F6D3D3-A011','rE5A2F6D3D3_q11','Local pickup',5,1.0,24.0,196.81);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A012','Compact Charge Resistor Module','Maintenance Supplies','consu',356.01,196.22,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'PE5A2F6D3D3-A012','rE5A2F6D3D3_q12','Scheduled freight',5,1.0,24.0,199.06);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A013','Quick-Release Resistor Board','Power Transmission','consu',273.84,194.05,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'PE5A2F6D3D3-A013','rE5A2F6D3D3_q13','Regional lane',4,1.0,24.0,202.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A014','Dual-Stage Resistor Board','Industrial Spare Parts','consu',313.78,224.8,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'PE5A2F6D3D3-A014','rE5A2F6D3D3_q14','Local pickup',5,1.0,24.0,219.35);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A015','Powder-Coated Management System Board','Power Transmission','consu',389.93,272.26,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'PE5A2F6D3D3-A015','rE5A2F6D3D3_q15','Scheduled freight',8,1.0,24.0,266.39);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A016','Food-Grade Balancing Resistor Board','Electrical Components','consu',356.69,223.34,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'PE5A2F6D3D3-A016','rE5A2F6D3D3_q16','Bulk shipment',5,1.0,24.0,225.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A017','Extended-Life Interconnect Busbar Set','Seals and Gaskets','consu',202.78,124.01,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'PE5A2F6D3D3-A017','rE5A2F6D3D3_q17','Bulk shipment',5,1.0,24.0,129.94);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A018','Low-Profile Resistor Board','Replacement Parts','consu',290.15,165.4,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'PE5A2F6D3D3-A018','rE5A2F6D3D3_q18','Warehouse direct',3,1.0,24.0,171.76);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A019','Low-Noise 3.2V 100Ah','Seals and Gaskets','consu',281.37,199.7,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'PE5A2F6D3D3-A019','rE5A2F6D3D3_q19','Local pickup',6,1.0,24.0,196.13);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A020','Metric 21700 5Ah','Seals and Gaskets','consu',341.71,210.33,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'PE5A2F6D3D3-A020','rE5A2F6D3D3_q20','Warehouse direct',7,1.0,24.0,208.53);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A021','Precision Voltage Contactor Assembly','Replacement Parts','consu',185.36,124.29,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'PE5A2F6D3D3-A021','rE5A2F6D3D3_q21','Local pickup',8,1.0,24.0,123.21);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A022','Stainless Cell 3.2V 100Ah','Seals and Gaskets','consu',272.94,193.64,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'PE5A2F6D3D3-A022','rE5A2F6D3D3_q22','Standard delivery',5,1.0,24.0,208.38);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A023','Spring-Loaded Management System Board','Fasteners and Fixings','consu',268.14,149.75,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'PE5A2F6D3D3-A023','rE5A2F6D3D3_q23','Standard delivery',5,1.0,24.0,143.52);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A024','Low-Temp Management System Board','Replacement Parts','consu',291.99,190.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'PE5A2F6D3D3-A024','rE5A2F6D3D3_q24','Cross-dock',6,1.0,24.0,203.64);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A025','Zero-Backlash Management System Board','Hardware Accessories','consu',371.25,215.4,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'PE5A2F6D3D3-A025','rE5A2F6D3D3_q25','Local pickup',3,1.0,24.0,207.14);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A026','Anti-Vibration Pad Insulation Sheet','Seals and Gaskets','consu',414.99,256.84,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'PE5A2F6D3D3-A026','rE5A2F6D3D3_q26','Regional lane',3,1.0,24.0,248.35);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A027','Modular System Board','Power Transmission','consu',203.9,111.6,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'PE5A2F6D3D3-A027','rE5A2F6D3D3_q27','Regional lane',6,1.0,24.0,120.13);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A028','Economy 21700 5Ah','Industrial Spare Parts','consu',312.78,166.19,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'PE5A2F6D3D3-A028','rE5A2F6D3D3_q28','Local pickup',4,1.0,24.0,177.09);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A029','Non-Magnetic Management System Board','Pneumatic Components','consu',191.59,115.99,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'PE5A2F6D3D3-A029','rE5A2F6D3D3_q29','Cross-dock',5,1.0,24.0,118.71);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A030','High-Torque Insulation Sheet','Power Transmission','consu',314.61,207.96,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'PE5A2F6D3D3-A030','rE5A2F6D3D3_q30','Standard delivery',5,1.0,24.0,213.74);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A031','UV-Stable Resistor Module','Industrial Spare Parts','consu',395.49,217.51,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(57,'PE5A2F6D3D3-A031','rE5A2F6D3D3_q31','Express route',7,1.0,24.0,212.68);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A032','Low-Flow Aluminum Enclosure Housing','Pneumatic Components','consu',391.77,212.15,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(58,'PE5A2F6D3D3-A032','rE5A2F6D3D3_q32','Standard delivery',8,1.0,24.0,204.86);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A033','Rapid-Lock Sensor Hall Effect','Pneumatic Components','consu',323.55,191.16,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(59,'PE5A2F6D3D3-A033','rE5A2F6D3D3_q33','Express route',3,1.0,24.0,182.28);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A034','Heat-Treated Management System Board','Fasteners and Fixings','consu',349.99,189.11,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(60,'PE5A2F6D3D3-A034','rE5A2F6D3D3_q34','Express route',6,1.0,24.0,191.16);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A035','Standard Insulation Sheet','Seals and Gaskets','consu',355.23,192.52,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(61,'PE5A2F6D3D3-A035','rE5A2F6D3D3_q35','Warehouse direct',6,1.0,24.0,198.39);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A036','Threaded Cell 3.2V 100Ah','Power Transmission','consu',383.31,217.33,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(62,'PE5A2F6D3D3-A036','rE5A2F6D3D3_q36','Scheduled freight',4,1.0,24.0,222.64);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A037','High-Performance Circuit Breaker 100A','Electrical Components','consu',211.4,124.83,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(63,'PE5A2F6D3D3-A037','rE5A2F6D3D3_q37','Regional lane',8,1.0,24.0,127.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A038','Sealed Busbar Set','Fasteners and Fixings','consu',381.67,239.82,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(64,'PE5A2F6D3D3-A038','rE5A2F6D3D3_q38','Cross-dock',7,1.0,24.0,239.5);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A039','Low-Friction Insulation Sheet','Industrial Spare Parts','consu',288.89,205.65,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(65,'PE5A2F6D3D3-A039','rE5A2F6D3D3_q39','Cross-dock',4,1.0,24.0,199.84);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A040','Wide-Body Voltage Contactor Assembly','Maintenance Supplies','consu',364.81,201.66,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(66,'PE5A2F6D3D3-A040','rE5A2F6D3D3_q40','Local pickup',3,1.0,24.0,194.97);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A041','Heavy-Duty Hall Effect','Seals and Gaskets','consu',383.82,270.46,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(67,'PE5A2F6D3D3-A041','rE5A2F6D3D3_q41','Warehouse direct',8,1.0,24.0,283.89);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A042','Tapered Sensor Hall Effect','Fasteners and Fixings','consu',403.81,221.44,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(68,'PE5A2F6D3D3-A042','rE5A2F6D3D3_q42','Regional lane',6,1.0,24.0,215.19);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A043','Pressure-Balanced Sensor NTC Probe','Pneumatic Components','consu',351.38,218.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(69,'PE5A2F6D3D3-A043','rE5A2F6D3D3_q43','Cross-dock',7,1.0,24.0,230.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A044','Adjustable Resistor Module','Pneumatic Components','consu',392.39,226.83,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(70,'PE5A2F6D3D3-A044','rE5A2F6D3D3_q44','Regional lane',6,1.0,24.0,239.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A045','Reinforced Aluminum Enclosure Housing','Industrial Spare Parts','consu',186.92,110.35,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(71,'PE5A2F6D3D3-A045','rE5A2F6D3D3_q45','Local pickup',6,1.0,24.0,107.52);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A046','Snap-Fit Cell 3.2V 100Ah','Mechanical Components','consu',252.97,154.01,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(72,'PE5A2F6D3D3-A046','rE5A2F6D3D3_q46','Standard delivery',4,1.0,24.0,149.61);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A047','Thermal-Guard System Board','Electrical Components','consu',295.41,187.01,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(73,'PE5A2F6D3D3-A047','rE5A2F6D3D3_q47','Regional lane',5,1.0,24.0,186.54);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A048','Double-Row Enclosure Housing','Pneumatic Components','consu',253.42,133.45,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(74,'PE5A2F6D3D3-A048','rE5A2F6D3D3_q48','Warehouse direct',4,1.0,24.0,142.5);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A049','Corrosion-Resistant Interconnect Busbar Set','Industrial Spare Parts','consu',286.3,199.77,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(75,'PE5A2F6D3D3-A049','rE5A2F6D3D3_q49','Regional lane',7,1.0,24.0,211.16);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PE5A2F6D3D3-A050','Cleanroom Breaker 100A','Power Transmission','consu',275.57,196.29,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(76,'PE5A2F6D3D3-A050','rE5A2F6D3D3_q50','Warehouse direct',7,1.0,24.0,210.8);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'P38B062B902-SUBA-02','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P38B062B902-BAT-CYL-102',9.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P38B062B902-BAT-CIB-104',8.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'P38B062B902-SUBB-02','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P38B062B902-BAT-HVC-107',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P38B062B902-BAT-PCR-109',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'P38B062B902-BAT-PPS-010','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P38B062B902-SUBA-02',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P38B062B902-SUBB-02',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P38B062B902-BAT-CBR-111',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'PE5A2F6D3D3-A014','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'PE5A2F6D3D3-A010',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'PE5A2F6D3D3-A032',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'PE5A2F6D3D3-A028','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'PE5A2F6D3D3-A021',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'PE5A2F6D3D3-A011','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'PE5A2F6D3D3-A036',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'PE5A2F6D3D3-A028',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'PE5A2F6D3D3-A007','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'PE5A2F6D3D3-A050',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'PE5A2F6D3D3-A045','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'PE5A2F6D3D3-A039',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'PE5A2F6D3D3-A009',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'PE5A2F6D3D3-A033','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'PE5A2F6D3D3-A039',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'PE5A2F6D3D3-A049',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'PE5A2F6D3D3-A009','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'PE5A2F6D3D3-A014',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'PE5A2F6D3D3-A006',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(11,'PE5A2F6D3D3-A015','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'PE5A2F6D3D3-A039',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'PE5A2F6D3D3-A012',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(12,'PE5A2F6D3D3-A006','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(12,'PE5A2F6D3D3-A001',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(12,'PE5A2F6D3D3-A013',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(13,'PE5A2F6D3D3-A036','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(13,'PE5A2F6D3D3-A044',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(13,'PE5A2F6D3D3-A023',2.0);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P38B062B902-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P38B062B902-WC02','Fabrication Cell 2',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P38B062B902-WC03','Precision Bench 3',0,0,NULL,NULL);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P38B062B902-BAT-CBR-111',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P38B062B902-BAT-CIB-104',NULL,21.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P38B062B902-BAT-CYL-102',NULL,130.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P38B062B902-BAT-HVC-107',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P38B062B902-BAT-PCR-109',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P38B062B902-BAT-PPS-010',NULL,208.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A001',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A002',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A003',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A004',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A005',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A006',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A007',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A008',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A009',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A010',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A011',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A012',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A013',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A014',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A015',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A016',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A017',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A018',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A019',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A020',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A021',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A022',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A023',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A024',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A025',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A026',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A027',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A028',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A029',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A030',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A031',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A032',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A033',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A034',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A035',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A036',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A037',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A038',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A039',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A040',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A041',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A042',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A043',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A044',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A045',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A046',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A047',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A048',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A049',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PE5A2F6D3D3-A050',NULL,15.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'r38B062B902_c01','P38B062B902-BAT-PPS-010',19,8,58129.6,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'r38B062B902_c02','P38B062B902-BAT-PPS-010',18,8,57405.92,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'r38B062B902_c03','P38B062B902-BAT-PPS-010',18,8,54431.01,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'r38B062B902_c04','P38B062B902-BAT-PPS-010',18,8,55689.54,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'r38B062B902_c05','P38B062B902-BAT-PPS-010',21,8,65302.81,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'r38B062B902_c06','P38B062B902-BAT-PPS-010',18,8,55781.67,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'r38B062B902_c07','P38B062B902-BAT-PPS-010',19,8,57964.95,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'r38B062B902_c08','P38B062B902-BAT-PPS-010',20,8,60246.27,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(9,'r38B062B902_c09','P38B062B902-BAT-PPS-010',24,9,76407.03,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(10,'r38B062B902_c10','P38B062B902-BAT-PPS-010',18,9,52526.63,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(11,'r38B062B902_c11','P38B062B902-BAT-PPS-010',21,9,63637.8,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(12,'r38B062B902_c12','P38B062B902-BAT-PPS-010',18,9,55106.7,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(13,'r38B062B902_c13','P38B062B902-BAT-PPS-010',23,10,67454.26,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(14,'r38B062B902_c14','P38B062B902-BAT-PPS-010',20,10,64080.34,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(15,'r38B062B902_c15','P38B062B902-BAT-PPS-010',27,10,79359.29,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(16,'r38B062B902_c16','P38B062B902-BAT-PPS-010',19,11,56080.08,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(17,'r38B062B902_c17','P38B062B902-BAT-PPS-010',18,11,54496.45,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(18,'r38B062B902_c18','P38B062B902-BAT-PPS-010',18,11,53629.11,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(19,'r38B062B902_c19','P38B062B902-BAT-PPS-010',22,11,68839.83,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(20,'r38B062B902_c20','P38B062B902-BAT-PPS-010',20,12,63100.92,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(21,'r38B062B902_c21','P38B062B902-BAT-PPS-010',21,12,64477.99,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(22,'r38B062B902_c22','P38B062B902-BAT-PPS-010',18,13,54838.39,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(23,'r38B062B902_c23','P38B062B902-BAT-PPS-010',23,13,67443.19,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(24,'r38B062B902_c24','P38B062B902-BAT-PPS-010',21,13,62643.21,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(25,'r38B062B902_c25','P38B062B902-BAT-PPS-010',19,13,57175.02,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(26,'r38B062B902_c26','P38B062B902-BAT-PPS-010',19,13,56782.27,NULL);
