-- agentic-labs/erp-bench scenario 2146: Modular Rack Battery System 20kWh
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c01','Beacon Arena','customer',0,352055.78,NULL,NULL,'orders@beaconarena.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c02','Dune Enterprises','customer',0,327706.01,NULL,NULL,'orders@duneenterprises.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c03','Meridian Advisory','customer',0,303628.25,NULL,NULL,'orders@meridianadvisory.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c04','Aether Consortium','customer',0,359031.22,NULL,NULL,'orders@aetherconsortium.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c05','Sierra Clinics','customer',0,342730.14,NULL,NULL,'orders@sierraclinics.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c06','Axis Robotics','customer',0,359409.86,NULL,NULL,'orders@axisrobotics.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c07','Trident Research','customer',0,505930.53,NULL,NULL,'orders@tridentresearch.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c08','Westfield Archive','customer',0,314482.91,NULL,NULL,'orders@westfieldarchive.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c09','Bridgeway Trading Co','customer',0,364608.13,NULL,NULL,'orders@bridgewaytradingco.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c10','Quantum Initiative','customer',0,322718.84,NULL,NULL,'orders@quantuminitiative.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c11','Catalyst Council','customer',0,352781.29,NULL,NULL,'orders@catalystcouncil.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c12','Cipher Lyceum','customer',0,389731.05,NULL,NULL,'orders@cipherlyceum.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c13','Blaze Greenhouse','customer',0,328371.08,NULL,NULL,'orders@blazegreenhouse.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c14','Peak Workspaces','customer',0,363871.34,NULL,NULL,'orders@peakworkspaces.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c15','Ivory Studios North','customer',0,423873.28,NULL,NULL,'orders@ivorystudiosnorth.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c16','Hartland Theater','customer',0,311063.25,NULL,NULL,'orders@hartlandtheater.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c17','Oakmont Society','customer',0,482909.14,NULL,NULL,'orders@oakmontsociety.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c18','Citadel Studios','customer',0,556305.79,NULL,NULL,'orders@citadelstudios.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c19','Grove Bureau','customer',0,412466.84,NULL,NULL,'orders@grovebureau.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c20','Gateway Institute','customer',0,519842.2,NULL,NULL,'orders@gatewayinstitute.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c21','Flux Chambers','customer',0,356601.72,NULL,NULL,'orders@fluxchambers.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c22','Arrow Agency','customer',0,356369.66,NULL,NULL,'orders@arrowagency.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c23','Nexus Group','customer',0,416876.15,NULL,NULL,'orders@nexusgroup.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c24','Spark Museum','customer',0,543867.59,NULL,NULL,'orders@sparkmuseum.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c25','Raven Studios West','customer',0,424691.72,NULL,NULL,'orders@ravenstudioswest.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c26','Quartz Pictures','customer',0,429558.27,NULL,NULL,'orders@quartzpictures.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c27','Metro Studios South','customer',0,334543.79,NULL,NULL,'orders@metrostudiossouth.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c28','Ridge Workshop','customer',0,300811.26,NULL,NULL,'orders@ridgeworkshop.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c29','Aegis Conservatory','customer',0,430897.9,NULL,NULL,'orders@aegisconservatory.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rCA0647C85B_c30','Cobalt Pavilion','customer',0,529234.83,NULL,NULL,'orders@cobaltpavilion.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p01','Ironside Engineering Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@ironsideengineering.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p02','Lumen Technologies Field Ops','customer',0,NULL,NULL,NULL,'contact@lumentechnologies.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p03','Equinox Solutions HQ Procurement','customer',0,NULL,NULL,NULL,'contact@equinoxsolutions.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p04','Bronze Fabrication Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@bronzefabrication.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p05','Pivot Fabrication Quality Lab','customer',0,NULL,NULL,NULL,'contact@pivotfabrication.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p06','Cascade Assembly R&D Workshop','customer',0,NULL,NULL,NULL,'contact@cascadeassembly.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p07','Canton Services Quality Lab','customer',0,NULL,NULL,NULL,'contact@cantonservices.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p08','Northbridge Technologies Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@northbridgetechnologies.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p09','Conduit Manufacturing Test Facility','customer',0,NULL,NULL,NULL,'contact@conduitmanufacturing.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p10','Circuit Industries Test Facility','customer',0,NULL,NULL,NULL,'contact@circuitindustries.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p11','Spire Industries Quality Lab','customer',0,NULL,NULL,NULL,'contact@spireindustries.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p12','Drift Solutions Prototype Shop','customer',0,NULL,NULL,NULL,'contact@driftsolutions.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p13','Sterling Solutions HQ Procurement','customer',0,NULL,NULL,NULL,'contact@sterlingsolutions.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p14','Baseline Services R&D Workshop','customer',0,NULL,NULL,NULL,'contact@baselineservices.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p15','Eclipse Assembly Tooling Center','customer',0,NULL,NULL,NULL,'contact@eclipseassembly.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p16','Iron Technologies Site Logistics','customer',0,NULL,NULL,NULL,'contact@irontechnologies.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p17','Evergreen Fabrication R&D Workshop','customer',0,NULL,NULL,NULL,'contact@evergreenfabrication.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p18','Stonewall Manufacturing Tooling Center','customer',0,NULL,NULL,NULL,'contact@stonewallmanufacturing.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p19','Horizon Engineering Quality Lab','customer',0,NULL,NULL,NULL,'contact@horizonengineering.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p20','Crown Production Tooling Center','customer',0,NULL,NULL,NULL,'contact@crownproduction.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p21','Cardinal Technologies HQ Procurement','customer',0,NULL,NULL,NULL,'contact@cardinaltechnologies.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p22','Silverline Manufacturing Field Ops','customer',0,NULL,NULL,NULL,'contact@silverlinemanufacturing.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p23','Atlas Manufacturing HQ Procurement','customer',0,NULL,NULL,NULL,'contact@atlasmanufacturing.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p24','Lakewood Services R&D Workshop','customer',0,NULL,NULL,NULL,'contact@lakewoodservices.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p25','Globe Services Site Logistics','customer',0,NULL,NULL,NULL,'contact@globeservices.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p26','Brookfield Services Tooling Center','customer',0,NULL,NULL,NULL,'contact@brookfieldservices.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p27','Echo Production Field Ops','customer',0,NULL,NULL,NULL,'contact@echoproduction.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p28','Forge Technologies Test Facility','customer',0,NULL,NULL,NULL,'contact@forgetechnologies.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p29','Arbor Assembly Tooling Center','customer',0,NULL,NULL,NULL,'contact@arborassembly.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p30','Adjacent Customer 1 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer001.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p31','Adjacent Customer 2 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer002.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p32','Adjacent Customer 3 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer003.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p33','Adjacent Customer 4 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer004.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p34','Adjacent Customer 5 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer005.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p35','Adjacent Customer 6 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer006.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p36','Adjacent Customer 7 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer007.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p37','Adjacent Customer 8 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer008.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p38','Adjacent Customer 9 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer009.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p39','Adjacent Customer 10 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer010.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p40','Adjacent Customer 11 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer011.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p41','Adjacent Customer 12 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer012.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p42','Adjacent Customer 13 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer013.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p43','Adjacent Customer 14 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer014.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p44','Adjacent Customer 15 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer015.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p45','Adjacent Customer 16 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer016.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p46','Adjacent Customer 17 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer017.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p47','Adjacent Customer 18 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer018.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p48','Adjacent Customer 19 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer019.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p49','Adjacent Customer 20 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer020.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDE701E2CF0_p50','Adjacent Customer 21 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer021.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q01','Opal Materials','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q02','Trellis Movers','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q03','Thornton Integrators','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q04','Riverdale Warehousing','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q05','Helix Transport','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q06','Garnet Fabrication','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q07','Ember Carriers','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q08','Cosmo Procurement','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q09','Stratos Assemblies','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q10','Pinnacle Supply','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q11','Compass Shipping','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q12','Vantage Merchants','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q13','Oxide Partners','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q14','Baltic Distribution','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q15','Anvil Forwarders','vendor',15,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q16','Haven Sourcing','vendor',16,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q17','Orbital Provisions','vendor',17,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q18','Sapphire Exporters','vendor',18,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q19','Spectra Holdings','vendor',19,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q20','Polar Commodities','vendor',20,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q21','Scion Industries','vendor',21,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rCA0647C85B_q22','Ridgeline Warehouse','vendor',22,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q01','Onyx Wholesale','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q02','Osprey Logistics','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q03','Alpine Carriers','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q04','Chrome Resources','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q05','Indigo Parts Co','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q06','Monarch Transit','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q07','Lance Procurement','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q08','Zenith Carriers','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q09','Clearwater Procurement','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q10','Slate Freight','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q11','Crest Resources','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q12','Marble Parts Co','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q13','Element Supply','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q14','Skyline Logistics','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q15','Copper Freight','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q16','Apex Parts Co','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q17','Coral Procurement','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q18','Prism Freight','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q19','Comet Transit','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q20','Redstone Networks','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q21','Sentinel Carriers','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q22','Summit Freight','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q23','Solace Sourcing','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q24','Matrix Carriers','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q25','Crestview Parts Co','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q26','Borough Sourcing','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q27','Cedar Wholesale','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q28','Ashford Procurement','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q29','Bayshore Procurement','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q30','Jade Distribution','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q31','Millbrook Networks','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q32','Flint Networks','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q33','Fairview Networks','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q34','Velocity Materials','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q35','Lattice Procurement','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q36','Vertex Sourcing','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q37','Granite Supply','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q38','Pacific Components','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q39','Mosaic Networks','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q40','Ironwood Logistics','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q41','Arc Transit','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q42','Noble Trading','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q43','Steel Freight','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q44','Terra Resources','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q45','Titan Materials','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q46','Keystone Components','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q47','Alloy Wholesale','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q48','Aurora Wholesale','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q49','Ledger Networks','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDE701E2CF0_q50','Nimbus Supply','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PCA0647C85B-BAT-MRB-009','Modular Rack Battery System 20kWh','Power Equipment','consu',16199.21,9493.94,'buy,manufacture',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'PCA0647C85B-BAT-MRB-009','rCA0647C85B_q01','Priority Shuttle lane (9d transit, 10-46 units)',9,10.0,46.0,8569.57);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'PCA0647C85B-BAT-MRB-009','rCA0647C85B_q02','Express Air lane (6d transit, 1-1 units)',6,1.0,1.0,14608.93);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'PCA0647C85B-BAT-MRB-009','rCA0647C85B_q03','Bulk Container lane (24d transit, 345-349 units)',24,345.0,349.0,6329.02);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'PCA0647C85B-BAT-MRB-009','rCA0647C85B_q04','Economy Ocean lane (21d transit, 7-7 units)',21,7.0,7.0,5760.18);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'PCA0647C85B-BAT-MRB-009','rCA0647C85B_q05','Microfactory Build-to-Order lane (6d transit, 6-52 units)',6,6.0,52.0,13538.15);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'PCA0647C85B-BAT-MRB-009','rCA0647C85B_q06','Hybrid Expedite lane (10d transit, 9-116 units)',10,9.0,116.0,12027.19);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PCA0647C85B-SUBA-02','Modular Rack Battery System 20kWh Subassembly A','Power Equipment','consu',4535.78,242.81,'manufacture',NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PCA0647C85B-SUBB-02','Modular Rack Battery System 20kWh Subassembly B','Power Equipment','consu',4535.78,59.95,'manufacture',NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PCA0647C85B-BAT-NTC-112','Temperature Sensor NTC Probe','Power Equipment','consu',8.0,2.64,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'PCA0647C85B-BAT-NTC-112','rCA0647C85B_q07','Rapid Works (4d)',4,10.0,1488.0,4.22);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'PCA0647C85B-BAT-NTC-112','rCA0647C85B_q08','Hybrid Fabricators (6d)',6,13.0,19.0,3.91);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'PCA0647C85B-BAT-NTC-112','rCA0647C85B_q09','Domestic Supply (6d)',6,11.0,923.0,2.64);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PCA0647C85B-BAT-PLC-101','Prismatic LFP Cell 3.2V 100Ah','Power Equipment','consu',68.61,31.86,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'PCA0647C85B-BAT-PLC-101','rCA0647C85B_q10','Rapid Works (2d)',2,6.0,570.0,37.54);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'PCA0647C85B-BAT-PLC-101','rCA0647C85B_q11','Hybrid Fabricators (4d)',4,19.0,846.0,37.59);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'PCA0647C85B-BAT-PLC-101','rCA0647C85B_q12','Import Consolidator (4d)',4,45.0,293.0,31.86);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PCA0647C85B-BAT-CYL-102','Cylindrical Cell 21700 5Ah','Power Equipment','consu',4.9,1.71,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'PCA0647C85B-BAT-CYL-102','rCA0647C85B_q13','Rapid Works (2d)',2,7.0,33.0,3.17);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'PCA0647C85B-BAT-CYL-102','rCA0647C85B_q14','Import Consolidator (4d)',4,41.0,2903.0,1.71);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'PCA0647C85B-BAT-CYL-102','rCA0647C85B_q15','Domestic Supply (4d)',4,10.0,636.0,2.48);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PCA0647C85B-BAT-DCB-110','DC Circuit Breaker 100A','Power Equipment','consu',76.73,29.27,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'PCA0647C85B-BAT-DCB-110','rCA0647C85B_q16','Rapid Works (4d)',4,6.0,25.0,41.01);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'PCA0647C85B-BAT-DCB-110','rCA0647C85B_q17','Domestic Supply (4d)',4,14.0,184.0,36.35);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'PCA0647C85B-BAT-DCB-110','rCA0647C85B_q18','Hybrid Fabricators (4d)',4,10.0,31.0,39.7);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'PCA0647C85B-BAT-DCB-110','rCA0647C85B_q19','Import Consolidator (4d)',4,41.0,92.0,29.27);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PCA0647C85B-BAT-CBR-111','Cell Balancing Resistor Board','Power Equipment','consu',43.49,15.92,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'PCA0647C85B-BAT-CBR-111','rCA0647C85B_q20','Rapid Works (3d)',3,5.0,71.0,26.05);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'PCA0647C85B-BAT-CBR-111','rCA0647C85B_q21','Hybrid Fabricators (4d)',4,12.0,35.0,22.4);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'PCA0647C85B-BAT-CBR-111','rCA0647C85B_q22','Import Consolidator (4d)',4,38.0,92.0,15.92);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A001','Lightweight Cell 21700 5Ah','Mechanical Components','consu',310.12,211.03,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'PDE701E2CF0-A001','rDE701E2CF0_q01','Cross-dock',7,1.0,24.0,203.98);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A002','Low-Noise Voltage Contactor Assembly','Mechanical Components','consu',380.44,226.05,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'PDE701E2CF0-A002','rDE701E2CF0_q02','Standard delivery',7,1.0,24.0,239.53);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A003','Low-Flow Resistor Board','Hardware Accessories','consu',290.14,181.48,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'PDE701E2CF0-A003','rDE701E2CF0_q03','Warehouse direct',4,1.0,24.0,181.39);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A004','High-Performance Circuit Breaker 100A','Pneumatic Components','consu',210.38,121.34,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'PDE701E2CF0-A004','rDE701E2CF0_q04','Warehouse direct',7,1.0,24.0,115.34);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A005','Premium Busbar Set','Hardware Accessories','consu',280.92,183.65,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'PDE701E2CF0-A005','rDE701E2CF0_q05','Bulk shipment',4,1.0,24.0,194.57);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A006','Corrosion-Resistant Resistor Module','Mechanical Components','consu',257.07,168.78,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'PDE701E2CF0-A006','rDE701E2CF0_q06','Bulk shipment',5,1.0,24.0,166.21);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A007','Pressure-Balanced Aluminum Enclosure Housing','Fasteners and Fixings','consu',384.94,237.19,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'PDE701E2CF0-A007','rDE701E2CF0_q07','Bulk shipment',5,1.0,24.0,249.43);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A008','Heavy-Duty Hall Effect','Replacement Parts','consu',302.88,191.11,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'PDE701E2CF0-A008','rDE701E2CF0_q08','Bulk shipment',7,1.0,24.0,192.98);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A009','Low-Temp Balancing Resistor Board','Seals and Gaskets','consu',316.84,182.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'PDE701E2CF0-A009','rDE701E2CF0_q09','Express route',6,1.0,24.0,180.2);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A010','Hardened Contactor Assembly','Replacement Parts','consu',207.76,125.48,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'PDE701E2CF0-A010','rDE701E2CF0_q10','Regional lane',6,1.0,24.0,127.01);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A011','Cleanroom Sensor Hall Effect','Pneumatic Components','consu',315.28,195.56,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'PDE701E2CF0-A011','rDE701E2CF0_q11','Express route',3,1.0,24.0,204.79);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A012','Self-Lubricating Balancing Resistor Board','Fasteners and Fixings','consu',184.85,125.94,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'PDE701E2CF0-A012','rDE701E2CF0_q12','Regional lane',8,1.0,24.0,135.61);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A013','Flanged Hall Effect','Pneumatic Components','consu',180.83,103.51,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'PDE701E2CF0-A013','rDE701E2CF0_q13','Express route',6,1.0,24.0,100.64);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A014','Universal Sensor Hall Effect','Replacement Parts','consu',299.65,167.86,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'PDE701E2CF0-A014','rDE701E2CF0_q14','Warehouse direct',8,1.0,24.0,159.68);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A015','Standard Contactor Assembly','Fasteners and Fixings','consu',394.17,225.29,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'PDE701E2CF0-A015','rDE701E2CF0_q15','Regional lane',8,1.0,24.0,223.44);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A016','High-Flow Sensor NTC Probe','Seals and Gaskets','consu',389.22,229.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'PDE701E2CF0-A016','rDE701E2CF0_q16','Express route',7,1.0,24.0,221.95);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A017','Narrow-Body Resistor Module','Seals and Gaskets','consu',357.73,217.8,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'PDE701E2CF0-A017','rDE701E2CF0_q17','Regional lane',6,1.0,24.0,223.7);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A018','Food-Grade Hall Effect','Electrical Components','consu',226.6,154.97,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'PDE701E2CF0-A018','rDE701E2CF0_q18','Local pickup',4,1.0,24.0,151.25);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A019','Thermal-Guard Breaker 100A','Mechanical Components','consu',295.23,195.77,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'PDE701E2CF0-A019','rDE701E2CF0_q19','Standard delivery',7,1.0,24.0,193.74);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A020','Non-Magnetic Management System Board','Fasteners and Fixings','consu',327.67,194.68,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'PDE701E2CF0-A020','rDE701E2CF0_q20','Warehouse direct',3,1.0,24.0,208.09);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A021','High-Torque Pad Insulation Sheet','Fasteners and Fixings','consu',296.9,166.46,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'PDE701E2CF0-A021','rDE701E2CF0_q21','Local pickup',6,1.0,24.0,167.54);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A022','Reinforced Resistor Module','Seals and Gaskets','consu',299.5,199.64,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'PDE701E2CF0-A022','rDE701E2CF0_q22','Regional lane',5,1.0,24.0,203.25);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A023','Weatherproof Hall Effect','Electrical Components','consu',245.2,135.93,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'PDE701E2CF0-A023','rDE701E2CF0_q23','Local pickup',5,1.0,24.0,131.75);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A024','Extended-Life NTC Probe','Power Transmission','consu',260.28,142.79,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'PDE701E2CF0-A024','rDE701E2CF0_q24','Standard delivery',4,1.0,24.0,152.33);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A025','Compact System Board','Mechanical Components','consu',221.24,150.67,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'PDE701E2CF0-A025','rDE701E2CF0_q25','Scheduled freight',7,1.0,24.0,159.2);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A026','Heat-Treated Circuit Breaker 100A','Industrial Spare Parts','consu',194.17,114.15,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'PDE701E2CF0-A026','rDE701E2CF0_q26','Standard delivery',6,1.0,24.0,109.23);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A027','Threaded Busbar Set','Mechanical Components','consu',349.68,193.9,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'PDE701E2CF0-A027','rDE701E2CF0_q27','Warehouse direct',7,1.0,24.0,205.43);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A028','Single-Stage Charge Resistor Module','Electrical Components','consu',413.19,255.23,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'PDE701E2CF0-A028','rDE701E2CF0_q28','Local pickup',5,1.0,24.0,255.63);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A029','Impact-Rated Sensor NTC Probe','Pneumatic Components','consu',258.37,164.92,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'PDE701E2CF0-A029','rDE701E2CF0_q29','Warehouse direct',7,1.0,24.0,167.4);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A030','Anodized Enclosure Housing','Maintenance Supplies','consu',413.92,220.82,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'PDE701E2CF0-A030','rDE701E2CF0_q30','Standard delivery',4,1.0,24.0,219.36);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A031','Stainless Management System Board','Mechanical Components','consu',256.74,170.73,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'PDE701E2CF0-A031','rDE701E2CF0_q31','Local pickup',4,1.0,24.0,181.75);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A032','Low-Profile Hall Effect','Fasteners and Fixings','consu',200.27,131.53,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'PDE701E2CF0-A032','rDE701E2CF0_q32','Scheduled freight',7,1.0,24.0,126.77);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A033','High-Temp System Board','Mechanical Components','consu',415.05,283.46,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'PDE701E2CF0-A033','rDE701E2CF0_q33','Regional lane',4,1.0,24.0,280.93);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A034','Zero-Backlash Management System Board','Industrial Spare Parts','consu',252.41,149.77,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'PDE701E2CF0-A034','rDE701E2CF0_q34','Regional lane',3,1.0,24.0,145.3);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A035','Tapered Voltage Contactor Assembly','Power Transmission','consu',354.23,241.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(57,'PDE701E2CF0-A035','rDE701E2CF0_q35','Express route',7,1.0,24.0,230.97);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A036','Dual-Stage System Board','Pneumatic Components','consu',245.61,149.39,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(58,'PDE701E2CF0-A036','rDE701E2CF0_q36','Cross-dock',8,1.0,24.0,153.75);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A037','Anti-Vibration Sensor NTC Probe','Mechanical Components','consu',280.81,201.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(59,'PDE701E2CF0-A037','rDE701E2CF0_q37','Express route',7,1.0,24.0,210.15);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A038','Cold-Rolled Resistor Module','Electrical Components','consu',412.89,252.32,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(60,'PDE701E2CF0-A038','rDE701E2CF0_q38','Scheduled freight',3,1.0,24.0,261.5);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A039','Quick-Release Insulation Sheet','Seals and Gaskets','consu',384.12,220.13,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(61,'PDE701E2CF0-A039','rDE701E2CF0_q39','Local pickup',4,1.0,24.0,219.54);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A040','Industrial Sensor Hall Effect','Replacement Parts','consu',360.95,258.1,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(62,'PDE701E2CF0-A040','rDE701E2CF0_q40','Standard delivery',3,1.0,24.0,273.22);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A041','Powder-Coated Insulation Sheet','Industrial Spare Parts','consu',191.27,126.93,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(63,'PDE701E2CF0-A041','rDE701E2CF0_q41','Standard delivery',5,1.0,24.0,128.08);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A042','Low-Friction Cell 21700 5Ah','Maintenance Supplies','consu',224.19,155.47,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(64,'PDE701E2CF0-A042','rDE701E2CF0_q42','Cross-dock',7,1.0,24.0,163.34);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A043','Medical-Grade Pad Insulation Sheet','Hardware Accessories','consu',203.4,142.25,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(65,'PDE701E2CF0-A043','rDE701E2CF0_q43','Regional lane',4,1.0,24.0,147.33);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A044','Sealed Insulation Sheet','Replacement Parts','consu',333.17,237.35,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(66,'PDE701E2CF0-A044','rDE701E2CF0_q44','Bulk shipment',6,1.0,24.0,227.77);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A045','Wide-Body Busbar Set','Electrical Components','consu',390.66,255.05,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(67,'PDE701E2CF0-A045','rDE701E2CF0_q45','Bulk shipment',3,1.0,24.0,269.02);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A046','Adjustable Enclosure Housing','Pneumatic Components','consu',251.04,151.78,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(68,'PDE701E2CF0-A046','rDE701E2CF0_q46','Warehouse direct',6,1.0,24.0,157.1);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A047','Rapid-Lock Sensor Hall Effect','Mechanical Components','consu',402.56,269.25,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(69,'PDE701E2CF0-A047','rDE701E2CF0_q47','Local pickup',4,1.0,24.0,283.06);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A048','UV-Stable Enclosure Housing','Power Transmission','consu',274.31,160.14,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(70,'PDE701E2CF0-A048','rDE701E2CF0_q48','Cross-dock',6,1.0,24.0,171.24);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A049','Precision Resistor Module','Pneumatic Components','consu',297.98,162.31,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(71,'PDE701E2CF0-A049','rDE701E2CF0_q49','Regional lane',4,1.0,24.0,171.56);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDE701E2CF0-A050','Commercial Balancing Resistor Board','Maintenance Supplies','consu',208.92,116.26,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(72,'PDE701E2CF0-A050','rDE701E2CF0_q50','Cross-dock',6,1.0,24.0,123.31);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'PCA0647C85B-SUBA-02','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PCA0647C85B-BAT-PLC-101',6.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PCA0647C85B-BAT-CYL-102',9.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'PCA0647C85B-SUBB-02','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PCA0647C85B-BAT-DCB-110',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PCA0647C85B-BAT-CBR-111',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'PCA0647C85B-BAT-MRB-009','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'PCA0647C85B-SUBA-02',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'PCA0647C85B-SUBB-02',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'PCA0647C85B-BAT-NTC-112',7.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'PDE701E2CF0-A037','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'PDE701E2CF0-A024',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'PDE701E2CF0-A008',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'PDE701E2CF0-A020','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'PDE701E2CF0-A031',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'PDE701E2CF0-A045','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'PDE701E2CF0-A015',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'PDE701E2CF0-A032','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'PDE701E2CF0-A039',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'PDE701E2CF0-A049',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'PDE701E2CF0-A046','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'PDE701E2CF0-A045',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'PDE701E2CF0-A027',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'PDE701E2CF0-A029','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'PDE701E2CF0-A009',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'PDE701E2CF0-A013',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'PDE701E2CF0-A028','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'PDE701E2CF0-A019',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(11,'PDE701E2CF0-A039','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'PDE701E2CF0-A042',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(12,'PDE701E2CF0-A007','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(12,'PDE701E2CF0-A004',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(12,'PDE701E2CF0-A019',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(13,'PDE701E2CF0-A011','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(13,'PDE701E2CF0-A049',1.0);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PCA0647C85B-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PCA0647C85B-WC02','Fabrication Cell 2',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PCA0647C85B-WC03','Precision Bench 3',0,0,NULL,NULL);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PCA0647C85B-BAT-CBR-111',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PCA0647C85B-BAT-CYL-102',NULL,129.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PCA0647C85B-BAT-DCB-110',NULL,18.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PCA0647C85B-BAT-MRB-009',NULL,276.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PCA0647C85B-BAT-NTC-112',NULL,34.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PCA0647C85B-BAT-PLC-101',NULL,45.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A001',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A002',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A003',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A004',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A005',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A006',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A007',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A008',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A009',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A010',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A011',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A012',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A013',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A014',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A015',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A016',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A017',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A018',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A019',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A020',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A021',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A022',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A023',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A024',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A025',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A026',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A027',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A028',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A029',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A030',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A031',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A032',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A033',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A034',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A035',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A036',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A037',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A038',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A039',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A040',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A041',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A042',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A043',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A044',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A045',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A046',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A047',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A048',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A049',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDE701E2CF0-A050',NULL,13.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'rCA0647C85B_c01','PCA0647C85B-BAT-MRB-009',20,8,352055.78,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'rCA0647C85B_c02','PCA0647C85B-BAT-MRB-009',19,8,327706.01,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'rCA0647C85B_c03','PCA0647C85B-BAT-MRB-009',18,8,303628.25,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'rCA0647C85B_c04','PCA0647C85B-BAT-MRB-009',20,8,359031.22,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'rCA0647C85B_c05','PCA0647C85B-BAT-MRB-009',19,9,342730.14,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'rCA0647C85B_c06','PCA0647C85B-BAT-MRB-009',20,9,359409.86,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'rCA0647C85B_c07','PCA0647C85B-BAT-MRB-009',29,9,505930.53,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'rCA0647C85B_c08','PCA0647C85B-BAT-MRB-009',18,9,314482.91,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(9,'rCA0647C85B_c09','PCA0647C85B-BAT-MRB-009',22,9,364608.13,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(10,'rCA0647C85B_c10','PCA0647C85B-BAT-MRB-009',19,10,322718.84,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(11,'rCA0647C85B_c11','PCA0647C85B-BAT-MRB-009',20,10,352781.29,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(12,'rCA0647C85B_c12','PCA0647C85B-BAT-MRB-009',23,10,389731.05,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(13,'rCA0647C85B_c13','PCA0647C85B-BAT-MRB-009',19,10,328371.08,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(14,'rCA0647C85B_c14','PCA0647C85B-BAT-MRB-009',22,10,363871.34,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(15,'rCA0647C85B_c15','PCA0647C85B-BAT-MRB-009',25,10,423873.28,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(16,'rCA0647C85B_c16','PCA0647C85B-BAT-MRB-009',18,11,311063.25,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(17,'rCA0647C85B_c17','PCA0647C85B-BAT-MRB-009',28,11,482909.14,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(18,'rCA0647C85B_c18','PCA0647C85B-BAT-MRB-009',32,11,556305.79,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(19,'rCA0647C85B_c19','PCA0647C85B-BAT-MRB-009',24,11,412466.84,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(20,'rCA0647C85B_c20','PCA0647C85B-BAT-MRB-009',31,11,519842.2,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(21,'rCA0647C85B_c21','PCA0647C85B-BAT-MRB-009',21,11,356601.72,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(22,'rCA0647C85B_c22','PCA0647C85B-BAT-MRB-009',21,12,356369.66,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(23,'rCA0647C85B_c23','PCA0647C85B-BAT-MRB-009',25,12,416876.15,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(24,'rCA0647C85B_c24','PCA0647C85B-BAT-MRB-009',32,12,543867.59,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(25,'rCA0647C85B_c25','PCA0647C85B-BAT-MRB-009',25,12,424691.72,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(26,'rCA0647C85B_c26','PCA0647C85B-BAT-MRB-009',25,13,429558.27,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(27,'rCA0647C85B_c27','PCA0647C85B-BAT-MRB-009',20,13,334543.79,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(28,'rCA0647C85B_c28','PCA0647C85B-BAT-MRB-009',18,13,300811.26,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(29,'rCA0647C85B_c29','PCA0647C85B-BAT-MRB-009',25,13,430897.9,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(30,'rCA0647C85B_c30','PCA0647C85B-BAT-MRB-009',32,13,529234.83,NULL);
