-- agentic-labs/erp-bench scenario 2121: Sediment Pre-Filter Assembly
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA4626FF73D_c01','Pinnacle Trading Co','customer',0,10858.27,NULL,NULL,'orders@pinnacletradingco.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA4626FF73D_c02','Ledger Exchange','customer',0,19551.46,NULL,NULL,'orders@ledgerexchange.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA4626FF73D_c03','Granite Labs','customer',0,12756.25,NULL,NULL,'orders@granitelabs.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA4626FF73D_c04','Arrow Architects','customer',0,13008.22,NULL,NULL,'orders@arrowarchitects.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA4626FF73D_c05','Copper Workshop','customer',0,10120.16,NULL,NULL,'orders@copperworkshop.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA4626FF73D_c06','Alpine Studios North','customer',0,16744.22,NULL,NULL,'orders@alpinestudiosnorth.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA4626FF73D_c07','Oakmont Refinery','customer',0,20460.82,NULL,NULL,'orders@oakmontrefinery.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA4626FF73D_c08','Slate Society','customer',0,20332.3,NULL,NULL,'orders@slatesociety.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA4626FF73D_c09','Borough Enterprises','customer',0,18705.1,NULL,NULL,'orders@boroughenterprises.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p01','Osprey Operations Site Logistics','customer',0,NULL,NULL,NULL,'contact@ospreyoperations.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p02','Pivot Operations Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@pivotoperations.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p03','Brookfield Fabrication Quality Lab','customer',0,NULL,NULL,NULL,'contact@brookfieldfabrication.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p04','Ironwood Technologies Site Logistics','customer',0,NULL,NULL,NULL,'contact@ironwoodtechnologies.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p05','Stratos Industries Test Facility','customer',0,NULL,NULL,NULL,'contact@stratosindustries.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p06','Peak Engineering Site Logistics','customer',0,NULL,NULL,NULL,'contact@peakengineering.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p07','Echo Production HQ Procurement','customer',0,NULL,NULL,NULL,'contact@echoproduction.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p08','Northbridge Fabrication Prototype Shop','customer',0,NULL,NULL,NULL,'contact@northbridgefabrication.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p09','Ridge Industries Tooling Center','customer',0,NULL,NULL,NULL,'contact@ridgeindustries.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p10','Monarch Solutions Tooling Center','customer',0,NULL,NULL,NULL,'contact@monarchsolutions.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p11','Raven Assembly Site Logistics','customer',0,NULL,NULL,NULL,'contact@ravenassembly.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p12','Aether Technologies Field Ops','customer',0,NULL,NULL,NULL,'contact@aethertechnologies.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p13','Nexus Manufacturing Prototype Shop','customer',0,NULL,NULL,NULL,'contact@nexusmanufacturing.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p14','Sapphire Services Test Facility','customer',0,NULL,NULL,NULL,'contact@sapphireservices.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p15','Oxide Production R&D Workshop','customer',0,NULL,NULL,NULL,'contact@oxideproduction.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p16','Flux Technologies HQ Procurement','customer',0,NULL,NULL,NULL,'contact@fluxtechnologies.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p17','Ironside Production Site Logistics','customer',0,NULL,NULL,NULL,'contact@ironsideproduction.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p18','Element Engineering R&D Workshop','customer',0,NULL,NULL,NULL,'contact@elementengineering.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p19','Canton Solutions Site Logistics','customer',0,NULL,NULL,NULL,'contact@cantonsolutions.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p20','Crestview Manufacturing Test Facility','customer',0,NULL,NULL,NULL,'contact@crestviewmanufacturing.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p21','Cardinal Technologies Site Logistics','customer',0,NULL,NULL,NULL,'contact@cardinaltechnologies.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p22','Lattice Assembly Test Facility','customer',0,NULL,NULL,NULL,'contact@latticeassembly.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p23','Pacific Services Site Logistics','customer',0,NULL,NULL,NULL,'contact@pacificservices.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p24','Garnet Industries Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@garnetindustries.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p25','Atlas Industries HQ Procurement','customer',0,NULL,NULL,NULL,'contact@atlasindustries.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p26','Bridgeway Solutions Site Logistics','customer',0,NULL,NULL,NULL,'contact@bridgewaysolutions.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p27','Titan Services Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@titanservices.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p28','Matrix Production Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@matrixproduction.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p29','Ember Technologies HQ Procurement','customer',0,NULL,NULL,NULL,'contact@embertechnologies.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p30','Vertex Manufacturing Test Facility','customer',0,NULL,NULL,NULL,'contact@vertexmanufacturing.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p31','Metro Services Prototype Shop','customer',0,NULL,NULL,NULL,'contact@metroservices.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p32','Cascade Fabrication R&D Workshop','customer',0,NULL,NULL,NULL,'contact@cascadefabrication.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p33','Spark Engineering Tooling Center','customer',0,NULL,NULL,NULL,'contact@sparkengineering.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p34','Axis Engineering Quality Lab','customer',0,NULL,NULL,NULL,'contact@axisengineering.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p35','Velocity Assembly Quality Lab','customer',0,NULL,NULL,NULL,'contact@velocityassembly.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p36','Cedar Fabrication Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@cedarfabrication.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p37','Polar Engineering Field Ops','customer',0,NULL,NULL,NULL,'contact@polarengineering.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p38','Nimbus Solutions Test Facility','customer',0,NULL,NULL,NULL,'contact@nimbussolutions.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p39','Cobalt Engineering Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@cobaltengineering.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p40','Cosmo Production Tooling Center','customer',0,NULL,NULL,NULL,'contact@cosmoproduction.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p41','Circuit Assembly Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@circuitassembly.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p42','Aurora Production Test Facility','customer',0,NULL,NULL,NULL,'contact@auroraproduction.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p43','Arbor Operations Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@arboroperations.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p44','Iron Manufacturing Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@ironmanufacturing.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p45','Anvil Fabrication Prototype Shop','customer',0,NULL,NULL,NULL,'contact@anvilfabrication.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p46','Globe Fabrication Quality Lab','customer',0,NULL,NULL,NULL,'contact@globefabrication.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p47','Terra Production Prototype Shop','customer',0,NULL,NULL,NULL,'contact@terraproduction.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p48','Arc Assembly HQ Procurement','customer',0,NULL,NULL,NULL,'contact@arcassembly.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p49','Lakewood Manufacturing Site Logistics','customer',0,NULL,NULL,NULL,'contact@lakewoodmanufacturing.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r385A5AFCC6_p50','Bayshore Services Site Logistics','customer',0,NULL,NULL,NULL,'contact@bayshoreservices.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q01','Citadel Operations','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q02','Scion Freight','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q03','Catalyst Distributors','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q04','Riverdale Materials','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q05','Lumen Industries','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q06','Keystone Packagers','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q07','Clearwater Wholesalers','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q08','Comet Transport','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q09','Crown Assemblies','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q10','Alloy Microfactory','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q11','Vantage Networks','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q12','Apex Distribution','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q13','Redstone Provisions','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q14','Haven Merchants','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q15','Crest Supply','vendor',15,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q16','Steel Partners','vendor',16,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q17','Baltic Forwarders','vendor',17,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q18','Ashford Exporters','vendor',18,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q19','Zenith Manufacturing','vendor',19,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA4626FF73D_q20','Summit Fabrication','vendor',20,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q01','Eclipse Resources','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q02','Conduit Materials','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q03','Flint Networks','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q04','Chrome Trading','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q05','Westfield Sourcing','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q06','Orbital Networks','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q07','Thornton Trading','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q08','Sterling Resources','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q09','Sierra Wholesale','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q10','Blaze Freight','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q11','Skyline Components','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q12','Quantum Wholesale','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q13','Solace Supply','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q14','Cipher Resources','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q15','Beacon Parts Co','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q16','Onyx Distribution','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q17','Fairview Components','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q18','Stonewall Supply','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q19','Ridgeline Transit','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q20','Jade Procurement','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q21','Noble Procurement','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q22','Spire Carriers','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q23','Silverline Parts Co','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q24','Compass Transit','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q25','Evergreen Materials','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q26','Spectra Procurement','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q27','Hartland Logistics','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q28','Dune Components','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q29','Gateway Carriers','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q30','Meridian Distribution','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q31','Indigo Components','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q32','Opal Networks','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q33','Millbrook Parts Co','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q34','Coral Materials','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q35','Trident Materials','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q36','Quartz Freight','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q37','Helix Parts Co','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q38','Bronze Wholesale','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q39','Prism Trading','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q40','Mosaic Distribution','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q41','Marble Supply','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q42','Aegis Components','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q43','Grove Components','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q44','Lance Logistics','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q45','Equinox Sourcing','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q46','Ivory Trading','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q47','Drift Carriers','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q48','Baseline Distribution','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q49','Horizon Procurement','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r385A5AFCC6_q50','Sentinel Parts Co','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA4626FF73D-WTR-SPF-005','Sediment Pre-Filter Assembly','Utility Equipment','consu',703.63,379.06,'buy,manufacture',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'PA4626FF73D-WTR-SPF-005','rA4626FF73D_q01','Priority Shuttle lane (9d transit, 11-53 units)',9,11.0,53.0,408.13);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'PA4626FF73D-WTR-SPF-005','rA4626FF73D_q02','Express Air lane (7d transit, 4-10 units)',7,4.0,10.0,621.69);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'PA4626FF73D-WTR-SPF-005','rA4626FF73D_q03','Bulk Container lane (23d transit, 94-113 units)',23,94.0,113.0,262.89);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'PA4626FF73D-WTR-SPF-005','rA4626FF73D_q04','Regional Cross-Dock lane (13d transit, 8-76 units)',13,8.0,76.0,442.31);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'PA4626FF73D-WTR-SPF-005','rA4626FF73D_q05','Microfactory Build-to-Order lane (8d transit, 5-32 units)',8,5.0,32.0,598.22);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'PA4626FF73D-WTR-SPF-005','rA4626FF73D_q06','Scheduled Freight lane (17d transit, 7-27 units)',17,7.0,27.0,386.3);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA4626FF73D-SUB-02','Sediment Pre-Filter Assembly Subassembly','Utility Equipment','consu',277.35,184.9,'manufacture',NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA4626FF73D-WTR-DRC-118','DI Resin Cartridge Mixed Bed','Utility Equipment','consu',76.59,26.68,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'PA4626FF73D-WTR-DRC-118','rA4626FF73D_q07','Rapid Works (2d)',2,9.0,10.0,49.79);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'PA4626FF73D-WTR-DRC-118','rA4626FF73D_q08','Hybrid Fabricators (4d)',4,19.0,122.0,41.73);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'PA4626FF73D-WTR-DRC-118','rA4626FF73D_q09','Domestic Supply (5d)',5,16.0,182.0,36.72);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'PA4626FF73D-WTR-DRC-118','rA4626FF73D_q10','Import Consolidator (6d)',6,27.0,118.0,26.68);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA4626FF73D-WTR-SSM-120','Stainless Steel Manifold Set','Utility Equipment','consu',139.67,63.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'PA4626FF73D-WTR-SSM-120','rA4626FF73D_q11','Rapid Works (4d)',4,8.0,44.0,76.21);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'PA4626FF73D-WTR-SSM-120','rA4626FF73D_q12','Import Consolidator (6d)',6,30.0,42.0,63.93);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'PA4626FF73D-WTR-SSM-120','rA4626FF73D_q13','Hybrid Fabricators (6d)',6,17.0,69.0,63.37);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA4626FF73D-WTR-PUF-114','PVC Union Fitting Pack','Utility Equipment','consu',14.28,4.95,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'PA4626FF73D-WTR-PUF-114','rA4626FF73D_q14','Rapid Works (2d)',2,6.0,36.0,7.47);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'PA4626FF73D-WTR-PUF-114','rA4626FF73D_q15','Domestic Supply (4d)',4,26.0,99.0,6.54);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'PA4626FF73D-WTR-PUF-114','rA4626FF73D_q16','Import Consolidator (4d)',4,27.0,405.0,4.95);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'PA4626FF73D-WTR-PUF-114','rA4626FF73D_q17','Hybrid Fabricators (4d)',4,8.0,495.0,6.72);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA4626FF73D-WTR-BPM-115','Booster Pump Motor 1HP','Utility Equipment','consu',246.07,106.41,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'PA4626FF73D-WTR-BPM-115','rA4626FF73D_q18','Rapid Works (4d)',4,11.0,39.0,148.68);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'PA4626FF73D-WTR-BPM-115','rA4626FF73D_q19','Import Consolidator (4d)',4,44.0,59.0,106.41);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'PA4626FF73D-WTR-BPM-115','rA4626FF73D_q20','Hybrid Fabricators (4d)',4,16.0,26.0,168.71);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A001','Hardened Bracket Set','Fasteners and Fixings','consu',272.48,163.94,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'P385A5AFCC6-A001','r385A5AFCC6_q01','Express route',8,1.0,24.0,168.82);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A002','Low-Flow Carbon Cartridge 20in','Power Transmission','consu',305.06,175.31,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'P385A5AFCC6-A002','r385A5AFCC6_q02','Cross-dock',4,1.0,24.0,180.28);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A003','Anodized Sleeve Set','Industrial Spare Parts','consu',376.63,226.36,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'P385A5AFCC6-A003','r385A5AFCC6_q03','Regional lane',7,1.0,24.0,229.58);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A004','Medical-Grade Filter Cartridge 5um','Power Transmission','consu',345.17,247.89,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'P385A5AFCC6-A004','r385A5AFCC6_q04','Local pickup',5,1.0,24.0,267.16);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A005','Dual-Stage Cartridge 20in','Power Transmission','consu',375.11,219.3,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'P385A5AFCC6-A005','r385A5AFCC6_q05','Warehouse direct',5,1.0,24.0,219.34);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A006','Sealed Sleeve Set','Replacement Parts','consu',327.73,212.52,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'P385A5AFCC6-A006','r385A5AFCC6_q06','Cross-dock',7,1.0,24.0,209.93);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A007','Wide-Body Sensor Module','Power Transmission','consu',344.58,208.61,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'P385A5AFCC6-A007','r385A5AFCC6_q07','Scheduled freight',3,1.0,24.0,208.92);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A008','High-Flow Conductivity Sensor','Maintenance Supplies','consu',229.73,126.08,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'P385A5AFCC6-A008','r385A5AFCC6_q08','Regional lane',5,1.0,24.0,126.29);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A009','Double-Row Housing FRP','Power Transmission','consu',306.66,199.79,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'P385A5AFCC6-A009','r385A5AFCC6_q09','Scheduled freight',8,1.0,24.0,215.63);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A010','Flanged Element 4x40','Electrical Components','consu',201.58,106.2,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'P385A5AFCC6-A010','r385A5AFCC6_q10','Express route',4,1.0,24.0,107.39);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A011','High-Torque Bracket Set','Electrical Components','consu',246.68,134.67,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'P385A5AFCC6-A011','r385A5AFCC6_q11','Local pickup',6,1.0,24.0,137.68);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A012','Compact Cartridge 20in','Hardware Accessories','consu',230.15,124.63,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'P385A5AFCC6-A012','r385A5AFCC6_q12','Scheduled freight',3,1.0,24.0,123.51);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A013','Economy Meter Sensor Module','Fasteners and Fixings','consu',373.82,217.17,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'P385A5AFCC6-A013','r385A5AFCC6_q13','Local pickup',7,1.0,24.0,224.91);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A014','Threaded Valve Assembly','Fasteners and Fixings','consu',214.35,143.71,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'P385A5AFCC6-A014','r385A5AFCC6_q14','Warehouse direct',4,1.0,24.0,154.15);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A015','Anti-Vibration Filter Cartridge 5um','Seals and Gaskets','consu',256.1,160.59,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'P385A5AFCC6-A015','r385A5AFCC6_q15','Cross-dock',3,1.0,24.0,159.7);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A016','Lightweight Metering Pump','Industrial Spare Parts','consu',200.32,108.54,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'P385A5AFCC6-A016','r385A5AFCC6_q16','Standard delivery',5,1.0,24.0,103.41);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A017','Metric Sleeve Set','Seals and Gaskets','consu',193.51,123.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'P385A5AFCC6-A017','r385A5AFCC6_q17','Cross-dock',5,1.0,24.0,124.61);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A018','High-Temp Valve Assembly','Fasteners and Fixings','consu',305.24,204.84,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'P385A5AFCC6-A018','r385A5AFCC6_q18','Express route',4,1.0,24.0,200.55);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A019','Commercial Gauge 0 100PSI','Seals and Gaskets','consu',333.24,208.26,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'P385A5AFCC6-A019','r385A5AFCC6_q19','Bulk shipment',6,1.0,24.0,199.06);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A020','Zero-Backlash Cartridge 5um','Maintenance Supplies','consu',394.43,256.35,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'P385A5AFCC6-A020','r385A5AFCC6_q20','Bulk shipment',4,1.0,24.0,254.21);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A021','Low-Profile Solenoid Valve Assembly','Industrial Spare Parts','consu',256.43,136.11,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'P385A5AFCC6-A021','r385A5AFCC6_q21','Bulk shipment',8,1.0,24.0,129.69);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A022','Universal TDS Conductivity Sensor','Electrical Components','consu',311.14,192.31,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'P385A5AFCC6-A022','r385A5AFCC6_q22','Express route',4,1.0,24.0,187.54);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A023','Heat-Treated Vessel Housing FRP','Electrical Components','consu',196.46,104.59,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'P385A5AFCC6-A023','r385A5AFCC6_q23','Cross-dock',7,1.0,24.0,110.56);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A024','Adjustable Sensor Module','Pneumatic Components','consu',294.62,194.6,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'P385A5AFCC6-A024','r385A5AFCC6_q24','Warehouse direct',4,1.0,24.0,198.06);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A025','High-Cycle Chemical Metering Pump','Power Transmission','consu',257.87,160.63,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'P385A5AFCC6-A025','r385A5AFCC6_q25','Express route',6,1.0,24.0,155.26);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A026','Cleanroom Chemical Metering Pump','Power Transmission','consu',258.39,182.4,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'P385A5AFCC6-A026','r385A5AFCC6_q26','Scheduled freight',7,1.0,24.0,186.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A027','Modular Cartridge 5um','Hardware Accessories','consu',344.46,202.07,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'P385A5AFCC6-A027','r385A5AFCC6_q27','Cross-dock',4,1.0,24.0,211.86);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A028','Industrial Sleeve Set','Hardware Accessories','consu',319.51,214.86,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'P385A5AFCC6-A028','r385A5AFCC6_q28','Cross-dock',4,1.0,24.0,224.34);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A029','Reinforced Sleeve Set','Mechanical Components','consu',361.73,258.15,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'P385A5AFCC6-A029','r385A5AFCC6_q29','Bulk shipment',7,1.0,24.0,252.79);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A030','Precision Quartz Sleeve Set','Fasteners and Fixings','consu',197.98,138.92,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'P385A5AFCC6-A030','r385A5AFCC6_q30','Cross-dock',4,1.0,24.0,143.91);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A031','Cold-Rolled TDS Conductivity Sensor','Power Transmission','consu',390.55,230.33,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'P385A5AFCC6-A031','r385A5AFCC6_q31','Express route',5,1.0,24.0,246.67);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A032','Narrow-Body Pressure Pump Assembly','Maintenance Supplies','consu',411.59,214.55,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'P385A5AFCC6-A032','r385A5AFCC6_q32','Express route',3,1.0,24.0,227.07);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A033','Powder-Coated Solenoid Valve Assembly','Mechanical Components','consu',365.21,212.19,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'P385A5AFCC6-A033','r385A5AFCC6_q33','Express route',8,1.0,24.0,207.73);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A034','Corrosion-Resistant Carbon Cartridge 20in','Pneumatic Components','consu',242.22,129.33,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'P385A5AFCC6-A034','r385A5AFCC6_q34','Bulk shipment',5,1.0,24.0,125.19);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A035','Snap-Fit Valve Assembly','Mechanical Components','consu',253.06,175.72,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'P385A5AFCC6-A035','r385A5AFCC6_q35','Standard delivery',3,1.0,24.0,176.02);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A036','Low-Friction Pump Assembly','Pneumatic Components','consu',356.11,216.14,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'P385A5AFCC6-A036','r385A5AFCC6_q36','Scheduled freight',3,1.0,24.0,211.83);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A037','Heavy-Duty Carbon Cartridge 20in','Hardware Accessories','consu',385.53,276.44,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(57,'P385A5AFCC6-A037','r385A5AFCC6_q37','Standard delivery',5,1.0,24.0,276.32);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A038','Weatherproof 0 100PSI','Industrial Spare Parts','consu',400.84,235.07,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(58,'P385A5AFCC6-A038','r385A5AFCC6_q38','Cross-dock',7,1.0,24.0,238.15);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A039','Spring-Loaded Carbon Cartridge 20in','Mechanical Components','consu',417.16,243.13,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(59,'P385A5AFCC6-A039','r385A5AFCC6_q39','Express route',6,1.0,24.0,238.2);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A040','Premium TDS Conductivity Sensor','Power Transmission','consu',197.91,110.91,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(60,'P385A5AFCC6-A040','r385A5AFCC6_q40','Standard delivery',8,1.0,24.0,119.42);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A041','Pressure-Balanced Housing FRP','Pneumatic Components','consu',380.49,211.28,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(61,'P385A5AFCC6-A041','r385A5AFCC6_q41','Local pickup',5,1.0,24.0,214.29);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A042','Extended-Life Carbon Cartridge 20in','Power Transmission','consu',262.34,164.04,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(62,'P385A5AFCC6-A042','r385A5AFCC6_q42','Warehouse direct',4,1.0,24.0,173.33);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A043','Tapered Valve Assembly','Industrial Spare Parts','consu',199.14,129.9,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(63,'P385A5AFCC6-A043','r385A5AFCC6_q43','Cross-dock',8,1.0,24.0,137.06);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A044','Self-Lubricating Valve Assembly','Seals and Gaskets','consu',358.33,227.93,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(64,'P385A5AFCC6-A044','r385A5AFCC6_q44','Standard delivery',4,1.0,24.0,220.62);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A045','High-Performance Vessel Housing FRP','Electrical Components','consu',218.66,136.38,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(65,'P385A5AFCC6-A045','r385A5AFCC6_q45','Warehouse direct',4,1.0,24.0,130.2);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A046','Single-Stage Element 4x40','Electrical Components','consu',308.25,174.77,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(66,'P385A5AFCC6-A046','r385A5AFCC6_q46','Scheduled freight',4,1.0,24.0,186.3);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A047','Standard Sensor Module','Mechanical Components','consu',311.96,176.36,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(67,'P385A5AFCC6-A047','r385A5AFCC6_q47','Cross-dock',4,1.0,24.0,187.67);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A048','Low-Temp Valve Assembly','Industrial Spare Parts','consu',400.42,219.26,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(68,'P385A5AFCC6-A048','r385A5AFCC6_q48','Local pickup',3,1.0,24.0,213.42);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A049','UV-Stable Sleeve Set','Pneumatic Components','consu',352.59,205.8,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(69,'P385A5AFCC6-A049','r385A5AFCC6_q49','Standard delivery',7,1.0,24.0,203.1);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P385A5AFCC6-A050','Thermal-Guard Vessel Housing FRP','Replacement Parts','consu',417.25,257.61,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(70,'P385A5AFCC6-A050','r385A5AFCC6_q50','Bulk shipment',6,1.0,24.0,259.79);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'PA4626FF73D-SUB-02','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PA4626FF73D-WTR-PUF-114',5.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PA4626FF73D-WTR-BPM-115',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'PA4626FF73D-WTR-SPF-005','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PA4626FF73D-SUB-02',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PA4626FF73D-WTR-DRC-118',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PA4626FF73D-WTR-SSM-120',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'P385A5AFCC6-A039','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P385A5AFCC6-A022',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'P385A5AFCC6-A014','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'P385A5AFCC6-A042',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'P385A5AFCC6-A002','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P385A5AFCC6-A050',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'P385A5AFCC6-A005','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P385A5AFCC6-A042',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P385A5AFCC6-A011',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'P385A5AFCC6-A024','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'P385A5AFCC6-A021',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'P385A5AFCC6-A026','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P385A5AFCC6-A020',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'P385A5AFCC6-A008','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P385A5AFCC6-A020',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'P385A5AFCC6-A050','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P385A5AFCC6-A005',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(11,'P385A5AFCC6-A007','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'P385A5AFCC6-A010',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(12,'P385A5AFCC6-A023','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(12,'P385A5AFCC6-A043',2.0);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PA4626FF73D-WC02','Fabrication Cell 2',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PA4626FF73D-WC03','Precision Bench 3',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PA4626FF73D-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA4626FF73D-WTR-BPM-115',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA4626FF73D-WTR-DRC-118',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA4626FF73D-WTR-PUF-114',NULL,28.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA4626FF73D-WTR-SPF-005',NULL,99.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA4626FF73D-WTR-SSM-120',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A001',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A002',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A003',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A004',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A005',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A006',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A007',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A008',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A009',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A010',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A011',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A012',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A013',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A014',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A015',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A016',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A017',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A018',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A019',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A020',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A021',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A022',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A023',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A024',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A025',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A026',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A027',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A028',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A029',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A030',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A031',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A032',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A033',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A034',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A035',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A036',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A037',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A038',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A039',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A040',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A041',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A042',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A043',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A044',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A045',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A046',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A047',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A048',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A049',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P385A5AFCC6-A050',NULL,11.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'rA4626FF73D_c01','PA4626FF73D-WTR-SPF-005',14,8,10858.27,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'rA4626FF73D_c02','PA4626FF73D-WTR-SPF-005',26,8,19551.46,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'rA4626FF73D_c03','PA4626FF73D-WTR-SPF-005',17,9,12756.25,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'rA4626FF73D_c04','PA4626FF73D-WTR-SPF-005',17,10,13008.22,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'rA4626FF73D_c05','PA4626FF73D-WTR-SPF-005',14,11,10120.16,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'rA4626FF73D_c06','PA4626FF73D-WTR-SPF-005',23,13,16744.22,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'rA4626FF73D_c07','PA4626FF73D-WTR-SPF-005',26,13,20460.82,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'rA4626FF73D_c08','PA4626FF73D-WTR-SPF-005',26,13,20332.3,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(9,'rA4626FF73D_c09','PA4626FF73D-WTR-SPF-005',26,14,18705.1,NULL);
