-- agentic-labs/erp-bench scenario 2041: Wet Lab Sink Bench
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r70B1F1D4EF_c01','Riverdale Ventures','customer',0,29686.38,NULL,NULL,'orders@riverdaleventures.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r70B1F1D4EF_c02','Cascade Studios East','customer',0,20466.09,NULL,NULL,'orders@cascadestudioseast.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r70B1F1D4EF_c03','Alpine Alliance','customer',0,33688.17,NULL,NULL,'orders@alpinealliance.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r70B1F1D4EF_c04','Ironwood Solutions Group','customer',0,37734.11,NULL,NULL,'orders@ironwoodsolutionsgroup.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r70B1F1D4EF_c05','Crestview Fabricators','customer',0,31926.98,NULL,NULL,'orders@crestviewfabricators.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r70B1F1D4EF_c06','Lattice Reserve','customer',0,33441.7,NULL,NULL,'orders@latticereserve.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r70B1F1D4EF_c07','Lakewood Collective East','customer',0,29164.02,NULL,NULL,'orders@lakewoodcollectiveeast.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r70B1F1D4EF_c08','Equinox Agency','customer',0,31012.29,NULL,NULL,'orders@equinoxagency.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r70B1F1D4EF_c09','Aether Group','customer',0,34082.89,NULL,NULL,'orders@aethergroup.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r70B1F1D4EF_c10','Stratos Labs','customer',0,34462.56,NULL,NULL,'orders@stratoslabs.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p01','Silverline Production R&D Workshop','customer',0,NULL,NULL,NULL,'contact@silverlineproduction.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p02','Conduit Operations Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@conduitoperations.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p03','Pacific Technologies Site Logistics','customer',0,NULL,NULL,NULL,'contact@pacifictechnologies.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p04','Ironside Manufacturing Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@ironsidemanufacturing.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p05','Zenith Solutions Field Ops','customer',0,NULL,NULL,NULL,'contact@zenithsolutions.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p06','Blaze Fabrication Tooling Center','customer',0,NULL,NULL,NULL,'contact@blazefabrication.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p07','Grove Services R&D Workshop','customer',0,NULL,NULL,NULL,'contact@groveservices.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p08','Oxide Engineering Site Logistics','customer',0,NULL,NULL,NULL,'contact@oxideengineering.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p09','Drift Solutions Field Ops','customer',0,NULL,NULL,NULL,'contact@driftsolutions.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p10','Cobalt Assembly Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@cobaltassembly.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p11','Steel Technologies Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@steeltechnologies.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p12','Cipher Technologies Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@ciphertechnologies.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p13','Millbrook Engineering Prototype Shop','customer',0,NULL,NULL,NULL,'contact@millbrookengineering.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p14','Bronze Technologies Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@bronzetechnologies.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p15','Redstone Engineering Prototype Shop','customer',0,NULL,NULL,NULL,'contact@redstoneengineering.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p16','Citadel Manufacturing HQ Procurement','customer',0,NULL,NULL,NULL,'contact@citadelmanufacturing.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p17','Northbridge Solutions HQ Procurement','customer',0,NULL,NULL,NULL,'contact@northbridgesolutions.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p18','Metro Engineering R&D Workshop','customer',0,NULL,NULL,NULL,'contact@metroengineering.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p19','Indigo Industries Site Logistics','customer',0,NULL,NULL,NULL,'contact@indigoindustries.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p20','Cedar Production Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@cedarproduction.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p21','Summit Manufacturing Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@summitmanufacturing.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p22','Terra Operations Quality Lab','customer',0,NULL,NULL,NULL,'contact@terraoperations.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p23','Lance Manufacturing R&D Workshop','customer',0,NULL,NULL,NULL,'contact@lancemanufacturing.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p24','Apex Solutions Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@apexsolutions.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p25','Oakmont Technologies R&D Workshop','customer',0,NULL,NULL,NULL,'contact@oakmonttechnologies.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p26','Jade Services HQ Procurement','customer',0,NULL,NULL,NULL,'contact@jadeservices.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p27','Ivory Operations R&D Workshop','customer',0,NULL,NULL,NULL,'contact@ivoryoperations.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p28','Keystone Technologies Test Facility','customer',0,NULL,NULL,NULL,'contact@keystonetechnologies.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p29','Comet Solutions Tooling Center','customer',0,NULL,NULL,NULL,'contact@cometsolutions.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p30','Trident Operations Test Facility','customer',0,NULL,NULL,NULL,'contact@tridentoperations.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p31','Quartz Operations HQ Procurement','customer',0,NULL,NULL,NULL,'contact@quartzoperations.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p32','Evergreen Industries Site Logistics','customer',0,NULL,NULL,NULL,'contact@evergreenindustries.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p33','Vantage Industries Site Logistics','customer',0,NULL,NULL,NULL,'contact@vantageindustries.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p34','Dune Manufacturing Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@dunemanufacturing.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p35','Crest Services Field Ops','customer',0,NULL,NULL,NULL,'contact@crestservices.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p36','Coral Fabrication Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@coralfabrication.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p37','Fairview Industries Field Ops','customer',0,NULL,NULL,NULL,'contact@fairviewindustries.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p38','Sterling Operations Prototype Shop','customer',0,NULL,NULL,NULL,'contact@sterlingoperations.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p39','Ledger Engineering HQ Procurement','customer',0,NULL,NULL,NULL,'contact@ledgerengineering.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p40','Axis Industries Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@axisindustries.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p41','Cosmo Industries Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@cosmoindustries.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p42','Anvil Industries Quality Lab','customer',0,NULL,NULL,NULL,'contact@anvilindustries.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p43','Eclipse Operations Field Ops','customer',0,NULL,NULL,NULL,'contact@eclipseoperations.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p44','Osprey Fabrication Site Logistics','customer',0,NULL,NULL,NULL,'contact@ospreyfabrication.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p45','Gateway Assembly Field Ops','customer',0,NULL,NULL,NULL,'contact@gatewayassembly.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p46','Crown Services Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@crownservices.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p47','Helix Manufacturing Site Logistics','customer',0,NULL,NULL,NULL,'contact@helixmanufacturing.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p48','Meridian Technologies Prototype Shop','customer',0,NULL,NULL,NULL,'contact@meridiantechnologies.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p49','Marble Technologies Field Ops','customer',0,NULL,NULL,NULL,'contact@marbletechnologies.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rC7E3804B34_p50','Forge Operations Quality Lab','customer',0,NULL,NULL,NULL,'contact@forgeoperations.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r70B1F1D4EF_q01','Matrix Merchants','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r70B1F1D4EF_q02','Catalyst Shipping','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r70B1F1D4EF_q03','Spectra Industries','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r70B1F1D4EF_q04','Ridge Supply','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r70B1F1D4EF_q05','Haven Sourcing','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r70B1F1D4EF_q06','Compass Fulfillment','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q01','Raven Logistics','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q02','Scion Parts Co','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q03','Iron Freight','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q04','Arrow Parts Co','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q05','Noble Transit','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q06','Aegis Resources','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q07','Stonewall Networks','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q08','Ember Distribution','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q09','Trellis Materials','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q10','Chrome Logistics','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q11','Thornton Freight','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q12','Sapphire Carriers','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q13','Garnet Freight','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q14','Orbital Procurement','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q15','Titan Carriers','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q16','Atlas Parts Co','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q17','Solace Resources','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q18','Quantum Wholesale','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q19','Spire Networks','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q20','Nexus Parts Co','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q21','Arbor Materials','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q22','Clearwater Materials','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q23','Horizon Trading','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q24','Globe Trading','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q25','Beacon Parts Co','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q26','Flint Resources','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q27','Mosaic Logistics','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q28','Element Procurement','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q29','Vertex Components','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q30','Alloy Sourcing','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q31','Pivot Resources','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q32','Westfield Wholesale','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q33','Skyline Transit','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q34','Sentinel Parts Co','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q35','Echo Materials','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q36','Slate Distribution','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q37','Baseline Procurement','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q38','Sierra Parts Co','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q39','Lumen Sourcing','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q40','Aurora Sourcing','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q41','Copper Parts Co','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q42','Hartland Components','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q43','Flux Logistics','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q44','Prism Materials','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q45','Pinnacle Parts Co','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q46','Circuit Carriers','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q47','Peak Logistics','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q48','Velocity Trading','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q49','Borough Trading','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rC7E3804B34_q50','Baltic Freight','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P70B1F1D4EF-LAB-WLB-005','Wet Lab Sink Bench','Laboratory Equipment','consu',1918.8,1150.58,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'P70B1F1D4EF-LAB-WLB-005','r70B1F1D4EF_q01','Priority Shuttle lane (8d transit, 6-40 units)',8,6.0,40.0,1147.67);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'P70B1F1D4EF-LAB-WLB-005','r70B1F1D4EF_q02','Express Air lane (5d transit, 5-47 units)',5,5.0,47.0,1412.23);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'P70B1F1D4EF-LAB-WLB-005','r70B1F1D4EF_q03','Bulk Container lane (21d transit, 80-142 units)',21,80.0,142.0,736.02);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'P70B1F1D4EF-LAB-WLB-005','r70B1F1D4EF_q04','Air Charter lane (6d transit, 2-6 units)',6,2.0,6.0,1620.44);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'P70B1F1D4EF-LAB-WLB-005','r70B1F1D4EF_q05','Regional Cross-Dock lane (12d transit, 9-43 units)',12,9.0,43.0,959.39);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'P70B1F1D4EF-LAB-WLB-005','r70B1F1D4EF_q06','Microfactory Build-to-Order lane (8d transit, 3-3 units)',8,3.0,3.0,1362.24);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A001','UV-Stable Utility Channel Kit','Maintenance Supplies','consu',271.09,154.78,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'PC7E3804B34-A001','rC7E3804B34_q01','Scheduled freight',6,1.0,24.0,148.87);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A002','Low-Profile Support Frame','Fasteners and Fixings','consu',201.5,112.79,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'PC7E3804B34-A002','rC7E3804B34_q02','Express route',5,1.0,24.0,118.72);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A003','Rapid-Lock Reagent Shelf Unit','Hardware Accessories','consu',389.03,239.38,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'PC7E3804B34-A003','rC7E3804B34_q03','Express route',6,1.0,24.0,235.62);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A004','Impact-Rated Drain Fitting','Mechanical Components','consu',218.69,153.86,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'PC7E3804B34-A004','rC7E3804B34_q04','Standard delivery',3,1.0,24.0,156.58);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A005','Dual-Stage Basin Insert','Maintenance Supplies','consu',407.92,262.78,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'PC7E3804B34-A005','rC7E3804B34_q05','Express route',3,1.0,24.0,269.58);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A006','Flanged Drawer Slide Mechanism','Industrial Spare Parts','consu',395.35,232.8,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'PC7E3804B34-A006','rC7E3804B34_q06','Scheduled freight',6,1.0,24.0,246.74);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A007','Single-Stage Drawer Slide Mechanism','Pneumatic Components','consu',403.39,242.31,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'PC7E3804B34-A007','rC7E3804B34_q07','Warehouse direct',5,1.0,24.0,249.25);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A008','Precision Gas Valve Assembly','Power Transmission','consu',231.09,154.25,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'PC7E3804B34-A008','rC7E3804B34_q08','Standard delivery',5,1.0,24.0,152.56);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A009','Low-Noise Utility Channel Kit','Hardware Accessories','consu',356.52,221.1,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'PC7E3804B34-A009','rC7E3804B34_q09','Scheduled freight',5,1.0,24.0,213.93);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A010','Extended-Life Drain Fitting','Mechanical Components','consu',191.13,124.14,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'PC7E3804B34-A010','rC7E3804B34_q10','Scheduled freight',8,1.0,24.0,120.1);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A011','Sealed Resistant Top','Fasteners and Fixings','consu',262.24,147.67,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'PC7E3804B34-A011','rC7E3804B34_q11','Bulk shipment',8,1.0,24.0,153.83);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A012','Self-Lubricating Valve Assembly','Electrical Components','consu',305.92,209.09,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'PC7E3804B34-A012','rC7E3804B34_q12','Warehouse direct',8,1.0,24.0,205.88);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A013','Double-Row Accessory Panel','Hardware Accessories','consu',219.45,127.71,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'PC7E3804B34-A013','rC7E3804B34_q13','Standard delivery',5,1.0,24.0,122.01);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A014','Premium Pegboard Accessory Panel','Hardware Accessories','consu',189.14,120.82,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'PC7E3804B34-A014','rC7E3804B34_q14','Cross-dock',3,1.0,24.0,117.14);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A015','Quick-Release Anti Static Mat','Power Transmission','consu',218.88,123.02,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'PC7E3804B34-A015','rC7E3804B34_q15','Regional lane',5,1.0,24.0,130.89);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A016','Non-Magnetic Basin Insert','Pneumatic Components','consu',366.43,245.73,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'PC7E3804B34-A016','rC7E3804B34_q16','Bulk shipment',3,1.0,24.0,256.19);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A017','High-Cycle Reagent Shelf Unit','Industrial Spare Parts','consu',276.63,183.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'PC7E3804B34-A017','rC7E3804B34_q17','Warehouse direct',4,1.0,24.0,190.64);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A018','Food-Grade Steel Support Frame','Fasteners and Fixings','consu',282.88,157.1,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'PC7E3804B34-A018','rC7E3804B34_q18','Standard delivery',8,1.0,24.0,160.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A019','Hardened Anti Static Mat','Pneumatic Components','consu',370.97,226.21,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'PC7E3804B34-A019','rC7E3804B34_q19','Local pickup',3,1.0,24.0,224.53);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A020','Snap-Fit Drawer Slide Mechanism','Hardware Accessories','consu',383.67,217.95,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'PC7E3804B34-A020','rC7E3804B34_q20','Warehouse direct',8,1.0,24.0,218.15);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A021','Adjustable Reagent Shelf Unit','Electrical Components','consu',324.04,179.86,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'PC7E3804B34-A021','rC7E3804B34_q21','Bulk shipment',8,1.0,24.0,172.76);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A022','Thermal-Guard Gas Valve Assembly','Replacement Parts','consu',316.05,171.7,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'PC7E3804B34-A022','rC7E3804B34_q22','Local pickup',4,1.0,24.0,185.33);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A023','Universal Steel Support Frame','Industrial Spare Parts','consu',351.81,197.66,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'PC7E3804B34-A023','rC7E3804B34_q23','Scheduled freight',6,1.0,24.0,207.14);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A024','Anodized Resin Worktop Panel','Seals and Gaskets','consu',239.81,158.57,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'PC7E3804B34-A024','rC7E3804B34_q24','Express route',4,1.0,24.0,157.37);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A025','Economy Slide Mechanism','Fasteners and Fixings','consu',194.34,102.47,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'PC7E3804B34-A025','rC7E3804B34_q25','Warehouse direct',8,1.0,24.0,110.54);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A026','Zero-Backlash Channel Kit','Industrial Spare Parts','consu',368.41,231.43,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'PC7E3804B34-A026','rC7E3804B34_q26','Local pickup',6,1.0,24.0,232.11);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A027','Low-Flow Support Frame','Replacement Parts','consu',194.23,109.26,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'PC7E3804B34-A027','rC7E3804B34_q27','Regional lane',5,1.0,24.0,109.11);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A028','High-Temp Resin Worktop Panel','Power Transmission','consu',281.55,184.07,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'PC7E3804B34-A028','rC7E3804B34_q28','Scheduled freight',5,1.0,24.0,177.29);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A029','Industrial Gas Valve Assembly','Power Transmission','consu',375.54,227.5,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'PC7E3804B34-A029','rC7E3804B34_q29','Standard delivery',8,1.0,24.0,219.46);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A030','Wide-Body Chemical Resistant Top','Industrial Spare Parts','consu',404.33,259.95,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'PC7E3804B34-A030','rC7E3804B34_q30','Local pickup',3,1.0,24.0,253.84);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A031','Cold-Rolled Channel Kit','Fasteners and Fixings','consu',373.56,195.97,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'PC7E3804B34-A031','rC7E3804B34_q31','Cross-dock',6,1.0,24.0,198.18);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A032','Commercial Support Frame','Electrical Components','consu',371.17,231.94,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'PC7E3804B34-A032','rC7E3804B34_q32','Warehouse direct',5,1.0,24.0,224.48);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A033','High-Flow Valve Assembly','Maintenance Supplies','consu',223.64,158.78,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'PC7E3804B34-A033','rC7E3804B34_q33','Warehouse direct',7,1.0,24.0,170.57);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A034','Spring-Loaded with Drain Fitting','Pneumatic Components','consu',305.25,209.08,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'PC7E3804B34-A034','rC7E3804B34_q34','Standard delivery',8,1.0,24.0,220.31);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A035','Low-Friction Drain Fitting','Maintenance Supplies','consu',243.95,170.93,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'PC7E3804B34-A035','rC7E3804B34_q35','Standard delivery',5,1.0,24.0,170.03);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A036','Corrosion-Resistant Basin Insert','Seals and Gaskets','consu',305.9,218.96,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'PC7E3804B34-A036','rC7E3804B34_q36','Regional lane',5,1.0,24.0,223.21);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A037','Cleanroom Basin Insert','Replacement Parts','consu',329.05,178.87,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'PC7E3804B34-A037','rC7E3804B34_q37','Express route',6,1.0,24.0,188.39);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A038','Stainless Static Mat','Hardware Accessories','consu',302.87,202.76,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'PC7E3804B34-A038','rC7E3804B34_q38','Bulk shipment',3,1.0,24.0,211.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A039','High-Performance Sink Basin Insert','Seals and Gaskets','consu',392.43,241.31,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'PC7E3804B34-A039','rC7E3804B34_q39','Express route',3,1.0,24.0,250.35);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A040','Heavy-Duty Resin Worktop Panel','Fasteners and Fixings','consu',198.8,128.54,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'PC7E3804B34-A040','rC7E3804B34_q40','Scheduled freight',8,1.0,24.0,126.6);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A041','Standard Utility Channel Kit','Power Transmission','consu',331.15,187.11,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'PC7E3804B34-A041','rC7E3804B34_q41','Regional lane',4,1.0,24.0,184.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A042','Tapered Slide Mechanism','Pneumatic Components','consu',207.35,126.0,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'PC7E3804B34-A042','rC7E3804B34_q42','Scheduled freight',3,1.0,24.0,121.0);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A043','Modular with Drain Fitting','Power Transmission','consu',182.63,109.35,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'PC7E3804B34-A043','rC7E3804B34_q43','Bulk shipment',4,1.0,24.0,105.57);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A044','Threaded Spill Containment Tray','Maintenance Supplies','consu',310.33,167.87,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'PC7E3804B34-A044','rC7E3804B34_q44','Scheduled freight',8,1.0,24.0,176.2);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A045','Weatherproof Utility Channel Kit','Industrial Spare Parts','consu',207.74,110.47,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'PC7E3804B34-A045','rC7E3804B34_q45','Cross-dock',6,1.0,24.0,114.76);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A046','Compact Support Frame','Hardware Accessories','consu',183.35,112.95,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'PC7E3804B34-A046','rC7E3804B34_q46','Regional lane',4,1.0,24.0,107.98);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A047','Lightweight Channel Kit','Seals and Gaskets','consu',260.77,137.36,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'PC7E3804B34-A047','rC7E3804B34_q47','Warehouse direct',6,1.0,24.0,135.17);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A048','Powder-Coated Accessory Panel','Hardware Accessories','consu',309.36,178.44,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'PC7E3804B34-A048','rC7E3804B34_q48','Express route',6,1.0,24.0,170.55);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A049','Anti-Vibration Chemical Resistant Top','Mechanical Components','consu',418.74,295.6,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'PC7E3804B34-A049','rC7E3804B34_q49','Standard delivery',7,1.0,24.0,285.82);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PC7E3804B34-A050','Medical-Grade Shelf Unit','Mechanical Components','consu',373.37,206.55,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'PC7E3804B34-A050','rC7E3804B34_q50','Warehouse direct',4,1.0,24.0,215.22);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'PC7E3804B34-A014','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PC7E3804B34-A008',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'PC7E3804B34-A032','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PC7E3804B34-A026',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'PC7E3804B34-A040','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'PC7E3804B34-A034',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'PC7E3804B34-A007','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'PC7E3804B34-A001',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'PC7E3804B34-A003',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'PC7E3804B34-A043','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'PC7E3804B34-A008',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'PC7E3804B34-A046',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'PC7E3804B34-A017','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'PC7E3804B34-A043',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'PC7E3804B34-A004','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'PC7E3804B34-A005',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'PC7E3804B34-A042',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'PC7E3804B34-A005','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'PC7E3804B34-A015',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'PC7E3804B34-A018',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'PC7E3804B34-A033','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'PC7E3804B34-A008',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'PC7E3804B34-A022','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'PC7E3804B34-A032',3.0);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P70B1F1D4EF-LAB-WLB-005',NULL,68.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A001',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A002',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A003',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A004',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A005',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A006',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A007',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A008',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A009',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A010',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A011',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A012',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A013',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A014',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A015',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A016',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A017',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A018',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A019',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A020',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A021',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A022',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A023',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A024',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A025',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A026',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A027',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A028',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A029',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A030',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A031',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A032',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A033',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A034',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A035',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A036',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A037',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A038',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A039',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A040',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A041',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A042',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A043',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A044',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A045',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A046',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A047',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A048',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A049',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PC7E3804B34-A050',NULL,15.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'r70B1F1D4EF_c01','P70B1F1D4EF-LAB-WLB-005',14,8,29686.38,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'r70B1F1D4EF_c02','P70B1F1D4EF-LAB-WLB-005',14,8,20466.09,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'r70B1F1D4EF_c03','P70B1F1D4EF-LAB-WLB-005',17,9,33688.17,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'r70B1F1D4EF_c04','P70B1F1D4EF-LAB-WLB-005',19,10,37734.11,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'r70B1F1D4EF_c05','P70B1F1D4EF-LAB-WLB-005',16,10,31926.98,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'r70B1F1D4EF_c06','P70B1F1D4EF-LAB-WLB-005',17,10,33441.7,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'r70B1F1D4EF_c07','P70B1F1D4EF-LAB-WLB-005',14,10,29164.02,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'r70B1F1D4EF_c08','P70B1F1D4EF-LAB-WLB-005',15,10,31012.29,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(9,'r70B1F1D4EF_c09','P70B1F1D4EF-LAB-WLB-005',17,11,34082.89,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(10,'r70B1F1D4EF_c10','P70B1F1D4EF-LAB-WLB-005',17,12,34462.56,'draft');
