-- agentic-labs/erp-bench scenario 2237: Bifacial Solar Module 450W
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB42F55DDCD_c01','Oxide Exchange','customer',0,6907.57,NULL,NULL,'orders@oxideexchange.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB42F55DDCD_c02','Hartland Holdings','customer',0,5376.41,NULL,NULL,'orders@hartlandholdings.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB42F55DDCD_c03','Granite Consortium','customer',0,8642.56,NULL,NULL,'orders@graniteconsortium.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB42F55DDCD_c04','Flux Trust','customer',0,7062.64,NULL,NULL,'orders@fluxtrust.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB42F55DDCD_c05','Steel Trading Co','customer',0,10331.33,NULL,NULL,'orders@steeltradingco.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB42F55DDCD_c06','Clearwater Interactive','customer',0,11404.47,NULL,NULL,'orders@clearwaterinteractive.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB42F55DDCD_c07','Vantage Council','customer',0,10784.62,NULL,NULL,'orders@vantagecouncil.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB42F55DDCD_c08','Sapphire Productions','customer',0,11034.03,NULL,NULL,'orders@sapphireproductions.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB42F55DDCD_c09','Onyx Boutique','customer',0,11399.21,NULL,NULL,'orders@onyxboutique.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB42F55DDCD_c10','Lance Architects','customer',0,11513.36,NULL,NULL,'orders@lancearchitects.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p01','Silverline Engineering Prototype Shop','customer',0,NULL,NULL,NULL,'contact@silverlineengineering.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p02','Brookfield Production Tooling Center','customer',0,NULL,NULL,NULL,'contact@brookfieldproduction.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p03','Trellis Manufacturing Site Logistics','customer',0,NULL,NULL,NULL,'contact@trellismanufacturing.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p04','Cobalt Engineering Prototype Shop','customer',0,NULL,NULL,NULL,'contact@cobaltengineering.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p05','Redstone Solutions Field Ops','customer',0,NULL,NULL,NULL,'contact@redstonesolutions.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p06','Arc Solutions Prototype Shop','customer',0,NULL,NULL,NULL,'contact@arcsolutions.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p07','Citadel Technologies Test Facility','customer',0,NULL,NULL,NULL,'contact@citadeltechnologies.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p08','Pinnacle Services R&D Workshop','customer',0,NULL,NULL,NULL,'contact@pinnacleservices.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p09','Borough Services R&D Workshop','customer',0,NULL,NULL,NULL,'contact@boroughservices.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p10','Eclipse Technologies R&D Workshop','customer',0,NULL,NULL,NULL,'contact@eclipsetechnologies.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p11','Conduit Manufacturing Prototype Shop','customer',0,NULL,NULL,NULL,'contact@conduitmanufacturing.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p12','Atlas Services Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@atlasservices.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p13','Pacific Engineering Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@pacificengineering.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p14','Drift Technologies Tooling Center','customer',0,NULL,NULL,NULL,'contact@drifttechnologies.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p15','Fairview Technologies Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@fairviewtechnologies.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p16','Jade Engineering Test Facility','customer',0,NULL,NULL,NULL,'contact@jadeengineering.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p17','Beacon Production Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@beaconproduction.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p18','Bridgeway Engineering HQ Procurement','customer',0,NULL,NULL,NULL,'contact@bridgewayengineering.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p19','Polar Production Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@polarproduction.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p20','Crown Fabrication HQ Procurement','customer',0,NULL,NULL,NULL,'contact@crownfabrication.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p21','Solace Production HQ Procurement','customer',0,NULL,NULL,NULL,'contact@solaceproduction.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p22','Vertex Assembly Quality Lab','customer',0,NULL,NULL,NULL,'contact@vertexassembly.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p23','Baseline Fabrication Field Ops','customer',0,NULL,NULL,NULL,'contact@baselinefabrication.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p24','Aegis Services Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@aegisservices.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p25','Pivot Production Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@pivotproduction.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p26','Cardinal Fabrication Test Facility','customer',0,NULL,NULL,NULL,'contact@cardinalfabrication.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p27','Crest Manufacturing Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@crestmanufacturing.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p28','Ledger Technologies Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@ledgertechnologies.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p29','Helix Technologies Site Logistics','customer',0,NULL,NULL,NULL,'contact@helixtechnologies.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p30','Matrix Engineering HQ Procurement','customer',0,NULL,NULL,NULL,'contact@matrixengineering.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p31','Globe Production Test Facility','customer',0,NULL,NULL,NULL,'contact@globeproduction.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p32','Osprey Industries HQ Procurement','customer',0,NULL,NULL,NULL,'contact@ospreyindustries.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p33','Circuit Technologies Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@circuittechnologies.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p34','Alpine Operations Field Ops','customer',0,NULL,NULL,NULL,'contact@alpineoperations.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p35','Ridge Operations HQ Procurement','customer',0,NULL,NULL,NULL,'contact@ridgeoperations.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p36','Metro Production HQ Procurement','customer',0,NULL,NULL,NULL,'contact@metroproduction.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p37','Lumen Technologies Test Facility','customer',0,NULL,NULL,NULL,'contact@lumentechnologies.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p38','Zenith Services Field Ops','customer',0,NULL,NULL,NULL,'contact@zenithservices.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p39','Ivory Technologies Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@ivorytechnologies.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p40','Spark Solutions R&D Workshop','customer',0,NULL,NULL,NULL,'contact@sparksolutions.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p41','Aurora Assembly R&D Workshop','customer',0,NULL,NULL,NULL,'contact@auroraassembly.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p42','Trident Operations Field Ops','customer',0,NULL,NULL,NULL,'contact@tridentoperations.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p43','Nimbus Operations R&D Workshop','customer',0,NULL,NULL,NULL,'contact@nimbusoperations.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p44','Opal Production Field Ops','customer',0,NULL,NULL,NULL,'contact@opalproduction.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p45','Cascade Manufacturing Test Facility','customer',0,NULL,NULL,NULL,'contact@cascademanufacturing.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p46','Indigo Assembly Field Ops','customer',0,NULL,NULL,NULL,'contact@indigoassembly.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p47','Arrow Industries HQ Procurement','customer',0,NULL,NULL,NULL,'contact@arrowindustries.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p48','Sterling Technologies HQ Procurement','customer',0,NULL,NULL,NULL,'contact@sterlingtechnologies.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p49','Oakmont Solutions Tooling Center','customer',0,NULL,NULL,NULL,'contact@oakmontsolutions.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r3456DF35DA_p50','Arbor Technologies Test Facility','customer',0,NULL,NULL,NULL,'contact@arbortechnologies.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB42F55DDCD_q01','Sentinel Procurement','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB42F55DDCD_q02','Ashford Distribution','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB42F55DDCD_q03','Northbridge Manufacturing','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB42F55DDCD_q04','Copper Holdings','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB42F55DDCD_q05','Ember Components','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB42F55DDCD_q06','Compass Haulage','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB42F55DDCD_q07','Evergreen Depot','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB42F55DDCD_q08','Riverdale Industries','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB42F55DDCD_q09','Cedar Provisions','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB42F55DDCD_q10','Ironside Transport','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB42F55DDCD_q11','Flint Networks','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB42F55DDCD_q12','Sierra Consolidators','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB42F55DDCD_q13','Westfield Transit','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB42F55DDCD_q14','Element Fabrication','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB42F55DDCD_q15','Baltic Warehouse','vendor',15,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB42F55DDCD_q16','Anvil Microfactory','vendor',16,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB42F55DDCD_q17','Nexus Packagers','vendor',17,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB42F55DDCD_q18','Mosaic Supply','vendor',18,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB42F55DDCD_q19','Axis Distributors','vendor',19,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q01','Gateway Logistics','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q02','Chrome Sourcing','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q03','Titan Wholesale','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q04','Thornton Materials','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q05','Summit Parts Co','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q06','Equinox Resources','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q07','Crestview Distribution','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q08','Lakewood Logistics','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q09','Alloy Components','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q10','Ridgeline Components','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q11','Velocity Procurement','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q12','Echo Materials','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q13','Keystone Logistics','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q14','Canton Parts Co','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q15','Cosmo Trading','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q16','Prism Wholesale','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q17','Aether Logistics','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q18','Forge Materials','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q19','Ironwood Resources','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q20','Spectra Wholesale','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q21','Cipher Trading','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q22','Spire Networks','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q23','Stonewall Parts Co','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q24','Bayshore Wholesale','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q25','Noble Sourcing','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q26','Millbrook Procurement','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q27','Catalyst Parts Co','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q28','Orbital Parts Co','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q29','Bronze Parts Co','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q30','Haven Components','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q31','Slate Transit','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q32','Skyline Procurement','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q33','Iron Components','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q34','Terra Supply','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q35','Peak Materials','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q36','Stratos Logistics','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q37','Monarch Parts Co','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q38','Lattice Carriers','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q39','Apex Transit','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q40','Quartz Freight','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q41','Quantum Components','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q42','Marble Carriers','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q43','Coral Carriers','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q44','Meridian Wholesale','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q45','Blaze Carriers','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q46','Comet Procurement','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q47','Raven Parts Co','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q48','Dune Trading','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q49','Horizon Wholesale','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r3456DF35DA_q50','Grove Parts Co','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PB42F55DDCD-SOL-BFM-002','Bifacial Solar Module 450W','Power Equipment','consu',404.77,228.58,'buy,manufacture',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'PB42F55DDCD-SOL-BFM-002','rB42F55DDCD_q01','Priority Shuttle lane (9d transit, 14-18 units)',9,14.0,18.0,253.25);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'PB42F55DDCD-SOL-BFM-002','rB42F55DDCD_q02','Express Air lane (7d transit, 4-5 units)',7,4.0,5.0,338.76);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'PB42F55DDCD-SOL-BFM-002','rB42F55DDCD_q03','Regional Cross-Dock lane (11d transit, 9-9 units)',11,9.0,9.0,236.73);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'PB42F55DDCD-SOL-BFM-002','rB42F55DDCD_q04','Economy Ocean lane (24d transit, 13-13 units)',24,13.0,13.0,144.36);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'PB42F55DDCD-SOL-BFM-002','rB42F55DDCD_q05','Microfactory Build-to-Order lane (6d transit, 3-4 units)',6,3.0,4.0,321.96);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PB42F55DDCD-RESMOD-02','Bifacial Solar Module 450W Restricted Module','Power Equipment','consu',245.87,163.91,'manufacture',NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PB42F55DDCD-SOL-GSF-112','Ground Screw Foundation Pile','Power Equipment','consu',30.92,11.11,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'PB42F55DDCD-SOL-GSF-112','rB42F55DDCD_q06','Rapid Works (3d)',3,12.0,263.0,15.41);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'PB42F55DDCD-SOL-GSF-112','rB42F55DDCD_q07','Import Consolidator (6d)',6,26.0,337.0,11.94);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'PB42F55DDCD-SOL-GSF-112','rB42F55DDCD_q08','Domestic Supply (5d)',5,20.0,32.0,11.11);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'PB42F55DDCD-SOL-GSF-112','rB42F55DDCD_q09','Hybrid Fabricators (6d)',6,20.0,104.0,14.95);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PB42F55DDCD-SOL-ECF-122','Edge Clamp Fastener Pack','Power Equipment','consu',10.47,4.43,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'PB42F55DDCD-SOL-ECF-122','rB42F55DDCD_q10','Rapid Works (3d)',3,8.0,751.0,5.33);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'PB42F55DDCD-SOL-ECF-122','rB42F55DDCD_q11','Hybrid Fabricators (4d)',4,17.0,66.0,4.43);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'PB42F55DDCD-SOL-ECF-122','rB42F55DDCD_q12','Domestic Supply (6d)',6,26.0,171.0,4.5);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PB42F55DDCD-SOL-AFE-105','Aluminum Frame Extrusion Set','Power Equipment','consu',40.33,18.19,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'PB42F55DDCD-SOL-AFE-105','rB42F55DDCD_q13','Rapid Works (3d)',3,7.0,82.0,21.62);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'PB42F55DDCD-SOL-AFE-105','rB42F55DDCD_q14','Hybrid Fabricators (4d)',4,16.0,211.0,22.9);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'PB42F55DDCD-SOL-AFE-105','rB42F55DDCD_q15','Domestic Supply (4d)',4,18.0,232.0,18.19);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PB42F55DDCD-SOL-MIM-109','Micro-Inverter Module','Power Equipment','consu',158.99,77.15,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'PB42F55DDCD-SOL-MIM-109','rB42F55DDCD_q16','Rapid Works (3d)',3,6.0,44.0,120.4);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'PB42F55DDCD-SOL-MIM-109','rB42F55DDCD_q17','Hybrid Fabricators (4d)',4,17.0,32.0,89.38);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'PB42F55DDCD-SOL-MIM-109','rB42F55DDCD_q18','Import Consolidator (4d)',4,39.0,46.0,77.15);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'PB42F55DDCD-SOL-MIM-109','rB42F55DDCD_q19','Domestic Supply (4d)',4,17.0,151.0,83.05);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A001','Impact-Rated T Slot 4m','Pneumatic Components','consu',185.86,109.05,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'P3456DF35DA-A001','r3456DF35DA_q01','Regional lane',7,1.0,24.0,105.04);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A002','Premium Front Sheet','Pneumatic Components','consu',279.91,201.49,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'P3456DF35DA-A002','r3456DF35DA_q02','Regional lane',8,1.0,24.0,214.84);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A003','Industrial Bypass Diodes','Electrical Components','consu',326.88,177.19,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'P3456DF35DA-A003','r3456DF35DA_q03','Bulk shipment',8,1.0,24.0,169.59);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A004','Adjustable Inverter 5kW','Industrial Spare Parts','consu',360.14,247.8,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'P3456DF35DA-A004','r3456DF35DA_q04','Standard delivery',8,1.0,24.0,263.93);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A005','Compact Foundation Pile','Maintenance Supplies','consu',240.5,149.58,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'P3456DF35DA-A005','r3456DF35DA_q05','Regional lane',7,1.0,24.0,155.36);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A006','Low-Flow Encapsulant Film Roll','Pneumatic Components','consu',341.91,186.18,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'P3456DF35DA-A006','r3456DF35DA_q06','Standard delivery',3,1.0,24.0,194.97);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A007','Dual-Stage Film Roll','Maintenance Supplies','consu',385.33,226.64,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'P3456DF35DA-A007','r3456DF35DA_q07','Scheduled freight',3,1.0,24.0,230.81);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A008','Precision Extrusion Set','Maintenance Supplies','consu',200.22,135.61,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'P3456DF35DA-A008','r3456DF35DA_q08','Standard delivery',5,1.0,24.0,137.18);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A009','Low-Profile Protective Film','Fasteners and Fixings','consu',181.55,97.04,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'P3456DF35DA-A009','r3456DF35DA_q09','Standard delivery',7,1.0,24.0,97.43);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A010','Commercial Backsheet Protective Film','Fasteners and Fixings','consu',385.97,274.73,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'P3456DF35DA-A010','r3456DF35DA_q10','Regional lane',7,1.0,24.0,279.56);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A011','Metric Hook Mounting Bracket','Replacement Parts','consu',371.21,234.44,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'P3456DF35DA-A011','r3456DF35DA_q11','Standard delivery',7,1.0,24.0,227.59);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A012','High-Cycle Film Roll','Pneumatic Components','consu',327.15,177.27,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'P3456DF35DA-A012','r3456DF35DA_q12','Standard delivery',6,1.0,24.0,183.07);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A013','Non-Magnetic Micro Inverter Module','Electrical Components','consu',351.59,234.41,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'P3456DF35DA-A013','r3456DF35DA_q13','Cross-dock',5,1.0,24.0,232.29);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A014','Sealed Hook Mounting Bracket','Fasteners and Fixings','consu',369.3,238.19,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'P3456DF35DA-A014','r3456DF35DA_q14','Bulk shipment',5,1.0,24.0,246.78);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A015','Cleanroom Front Sheet','Fasteners and Fixings','consu',180.23,96.33,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'P3456DF35DA-A015','r3456DF35DA_q15','Bulk shipment',5,1.0,24.0,93.28);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A016','Medical-Grade Cable Set','Maintenance Supplies','consu',314.55,168.88,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'P3456DF35DA-A016','r3456DF35DA_q16','Cross-dock',8,1.0,24.0,164.04);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A017','Heat-Treated Glass Front Sheet','Hardware Accessories','consu',404.77,256.29,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'P3456DF35DA-A017','r3456DF35DA_q17','Scheduled freight',8,1.0,24.0,272.59);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A018','High-Torque Extrusion Set','Pneumatic Components','consu',338.38,227.9,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'P3456DF35DA-A018','r3456DF35DA_q18','Cross-dock',8,1.0,24.0,237.81);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A019','Pressure-Balanced Protective Film','Industrial Spare Parts','consu',375.52,261.47,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'P3456DF35DA-A019','r3456DF35DA_q19','Cross-dock',7,1.0,24.0,254.06);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A020','Food-Grade Extrusion Set','Power Transmission','consu',241.01,151.61,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'P3456DF35DA-A020','r3456DF35DA_q20','Express route',7,1.0,24.0,146.61);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A021','Rapid-Lock with Bypass Diodes','Replacement Parts','consu',298.46,191.75,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'P3456DF35DA-A021','r3456DF35DA_q21','Warehouse direct',5,1.0,24.0,205.3);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A022','Wide-Body Encapsulant Film Roll','Hardware Accessories','consu',416.27,244.81,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'P3456DF35DA-A022','r3456DF35DA_q22','Express route',6,1.0,24.0,258.76);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A023','Single-Stage Encapsulant Film Roll','Hardware Accessories','consu',412.57,215.0,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'P3456DF35DA-A023','r3456DF35DA_q23','Regional lane',8,1.0,24.0,218.69);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A024','Quick-Release String Inverter 5kW','Industrial Spare Parts','consu',346.28,220.17,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'P3456DF35DA-A024','r3456DF35DA_q24','Local pickup',7,1.0,24.0,216.73);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A025','Stainless Micro Inverter Module','Mechanical Components','consu',341.77,180.64,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'P3456DF35DA-A025','r3456DF35DA_q25','Regional lane',5,1.0,24.0,185.5);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A026','Flanged String Set','Hardware Accessories','consu',378.47,226.67,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'P3456DF35DA-A026','r3456DF35DA_q26','Standard delivery',8,1.0,24.0,225.92);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A027','Powder-Coated with Bypass Diodes','Seals and Gaskets','consu',371.45,254.28,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'P3456DF35DA-A027','r3456DF35DA_q27','Scheduled freight',5,1.0,24.0,261.48);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A028','Universal Frame Extrusion Set','Replacement Parts','consu',206.04,118.11,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'P3456DF35DA-A028','r3456DF35DA_q28','Local pickup',5,1.0,24.0,125.22);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A029','Lightweight Bypass Diodes','Industrial Spare Parts','consu',256.23,165.21,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'P3456DF35DA-A029','r3456DF35DA_q29','Regional lane',7,1.0,24.0,160.29);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A030','Narrow-Body String Inverter 5kW','Replacement Parts','consu',338.76,207.24,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'P3456DF35DA-A030','r3456DF35DA_q30','Warehouse direct',7,1.0,24.0,218.46);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A031','Corrosion-Resistant Slot 4m','Power Transmission','consu',410.5,235.45,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'P3456DF35DA-A031','r3456DF35DA_q31','Express route',6,1.0,24.0,231.91);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A032','Standard Glass Front Sheet','Electrical Components','consu',180.47,102.75,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'P3456DF35DA-A032','r3456DF35DA_q32','Cross-dock',7,1.0,24.0,104.64);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A033','Low-Noise Encapsulant Film Roll','Pneumatic Components','consu',338.55,242.46,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'P3456DF35DA-A033','r3456DF35DA_q33','Bulk shipment',7,1.0,24.0,240.69);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A034','Reinforced Encapsulant Film Roll','Seals and Gaskets','consu',315.48,207.29,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'P3456DF35DA-A034','r3456DF35DA_q34','Cross-dock',8,1.0,24.0,201.64);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A035','High-Temp Hook Mounting Bracket','Seals and Gaskets','consu',318.18,190.12,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'P3456DF35DA-A035','r3456DF35DA_q35','Local pickup',4,1.0,24.0,187.61);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A036','Thermal-Guard Inverter Module','Mechanical Components','consu',320.16,201.38,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'P3456DF35DA-A036','r3456DF35DA_q36','Standard delivery',5,1.0,24.0,212.33);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A037','Cold-Rolled Cable Set','Power Transmission','consu',412.17,291.55,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'P3456DF35DA-A037','r3456DF35DA_q37','Local pickup',6,1.0,24.0,281.57);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A038','Anodized Connector Cable Set','Hardware Accessories','consu',281.61,164.98,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(57,'P3456DF35DA-A038','r3456DF35DA_q38','Scheduled freight',6,1.0,24.0,177.71);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A039','UV-Stable String Inverter 5kW','Hardware Accessories','consu',295.36,192.09,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(58,'P3456DF35DA-A039','r3456DF35DA_q39','Express route',4,1.0,24.0,184.78);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A040','Weatherproof Screw Foundation Pile','Replacement Parts','consu',219.33,127.93,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(59,'P3456DF35DA-A040','r3456DF35DA_q40','Warehouse direct',3,1.0,24.0,134.11);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A041','Hardened Slot 4m','Hardware Accessories','consu',415.39,270.77,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(60,'P3456DF35DA-A041','r3456DF35DA_q41','Regional lane',3,1.0,24.0,260.98);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A042','Heavy-Duty Backsheet Protective Film','Mechanical Components','consu',366.02,216.77,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(61,'P3456DF35DA-A042','r3456DF35DA_q42','Local pickup',6,1.0,24.0,218.84);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A043','Anti-Vibration Backsheet Protective Film','Industrial Spare Parts','consu',399.06,285.35,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(62,'P3456DF35DA-A043','r3456DF35DA_q43','Local pickup',3,1.0,24.0,296.18);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A044','Zero-Backlash Hook Mounting Bracket','Hardware Accessories','consu',360.51,249.61,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(63,'P3456DF35DA-A044','r3456DF35DA_q44','Bulk shipment',7,1.0,24.0,259.86);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A045','Tapered Connector Cable Set','Industrial Spare Parts','consu',406.58,212.78,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(64,'P3456DF35DA-A045','r3456DF35DA_q45','Regional lane',3,1.0,24.0,227.08);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A046','High-Performance Backsheet Protective Film','Pneumatic Components','consu',379.85,269.83,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(65,'P3456DF35DA-A046','r3456DF35DA_q46','Standard delivery',6,1.0,24.0,282.52);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A047','Threaded Cell String Set','Pneumatic Components','consu',216.33,114.04,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(66,'P3456DF35DA-A047','r3456DF35DA_q47','Bulk shipment',8,1.0,24.0,109.25);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A048','Double-Row T Slot 4m','Fasteners and Fixings','consu',320.08,201.55,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(67,'P3456DF35DA-A048','r3456DF35DA_q48','Warehouse direct',6,1.0,24.0,207.43);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A049','Spring-Loaded Cable Set','Mechanical Components','consu',250.87,155.03,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(68,'P3456DF35DA-A049','r3456DF35DA_q49','Bulk shipment',3,1.0,24.0,164.23);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P3456DF35DA-A050','Extended-Life Slot 4m','Mechanical Components','consu',297.32,168.43,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(69,'P3456DF35DA-A050','r3456DF35DA_q50','Local pickup',6,1.0,24.0,169.33);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'PB42F55DDCD-RESMOD-02','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PB42F55DDCD-SOL-AFE-105',4.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PB42F55DDCD-SOL-MIM-109',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'PB42F55DDCD-SOL-BFM-002','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PB42F55DDCD-RESMOD-02',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PB42F55DDCD-SOL-GSF-112',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PB42F55DDCD-SOL-ECF-122',6.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'P3456DF35DA-A019','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P3456DF35DA-A038',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'P3456DF35DA-A003','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'P3456DF35DA-A029',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'P3456DF35DA-A020','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P3456DF35DA-A015',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P3456DF35DA-A031',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'P3456DF35DA-A014','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P3456DF35DA-A037',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P3456DF35DA-A004',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'P3456DF35DA-A042','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'P3456DF35DA-A024',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'P3456DF35DA-A021',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'P3456DF35DA-A041','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P3456DF35DA-A044',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'P3456DF35DA-A038','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P3456DF35DA-A036',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'P3456DF35DA-A001','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P3456DF35DA-A004',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P3456DF35DA-A030',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(11,'P3456DF35DA-A046','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'P3456DF35DA-A036',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(12,'P3456DF35DA-A036','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(12,'P3456DF35DA-A013',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(12,'P3456DF35DA-A034',3.0);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PB42F55DDCD-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PB42F55DDCD-WC02','Fabrication Cell 2',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PB42F55DDCD-WC03','Precision Bench 3',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PB42F55DDCD-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PB42F55DDCD-SOL-AFE-105',NULL,22.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PB42F55DDCD-SOL-BFM-002',NULL,50.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PB42F55DDCD-SOL-ECF-122',NULL,45.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PB42F55DDCD-SOL-GSF-112',NULL,18.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PB42F55DDCD-SOL-MIM-109',NULL,16.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A001',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A002',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A003',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A004',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A005',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A006',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A007',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A008',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A009',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A010',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A011',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A012',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A013',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A014',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A015',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A016',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A017',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A018',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A019',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A020',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A021',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A022',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A023',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A024',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A025',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A026',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A027',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A028',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A029',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A030',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A031',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A032',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A033',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A034',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A035',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A036',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A037',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A038',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A039',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A040',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A041',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A042',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A043',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A044',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A045',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A046',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A047',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A048',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A049',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P3456DF35DA-A050',NULL,14.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'rB42F55DDCD_c01','PB42F55DDCD-SOL-BFM-002',16,8,6907.57,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'rB42F55DDCD_c02','PB42F55DDCD-SOL-BFM-002',14,8,5376.41,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'rB42F55DDCD_c03','PB42F55DDCD-SOL-BFM-002',20,9,8642.56,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'rB42F55DDCD_c04','PB42F55DDCD-SOL-BFM-002',17,9,7062.64,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'rB42F55DDCD_c05','PB42F55DDCD-SOL-BFM-002',23,10,10331.33,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'rB42F55DDCD_c06','PB42F55DDCD-SOL-BFM-002',26,10,11404.47,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'rB42F55DDCD_c07','PB42F55DDCD-SOL-BFM-002',26,13,10784.62,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'rB42F55DDCD_c08','PB42F55DDCD-SOL-BFM-002',26,13,11034.03,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(9,'rB42F55DDCD_c09','PB42F55DDCD-SOL-BFM-002',26,14,11399.21,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(10,'rB42F55DDCD_c10','PB42F55DDCD-SOL-BFM-002',26,14,11513.36,'draft');
