-- agentic-labs/erp-bench scenario 2249: Landing Door Assembly Single-Speed
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rED61E153BE_c01','Metro Atelier','customer',0,64378.99,NULL,NULL,'orders@metroatelier.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rED61E153BE_c02','Fairview Exchange','customer',0,69909.67,NULL,NULL,'orders@fairviewexchange.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rED61E153BE_c03','Ridge Enterprises','customer',0,50548.86,NULL,NULL,'orders@ridgeenterprises.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rED61E153BE_c04','Borough Boutique','customer',0,61983.01,NULL,NULL,'orders@boroughboutique.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rED61E153BE_c05','Copper Collective','customer',0,101619.23,NULL,NULL,'orders@coppercollective.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rED61E153BE_c06','Blaze Creative','customer',0,71421.99,NULL,NULL,'orders@blazecreative.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rED61E153BE_c07','Sierra Collective East','customer',0,94284.34,NULL,NULL,'orders@sierracollectiveeast.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rED61E153BE_c08','Compass Pavilion','customer',0,93096.66,NULL,NULL,'orders@compasspavilion.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rED61E153BE_c09','Cipher Designs','customer',0,100819.26,NULL,NULL,'orders@cipherdesigns.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p01','Catalyst Assembly Tooling Center','customer',0,NULL,NULL,NULL,'contact@catalystassembly.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p02','Alloy Operations R&D Workshop','customer',0,NULL,NULL,NULL,'contact@alloyoperations.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p03','Spectra Services Site Logistics','customer',0,NULL,NULL,NULL,'contact@spectraservices.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p04','Coral Operations Test Facility','customer',0,NULL,NULL,NULL,'contact@coraloperations.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p05','Dune Industries Site Logistics','customer',0,NULL,NULL,NULL,'contact@duneindustries.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p06','Granite Solutions Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@granitesolutions.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p07','Lattice Solutions Quality Lab','customer',0,NULL,NULL,NULL,'contact@latticesolutions.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p08','Clearwater Engineering Prototype Shop','customer',0,NULL,NULL,NULL,'contact@clearwaterengineering.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p09','Eclipse Assembly R&D Workshop','customer',0,NULL,NULL,NULL,'contact@eclipseassembly.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p10','Quartz Fabrication Quality Lab','customer',0,NULL,NULL,NULL,'contact@quartzfabrication.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p11','Element Services Tooling Center','customer',0,NULL,NULL,NULL,'contact@elementservices.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p12','Bronze Technologies Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@bronzetechnologies.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p13','Citadel Industries Site Logistics','customer',0,NULL,NULL,NULL,'contact@citadelindustries.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p14','Alpine Manufacturing HQ Procurement','customer',0,NULL,NULL,NULL,'contact@alpinemanufacturing.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p15','Trident Engineering Field Ops','customer',0,NULL,NULL,NULL,'contact@tridentengineering.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p16','Ledger Services Field Ops','customer',0,NULL,NULL,NULL,'contact@ledgerservices.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p17','Bridgeway Solutions R&D Workshop','customer',0,NULL,NULL,NULL,'contact@bridgewaysolutions.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p18','Slate Production Site Logistics','customer',0,NULL,NULL,NULL,'contact@slateproduction.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p19','Ironwood Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@ironwoodassembly.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p20','Titan Technologies Site Logistics','customer',0,NULL,NULL,NULL,'contact@titantechnologies.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p21','Garnet Fabrication R&D Workshop','customer',0,NULL,NULL,NULL,'contact@garnetfabrication.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p22','Vertex Operations Prototype Shop','customer',0,NULL,NULL,NULL,'contact@vertexoperations.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p23','Steel Technologies Site Logistics','customer',0,NULL,NULL,NULL,'contact@steeltechnologies.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p24','Aurora Engineering Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@auroraengineering.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p25','Northbridge Engineering R&D Workshop','customer',0,NULL,NULL,NULL,'contact@northbridgeengineering.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p26','Aether Production Site Logistics','customer',0,NULL,NULL,NULL,'contact@aetherproduction.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p27','Chrome Services Prototype Shop','customer',0,NULL,NULL,NULL,'contact@chromeservices.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p28','Apex Technologies HQ Procurement','customer',0,NULL,NULL,NULL,'contact@apextechnologies.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p29','Cosmo Fabrication R&D Workshop','customer',0,NULL,NULL,NULL,'contact@cosmofabrication.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p30','Hartland Industries HQ Procurement','customer',0,NULL,NULL,NULL,'contact@hartlandindustries.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p31','Summit Services Site Logistics','customer',0,NULL,NULL,NULL,'contact@summitservices.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p32','Onyx Manufacturing HQ Procurement','customer',0,NULL,NULL,NULL,'contact@onyxmanufacturing.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p33','Equinox Engineering Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@equinoxengineering.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p34','Crest Technologies Prototype Shop','customer',0,NULL,NULL,NULL,'contact@cresttechnologies.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p35','Monarch Engineering Field Ops','customer',0,NULL,NULL,NULL,'contact@monarchengineering.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p36','Aegis Services Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@aegisservices.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p37','Zenith Industries Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@zenithindustries.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p38','Orbital Production HQ Procurement','customer',0,NULL,NULL,NULL,'contact@orbitalproduction.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p39','Circuit Services Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@circuitservices.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p40','Bayshore Assembly Site Logistics','customer',0,NULL,NULL,NULL,'contact@bayshoreassembly.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p41','Thornton Technologies Prototype Shop','customer',0,NULL,NULL,NULL,'contact@thorntontechnologies.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p42','Lakewood Manufacturing Test Facility','customer',0,NULL,NULL,NULL,'contact@lakewoodmanufacturing.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p43','Arbor Production Tooling Center','customer',0,NULL,NULL,NULL,'contact@arborproduction.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p44','Lance Operations Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@lanceoperations.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p45','Meridian Industries Tooling Center','customer',0,NULL,NULL,NULL,'contact@meridianindustries.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p46','Ironside Operations Quality Lab','customer',0,NULL,NULL,NULL,'contact@ironsideoperations.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p47','Baltic Operations Tooling Center','customer',0,NULL,NULL,NULL,'contact@balticoperations.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p48','Canton Fabrication Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@cantonfabrication.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p49','Nimbus Solutions Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@nimbussolutions.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rDA5577803B_p50','Terra Fabrication R&D Workshop','customer',0,NULL,NULL,NULL,'contact@terrafabrication.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q01','Cobalt Distributors','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q02','Oakmont Procurement','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q03','Stratos Importers','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q04','Mosaic Networks','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q05','Indigo Assemblies','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q06','Matrix Freight','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q07','Prism Merchants','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q08','Flux Carriers','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q09','Noble Integrators','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q10','Nexus Components','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q11','Riverdale Exporters','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q12','Pinnacle Consolidators','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q13','Keystone Solutions','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q14','Forge Warehouse','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q15','Sentinel Depot','vendor',15,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q16','Sapphire Logistics','vendor',16,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q17','Westfield Conveyance','vendor',17,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q18','Vantage Packagers','vendor',18,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q19','Raven Commodities','vendor',19,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rED61E153BE_q20','Baseline Resources','vendor',20,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q01','Skyline Parts Co','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q02','Beacon Networks','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q03','Helix Sourcing','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q04','Oxide Distribution','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q05','Iron Procurement','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q06','Stonewall Wholesale','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q07','Osprey Resources','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q08','Silverline Materials','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q09','Quantum Wholesale','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q10','Anvil Sourcing','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q11','Crestview Carriers','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q12','Comet Sourcing','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q13','Cardinal Trading','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q14','Brookfield Networks','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q15','Horizon Sourcing','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q16','Globe Carriers','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q17','Spire Procurement','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q18','Sterling Resources','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q19','Pacific Resources','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q20','Conduit Materials','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q21','Ivory Transit','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q22','Cedar Transit','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q23','Scion Parts Co','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q24','Lumen Supply','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q25','Trellis Sourcing','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q26','Evergreen Parts Co','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q27','Redstone Wholesale','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q28','Arrow Parts Co','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q29','Gateway Freight','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q30','Crown Parts Co','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q31','Solace Parts Co','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q32','Millbrook Logistics','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q33','Marble Distribution','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q34','Polar Trading','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q35','Grove Distribution','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q36','Jade Resources','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q37','Drift Trading','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q38','Ashford Trading','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q39','Cascade Parts Co','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q40','Atlas Procurement','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q41','Ember Transit','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q42','Axis Trading','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q43','Flint Transit','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q44','Opal Transit','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q45','Pivot Components','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q46','Arc Supply','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q47','Echo Distribution','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q48','Ridgeline Transit','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q49','Velocity Freight','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rDA5577803B_q50','Spark Wholesale','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PED61E153BE-ELV-LDA-110','Landing Door Assembly Single-Speed','Building Systems','consu',3496.56,2075.63,'buy,manufacture',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'PED61E153BE-ELV-LDA-110','rED61E153BE_q01','Priority Shuttle lane (9d transit, 14-15 units)',9,14.0,15.0,2581.6);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'PED61E153BE-ELV-LDA-110','rED61E153BE_q02','Express Air lane (5d transit, 2-19 units)',5,2.0,19.0,3209.6);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'PED61E153BE-ELV-LDA-110','rED61E153BE_q03','Bulk Container lane (21d transit, 94-107 units)',21,94.0,107.0,1212.52);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'PED61E153BE-ELV-LDA-110','rED61E153BE_q04','Economy Ocean lane (21d transit, 8-20 units)',21,8.0,20.0,1897.4);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'PED61E153BE-ELV-LDA-110','rED61E153BE_q05','Bulk Container lane (26d transit, 94-94 units)',26,94.0,94.0,1067.16);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PED61E153BE-SUB-02','Landing Door Assembly Single-Speed Subassembly','Building Systems','consu',3060.65,2040.43,'manufacture',NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PED61E153BE-ELV-ERD-022','Emergency Rescue Device','Building Systems','consu',586.98,262.52,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'PED61E153BE-ELV-ERD-022','rED61E153BE_q06','Rapid Works (2d)',2,8.0,45.0,459.75);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'PED61E153BE-ELV-ERD-022','rED61E153BE_q07','Import Consolidator (6d)',6,26.0,37.0,262.52);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'PED61E153BE-ELV-ERD-022','rED61E153BE_q08','Domestic Supply (6d)',6,15.0,34.0,363.0);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'PED61E153BE-ELV-ERD-022','rED61E153BE_q09','Hybrid Fabricators (5d)',5,8.0,80.0,363.19);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PED61E153BE-ELV-SIL-024','Landing Sill Threshold Plate','Building Systems','consu',130.11,50.99,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'PED61E153BE-ELV-SIL-024','rED61E153BE_q10','Rapid Works (4d)',4,12.0,15.0,74.63);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'PED61E153BE-ELV-SIL-024','rED61E153BE_q11','Import Consolidator (6d)',6,27.0,34.0,50.99);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'PED61E153BE-ELV-SIL-024','rED61E153BE_q12','Domestic Supply (6d)',6,25.0,28.0,67.23);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PED61E153BE-ELV-MTR-001','Gearless Traction Motor','Building Systems','consu',2351.98,1284.03,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'PED61E153BE-ELV-MTR-001','rED61E153BE_q13','Rapid Works (3d)',3,12.0,47.0,1871.21);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'PED61E153BE-ELV-MTR-001','rED61E153BE_q14','Domestic Supply (4d)',4,23.0,48.0,1284.03);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'PED61E153BE-ELV-MTR-001','rED61E153BE_q15','Import Consolidator (4d)',4,31.0,49.0,1382.11);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'PED61E153BE-ELV-MTR-001','rED61E153BE_q16','Hybrid Fabricators (4d)',4,16.0,44.0,1648.17);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PED61E153BE-ELV-ENC-003','Incremental Shaft Encoder','Building Systems','consu',316.32,160.27,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'PED61E153BE-ELV-ENC-003','rED61E153BE_q17','Rapid Works (4d)',4,11.0,21.0,256.59);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'PED61E153BE-ELV-ENC-003','rED61E153BE_q18','Domestic Supply (4d)',4,21.0,67.0,207.15);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'PED61E153BE-ELV-ENC-003','rED61E153BE_q19','Import Consolidator (4d)',4,40.0,211.0,160.27);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'PED61E153BE-ELV-ENC-003','rED61E153BE_q20','Hybrid Fabricators (4d)',4,20.0,55.0,216.23);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A001','Anodized Ceiling Panel','Replacement Parts','consu',341.84,245.09,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'PDA5577803B-A001','rDA5577803B_q01','Warehouse direct',5,1.0,24.0,235.8);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A002','UV-Stable Sheave Assembly','Maintenance Supplies','consu',364.18,261.57,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'PDA5577803B-A002','rDA5577803B_q02','Scheduled freight',5,1.0,24.0,265.09);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A003','High-Temp Governor Assembly','Hardware Accessories','consu',295.97,198.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'PDA5577803B-A003','rDA5577803B_q03','Scheduled freight',7,1.0,24.0,194.41);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A004','Adjustable Incremental Shaft Encoder','Replacement Parts','consu',285.22,192.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'PDA5577803B-A004','rDA5577803B_q04','Local pickup',4,1.0,24.0,189.02);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A005','Industrial Top Inspection Box','Power Transmission','consu',295.54,204.39,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'PDA5577803B-A005','rDA5577803B_q05','Local pickup',7,1.0,24.0,215.5);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A006','High-Performance Button Module','Power Transmission','consu',215.77,135.71,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'PDA5577803B-A006','rDA5577803B_q06','Local pickup',5,1.0,24.0,135.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A007','Non-Magnetic Sheave Assembly','Replacement Parts','consu',208.64,119.05,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'PDA5577803B-A007','rDA5577803B_q07','Express route',8,1.0,24.0,122.4);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A008','Metric Sheave Assembly','Maintenance Supplies','consu',297.26,210.61,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'PDA5577803B-A008','rDA5577803B_q08','Standard delivery',7,1.0,24.0,203.68);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A009','Corrosion-Resistant Safety Gear Set','Industrial Spare Parts','consu',240.84,150.19,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'PDA5577803B-A009','rDA5577803B_q09','Bulk shipment',8,1.0,24.0,142.93);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A010','Economy Overspeed Governor Assembly','Industrial Spare Parts','consu',315.87,182.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'PDA5577803B-A010','rDA5577803B_q10','Bulk shipment',8,1.0,24.0,193.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A011','Standard Top Inspection Box','Replacement Parts','consu',362.18,252.25,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'PDA5577803B-A011','rDA5577803B_q11','Express route',5,1.0,24.0,264.71);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A012','Tapered Safety Gear Set','Pneumatic Components','consu',283.22,182.5,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'PDA5577803B-A012','rDA5577803B_q12','Warehouse direct',4,1.0,24.0,185.13);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A013','Reinforced Overspeed Governor Assembly','Replacement Parts','consu',338.85,232.55,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'PDA5577803B-A013','rDA5577803B_q13','Scheduled freight',5,1.0,24.0,235.96);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A014','Narrow-Body Electromagnetic Guide Shoe','Mechanical Components','consu',234.86,146.85,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'PDA5577803B-A014','rDA5577803B_q14','Cross-dock',6,1.0,24.0,156.89);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A015','Self-Lubricating Set 12mm','Fasteners and Fixings','consu',229.08,127.56,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'PDA5577803B-A015','rDA5577803B_q15','Scheduled freight',5,1.0,24.0,137.17);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A016','Zero-Backlash Incremental Shaft Encoder','Pneumatic Components','consu',389.63,224.87,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'PDA5577803B-A016','rDA5577803B_q16','Cross-dock',5,1.0,24.0,215.06);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A017','Medical-Grade Top Inspection Box','Electrical Components','consu',246.48,141.75,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'PDA5577803B-A017','rDA5577803B_q17','Scheduled freight',5,1.0,24.0,143.73);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A018','Double-Row Deflector Sheave Assembly','Fasteners and Fixings','consu',297.28,200.45,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'PDA5577803B-A018','rDA5577803B_q18','Express route',3,1.0,24.0,190.79);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A019','Threaded Button Module','Seals and Gaskets','consu',381.44,257.48,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'PDA5577803B-A019','rDA5577803B_q19','Warehouse direct',5,1.0,24.0,259.53);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A020','Low-Flow Overspeed Governor Assembly','Power Transmission','consu',308.18,211.02,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'PDA5577803B-A020','rDA5577803B_q20','Local pickup',5,1.0,24.0,209.09);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A021','Stainless Inspection Box','Fasteners and Fixings','consu',336.48,192.11,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'PDA5577803B-A021','rDA5577803B_q21','Standard delivery',6,1.0,24.0,191.61);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A022','Lightweight Deflector Sheave Assembly','Electrical Components','consu',269.98,177.05,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'PDA5577803B-A022','rDA5577803B_q22','Warehouse direct',6,1.0,24.0,183.19);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A023','Quick-Release Governor Assembly','Replacement Parts','consu',337.31,207.1,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'PDA5577803B-A023','rDA5577803B_q23','Cross-dock',4,1.0,24.0,219.88);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A024','Low-Friction Shaft Encoder','Industrial Spare Parts','consu',184.68,102.35,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'PDA5577803B-A024','rDA5577803B_q24','Regional lane',6,1.0,24.0,107.39);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A025','Heat-Treated Top Inspection Box','Power Transmission','consu',191.84,108.16,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'PDA5577803B-A025','rDA5577803B_q25','Standard delivery',7,1.0,24.0,105.37);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A026','Weatherproof Safety Gear Set','Seals and Gaskets','consu',285.29,188.51,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'PDA5577803B-A026','rDA5577803B_q26','Bulk shipment',4,1.0,24.0,190.0);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A027','High-Flow Sheave Assembly','Hardware Accessories','consu',358.86,207.0,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'PDA5577803B-A027','rDA5577803B_q27','Scheduled freight',7,1.0,24.0,213.4);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A028','Dual-Stage Gear Set','Pneumatic Components','consu',226.52,120.16,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'PDA5577803B-A028','rDA5577803B_q28','Bulk shipment',8,1.0,24.0,122.31);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A029','Low-Profile Rope Set 12mm','Hardware Accessories','consu',405.78,212.86,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'PDA5577803B-A029','rDA5577803B_q29','Scheduled freight',6,1.0,24.0,202.47);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A030','Food-Grade LED Ceiling Panel','Maintenance Supplies','consu',292.41,152.85,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'PDA5577803B-A030','rDA5577803B_q30','Local pickup',3,1.0,24.0,147.7);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A031','Rapid-Lock Deflector Sheave Assembly','Pneumatic Components','consu',368.96,253.32,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'PDA5577803B-A031','rDA5577803B_q31','Scheduled freight',7,1.0,24.0,254.97);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A032','Heavy-Duty Governor Assembly','Fasteners and Fixings','consu',248.43,158.22,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'PDA5577803B-A032','rDA5577803B_q32','Regional lane',4,1.0,24.0,160.46);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A033','Low-Noise Governor Assembly','Power Transmission','consu',330.77,222.47,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'PDA5577803B-A033','rDA5577803B_q33','Express route',8,1.0,24.0,232.23);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A034','Low-Temp Overspeed Governor Assembly','Maintenance Supplies','consu',375.98,215.36,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'PDA5577803B-A034','rDA5577803B_q34','Cross-dock',7,1.0,24.0,213.17);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A035','Powder-Coated Deflector Sheave Assembly','Fasteners and Fixings','consu',279.71,158.94,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'PDA5577803B-A035','rDA5577803B_q35','Standard delivery',4,1.0,24.0,153.82);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A036','Premium Push Button Module','Mechanical Components','consu',371.44,216.6,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'PDA5577803B-A036','rDA5577803B_q36','Regional lane',7,1.0,24.0,214.21);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A037','Cold-Rolled Deflector Sheave Assembly','Pneumatic Components','consu',330.89,187.14,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(57,'PDA5577803B-A037','rDA5577803B_q37','Scheduled freight',3,1.0,24.0,180.73);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A038','Cleanroom Door Panel Stainless','Industrial Spare Parts','consu',357.89,194.06,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(58,'PDA5577803B-A038','rDA5577803B_q38','Local pickup',3,1.0,24.0,201.23);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A039','Anti-Vibration Set 12mm','Replacement Parts','consu',208.63,126.68,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(59,'PDA5577803B-A039','rDA5577803B_q39','Scheduled freight',8,1.0,24.0,121.17);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A040','High-Torque Ceiling Panel','Maintenance Supplies','consu',293.85,185.05,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(60,'PDA5577803B-A040','rDA5577803B_q40','Regional lane',8,1.0,24.0,191.41);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A041','Precision Top Inspection Box','Mechanical Components','consu',357.5,211.57,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(61,'PDA5577803B-A041','rDA5577803B_q41','Warehouse direct',4,1.0,24.0,223.9);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A042','Compact Gearless Traction Motor','Mechanical Components','consu',226.95,136.97,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(62,'PDA5577803B-A042','rDA5577803B_q42','Express route',4,1.0,24.0,147.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A043','Wide-Body Panel Stainless','Hardware Accessories','consu',371.25,256.14,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(63,'PDA5577803B-A043','rDA5577803B_q43','Bulk shipment',7,1.0,24.0,253.48);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A044','Single-Stage Sheave Assembly','Industrial Spare Parts','consu',404.92,253.84,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(64,'PDA5577803B-A044','rDA5577803B_q44','Local pickup',7,1.0,24.0,259.67);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A045','Universal Set 12mm','Fasteners and Fixings','consu',327.05,201.6,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(65,'PDA5577803B-A045','rDA5577803B_q45','Scheduled freight',7,1.0,24.0,213.24);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A046','Hardened Button Module','Electrical Components','consu',185.44,126.21,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(66,'PDA5577803B-A046','rDA5577803B_q46','Standard delivery',6,1.0,24.0,121.03);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A047','Extended-Life Governor Assembly','Hardware Accessories','consu',374.43,259.84,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(67,'PDA5577803B-A047','rDA5577803B_q47','Warehouse direct',8,1.0,24.0,257.72);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A048','Snap-Fit Ceiling Panel','Seals and Gaskets','consu',262.38,136.7,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(68,'PDA5577803B-A048','rDA5577803B_q48','Regional lane',7,1.0,24.0,145.02);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A049','Flanged Push Button Module','Pneumatic Components','consu',293.44,206.02,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(69,'PDA5577803B-A049','rDA5577803B_q49','Standard delivery',7,1.0,24.0,199.66);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PDA5577803B-A050','Commercial Door Panel Stainless','Hardware Accessories','consu',402.73,278.06,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(70,'PDA5577803B-A050','rDA5577803B_q50','Regional lane',3,1.0,24.0,300.01);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'PED61E153BE-SUB-02','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PED61E153BE-ELV-MTR-001',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PED61E153BE-ELV-ENC-003',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'PED61E153BE-ELV-LDA-110','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PED61E153BE-SUB-02',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PED61E153BE-ELV-ERD-022',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PED61E153BE-ELV-SIL-024',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'PDA5577803B-A002','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'PDA5577803B-A014',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'PDA5577803B-A022',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'PDA5577803B-A039','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'PDA5577803B-A042',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'PDA5577803B-A015',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'PDA5577803B-A005','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'PDA5577803B-A025',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'PDA5577803B-A001',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'PDA5577803B-A031','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'PDA5577803B-A004',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'PDA5577803B-A024','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'PDA5577803B-A001',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'PDA5577803B-A035',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'PDA5577803B-A042','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'PDA5577803B-A012',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'PDA5577803B-A008',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'PDA5577803B-A043','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'PDA5577803B-A029',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'PDA5577803B-A033','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'PDA5577803B-A034',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'PDA5577803B-A002',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(11,'PDA5577803B-A044','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'PDA5577803B-A014',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'PDA5577803B-A035',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(12,'PDA5577803B-A030','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(12,'PDA5577803B-A039',1.0);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PED61E153BE-WC02','Fabrication Cell 2',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PED61E153BE-WC03','Precision Bench 3',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PED61E153BE-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PED61E153BE-WC03','Precision Bench 3',0,0,NULL,NULL);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PED61E153BE-ELV-ENC-003',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PED61E153BE-ELV-ERD-022',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PED61E153BE-ELV-LDA-110',NULL,87.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PED61E153BE-ELV-MTR-001',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PED61E153BE-ELV-SIL-024',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A001',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A002',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A003',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A004',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A005',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A006',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A007',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A008',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A009',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A010',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A011',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A012',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A013',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A014',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A015',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A016',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A017',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A018',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A019',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A020',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A021',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A022',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A023',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A024',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A025',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A026',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A027',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A028',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A029',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A030',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A031',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A032',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A033',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A034',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A035',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A036',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A037',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A038',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A039',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A040',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A041',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A042',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A043',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A044',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A045',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A046',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A047',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A048',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A049',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PDA5577803B-A050',NULL,9.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'rED61E153BE_c01','PED61E153BE-ELV-LDA-110',18,8,64378.99,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'rED61E153BE_c02','PED61E153BE-ELV-LDA-110',18,9,69909.67,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'rED61E153BE_c03','PED61E153BE-ELV-LDA-110',14,9,50548.86,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'rED61E153BE_c04','PED61E153BE-ELV-LDA-110',17,9,61983.01,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'rED61E153BE_c05','PED61E153BE-ELV-LDA-110',26,9,101619.23,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'rED61E153BE_c06','PED61E153BE-ELV-LDA-110',19,13,71421.99,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'rED61E153BE_c07','PED61E153BE-ELV-LDA-110',26,13,94284.34,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'rED61E153BE_c08','PED61E153BE-ELV-LDA-110',25,13,93096.66,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(9,'rED61E153BE_c09','PED61E153BE-ELV-LDA-110',26,14,100819.26,NULL);
