-- agentic-labs/erp-bench scenario 2181: Laminar Flow Bench Horizontal
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAF749C7EEC_c01','Nexus Enterprises','customer',0,76578.74,NULL,NULL,'orders@nexusenterprises.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAF749C7EEC_c02','Trident Publishing','customer',0,92475.05,NULL,NULL,'orders@tridentpublishing.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAF749C7EEC_c03','Haven Conservatory','customer',0,126470.25,NULL,NULL,'orders@havenconservatory.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAF749C7EEC_c04','Cardinal Boutique','customer',0,113512.62,NULL,NULL,'orders@cardinalboutique.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAF749C7EEC_c05','Aether Studios South','customer',0,78478.35,NULL,NULL,'orders@aetherstudiossouth.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAF749C7EEC_c06','Eclipse Archive','customer',0,98638.22,NULL,NULL,'orders@eclipsearchive.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAF749C7EEC_c07','Onyx Cooperative','customer',0,116564.44,NULL,NULL,'orders@onyxcooperative.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAF749C7EEC_c08','Summit Studios East','customer',0,90651.94,NULL,NULL,'orders@summitstudioseast.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAF749C7EEC_c09','Ember Guild','customer',0,93626.65,NULL,NULL,'orders@emberguild.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p01','Quantum Technologies Quality Lab','customer',0,NULL,NULL,NULL,'contact@quantumtechnologies.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p02','Gateway Solutions R&D Workshop','customer',0,NULL,NULL,NULL,'contact@gatewaysolutions.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p03','Conduit Engineering Quality Lab','customer',0,NULL,NULL,NULL,'contact@conduitengineering.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p04','Iron Industries HQ Procurement','customer',0,NULL,NULL,NULL,'contact@ironindustries.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p05','Aurora Assembly R&D Workshop','customer',0,NULL,NULL,NULL,'contact@auroraassembly.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p06','Spark Technologies Quality Lab','customer',0,NULL,NULL,NULL,'contact@sparktechnologies.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p07','Mosaic Manufacturing Quality Lab','customer',0,NULL,NULL,NULL,'contact@mosaicmanufacturing.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p08','Flux Production Field Ops','customer',0,NULL,NULL,NULL,'contact@fluxproduction.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p09','Spire Technologies Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@spiretechnologies.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p10','Axis Engineering Tooling Center','customer',0,NULL,NULL,NULL,'contact@axisengineering.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p11','Anvil Production Prototype Shop','customer',0,NULL,NULL,NULL,'contact@anvilproduction.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p12','Lance Production Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@lanceproduction.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p13','Quartz Solutions Field Ops','customer',0,NULL,NULL,NULL,'contact@quartzsolutions.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p14','Metro Industries Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@metroindustries.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p15','Arc Production Prototype Shop','customer',0,NULL,NULL,NULL,'contact@arcproduction.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p16','Noble Solutions Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@noblesolutions.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p17','Atlas Fabrication HQ Procurement','customer',0,NULL,NULL,NULL,'contact@atlasfabrication.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p18','Bridgeway Fabrication Tooling Center','customer',0,NULL,NULL,NULL,'contact@bridgewayfabrication.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p19','Steel Industries Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@steelindustries.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p20','Baltic Engineering Prototype Shop','customer',0,NULL,NULL,NULL,'contact@balticengineering.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p21','Bronze Production HQ Procurement','customer',0,NULL,NULL,NULL,'contact@bronzeproduction.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p22','Cosmo Assembly HQ Procurement','customer',0,NULL,NULL,NULL,'contact@cosmoassembly.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p23','Comet Services R&D Workshop','customer',0,NULL,NULL,NULL,'contact@cometservices.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p24','Equinox Operations HQ Procurement','customer',0,NULL,NULL,NULL,'contact@equinoxoperations.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p25','Marble Technologies Field Ops','customer',0,NULL,NULL,NULL,'contact@marbletechnologies.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p26','Globe Engineering Prototype Shop','customer',0,NULL,NULL,NULL,'contact@globeengineering.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p27','Baseline Technologies Field Ops','customer',0,NULL,NULL,NULL,'contact@baselinetechnologies.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p28','Silverline Engineering Prototype Shop','customer',0,NULL,NULL,NULL,'contact@silverlineengineering.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p29','Velocity Operations Tooling Center','customer',0,NULL,NULL,NULL,'contact@velocityoperations.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p30','Oxide Production Prototype Shop','customer',0,NULL,NULL,NULL,'contact@oxideproduction.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p31','Vertex Industries HQ Procurement','customer',0,NULL,NULL,NULL,'contact@vertexindustries.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p32','Forge Industries Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@forgeindustries.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p33','Jade Technologies Quality Lab','customer',0,NULL,NULL,NULL,'contact@jadetechnologies.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p34','Borough Services Tooling Center','customer',0,NULL,NULL,NULL,'contact@boroughservices.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p35','Chrome Services R&D Workshop','customer',0,NULL,NULL,NULL,'contact@chromeservices.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p36','Crest Technologies Site Logistics','customer',0,NULL,NULL,NULL,'contact@cresttechnologies.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p37','Ledger Fabrication Site Logistics','customer',0,NULL,NULL,NULL,'contact@ledgerfabrication.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p38','Nimbus Technologies HQ Procurement','customer',0,NULL,NULL,NULL,'contact@nimbustechnologies.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p39','Echo Solutions Prototype Shop','customer',0,NULL,NULL,NULL,'contact@echosolutions.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p40','Pivot Assembly HQ Procurement','customer',0,NULL,NULL,NULL,'contact@pivotassembly.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p41','Opal Services Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@opalservices.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p42','Crown Services R&D Workshop','customer',0,NULL,NULL,NULL,'contact@crownservices.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p43','Citadel Technologies Site Logistics','customer',0,NULL,NULL,NULL,'contact@citadeltechnologies.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p44','Canton Industries Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@cantonindustries.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p45','Terra Services Quality Lab','customer',0,NULL,NULL,NULL,'contact@terraservices.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p46','Evergreen Manufacturing R&D Workshop','customer',0,NULL,NULL,NULL,'contact@evergreenmanufacturing.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p47','Adjacent Customer 1 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer001.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p48','Adjacent Customer 2 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer002.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p49','Adjacent Customer 3 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer003.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2D60A1FFA4_p50','Adjacent Customer 4 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer004.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q01','Osprey Warehousing','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q02','Circuit Logistics','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q03','Lumen Manufacturing','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q04','Compass Resources','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q05','Sierra Transport','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q06','Indigo Carriers','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q07','Orbital Operations','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q08','Element Partners','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q09','Vantage Supply','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q10','Ivory Materials','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q11','Dune Wholesalers','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q12','Thornton Packagers','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q13','Aegis Commodities','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q14','Pacific Networks','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q15','Arbor Assemblies','vendor',15,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q16','Cobalt Transit','vendor',16,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q17','Beacon Fabrication','vendor',17,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q18','Crestview Integrators','vendor',18,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q19','Spectra Conveyance','vendor',19,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q20','Brookfield Solutions','vendor',20,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q21','Alpine Provisions','vendor',21,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q22','Cedar Depot','vendor',22,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q23','Redstone Components','vendor',23,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q24','Stonewall Fulfillment','vendor',24,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q25','Lakewood Consolidators','vendor',25,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAF749C7EEC_q26','Ridgeline Shipping','vendor',26,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q01','Ironwood Carriers','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q02','Hartland Transit','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q03','Northbridge Networks','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q04','Ashford Networks','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q05','Oakmont Components','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q06','Solace Sourcing','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q07','Scion Components','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q08','Bayshore Logistics','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q09','Granite Distribution','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q10','Flint Networks','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q11','Drift Carriers','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q12','Peak Transit','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q13','Helix Components','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q14','Clearwater Wholesale','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q15','Sterling Networks','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q16','Zenith Components','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q17','Meridian Networks','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q18','Stratos Materials','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q19','Lattice Transit','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q20','Coral Networks','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q21','Fairview Logistics','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q22','Polar Resources','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q23','Prism Logistics','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q24','Copper Parts Co','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q25','Skyline Materials','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q26','Sapphire Parts Co','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q27','Garnet Carriers','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q28','Slate Freight','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q29','Blaze Parts Co','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q30','Cascade Logistics','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q31','Catalyst Wholesale','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q32','Ridge Carriers','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q33','Riverdale Logistics','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q34','Cipher Transit','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q35','Arrow Carriers','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q36','Raven Procurement','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q37','Alloy Transit','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q38','Grove Materials','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q39','Apex Networks','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q40','Matrix Supply','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q41','Ironside Wholesale','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q42','Westfield Components','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q43','Monarch Logistics','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q44','Sentinel Transit','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q45','Pinnacle Sourcing','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q46','Millbrook Resources','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q47','Horizon Transit','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q48','Trellis Materials','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q49','Keystone Distribution','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2D60A1FFA4_q50','Titan Distribution','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAF749C7EEC-CLR-LFH-006','Laminar Flow Bench Horizontal','Cleanroom Equipment','consu',5109.42,2823.09,'buy,manufacture',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'PAF749C7EEC-CLR-LFH-006','rAF749C7EEC_q01','Priority Shuttle lane (9d transit, 8-45 units)',9,8.0,45.0,3047.41);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'PAF749C7EEC-CLR-LFH-006','rAF749C7EEC_q02','Express Air lane (6d transit, 3-12 units)',6,3.0,12.0,4421.29);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'PAF749C7EEC-CLR-LFH-006','rAF749C7EEC_q03','Bulk Container lane (21d transit, 81-86 units)',21,81.0,86.0,1572.46);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'PAF749C7EEC-CLR-LFH-006','rAF749C7EEC_q04','Hybrid Expedite lane (11d transit, 3-53 units)',11,3.0,53.0,3714.64);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'PAF749C7EEC-CLR-LFH-006','rAF749C7EEC_q05','Bulk Container lane (26d transit, 81-88 units)',26,81.0,88.0,1814.78);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'PAF749C7EEC-CLR-LFH-006','rAF749C7EEC_q06','Air Charter lane (5d transit, 3-3 units)',5,3.0,3.0,4515.22);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAF749C7EEC-CLR-UFP-102','ULPA Filter Panel 2x4 99.9995%','Cleanroom Equipment','consu',418.43,188.7,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'PAF749C7EEC-CLR-UFP-102','rAF749C7EEC_q07','Rapid Works (3d)',3,7.0,16.0,268.35);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'PAF749C7EEC-CLR-UFP-102','rAF749C7EEC_q08','Import Consolidator (6d)',6,38.0,49.0,188.7);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'PAF749C7EEC-CLR-UFP-102','rAF749C7EEC_q09','Hybrid Fabricators (5d)',5,12.0,94.0,246.91);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'PAF749C7EEC-CLR-UFP-102','rAF749C7EEC_q10','Domestic Supply (4d)',4,13.0,25.0,239.17);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAF749C7EEC-CLR-WPD-121','Window Panel Double-Pane Sealed','Cleanroom Equipment','consu',215.04,90.35,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'PAF749C7EEC-CLR-WPD-121','rAF749C7EEC_q11','Rapid Works (4d)',4,4.0,11.0,147.74);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'PAF749C7EEC-CLR-WPD-121','rAF749C7EEC_q12','Import Consolidator (6d)',6,45.0,105.0,90.35);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'PAF749C7EEC-CLR-WPD-121','rAF749C7EEC_q13','Hybrid Fabricators (6d)',6,20.0,28.0,158.87);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'PAF749C7EEC-CLR-WPD-121','rAF749C7EEC_q14','Domestic Supply (5d)',5,25.0,61.0,121.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAF749C7EEC-CLR-EOP-122','Electrical Outlet Panel IP65','Cleanroom Equipment','consu',55.61,20.51,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'PAF749C7EEC-CLR-EOP-122','rAF749C7EEC_q15','Rapid Works (4d)',4,9.0,29.0,25.67);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'PAF749C7EEC-CLR-EOP-122','rAF749C7EEC_q16','Domestic Supply (6d)',6,14.0,15.0,26.28);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'PAF749C7EEC-CLR-EOP-122','rAF749C7EEC_q17','Hybrid Fabricators (6d)',6,20.0,23.0,24.68);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'PAF749C7EEC-CLR-EOP-122','rAF749C7EEC_q18','Import Consolidator (6d)',6,44.0,113.0,20.51);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAF749C7EEC-CLR-PFP-124','Pre-Filter Panel Pleated 4in','Cleanroom Equipment','consu',22.82,7.69,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'PAF749C7EEC-CLR-PFP-124','rAF749C7EEC_q19','Rapid Works (2d)',2,4.0,69.0,10.07);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'PAF749C7EEC-CLR-PFP-124','rAF749C7EEC_q20','Hybrid Fabricators (5d)',5,10.0,284.0,10.18);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'PAF749C7EEC-CLR-PFP-124','rAF749C7EEC_q21','Import Consolidator (6d)',6,28.0,325.0,7.69);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'PAF749C7EEC-CLR-PFP-124','rAF749C7EEC_q22','Domestic Supply (6d)',6,20.0,43.0,9.83);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAF749C7EEC-CLR-AVS-126','Airflow Velocity Sensor Probe','Cleanroom Equipment','consu',132.41,61.93,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'PAF749C7EEC-CLR-AVS-126','rAF749C7EEC_q23','Rapid Works (3d)',3,12.0,44.0,68.87);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'PAF749C7EEC-CLR-AVS-126','rAF749C7EEC_q24','Hybrid Fabricators (5d)',5,8.0,9.0,80.23);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'PAF749C7EEC-CLR-AVS-126','rAF749C7EEC_q25','Domestic Supply (4d)',4,24.0,75.0,69.2);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'PAF749C7EEC-CLR-AVS-126','rAF749C7EEC_q26','Import Consolidator (6d)',6,31.0,54.0,61.93);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A001','Weatherproof Light Panel','Fasteners and Fixings','consu',412.41,246.05,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'P2D60A1FFA4-A001','r2D60A1FFA4_q01','Warehouse direct',5,1.0,24.0,251.95);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A002','High-Flow Low Wall','Mechanical Components','consu',335.87,188.77,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'P2D60A1FFA4-A002','r2D60A1FFA4_q02','Warehouse direct',5,1.0,24.0,202.13);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A003','Tapered Grid T Bar','Industrial Spare Parts','consu',279.67,163.32,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'P2D60A1FFA4-A003','r2D60A1FFA4_q03','Scheduled freight',3,1.0,24.0,155.61);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A004','Sealed Curtain Door Set','Maintenance Supplies','consu',408.9,230.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'P2D60A1FFA4-A004','r2D60A1FFA4_q04','Local pickup',4,1.0,24.0,241.11);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A005','High-Torque Grille Low Wall','Fasteners and Fixings','consu',183.03,114.56,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'P2D60A1FFA4-A005','r2D60A1FFA4_q05','Bulk shipment',3,1.0,24.0,112.01);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A006','Industrial Low Wall','Pneumatic Components','consu',376.04,209.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'P2D60A1FFA4-A006','r2D60A1FFA4_q06','Warehouse direct',7,1.0,24.0,216.33);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A007','Universal Gasket Frame','Industrial Spare Parts','consu',297.07,197.57,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'P2D60A1FFA4-A007','r2D60A1FFA4_q07','Warehouse direct',6,1.0,24.0,197.47);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A008','High-Cycle Door Set','Mechanical Components','consu',411.28,254.38,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'P2D60A1FFA4-A008','r2D60A1FFA4_q08','Regional lane',3,1.0,24.0,270.03);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A009','Economy Low Wall','Maintenance Supplies','consu',298.94,166.28,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'P2D60A1FFA4-A009','r2D60A1FFA4_q09','Standard delivery',8,1.0,24.0,162.68);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A010','Flanged Flush Mount','Seals and Gaskets','consu',194.57,122.85,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'P2D60A1FFA4-A010','r2D60A1FFA4_q10','Bulk shipment',8,1.0,24.0,117.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A011','Single-Stage Unit Motor Assembly','Replacement Parts','consu',233.07,164.95,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'P2D60A1FFA4-A011','r2D60A1FFA4_q11','Cross-dock',7,1.0,24.0,177.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A012','Heat-Treated Motor Assembly','Mechanical Components','consu',212.38,152.34,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'P2D60A1FFA4-A012','r2D60A1FFA4_q12','Bulk shipment',7,1.0,24.0,159.3);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A013','Low-Profile Nozzle Set','Fasteners and Fixings','consu',318.99,227.92,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'P2D60A1FFA4-A013','r2D60A1FFA4_q13','Scheduled freight',7,1.0,24.0,231.71);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A014','Compact Grid T Bar','Maintenance Supplies','consu',290.26,199.23,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'P2D60A1FFA4-A014','r2D60A1FFA4_q14','Standard delivery',7,1.0,24.0,205.64);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A015','Anodized Motor Assembly','Electrical Components','consu',323.51,226.01,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'P2D60A1FFA4-A015','r2D60A1FFA4_q15','Bulk shipment',7,1.0,24.0,235.41);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A016','Hardened Corner Cove','Replacement Parts','consu',287.06,162.58,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'P2D60A1FFA4-A016','r2D60A1FFA4_q16','Cross-dock',3,1.0,24.0,174.44);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A017','Impact-Rated Differential Pressure Gauge','Fasteners and Fixings','consu',226.1,144.83,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'P2D60A1FFA4-A017','r2D60A1FFA4_q17','Local pickup',3,1.0,24.0,143.71);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A018','Premium Door Set','Mechanical Components','consu',212.47,141.79,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'P2D60A1FFA4-A018','r2D60A1FFA4_q18','Bulk shipment',4,1.0,24.0,151.21);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A019','High-Temp Flush Mount','Pneumatic Components','consu',203.71,110.73,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'P2D60A1FFA4-A019','r2D60A1FFA4_q19','Local pickup',4,1.0,24.0,108.4);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A020','Powder-Coated Door Set','Pneumatic Components','consu',211.75,115.97,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'P2D60A1FFA4-A020','r2D60A1FFA4_q20','Local pickup',8,1.0,24.0,116.5);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A021','Self-Lubricating Corner Cove','Maintenance Supplies','consu',234.16,166.05,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'P2D60A1FFA4-A021','r2D60A1FFA4_q21','Cross-dock',5,1.0,24.0,178.89);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A022','Rapid-Lock 2x4 99.99%','Mechanical Components','consu',416.63,267.85,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'P2D60A1FFA4-A022','r2D60A1FFA4_q22','Local pickup',3,1.0,24.0,287.29);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A023','Threaded Door Set','Fasteners and Fixings','consu',222.11,142.25,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'P2D60A1FFA4-A023','r2D60A1FFA4_q23','Bulk shipment',8,1.0,24.0,136.24);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A024','Commercial Corner Cove','Industrial Spare Parts','consu',181.89,95.07,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'P2D60A1FFA4-A024','r2D60A1FFA4_q24','Standard delivery',3,1.0,24.0,95.93);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A025','Corrosion-Resistant Flush Mount','Electrical Components','consu',314.64,213.02,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'P2D60A1FFA4-A025','r2D60A1FFA4_q25','Cross-dock',3,1.0,24.0,204.71);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A026','Medical-Grade Grid T Bar','Industrial Spare Parts','consu',209.48,142.19,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'P2D60A1FFA4-A026','r2D60A1FFA4_q26','Scheduled freight',6,1.0,24.0,142.76);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A027','Wide-Body Light Panel','Fasteners and Fixings','consu',349.45,229.18,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'P2D60A1FFA4-A027','r2D60A1FFA4_q27','Bulk shipment',7,1.0,24.0,227.3);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A028','Snap-Fit Corner Cove','Seals and Gaskets','consu',399.81,214.62,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'P2D60A1FFA4-A028','r2D60A1FFA4_q28','Cross-dock',4,1.0,24.0,211.95);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A029','Low-Noise 2x4 99.99%','Replacement Parts','consu',278.85,195.44,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'P2D60A1FFA4-A029','r2D60A1FFA4_q29','Express route',8,1.0,24.0,192.34);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A030','Zero-Backlash Seal Gasket Frame','Electrical Components','consu',258.07,150.81,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'P2D60A1FFA4-A030','r2D60A1FFA4_q30','Express route',4,1.0,24.0,146.1);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A031','Double-Row Corner Cove','Hardware Accessories','consu',393.15,252.47,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(57,'P2D60A1FFA4-A031','r2D60A1FFA4_q31','Express route',7,1.0,24.0,253.76);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A032','Narrow-Body Low Wall','Maintenance Supplies','consu',259.72,182.72,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(58,'P2D60A1FFA4-A032','r2D60A1FFA4_q32','Local pickup',6,1.0,24.0,192.9);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A033','Extended-Life Panel Flush Mount','Mechanical Components','consu',385.12,271.64,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(59,'P2D60A1FFA4-A033','r2D60A1FFA4_q33','Standard delivery',3,1.0,24.0,260.07);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A034','Reinforced Panel 2x4 99.9995%','Mechanical Components','consu',252.31,151.8,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(60,'P2D60A1FFA4-A034','r2D60A1FFA4_q34','Cross-dock',5,1.0,24.0,149.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A035','Metric Pressure Gauge','Maintenance Supplies','consu',400.35,208.41,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(61,'P2D60A1FFA4-A035','r2D60A1FFA4_q35','Regional lane',7,1.0,24.0,209.09);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A036','Non-Magnetic Curtain Door Set','Maintenance Supplies','consu',278.31,174.45,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(62,'P2D60A1FFA4-A036','r2D60A1FFA4_q36','Regional lane',4,1.0,24.0,175.02);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A037','Low-Friction Panel Flush Mount','Replacement Parts','consu',217.52,147.66,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(63,'P2D60A1FFA4-A037','r2D60A1FFA4_q37','Regional lane',8,1.0,24.0,158.08);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A038','Quick-Release Gasket Frame','Electrical Components','consu',209.61,148.74,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(64,'P2D60A1FFA4-A038','r2D60A1FFA4_q38','Express route',8,1.0,24.0,160.17);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A039','Spring-Loaded Motor Assembly','Fasteners and Fixings','consu',254.13,150.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(65,'P2D60A1FFA4-A039','r2D60A1FFA4_q39','Cross-dock',7,1.0,24.0,150.3);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A040','Pressure-Balanced Steel Corner Cove','Industrial Spare Parts','consu',203.16,116.39,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(66,'P2D60A1FFA4-A040','r2D60A1FFA4_q40','Cross-dock',8,1.0,24.0,113.17);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A041','Low-Flow Door Set','Industrial Spare Parts','consu',348.68,204.9,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(67,'P2D60A1FFA4-A041','r2D60A1FFA4_q41','Bulk shipment',3,1.0,24.0,202.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A042','Modular 2x4 99.99%','Electrical Components','consu',316.72,206.54,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(68,'P2D60A1FFA4-A042','r2D60A1FFA4_q42','Express route',7,1.0,24.0,213.4);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A043','Adjustable Door Set','Seals and Gaskets','consu',348.41,213.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(69,'P2D60A1FFA4-A043','r2D60A1FFA4_q43','Scheduled freight',4,1.0,24.0,227.48);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A044','Standard Nozzle Set','Fasteners and Fixings','consu',261.69,168.46,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(70,'P2D60A1FFA4-A044','r2D60A1FFA4_q44','Regional lane',4,1.0,24.0,160.19);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A045','High-Performance Motor Assembly','Pneumatic Components','consu',416.16,256.55,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(71,'P2D60A1FFA4-A045','r2D60A1FFA4_q45','Local pickup',6,1.0,24.0,251.2);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A046','Precision Flush Mount','Fasteners and Fixings','consu',222.14,137.51,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(72,'P2D60A1FFA4-A046','r2D60A1FFA4_q46','Regional lane',7,1.0,24.0,137.21);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A047','Heavy-Duty Differential Pressure Gauge','Industrial Spare Parts','consu',338.93,242.6,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(73,'P2D60A1FFA4-A047','r2D60A1FFA4_q47','Bulk shipment',3,1.0,24.0,233.73);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A048','Anti-Vibration T Bar','Power Transmission','consu',354.06,235.74,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(74,'P2D60A1FFA4-A048','r2D60A1FFA4_q48','Regional lane',6,1.0,24.0,230.52);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A049','Dual-Stage Panel 2x4 99.99%','Industrial Spare Parts','consu',278.87,171.08,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(75,'P2D60A1FFA4-A049','r2D60A1FFA4_q49','Cross-dock',5,1.0,24.0,168.2);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2D60A1FFA4-A050','Low-Temp Door Set','Power Transmission','consu',199.75,126.79,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(76,'P2D60A1FFA4-A050','r2D60A1FFA4_q50','Standard delivery',8,1.0,24.0,131.16);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'PAF749C7EEC-CLR-LFH-006','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PAF749C7EEC-CLR-UFP-102',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PAF749C7EEC-CLR-WPD-121',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PAF749C7EEC-CLR-EOP-122',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PAF749C7EEC-CLR-PFP-124',4.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PAF749C7EEC-CLR-AVS-126',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'P2D60A1FFA4-A010','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P2D60A1FFA4-A016',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'P2D60A1FFA4-A012','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P2D60A1FFA4-A021',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'P2D60A1FFA4-A047','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'P2D60A1FFA4-A022',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'P2D60A1FFA4-A006',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'P2D60A1FFA4-A002','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P2D60A1FFA4-A033',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P2D60A1FFA4-A021',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'P2D60A1FFA4-A020','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P2D60A1FFA4-A013',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'P2D60A1FFA4-A015','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'P2D60A1FFA4-A046',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'P2D60A1FFA4-A001',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'P2D60A1FFA4-A007','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P2D60A1FFA4-A047',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P2D60A1FFA4-A040',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'P2D60A1FFA4-A037','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P2D60A1FFA4-A036',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P2D60A1FFA4-A041',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'P2D60A1FFA4-A050','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P2D60A1FFA4-A038',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(11,'P2D60A1FFA4-A016','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'P2D60A1FFA4-A009',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'P2D60A1FFA4-A006',3.0);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PAF749C7EEC-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAF749C7EEC-CLR-AVS-126',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAF749C7EEC-CLR-EOP-122',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAF749C7EEC-CLR-LFH-006',NULL,22.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAF749C7EEC-CLR-PFP-124',NULL,31.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAF749C7EEC-CLR-UFP-102',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAF749C7EEC-CLR-WPD-121',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A001',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A002',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A003',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A004',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A005',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A006',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A007',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A008',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A009',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A010',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A011',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A012',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A013',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A014',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A015',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A016',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A017',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A018',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A019',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A020',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A021',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A022',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A023',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A024',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A025',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A026',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A027',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A028',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A029',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A030',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A031',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A032',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A033',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A034',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A035',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A036',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A037',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A038',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A039',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A040',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A041',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A042',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A043',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A044',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A045',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A046',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A047',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A048',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A049',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2D60A1FFA4-A050',NULL,14.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'rAF749C7EEC_c01','PAF749C7EEC-CLR-LFH-006',14,8,76578.74,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'rAF749C7EEC_c02','PAF749C7EEC-CLR-LFH-006',17,8,92475.05,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'rAF749C7EEC_c03','PAF749C7EEC-CLR-LFH-006',23,8,126470.25,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'rAF749C7EEC_c04','PAF749C7EEC-CLR-LFH-006',21,8,113512.62,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'rAF749C7EEC_c05','PAF749C7EEC-CLR-LFH-006',15,11,78478.35,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'rAF749C7EEC_c06','PAF749C7EEC-CLR-LFH-006',18,11,98638.22,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'rAF749C7EEC_c07','PAF749C7EEC-CLR-LFH-006',21,11,116564.44,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'rAF749C7EEC_c08','PAF749C7EEC-CLR-LFH-006',16,11,90651.94,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(9,'rAF749C7EEC_c09','PAF749C7EEC-CLR-LFH-006',17,14,93626.65,NULL);
