-- agentic-labs/erp-bench scenario 2189: Air-Powered Dock Leveler 35000lb
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF024ECDF2B_c01','Element Workspaces','customer',0,120422.43,NULL,NULL,'orders@elementworkspaces.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF024ECDF2B_c02','Sterling Manufactory','customer',0,87037.58,NULL,NULL,'orders@sterlingmanufactory.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF024ECDF2B_c03','Bridgeway Studios South','customer',0,153412.16,NULL,NULL,'orders@bridgewaystudiossouth.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF024ECDF2B_c04','Millbrook Bureau','customer',0,135233.54,NULL,NULL,'orders@millbrookbureau.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF024ECDF2B_c05','Lumen Lyceum','customer',0,146420.72,NULL,NULL,'orders@lumenlyceum.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF024ECDF2B_c06','Lance Robotics','customer',0,149802.07,NULL,NULL,'orders@lancerobotics.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF024ECDF2B_c07','Sentinel Theater','customer',0,154244.18,NULL,NULL,'orders@sentineltheater.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF024ECDF2B_c08','Garnet Interactive','customer',0,149813.78,NULL,NULL,'orders@garnetinteractive.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p01','Trident Technologies Field Ops','customer',0,NULL,NULL,NULL,'contact@tridenttechnologies.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p02','Arrow Services Site Logistics','customer',0,NULL,NULL,NULL,'contact@arrowservices.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p03','Conduit Manufacturing Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@conduitmanufacturing.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p04','Forge Engineering Prototype Shop','customer',0,NULL,NULL,NULL,'contact@forgeengineering.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p05','Coral Assembly Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@coralassembly.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p06','Borough Assembly Test Facility','customer',0,NULL,NULL,NULL,'contact@boroughassembly.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p07','Crestview Industries R&D Workshop','customer',0,NULL,NULL,NULL,'contact@crestviewindustries.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p08','Polar Operations Prototype Shop','customer',0,NULL,NULL,NULL,'contact@polaroperations.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p09','Meridian Technologies Tooling Center','customer',0,NULL,NULL,NULL,'contact@meridiantechnologies.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p10','Ashford Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@ashfordassembly.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p11','Monarch Production Tooling Center','customer',0,NULL,NULL,NULL,'contact@monarchproduction.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p12','Alpine Operations Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@alpineoperations.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p13','Spark Manufacturing HQ Procurement','customer',0,NULL,NULL,NULL,'contact@sparkmanufacturing.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p14','Jade Operations Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@jadeoperations.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p15','Arc Fabrication HQ Procurement','customer',0,NULL,NULL,NULL,'contact@arcfabrication.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p16','Silverline Fabrication Quality Lab','customer',0,NULL,NULL,NULL,'contact@silverlinefabrication.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p17','Evergreen Technologies R&D Workshop','customer',0,NULL,NULL,NULL,'contact@evergreentechnologies.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p18','Compass Manufacturing Prototype Shop','customer',0,NULL,NULL,NULL,'contact@compassmanufacturing.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p19','Citadel Fabrication Prototype Shop','customer',0,NULL,NULL,NULL,'contact@citadelfabrication.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p20','Apex Assembly HQ Procurement','customer',0,NULL,NULL,NULL,'contact@apexassembly.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p21','Comet Industries Tooling Center','customer',0,NULL,NULL,NULL,'contact@cometindustries.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p22','Grove Industries HQ Procurement','customer',0,NULL,NULL,NULL,'contact@groveindustries.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p23','Cascade Fabrication Tooling Center','customer',0,NULL,NULL,NULL,'contact@cascadefabrication.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p24','Cipher Production HQ Procurement','customer',0,NULL,NULL,NULL,'contact@cipherproduction.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p25','Stratos Manufacturing Site Logistics','customer',0,NULL,NULL,NULL,'contact@stratosmanufacturing.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p26','Ironwood Engineering Test Facility','customer',0,NULL,NULL,NULL,'contact@ironwoodengineering.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p27','Keystone Technologies Site Logistics','customer',0,NULL,NULL,NULL,'contact@keystonetechnologies.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p28','Thornton Assembly Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@thorntonassembly.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p29','Ledger Production Test Facility','customer',0,NULL,NULL,NULL,'contact@ledgerproduction.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p30','Riverdale Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@riverdaleassembly.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p31','Iron Services Field Ops','customer',0,NULL,NULL,NULL,'contact@ironservices.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p32','Bayshore Industries Field Ops','customer',0,NULL,NULL,NULL,'contact@bayshoreindustries.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p33','Arbor Solutions Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@arborsolutions.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p34','Aegis Operations Quality Lab','customer',0,NULL,NULL,NULL,'contact@aegisoperations.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p35','Quartz Engineering Test Facility','customer',0,NULL,NULL,NULL,'contact@quartzengineering.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p36','Slate Production Tooling Center','customer',0,NULL,NULL,NULL,'contact@slateproduction.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p37','Blaze Production Test Facility','customer',0,NULL,NULL,NULL,'contact@blazeproduction.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p38','Raven Solutions Field Ops','customer',0,NULL,NULL,NULL,'contact@ravensolutions.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p39','Pivot Services Prototype Shop','customer',0,NULL,NULL,NULL,'contact@pivotservices.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p40','Flint Engineering Prototype Shop','customer',0,NULL,NULL,NULL,'contact@flintengineering.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p41','Helix Engineering Site Logistics','customer',0,NULL,NULL,NULL,'contact@helixengineering.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p42','Ridge Operations Tooling Center','customer',0,NULL,NULL,NULL,'contact@ridgeoperations.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p43','Orbital Assembly Tooling Center','customer',0,NULL,NULL,NULL,'contact@orbitalassembly.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p44','Metro Technologies Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@metrotechnologies.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p45','Adjacent Customer 1 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer001.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p46','Adjacent Customer 2 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer002.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p47','Adjacent Customer 3 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer003.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p48','Adjacent Customer 4 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer004.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p49','Adjacent Customer 5 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer005.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1BF92FCD11_p50','Adjacent Customer 6 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer006.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q01','Stonewall Transit','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q02','Nimbus Carriers','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q03','Anvil Sourcing','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q04','Fairview Solutions','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q05','Equinox Packagers','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q06','Axis Fulfillment','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q07','Sierra Movers','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q08','Steel Manufacturing','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q09','Osprey Conveyance','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q10','Prism Operations','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q11','Spire Consolidators','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q12','Chrome Fabrication','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q13','Aurora Materials','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q14','Trellis Transport','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q15','Atlas Depot','vendor',15,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q16','Catalyst Shipping','vendor',16,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q17','Titan Warehousing','vendor',17,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q18','Matrix Integrators','vendor',18,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q19','Cobalt Warehouse','vendor',19,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q20','Granite Procurement','vendor',20,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q21','Peak Microfactory','vendor',21,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q22','Alloy Wholesalers','vendor',22,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q23','Lattice Exporters','vendor',23,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q24','Cedar Resources','vendor',24,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q25','Pinnacle Distributors','vendor',25,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q26','Westfield Commodities','vendor',26,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q27','Gateway Logistics','vendor',27,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q28','Eclipse Importers','vendor',28,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF024ECDF2B_q29','Oakmont Provisions','vendor',29,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q01','Brookfield Networks','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q02','Circuit Trading','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q03','Ironside Wholesale','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q04','Pacific Supply','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q05','Canton Procurement','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q06','Onyx Wholesale','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q07','Northbridge Supply','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q08','Globe Trading','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q09','Opal Distribution','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q10','Oxide Resources','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q11','Spectra Parts Co','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q12','Terra Distribution','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q13','Cosmo Wholesale','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q14','Clearwater Materials','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q15','Aether Procurement','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q16','Indigo Resources','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q17','Drift Materials','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q18','Nexus Freight','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q19','Vertex Freight','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q20','Cardinal Freight','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q21','Crest Freight','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q22','Ember Components','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q23','Flux Carriers','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q24','Baltic Supply','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q25','Quantum Trading','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q26','Solace Materials','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q27','Ridgeline Components','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q28','Mosaic Networks','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q29','Skyline Wholesale','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q30','Bronze Trading','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q31','Hartland Wholesale','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q32','Sapphire Carriers','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q33','Scion Sourcing','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q34','Velocity Trading','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q35','Ivory Carriers','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q36','Lakewood Transit','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q37','Redstone Carriers','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q38','Dune Carriers','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q39','Noble Distribution','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q40','Marble Trading','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q41','Baseline Resources','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q42','Echo Supply','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q43','Summit Procurement','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q44','Zenith Resources','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q45','Horizon Trading','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q46','Vantage Supply','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q47','Crown Networks','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q48','Beacon Procurement','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q49','Haven Networks','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1BF92FCD11_q50','Copper Freight','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF024ECDF2B-DCK-APD-003','Air-Powered Dock Leveler 35000lb','Material Handling Equipment','consu',5300.88,3393.75,'manufacture',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'PF024ECDF2B-DCK-APD-003','rF024ECDF2B_q01','Priority Shuttle lane (8d transit, 12-65 units)',8,12.0,65.0,2999.88);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'PF024ECDF2B-DCK-APD-003','rF024ECDF2B_q02','Express Air lane (6d transit, 1-14 units)',6,1.0,14.0,4214.31);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'PF024ECDF2B-DCK-APD-003','rF024ECDF2B_q03','Bulk Container lane (21d transit, 96-191 units)',21,96.0,191.0,1579.66);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'PF024ECDF2B-DCK-APD-003','rF024ECDF2B_q04','Microfactory Build-to-Order lane (8d transit, 3-5 units)',8,3.0,5.0,3987.92);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'PF024ECDF2B-DCK-APD-003','rF024ECDF2B_q05','Air Charter lane (5d transit, 1-12 units)',5,1.0,12.0,4667.21);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'PF024ECDF2B-DCK-APD-003','rF024ECDF2B_q06','Hybrid Expedite lane (9d transit, 6-37 units)',9,6.0,37.0,3407.0);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF024ECDF2B-DCK-DPS-103','Deck Plate Steel 3/8in','Material Handling Equipment','consu',690.03,366.8,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'PF024ECDF2B-DCK-DPS-103','rF024ECDF2B_q07','Rapid Works (2d)',2,10.0,30.0,470.75);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'PF024ECDF2B-DCK-DPS-103','rF024ECDF2B_q08','Hybrid Fabricators (4d)',4,14.0,55.0,437.89);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'PF024ECDF2B-DCK-DPS-103','rF024ECDF2B_q09','Domestic Supply (5d)',5,20.0,26.0,403.37);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'PF024ECDF2B-DCK-DPS-103','rF024ECDF2B_q10','Import Consolidator (6d)',6,33.0,50.0,366.8);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF024ECDF2B-DCK-HDA-107','Hold-Down Assembly Spring','Material Handling Equipment','consu',66.45,23.36,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'PF024ECDF2B-DCK-HDA-107','rF024ECDF2B_q11','Rapid Works (4d)',4,11.0,62.0,34.01);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'PF024ECDF2B-DCK-HDA-107','rF024ECDF2B_q12','Domestic Supply (6d)',6,15.0,21.0,32.44);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'PF024ECDF2B-DCK-HDA-107','rF024ECDF2B_q13','Hybrid Fabricators (4d)',4,15.0,105.0,31.71);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'PF024ECDF2B-DCK-HDA-107','rF024ECDF2B_q14','Import Consolidator (6d)',6,43.0,307.0,23.36);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF024ECDF2B-DCK-TSA-115','Torsion Spring Assembly Set','Material Handling Equipment','consu',168.19,81.44,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'PF024ECDF2B-DCK-TSA-115','rF024ECDF2B_q15','Rapid Works (2d)',2,11.0,302.0,118.55);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'PF024ECDF2B-DCK-TSA-115','rF024ECDF2B_q16','Domestic Supply (6d)',6,21.0,61.0,81.44);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'PF024ECDF2B-DCK-TSA-115','rF024ECDF2B_q17','Hybrid Fabricators (6d)',6,11.0,12.0,99.81);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF024ECDF2B-DCK-RRW-118','Ramp Roller Wheel Assembly','Material Handling Equipment','consu',75.16,30.99,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'PF024ECDF2B-DCK-RRW-118','rF024ECDF2B_q18','Rapid Works (2d)',2,5.0,35.0,42.99);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'PF024ECDF2B-DCK-RRW-118','rF024ECDF2B_q19','Hybrid Fabricators (4d)',4,16.0,138.0,42.54);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'PF024ECDF2B-DCK-RRW-118','rF024ECDF2B_q20','Domestic Supply (5d)',5,27.0,291.0,32.7);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'PF024ECDF2B-DCK-RRW-118','rF024ECDF2B_q21','Import Consolidator (6d)',6,36.0,50.0,30.99);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF024ECDF2B-DCK-TGP-120','Toe Guard Safety Plate','Material Handling Equipment','consu',40.21,16.76,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'PF024ECDF2B-DCK-TGP-120','rF024ECDF2B_q22','Rapid Works (4d)',4,4.0,7.0,22.29);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'PF024ECDF2B-DCK-TGP-120','rF024ECDF2B_q23','Hybrid Fabricators (4d)',4,18.0,31.0,20.93);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'PF024ECDF2B-DCK-TGP-120','rF024ECDF2B_q24','Import Consolidator (6d)',6,38.0,99.0,16.76);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'PF024ECDF2B-DCK-TGP-120','rF024ECDF2B_q25','Domestic Supply (6d)',6,13.0,36.0,18.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF024ECDF2B-DCK-CLG-121','Communication Light Green/Red','Material Handling Equipment','consu',131.43,55.58,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'PF024ECDF2B-DCK-CLG-121','rF024ECDF2B_q26','Rapid Works (2d)',2,5.0,29.0,81.67);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'PF024ECDF2B-DCK-CLG-121','rF024ECDF2B_q27','Hybrid Fabricators (5d)',5,16.0,34.0,65.87);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'PF024ECDF2B-DCK-CLG-121','rF024ECDF2B_q28','Domestic Supply (5d)',5,19.0,49.0,55.58);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'PF024ECDF2B-DCK-CLG-121','rF024ECDF2B_q29','Import Consolidator (6d)',6,26.0,116.0,60.43);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A001','Hardened Plate Steel 3/8in','Industrial Spare Parts','consu',198.2,137.73,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'P1BF92FCD11-A001','r1BF92FCD11_q01','Scheduled freight',7,1.0,24.0,140.24);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A002','Wide-Body Button Panel','Electrical Components','consu',384.82,254.58,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'P1BF92FCD11-A002','r1BF92FCD11_q02','Standard delivery',4,1.0,24.0,270.5);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A003','High-Temp Curtain Assembly','Seals and Gaskets','consu',369.26,242.84,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'P1BF92FCD11-A003','r1BF92FCD11_q03','Scheduled freight',6,1.0,24.0,245.58);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A004','Weatherproof Push Button Panel','Seals and Gaskets','consu',225.97,122.1,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'P1BF92FCD11-A004','r1BF92FCD11_q04','Bulk shipment',3,1.0,24.0,116.48);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A005','High-Flow Shelter Curtain Assembly','Maintenance Supplies','consu',400.4,249.43,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'P1BF92FCD11-A005','r1BF92FCD11_q05','Bulk shipment',4,1.0,24.0,259.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A006','Anodized Laminated 12x12x4','Maintenance Supplies','consu',278.41,178.07,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'P1BF92FCD11-A006','r1BF92FCD11_q06','Standard delivery',3,1.0,24.0,176.63);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A007','Non-Magnetic Pad Set','Electrical Components','consu',324.07,222.57,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'P1BF92FCD11-A007','r1BF92FCD11_q07','Bulk shipment',3,1.0,24.0,218.72);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A008','Commercial Plate Steel 3/8in','Maintenance Supplies','consu',343.71,194.06,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'P1BF92FCD11-A008','r1BF92FCD11_q08','Local pickup',7,1.0,24.0,200.26);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A009','Cold-Rolled Curtain Assembly','Pneumatic Components','consu',205.58,112.44,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'P1BF92FCD11-A009','r1BF92FCD11_q09','Bulk shipment',6,1.0,24.0,116.57);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A010','Narrow-Body Extension 16in','Power Transmission','consu',340.03,212.43,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'P1BF92FCD11-A010','r1BF92FCD11_q10','Bulk shipment',6,1.0,24.0,227.47);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A011','Premium Assembly 8in','Pneumatic Components','consu',411.22,242.79,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'P1BF92FCD11-A011','r1BF92FCD11_q11','Scheduled freight',6,1.0,24.0,236.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A012','Double-Row Assembly Heavy Duty','Hardware Accessories','consu',375.23,268.22,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'P1BF92FCD11-A012','r1BF92FCD11_q12','Scheduled freight',5,1.0,24.0,261.24);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A013','Precision Unit 3HP','Replacement Parts','consu',184.12,122.45,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'P1BF92FCD11-A013','r1BF92FCD11_q13','Local pickup',6,1.0,24.0,127.91);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A014','Standard Warning Light','Seals and Gaskets','consu',238.2,154.97,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'P1BF92FCD11-A014','r1BF92FCD11_q14','Bulk shipment',7,1.0,24.0,158.24);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A015','Rapid-Lock Power Unit 3HP','Replacement Parts','consu',380.19,231.66,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'P1BF92FCD11-A015','r1BF92FCD11_q15','Cross-dock',5,1.0,24.0,226.81);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A016','Tapered Unit 3HP','Mechanical Components','consu',374.62,198.33,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'P1BF92FCD11-A016','r1BF92FCD11_q16','Bulk shipment',8,1.0,24.0,207.8);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A017','UV-Stable Push Button Panel','Hardware Accessories','consu',254.54,176.2,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'P1BF92FCD11-A017','r1BF92FCD11_q17','Local pickup',6,1.0,24.0,182.07);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A018','Compact Extension 16in','Industrial Spare Parts','consu',197.42,117.87,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'P1BF92FCD11-A018','r1BF92FCD11_q18','Warehouse direct',3,1.0,24.0,115.25);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A019','Zero-Backlash Shelter Curtain Assembly','Hardware Accessories','consu',208.15,132.43,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'P1BF92FCD11-A019','r1BF92FCD11_q19','Express route',3,1.0,24.0,140.68);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A020','Metric Down Assembly Spring','Hardware Accessories','consu',325.59,204.31,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'P1BF92FCD11-A020','r1BF92FCD11_q20','Express route',4,1.0,24.0,199.98);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A021','Low-Noise Laminated 12x12x4','Pneumatic Components','consu',405.24,229.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'P1BF92FCD11-A021','r1BF92FCD11_q21','Local pickup',3,1.0,24.0,223.1);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A022','Food-Grade Down Assembly Spring','Maintenance Supplies','consu',407.86,233.26,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'P1BF92FCD11-A022','r1BF92FCD11_q22','Express route',5,1.0,24.0,234.87);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A023','Extended-Life Curtain Assembly','Power Transmission','consu',250.64,145.78,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'P1BF92FCD11-A023','r1BF92FCD11_q23','Express route',4,1.0,24.0,153.03);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A024','Universal Power Unit 3HP','Power Transmission','consu',417.67,234.88,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'P1BF92FCD11-A024','r1BF92FCD11_q24','Scheduled freight',4,1.0,24.0,243.04);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A025','Economy Assembly Spring','Hardware Accessories','consu',205.05,131.99,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'P1BF92FCD11-A025','r1BF92FCD11_q25','Warehouse direct',6,1.0,24.0,127.26);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A026','Low-Temp Shelter Curtain Assembly','Hardware Accessories','consu',419.89,290.01,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'P1BF92FCD11-A026','r1BF92FCD11_q26','Cross-dock',3,1.0,24.0,313.17);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A027','Quick-Release Assembly 8in','Maintenance Supplies','consu',389.95,238.11,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'P1BF92FCD11-A027','r1BF92FCD11_q27','Express route',6,1.0,24.0,243.04);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A028','Modular Steel 3/8in','Industrial Spare Parts','consu',258.02,165.96,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(57,'P1BF92FCD11-A028','r1BF92FCD11_q28','Warehouse direct',8,1.0,24.0,178.93);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A029','Heavy-Duty Power Unit 3HP','Maintenance Supplies','consu',416.04,249.94,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(58,'P1BF92FCD11-A029','r1BF92FCD11_q29','Bulk shipment',4,1.0,24.0,253.63);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A030','Heat-Treated Power Unit 3HP','Industrial Spare Parts','consu',251.28,162.31,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(59,'P1BF92FCD11-A030','r1BF92FCD11_q30','Express route',5,1.0,24.0,174.86);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A031','Corrosion-Resistant Plate Steel 3/8in','Seals and Gaskets','consu',247.14,162.25,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(60,'P1BF92FCD11-A031','r1BF92FCD11_q31','Regional lane',4,1.0,24.0,173.86);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A032','Low-Friction Cylinder Assembly 8in','Seals and Gaskets','consu',224.23,155.78,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(61,'P1BF92FCD11-A032','r1BF92FCD11_q32','Local pickup',3,1.0,24.0,154.42);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A033','Stainless Extension 16in','Replacement Parts','consu',247.85,137.88,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(62,'P1BF92FCD11-A033','r1BF92FCD11_q33','Standard delivery',4,1.0,24.0,144.12);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A034','High-Cycle Support Drop Prop','Maintenance Supplies','consu',369.16,243.43,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(63,'P1BF92FCD11-A034','r1BF92FCD11_q34','Express route',3,1.0,24.0,251.05);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A035','Pressure-Balanced Assembly Heavy Duty','Hardware Accessories','consu',255.08,167.03,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(64,'P1BF92FCD11-A035','r1BF92FCD11_q35','Local pickup',8,1.0,24.0,169.68);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A036','High-Performance Heavy Duty','Pneumatic Components','consu',401.59,218.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(65,'P1BF92FCD11-A036','r1BF92FCD11_q36','Bulk shipment',6,1.0,24.0,211.74);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A037','Medical-Grade Extension 16in','Electrical Components','consu',181.98,122.05,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(66,'P1BF92FCD11-A037','r1BF92FCD11_q37','Cross-dock',7,1.0,24.0,125.67);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A038','Lightweight Support Drop Prop','Pneumatic Components','consu',324.14,223.35,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(67,'P1BF92FCD11-A038','r1BF92FCD11_q38','Warehouse direct',4,1.0,24.0,216.69);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A039','Industrial Heavy Duty','Pneumatic Components','consu',300.39,156.31,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(68,'P1BF92FCD11-A039','r1BF92FCD11_q39','Local pickup',7,1.0,24.0,151.78);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A040','Single-Stage Power Unit 3HP','Fasteners and Fixings','consu',282.38,149.99,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(69,'P1BF92FCD11-A040','r1BF92FCD11_q40','Bulk shipment',4,1.0,24.0,151.04);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A041','Snap-Fit Plate Extension 16in','Pneumatic Components','consu',257.74,147.08,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(70,'P1BF92FCD11-A041','r1BF92FCD11_q41','Cross-dock',3,1.0,24.0,145.8);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A042','Self-Lubricating Plate Extension 16in','Pneumatic Components','consu',276.47,189.99,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(71,'P1BF92FCD11-A042','r1BF92FCD11_q42','Standard delivery',6,1.0,24.0,191.62);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A043','Thermal-Guard Assembly 8in','Maintenance Supplies','consu',257.79,145.92,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(72,'P1BF92FCD11-A043','r1BF92FCD11_q43','Standard delivery',7,1.0,24.0,147.67);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A044','Spring-Loaded Extension 16in','Electrical Components','consu',415.02,289.52,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(73,'P1BF92FCD11-A044','r1BF92FCD11_q44','Regional lane',8,1.0,24.0,312.05);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A045','Threaded Unit 3HP','Replacement Parts','consu',406.4,227.51,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(74,'P1BF92FCD11-A045','r1BF92FCD11_q45','Express route',5,1.0,24.0,224.47);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A046','Adjustable Drop Prop','Fasteners and Fixings','consu',387.84,257.9,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(75,'P1BF92FCD11-A046','r1BF92FCD11_q46','Regional lane',5,1.0,24.0,268.38);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A047','Anti-Vibration Power Unit 3HP','Pneumatic Components','consu',241.77,160.62,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(76,'P1BF92FCD11-A047','r1BF92FCD11_q47','Express route',5,1.0,24.0,167.86);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A048','Low-Flow Push Button Panel','Pneumatic Components','consu',294.97,154.21,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(77,'P1BF92FCD11-A048','r1BF92FCD11_q48','Scheduled freight',6,1.0,24.0,159.11);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A049','Impact-Rated Button Panel','Pneumatic Components','consu',274.87,171.07,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(78,'P1BF92FCD11-A049','r1BF92FCD11_q49','Bulk shipment',8,1.0,24.0,165.64);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1BF92FCD11-A050','Cleanroom Down Assembly Spring','Hardware Accessories','consu',226.41,119.5,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(79,'P1BF92FCD11-A050','r1BF92FCD11_q50','Warehouse direct',8,1.0,24.0,123.48);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'PF024ECDF2B-DCK-APD-003','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PF024ECDF2B-DCK-DPS-103',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PF024ECDF2B-DCK-HDA-107',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PF024ECDF2B-DCK-TSA-115',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PF024ECDF2B-DCK-RRW-118',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PF024ECDF2B-DCK-TGP-120',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PF024ECDF2B-DCK-CLG-121',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'P1BF92FCD11-A043','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P1BF92FCD11-A037',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P1BF92FCD11-A021',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'P1BF92FCD11-A030','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P1BF92FCD11-A027',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P1BF92FCD11-A014',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'P1BF92FCD11-A021','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'P1BF92FCD11-A046',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'P1BF92FCD11-A027','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P1BF92FCD11-A043',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P1BF92FCD11-A030',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'P1BF92FCD11-A029','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P1BF92FCD11-A042',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'P1BF92FCD11-A045','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'P1BF92FCD11-A007',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'P1BF92FCD11-A028','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P1BF92FCD11-A001',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P1BF92FCD11-A042',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'P1BF92FCD11-A003','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P1BF92FCD11-A011',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P1BF92FCD11-A024',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'P1BF92FCD11-A024','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P1BF92FCD11-A037',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(11,'P1BF92FCD11-A008','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'P1BF92FCD11-A039',1.0);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PF024ECDF2B-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PF024ECDF2B-WC02','Fabrication Cell 2',0,0,NULL,NULL);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF024ECDF2B-DCK-APD-003',NULL,35.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF024ECDF2B-DCK-CLG-121',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF024ECDF2B-DCK-DPS-103',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF024ECDF2B-DCK-HDA-107',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF024ECDF2B-DCK-RRW-118',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF024ECDF2B-DCK-TGP-120',NULL,19.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF024ECDF2B-DCK-TSA-115',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A001',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A002',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A003',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A004',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A005',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A006',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A007',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A008',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A009',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A010',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A011',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A012',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A013',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A014',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A015',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A016',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A017',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A018',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A019',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A020',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A021',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A022',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A023',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A024',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A025',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A026',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A027',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A028',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A029',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A030',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A031',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A032',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A033',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A034',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A035',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A036',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A037',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A038',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A039',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A040',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A041',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A042',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A043',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A044',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A045',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A046',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A047',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A048',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A049',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1BF92FCD11-A050',NULL,9.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'rF024ECDF2B_c01','PF024ECDF2B-DCK-APD-003',21,8,120422.43,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'rF024ECDF2B_c02','PF024ECDF2B-DCK-APD-003',16,8,87037.58,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'rF024ECDF2B_c03','PF024ECDF2B-DCK-APD-003',26,8,153412.16,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'rF024ECDF2B_c04','PF024ECDF2B-DCK-APD-003',25,9,135233.54,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'rF024ECDF2B_c05','PF024ECDF2B-DCK-APD-003',26,10,146420.72,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'rF024ECDF2B_c06','PF024ECDF2B-DCK-APD-003',26,11,149802.07,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'rF024ECDF2B_c07','PF024ECDF2B-DCK-APD-003',26,11,154244.18,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'rF024ECDF2B_c08','PF024ECDF2B-DCK-APD-003',26,14,149813.78,NULL);
