-- agentic-labs/erp-bench scenario 2179: Laminar Flow Bench Horizontal
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1029F5D3C8_c01','Copper Fabricators','customer',0,129967.8,NULL,NULL,'orders@copperfabricators.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1029F5D3C8_c02','Stonewall Analytics','customer',0,96469.8,NULL,NULL,'orders@stonewallanalytics.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1029F5D3C8_c03','Drift Studios West','customer',0,107232.46,NULL,NULL,'orders@driftstudioswest.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1029F5D3C8_c04','Spark Academy','customer',0,74877.78,NULL,NULL,'orders@sparkacademy.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1029F5D3C8_c05','Helix Workshop','customer',0,79678.69,NULL,NULL,'orders@helixworkshop.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1029F5D3C8_c06','Ember Dynamics','customer',0,94180.33,NULL,NULL,'orders@emberdynamics.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1029F5D3C8_c07','Catalyst Guild','customer',0,98948.81,NULL,NULL,'orders@catalystguild.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r1029F5D3C8_c08','Cedar Cooperative','customer',0,101224.49,NULL,NULL,'orders@cedarcooperative.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p01','Atlas Fabrication HQ Procurement','customer',0,NULL,NULL,NULL,'contact@atlasfabrication.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p02','Pacific Assembly R&D Workshop','customer',0,NULL,NULL,NULL,'contact@pacificassembly.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p03','Cascade Services HQ Procurement','customer',0,NULL,NULL,NULL,'contact@cascadeservices.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p04','Slate Fabrication Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@slatefabrication.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p05','Echo Production Prototype Shop','customer',0,NULL,NULL,NULL,'contact@echoproduction.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p06','Brookfield Technologies HQ Procurement','customer',0,NULL,NULL,NULL,'contact@brookfieldtechnologies.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p07','Lumen Technologies Tooling Center','customer',0,NULL,NULL,NULL,'contact@lumentechnologies.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p08','Zenith Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@zenithassembly.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p09','Hartland Solutions Tooling Center','customer',0,NULL,NULL,NULL,'contact@hartlandsolutions.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p10','Cipher Services Tooling Center','customer',0,NULL,NULL,NULL,'contact@cipherservices.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p11','Lakewood Assembly R&D Workshop','customer',0,NULL,NULL,NULL,'contact@lakewoodassembly.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p12','Jade Solutions R&D Workshop','customer',0,NULL,NULL,NULL,'contact@jadesolutions.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p13','Eclipse Assembly R&D Workshop','customer',0,NULL,NULL,NULL,'contact@eclipseassembly.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p14','Osprey Manufacturing Tooling Center','customer',0,NULL,NULL,NULL,'contact@ospreymanufacturing.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p15','Scion Services Test Facility','customer',0,NULL,NULL,NULL,'contact@scionservices.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p16','Fairview Services HQ Procurement','customer',0,NULL,NULL,NULL,'contact@fairviewservices.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p17','Indigo Operations Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@indigooperations.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p18','Oakmont Assembly Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@oakmontassembly.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p19','Flint Engineering Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@flintengineering.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p20','Equinox Solutions HQ Procurement','customer',0,NULL,NULL,NULL,'contact@equinoxsolutions.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p21','Peak Assembly HQ Procurement','customer',0,NULL,NULL,NULL,'contact@peakassembly.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p22','Horizon Services Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@horizonservices.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p23','Iron Production Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@ironproduction.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p24','Crown Assembly Test Facility','customer',0,NULL,NULL,NULL,'contact@crownassembly.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p25','Thornton Operations HQ Procurement','customer',0,NULL,NULL,NULL,'contact@thorntonoperations.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p26','Aurora Manufacturing Site Logistics','customer',0,NULL,NULL,NULL,'contact@auroramanufacturing.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p27','Cardinal Operations Tooling Center','customer',0,NULL,NULL,NULL,'contact@cardinaloperations.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p28','Axis Fabrication R&D Workshop','customer',0,NULL,NULL,NULL,'contact@axisfabrication.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p29','Sierra Solutions Prototype Shop','customer',0,NULL,NULL,NULL,'contact@sierrasolutions.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p30','Haven Technologies Site Logistics','customer',0,NULL,NULL,NULL,'contact@haventechnologies.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p31','Orbital Technologies Prototype Shop','customer',0,NULL,NULL,NULL,'contact@orbitaltechnologies.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p32','Titan Operations HQ Procurement','customer',0,NULL,NULL,NULL,'contact@titanoperations.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p33','Solace Production Quality Lab','customer',0,NULL,NULL,NULL,'contact@solaceproduction.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p34','Millbrook Technologies Tooling Center','customer',0,NULL,NULL,NULL,'contact@millbrooktechnologies.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p35','Nexus Engineering Quality Lab','customer',0,NULL,NULL,NULL,'contact@nexusengineering.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p36','Aether Operations Site Logistics','customer',0,NULL,NULL,NULL,'contact@aetheroperations.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p37','Flux Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@fluxassembly.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p38','Riverdale Industries Test Facility','customer',0,NULL,NULL,NULL,'contact@riverdaleindustries.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p39','Gateway Manufacturing R&D Workshop','customer',0,NULL,NULL,NULL,'contact@gatewaymanufacturing.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p40','Alpine Assembly Test Facility','customer',0,NULL,NULL,NULL,'contact@alpineassembly.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p41','Quantum Services Tooling Center','customer',0,NULL,NULL,NULL,'contact@quantumservices.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p42','Spectra Fabrication Tooling Center','customer',0,NULL,NULL,NULL,'contact@spectrafabrication.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p43','Alloy Services Tooling Center','customer',0,NULL,NULL,NULL,'contact@alloyservices.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p44','Pivot Manufacturing R&D Workshop','customer',0,NULL,NULL,NULL,'contact@pivotmanufacturing.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p45','Arbor Operations Quality Lab','customer',0,NULL,NULL,NULL,'contact@arboroperations.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p46','Ironside Technologies Quality Lab','customer',0,NULL,NULL,NULL,'contact@ironsidetechnologies.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p47','Trellis Assembly R&D Workshop','customer',0,NULL,NULL,NULL,'contact@trellisassembly.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p48','Adjacent Customer 1 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer001.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p49','Adjacent Customer 2 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer002.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r2624A5E7AA_p50','Adjacent Customer 3 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer003.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q01','Trident Warehousing','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q02','Vantage Exporters','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q03','Anvil Supply','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q04','Opal Procurement','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q05','Skyline Transit','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q06','Bridgeway Movers','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q07','Borough Holdings','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q08','Lattice Depot','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q09','Summit Fabrication','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q10','Ridgeline Manufacturing','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q11','Polar Distributors','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q12','Marble Assemblies','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q13','Bronze Solutions','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q14','Comet Forwarders','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q15','Sterling Carriers','vendor',15,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q16','Pinnacle Partners','vendor',16,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q17','Metro Commodities','vendor',17,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q18','Ledger Packagers','vendor',18,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q19','Clearwater Shipping','vendor',19,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q20','Compass Haulage','vendor',20,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q21','Sentinel Transport','vendor',21,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q22','Forge Importers','vendor',22,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q23','Steel Materials','vendor',23,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q24','Bayshore Wholesalers','vendor',24,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q25','Silverline Sourcing','vendor',25,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r1029F5D3C8_q26','Matrix Conveyance','vendor',26,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q01','Terra Carriers','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q02','Vertex Transit','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q03','Evergreen Procurement','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q04','Grove Procurement','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q05','Velocity Networks','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q06','Blaze Trading','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q07','Aegis Components','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q08','Spire Carriers','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q09','Oxide Distribution','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q10','Crest Wholesale','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q11','Meridian Logistics','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q12','Apex Wholesale','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q13','Cosmo Procurement','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q14','Circuit Transit','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q15','Redstone Parts Co','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q16','Quartz Wholesale','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q17','Element Parts Co','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q18','Monarch Freight','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q19','Baseline Transit','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q20','Coral Components','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q21','Nimbus Trading','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q22','Ashford Components','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q23','Northbridge Carriers','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q24','Sapphire Wholesale','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q25','Arrow Carriers','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q26','Lance Sourcing','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q27','Ridge Materials','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q28','Ironwood Resources','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q29','Onyx Transit','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q30','Baltic Resources','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q31','Arc Logistics','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q32','Westfield Sourcing','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q33','Mosaic Procurement','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q34','Globe Resources','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q35','Raven Transit','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q36','Chrome Networks','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q37','Dune Parts Co','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q38','Citadel Procurement','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q39','Crestview Components','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q40','Beacon Transit','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q41','Keystone Procurement','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q42','Prism Carriers','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q43','Garnet Distribution','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q44','Granite Supply','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q45','Noble Distribution','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q46','Conduit Sourcing','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q47','Cobalt Parts Co','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q48','Stratos Wholesale','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q49','Ivory Wholesale','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r2624A5E7AA_q50','Canton Components','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1029F5D3C8-CLR-LFH-006','Laminar Flow Bench Horizontal','Cleanroom Equipment','consu',5101.82,2812.32,'buy,manufacture',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'P1029F5D3C8-CLR-LFH-006','r1029F5D3C8_q01','Priority Shuttle lane (10d transit, 5-6 units)',10,5.0,6.0,2956.39);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'P1029F5D3C8-CLR-LFH-006','r1029F5D3C8_q02','Express Air lane (6d transit, 2-3 units)',6,2.0,3.0,4043.31);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'P1029F5D3C8-CLR-LFH-006','r1029F5D3C8_q03','Bulk Container lane (21d transit, 72-72 units)',21,72.0,72.0,2070.41);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'P1029F5D3C8-CLR-LFH-006','r1029F5D3C8_q04','Economy Ocean lane (23d transit, 9-32 units)',23,9.0,32.0,2496.19);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'P1029F5D3C8-CLR-LFH-006','r1029F5D3C8_q05','Microfactory Build-to-Order lane (7d transit, 3-6 units)',7,3.0,6.0,3828.06);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'P1029F5D3C8-CLR-LFH-006','r1029F5D3C8_q06','Hybrid Expedite lane (11d transit, 4-9 units)',11,4.0,9.0,3686.74);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1029F5D3C8-CLR-DPG-108','Differential Pressure Gauge','Cleanroom Equipment','consu',79.97,25.54,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'P1029F5D3C8-CLR-DPG-108','r1029F5D3C8_q07','Rapid Works (3d)',3,6.0,12.0,45.44);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'P1029F5D3C8-CLR-DPG-108','r1029F5D3C8_q08','Import Consolidator (7d)',7,44.0,52.0,25.54);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'P1029F5D3C8-CLR-DPG-108','r1029F5D3C8_q09','Hybrid Fabricators (4d)',4,16.0,16.0,42.56);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'P1029F5D3C8-CLR-DPG-108','r1029F5D3C8_q10','Domestic Supply (5d)',5,16.0,35.0,35.39);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1029F5D3C8-CLR-RAG-109','Return Air Grille Low-Wall','Cleanroom Equipment','consu',50.03,17.08,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'P1029F5D3C8-CLR-RAG-109','r1029F5D3C8_q11','Rapid Works (3d)',3,5.0,58.0,24.77);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'P1029F5D3C8-CLR-RAG-109','r1029F5D3C8_q12','Domestic Supply (6d)',6,18.0,59.0,21.15);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'P1029F5D3C8-CLR-RAG-109','r1029F5D3C8_q13','Hybrid Fabricators (5d)',5,14.0,143.0,25.16);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'P1029F5D3C8-CLR-RAG-109','r1029F5D3C8_q14','Import Consolidator (7d)',7,26.0,66.0,17.08);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1029F5D3C8-CLR-IDC-113','Interlock Door Controller Module','Cleanroom Equipment','consu',247.89,106.15,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'P1029F5D3C8-CLR-IDC-113','r1029F5D3C8_q15','Rapid Works (2d)',2,8.0,17.0,172.91);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'P1029F5D3C8-CLR-IDC-113','r1029F5D3C8_q16','Domestic Supply (6d)',6,16.0,58.0,128.98);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'P1029F5D3C8-CLR-IDC-113','r1029F5D3C8_q17','Import Consolidator (7d)',7,36.0,49.0,106.15);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'P1029F5D3C8-CLR-IDC-113','r1029F5D3C8_q18','Hybrid Fabricators (7d)',7,17.0,18.0,153.42);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1029F5D3C8-CLR-GBS-118','Gowning Bench Stainless Steel','Cleanroom Equipment','consu',361.35,183.11,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'P1029F5D3C8-CLR-GBS-118','r1029F5D3C8_q19','Rapid Works (3d)',3,6.0,6.0,253.66);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'P1029F5D3C8-CLR-GBS-118','r1029F5D3C8_q20','Hybrid Fabricators (6d)',6,9.0,14.0,221.68);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'P1029F5D3C8-CLR-GBS-118','r1029F5D3C8_q21','Domestic Supply (4d)',4,12.0,63.0,186.04);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'P1029F5D3C8-CLR-GBS-118','r1029F5D3C8_q22','Import Consolidator (7d)',7,40.0,103.0,183.11);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P1029F5D3C8-CLR-RPM-129','Room Pressure Monitor Display','Cleanroom Equipment','consu',185.66,82.14,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'P1029F5D3C8-CLR-RPM-129','r1029F5D3C8_q23','Rapid Works (3d)',3,12.0,46.0,131.07);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'P1029F5D3C8-CLR-RPM-129','r1029F5D3C8_q24','Import Consolidator (7d)',7,36.0,43.0,82.14);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'P1029F5D3C8-CLR-RPM-129','r1029F5D3C8_q25','Hybrid Fabricators (6d)',6,11.0,40.0,107.81);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'P1029F5D3C8-CLR-RPM-129','r1029F5D3C8_q26','Domestic Supply (6d)',6,18.0,32.0,90.99);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A001','Thermal-Guard Corner Cove','Mechanical Components','consu',399.34,223.68,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'P2624A5E7AA-A001','r2624A5E7AA_q01','Warehouse direct',7,1.0,24.0,235.04);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A002','High-Performance 2x4 99.99%','Fasteners and Fixings','consu',368.74,252.84,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'P2624A5E7AA-A002','r2624A5E7AA_q02','Cross-dock',3,1.0,24.0,267.97);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A003','Medical-Grade Unit Motor Assembly','Industrial Spare Parts','consu',272.85,145.72,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'P2624A5E7AA-A003','r2624A5E7AA_q03','Regional lane',5,1.0,24.0,142.7);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A004','High-Temp Corner Cove','Power Transmission','consu',220.27,155.4,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'P2624A5E7AA-A004','r2624A5E7AA_q04','Warehouse direct',5,1.0,24.0,159.77);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A005','Narrow-Body Grille Low Wall','Power Transmission','consu',241.46,147.3,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'P2624A5E7AA-A005','r2624A5E7AA_q05','Warehouse direct',8,1.0,24.0,140.69);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A006','Heat-Treated 2x4 99.99%','Seals and Gaskets','consu',389.52,260.74,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'P2624A5E7AA-A006','r2624A5E7AA_q06','Local pickup',7,1.0,24.0,272.4);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A007','Heavy-Duty Panel Flush Mount','Seals and Gaskets','consu',228.58,126.07,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'P2624A5E7AA-A007','r2624A5E7AA_q07','Standard delivery',3,1.0,24.0,126.57);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A008','Lightweight Flush Mount','Industrial Spare Parts','consu',230.55,142.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'P2624A5E7AA-A008','r2624A5E7AA_q08','Bulk shipment',5,1.0,24.0,150.61);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A009','Threaded Flush Mount','Seals and Gaskets','consu',410.84,273.21,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'P2624A5E7AA-A009','r2624A5E7AA_q09','Warehouse direct',8,1.0,24.0,292.05);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A010','Corrosion-Resistant Motor Assembly','Electrical Components','consu',365.95,249.81,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'P2624A5E7AA-A010','r2624A5E7AA_q10','Regional lane',8,1.0,24.0,247.32);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A011','Quick-Release Panel 2x4 99.9995%','Seals and Gaskets','consu',288.21,171.84,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'P2624A5E7AA-A011','r2624A5E7AA_q11','Local pickup',3,1.0,24.0,168.6);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A012','Premium Panel 2x4 99.99%','Fasteners and Fixings','consu',251.44,162.07,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'P2624A5E7AA-A012','r2624A5E7AA_q12','Standard delivery',4,1.0,24.0,174.2);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A013','Flanged Pressure Gauge','Maintenance Supplies','consu',416.65,224.56,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'P2624A5E7AA-A013','r2624A5E7AA_q13','Express route',4,1.0,24.0,215.39);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A014','High-Torque Grille Low Wall','Seals and Gaskets','consu',290.92,196.89,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'P2624A5E7AA-A014','r2624A5E7AA_q14','Cross-dock',6,1.0,24.0,199.81);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A015','Spring-Loaded Low Wall','Electrical Components','consu',235.47,130.92,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'P2624A5E7AA-A015','r2624A5E7AA_q15','Regional lane',7,1.0,24.0,127.19);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A016','Reinforced T Bar','Fasteners and Fixings','consu',201.54,118.5,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'P2624A5E7AA-A016','r2624A5E7AA_q16','Express route',4,1.0,24.0,115.17);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A017','High-Flow Low Wall','Electrical Components','consu',339.46,210.8,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'P2624A5E7AA-A017','r2624A5E7AA_q17','Local pickup',5,1.0,24.0,221.95);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A018','Extended-Life Seal Gasket Frame','Pneumatic Components','consu',363.4,209.89,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'P2624A5E7AA-A018','r2624A5E7AA_q18','Standard delivery',8,1.0,24.0,213.58);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A019','Adjustable Seal Gasket Frame','Hardware Accessories','consu',189.4,115.5,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'P2624A5E7AA-A019','r2624A5E7AA_q19','Warehouse direct',4,1.0,24.0,113.73);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A020','Low-Friction Light Panel','Fasteners and Fixings','consu',384.58,223.98,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'P2624A5E7AA-A020','r2624A5E7AA_q20','Express route',4,1.0,24.0,227.37);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A021','Dual-Stage Panel Flush Mount','Seals and Gaskets','consu',332.59,199.36,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'P2624A5E7AA-A021','r2624A5E7AA_q21','Bulk shipment',3,1.0,24.0,214.25);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A022','Metric Curtain Door Set','Fasteners and Fixings','consu',302.26,165.12,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'P2624A5E7AA-A022','r2624A5E7AA_q22','Cross-dock',3,1.0,24.0,161.43);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A023','Modular Differential Pressure Gauge','Fasteners and Fixings','consu',369.9,265.87,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'P2624A5E7AA-A023','r2624A5E7AA_q23','Local pickup',4,1.0,24.0,262.79);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A024','Wide-Body Motor Assembly','Electrical Components','consu',198.75,123.73,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'P2624A5E7AA-A024','r2624A5E7AA_q24','Cross-dock',7,1.0,24.0,126.91);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A025','Economy T Bar','Mechanical Components','consu',371.5,203.8,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'P2624A5E7AA-A025','r2624A5E7AA_q25','Express route',3,1.0,24.0,207.1);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A026','Low-Temp Panel 2x4 99.99%','Pneumatic Components','consu',349.75,214.24,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'P2624A5E7AA-A026','r2624A5E7AA_q26','Warehouse direct',7,1.0,24.0,216.4);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A027','Industrial Panel 2x4 99.99%','Seals and Gaskets','consu',182.91,111.17,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'P2624A5E7AA-A027','r2624A5E7AA_q27','Bulk shipment',6,1.0,24.0,118.62);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A028','Food-Grade Pressure Gauge','Maintenance Supplies','consu',395.49,214.68,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'P2624A5E7AA-A028','r2624A5E7AA_q28','Bulk shipment',3,1.0,24.0,209.43);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A029','Low-Profile Grille Low Wall','Seals and Gaskets','consu',192.18,109.68,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'P2624A5E7AA-A029','r2624A5E7AA_q29','Bulk shipment',3,1.0,24.0,111.31);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A030','Double-Row Corner Cove','Industrial Spare Parts','consu',186.8,98.58,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'P2624A5E7AA-A030','r2624A5E7AA_q30','Express route',8,1.0,24.0,103.3);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A031','Standard Seal Gasket Frame','Hardware Accessories','consu',323.45,172.14,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(57,'P2624A5E7AA-A031','r2624A5E7AA_q31','Standard delivery',3,1.0,24.0,178.08);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A032','Weatherproof Pressure Gauge','Fasteners and Fixings','consu',288.33,191.9,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(58,'P2624A5E7AA-A032','r2624A5E7AA_q32','Bulk shipment',7,1.0,24.0,185.26);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A033','Cold-Rolled 2x4 99.99%','Fasteners and Fixings','consu',293.01,208.17,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(59,'P2624A5E7AA-A033','r2624A5E7AA_q33','Cross-dock',3,1.0,24.0,216.01);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A034','Anodized Panel 2x4 99.9995%','Pneumatic Components','consu',310.86,195.0,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(60,'P2624A5E7AA-A034','r2624A5E7AA_q34','Warehouse direct',6,1.0,24.0,198.79);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A035','Non-Magnetic 2x4 99.99%','Fasteners and Fixings','consu',203.2,118.81,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(61,'P2624A5E7AA-A035','r2624A5E7AA_q35','Local pickup',6,1.0,24.0,122.8);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A036','Low-Flow Door Set','Pneumatic Components','consu',250.18,141.14,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(62,'P2624A5E7AA-A036','r2624A5E7AA_q36','Standard delivery',7,1.0,24.0,147.12);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A037','High-Cycle Pressure Gauge','Maintenance Supplies','consu',349.06,243.53,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(63,'P2624A5E7AA-A037','r2624A5E7AA_q37','Local pickup',3,1.0,24.0,233.13);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A038','Powder-Coated Panel 2x4 99.99%','Mechanical Components','consu',254.32,136.27,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(64,'P2624A5E7AA-A038','r2624A5E7AA_q38','Warehouse direct',5,1.0,24.0,129.47);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A039','Tapered Gasket Frame','Power Transmission','consu',395.09,208.12,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(65,'P2624A5E7AA-A039','r2624A5E7AA_q39','Local pickup',4,1.0,24.0,221.39);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A040','Rapid-Lock LED Light Panel','Replacement Parts','consu',357.69,235.86,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(66,'P2624A5E7AA-A040','r2624A5E7AA_q40','Regional lane',6,1.0,24.0,236.96);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A041','Cleanroom Motor Assembly','Industrial Spare Parts','consu',270.24,150.39,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(67,'P2624A5E7AA-A041','r2624A5E7AA_q41','Express route',3,1.0,24.0,146.28);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A042','Low-Noise Flush Mount','Pneumatic Components','consu',383.44,275.81,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(68,'P2624A5E7AA-A042','r2624A5E7AA_q42','Warehouse direct',6,1.0,24.0,293.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A043','UV-Stable Pressure Gauge','Power Transmission','consu',354.03,247.22,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(69,'P2624A5E7AA-A043','r2624A5E7AA_q43','Cross-dock',3,1.0,24.0,255.47);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A044','Self-Lubricating Seal Gasket Frame','Maintenance Supplies','consu',409.51,278.21,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(70,'P2624A5E7AA-A044','r2624A5E7AA_q44','Standard delivery',5,1.0,24.0,266.47);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A045','Single-Stage Panel Flush Mount','Power Transmission','consu',313.05,199.27,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(71,'P2624A5E7AA-A045','r2624A5E7AA_q45','Express route',6,1.0,24.0,210.97);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A046','Stainless Curtain Door Set','Power Transmission','consu',226.13,124.54,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(72,'P2624A5E7AA-A046','r2624A5E7AA_q46','Express route',5,1.0,24.0,119.21);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A047','Sealed Seal Gasket Frame','Maintenance Supplies','consu',352.9,232.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(73,'P2624A5E7AA-A047','r2624A5E7AA_q47','Scheduled freight',6,1.0,24.0,225.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A048','Impact-Rated T Bar','Electrical Components','consu',233.74,164.97,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(74,'P2624A5E7AA-A048','r2624A5E7AA_q48','Scheduled freight',5,1.0,24.0,175.82);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A049','Anti-Vibration Flush Mount','Power Transmission','consu',241.61,173.28,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(75,'P2624A5E7AA-A049','r2624A5E7AA_q49','Standard delivery',8,1.0,24.0,168.83);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P2624A5E7AA-A050','Snap-Fit 2x4 99.99%','Mechanical Components','consu',325.7,234.11,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(76,'P2624A5E7AA-A050','r2624A5E7AA_q50','Local pickup',5,1.0,24.0,249.17);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'P1029F5D3C8-CLR-LFH-006','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P1029F5D3C8-CLR-DPG-108',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P1029F5D3C8-CLR-RAG-109',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P1029F5D3C8-CLR-IDC-113',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P1029F5D3C8-CLR-GBS-118',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P1029F5D3C8-CLR-RPM-129',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'P2624A5E7AA-A029','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P2624A5E7AA-A003',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'P2624A5E7AA-A007','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P2624A5E7AA-A048',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'P2624A5E7AA-A023','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'P2624A5E7AA-A032',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'P2624A5E7AA-A010','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P2624A5E7AA-A034',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'P2624A5E7AA-A028','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P2624A5E7AA-A047',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P2624A5E7AA-A039',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'P2624A5E7AA-A019','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'P2624A5E7AA-A016',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'P2624A5E7AA-A044','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P2624A5E7AA-A035',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P2624A5E7AA-A028',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'P2624A5E7AA-A009','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P2624A5E7AA-A005',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P2624A5E7AA-A015',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'P2624A5E7AA-A022','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P2624A5E7AA-A027',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P2624A5E7AA-A011',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(11,'P2624A5E7AA-A039','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'P2624A5E7AA-A030',1.0);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P1029F5D3C8-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P1029F5D3C8-WC02','Fabrication Cell 2',0,0,NULL,NULL);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1029F5D3C8-CLR-DPG-108',NULL,17.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1029F5D3C8-CLR-GBS-118',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1029F5D3C8-CLR-IDC-113',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1029F5D3C8-CLR-LFH-006',NULL,20.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1029F5D3C8-CLR-RAG-109',NULL,16.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P1029F5D3C8-CLR-RPM-129',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A001',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A002',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A003',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A004',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A005',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A006',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A007',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A008',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A009',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A010',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A011',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A012',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A013',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A014',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A015',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A016',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A017',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A018',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A019',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A020',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A021',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A022',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A023',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A024',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A025',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A026',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A027',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A028',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A029',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A030',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A031',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A032',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A033',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A034',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A035',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A036',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A037',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A038',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A039',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A040',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A041',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A042',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A043',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A044',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A045',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A046',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A047',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A048',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A049',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P2624A5E7AA-A050',NULL,5.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'r1029F5D3C8_c01','P1029F5D3C8-CLR-LFH-006',24,9,129967.8,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'r1029F5D3C8_c02','P1029F5D3C8-CLR-LFH-006',17,10,96469.8,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'r1029F5D3C8_c03','P1029F5D3C8-CLR-LFH-006',19,11,107232.46,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'r1029F5D3C8_c04','P1029F5D3C8-CLR-LFH-006',14,12,74877.78,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'r1029F5D3C8_c05','P1029F5D3C8-CLR-LFH-006',15,13,79678.69,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'r1029F5D3C8_c06','P1029F5D3C8-CLR-LFH-006',17,13,94180.33,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'r1029F5D3C8_c07','P1029F5D3C8-CLR-LFH-006',19,13,98948.81,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'r1029F5D3C8_c08','P1029F5D3C8-CLR-LFH-006',19,14,101224.49,NULL);
