-- agentic-labs/erp-bench scenario 2123: Multi-Stage Filtration Tower
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r43E89D45DC_c01','Silverline Society','customer',0,61132.53,NULL,NULL,'orders@silverlinesociety.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r43E89D45DC_c02','Lakewood Lyceum','customer',0,73349.11,NULL,NULL,'orders@lakewoodlyceum.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r43E89D45DC_c03','Baltic Collective East','customer',0,65277.63,NULL,NULL,'orders@balticcollectiveeast.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r43E89D45DC_c04','Riverdale Trust','customer',0,58336.48,NULL,NULL,'orders@riverdaletrust.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r43E89D45DC_c05','Velocity Robotics','customer',0,52496.98,NULL,NULL,'orders@velocityrobotics.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r43E89D45DC_c06','Sapphire Studios West','customer',0,74477.43,NULL,NULL,'orders@sapphirestudioswest.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r43E89D45DC_c07','Millbrook Creative','customer',0,73375.29,NULL,NULL,'orders@millbrookcreative.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r43E89D45DC_c08','Lance Guild','customer',0,53058.47,NULL,NULL,'orders@lanceguild.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r43E89D45DC_c09','Skyline Supply Co','customer',0,61426.34,NULL,NULL,'orders@skylinesupplyco.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p01','Arrow Fabrication Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@arrowfabrication.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p02','Gateway Industries R&D Workshop','customer',0,NULL,NULL,NULL,'contact@gatewayindustries.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p03','Anvil Services Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@anvilservices.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p04','Marble Assembly Site Logistics','customer',0,NULL,NULL,NULL,'contact@marbleassembly.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p05','Ivory Solutions R&D Workshop','customer',0,NULL,NULL,NULL,'contact@ivorysolutions.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p06','Brookfield Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@brookfieldassembly.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p07','Cipher Manufacturing Tooling Center','customer',0,NULL,NULL,NULL,'contact@ciphermanufacturing.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p08','Bayshore Manufacturing R&D Workshop','customer',0,NULL,NULL,NULL,'contact@bayshoremanufacturing.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p09','Copper Technologies Tooling Center','customer',0,NULL,NULL,NULL,'contact@coppertechnologies.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p10','Steel Assembly Quality Lab','customer',0,NULL,NULL,NULL,'contact@steelassembly.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p11','Oakmont Industries Prototype Shop','customer',0,NULL,NULL,NULL,'contact@oakmontindustries.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p12','Opal Services Prototype Shop','customer',0,NULL,NULL,NULL,'contact@opalservices.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p13','Cardinal Operations Field Ops','customer',0,NULL,NULL,NULL,'contact@cardinaloperations.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p14','Lattice Technologies Test Facility','customer',0,NULL,NULL,NULL,'contact@latticetechnologies.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p15','Grove Operations Site Logistics','customer',0,NULL,NULL,NULL,'contact@groveoperations.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p16','Iron Technologies Quality Lab','customer',0,NULL,NULL,NULL,'contact@irontechnologies.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p17','Beacon Services Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@beaconservices.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p18','Alpine Technologies Test Facility','customer',0,NULL,NULL,NULL,'contact@alpinetechnologies.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p19','Trident Fabrication Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@tridentfabrication.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p20','Garnet Technologies Tooling Center','customer',0,NULL,NULL,NULL,'contact@garnettechnologies.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p21','Bridgeway Manufacturing R&D Workshop','customer',0,NULL,NULL,NULL,'contact@bridgewaymanufacturing.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p22','Conduit Services HQ Procurement','customer',0,NULL,NULL,NULL,'contact@conduitservices.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p23','Pacific Manufacturing HQ Procurement','customer',0,NULL,NULL,NULL,'contact@pacificmanufacturing.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p24','Crestview Manufacturing HQ Procurement','customer',0,NULL,NULL,NULL,'contact@crestviewmanufacturing.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p25','Element Services Quality Lab','customer',0,NULL,NULL,NULL,'contact@elementservices.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p26','Aegis Services Prototype Shop','customer',0,NULL,NULL,NULL,'contact@aegisservices.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p27','Arbor Engineering Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@arborengineering.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p28','Crown Fabrication HQ Procurement','customer',0,NULL,NULL,NULL,'contact@crownfabrication.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p29','Granite Operations Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@graniteoperations.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p30','Alloy Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@alloyassembly.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p31','Onyx Solutions Tooling Center','customer',0,NULL,NULL,NULL,'contact@onyxsolutions.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p32','Oxide Industries Test Facility','customer',0,NULL,NULL,NULL,'contact@oxideindustries.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p33','Forge Operations Field Ops','customer',0,NULL,NULL,NULL,'contact@forgeoperations.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p34','Ridgeline Services Tooling Center','customer',0,NULL,NULL,NULL,'contact@ridgelineservices.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p35','Quantum Manufacturing Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@quantummanufacturing.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p36','Summit Fabrication Tooling Center','customer',0,NULL,NULL,NULL,'contact@summitfabrication.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p37','Sterling Assembly HQ Procurement','customer',0,NULL,NULL,NULL,'contact@sterlingassembly.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p38','Echo Industries Site Logistics','customer',0,NULL,NULL,NULL,'contact@echoindustries.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p39','Apex Operations Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@apexoperations.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p40','Lumen Engineering Site Logistics','customer',0,NULL,NULL,NULL,'contact@lumenengineering.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p41','Titan Services Field Ops','customer',0,NULL,NULL,NULL,'contact@titanservices.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p42','Sierra Production Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@sierraproduction.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p43','Scion Operations Test Facility','customer',0,NULL,NULL,NULL,'contact@scionoperations.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p44','Solace Operations Field Ops','customer',0,NULL,NULL,NULL,'contact@solaceoperations.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p45','Trellis Industries Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@trellisindustries.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p46','Zenith Operations Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@zenithoperations.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p47','Ridge Operations Site Logistics','customer',0,NULL,NULL,NULL,'contact@ridgeoperations.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p48','Crest Manufacturing Tooling Center','customer',0,NULL,NULL,NULL,'contact@crestmanufacturing.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p49','Stonewall Assembly HQ Procurement','customer',0,NULL,NULL,NULL,'contact@stonewallassembly.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6215EF4CAF_p50','Aurora Fabrication R&D Workshop','customer',0,NULL,NULL,NULL,'contact@aurorafabrication.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r43E89D45DC_q01','Metro Movers','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r43E89D45DC_q02','Vertex Conveyance','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r43E89D45DC_q03','Peak Haulage','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r43E89D45DC_q04','Bronze Warehousing','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r43E89D45DC_q05','Cosmo Assemblies','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r43E89D45DC_q06','Globe Manufacturing','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r43E89D45DC_q07','Noble Consolidators','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r43E89D45DC_q08','Pinnacle Materials','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r43E89D45DC_q09','Redstone Provisions','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r43E89D45DC_q10','Cobalt Industries','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r43E89D45DC_q11','Spire Exporters','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r43E89D45DC_q12','Blaze Fulfillment','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r43E89D45DC_q13','Comet Networks','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r43E89D45DC_q14','Flint Distribution','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r43E89D45DC_q15','Hartland Partners','vendor',15,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r43E89D45DC_q16','Terra Components','vendor',16,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r43E89D45DC_q17','Spark Carriers','vendor',17,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q01','Pivot Supply','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q02','Ember Networks','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q03','Sentinel Distribution','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q04','Coral Carriers','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q05','Nexus Supply','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q06','Ledger Parts Co','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q07','Circuit Logistics','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q08','Westfield Materials','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q09','Evergreen Wholesale','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q10','Canton Materials','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q11','Mosaic Parts Co','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q12','Orbital Components','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q13','Axis Wholesale','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q14','Aether Networks','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q15','Meridian Carriers','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q16','Ashford Supply','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q17','Flux Supply','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q18','Slate Carriers','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q19','Thornton Networks','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q20','Arc Components','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q21','Ironside Procurement','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q22','Monarch Freight','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q23','Baseline Carriers','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q24','Northbridge Resources','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q25','Nimbus Transit','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q26','Vantage Wholesale','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q27','Helix Trading','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q28','Stratos Transit','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q29','Cedar Sourcing','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q30','Quartz Components','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q31','Haven Sourcing','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q32','Compass Networks','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q33','Keystone Components','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q34','Spectra Freight','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q35','Equinox Trading','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q36','Borough Logistics','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q37','Prism Trading','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q38','Citadel Networks','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q39','Eclipse Networks','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q40','Dune Materials','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q41','Ironwood Distribution','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q42','Chrome Sourcing','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q43','Raven Carriers','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q44','Polar Logistics','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q45','Indigo Parts Co','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q46','Drift Networks','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q47','Clearwater Freight','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q48','Horizon Distribution','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q49','Cascade Transit','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6215EF4CAF_q50','Osprey Components','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P43E89D45DC-WTR-MSF-003','Multi-Stage Filtration Tower','Utility Equipment','consu',3488.97,2161.18,'buy,manufacture',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'P43E89D45DC-WTR-MSF-003','r43E89D45DC_q01','Priority Shuttle lane (9d transit, 8-17 units)',9,8.0,17.0,2170.29);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'P43E89D45DC-WTR-MSF-003','r43E89D45DC_q02','Express Air lane (5d transit, 1-9 units)',5,1.0,9.0,3377.75);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'P43E89D45DC-WTR-MSF-003','r43E89D45DC_q03','Bulk Container lane (24d transit, 76-93 units)',24,76.0,93.0,1452.61);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'P43E89D45DC-WTR-MSF-003','r43E89D45DC_q04','Regional Cross-Dock lane (14d transit, 9-41 units)',14,9.0,41.0,2244.96);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'P43E89D45DC-WTR-MSF-003','r43E89D45DC_q05','Economy Ocean lane (22d transit, 14-14 units)',22,14.0,14.0,1608.12);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P43E89D45DC-SUB-02','Multi-Stage Filtration Tower Subassembly','Utility Equipment','consu',976.91,532.58,'manufacture',NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P43E89D45DC-WTR-UVL-104','UV Lamp Quartz Sleeve Set','Utility Equipment','consu',93.33,32.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'P43E89D45DC-WTR-UVL-104','r43E89D45DC_q06','Rapid Works (3d)',3,11.0,81.0,48.92);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'P43E89D45DC-WTR-UVL-104','r43E89D45DC_q07','Hybrid Fabricators (6d)',6,10.0,21.0,53.84);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'P43E89D45DC-WTR-UVL-104','r43E89D45DC_q08','Import Consolidator (6d)',6,41.0,96.0,32.42);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P43E89D45DC-WTR-FMS-109','Flow Meter Sensor Module','Utility Equipment','consu',145.63,67.78,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'P43E89D45DC-WTR-FMS-109','r43E89D45DC_q09','Rapid Works (3d)',3,6.0,10.0,96.55);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'P43E89D45DC-WTR-FMS-109','r43E89D45DC_q10','Import Consolidator (6d)',6,35.0,36.0,67.78);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'P43E89D45DC-WTR-FMS-109','r43E89D45DC_q11','Domestic Supply (4d)',4,26.0,46.0,68.27);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P43E89D45DC-WTR-ROM-101','RO Membrane Element 4x40','Utility Equipment','consu',271.91,131.47,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'P43E89D45DC-WTR-ROM-101','r43E89D45DC_q12','Rapid Works (4d)',4,5.0,174.0,170.82);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'P43E89D45DC-WTR-ROM-101','r43E89D45DC_q13','Hybrid Fabricators (4d)',4,12.0,36.0,154.88);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'P43E89D45DC-WTR-ROM-101','r43E89D45DC_q14','Domestic Supply (4d)',4,20.0,96.0,131.47);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P43E89D45DC-WTR-PVH-102','Pressure Vessel Housing FRP','Utility Equipment','consu',406.57,153.39,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'P43E89D45DC-WTR-PVH-102','r43E89D45DC_q15','Rapid Works (2d)',2,6.0,6.0,247.23);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'P43E89D45DC-WTR-PVH-102','r43E89D45DC_q16','Import Consolidator (4d)',4,43.0,69.0,153.39);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'P43E89D45DC-WTR-PVH-102','r43E89D45DC_q17','Hybrid Fabricators (4d)',4,14.0,24.0,247.01);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A001','Anodized Bracket Set','Power Transmission','consu',200.83,125.47,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'P6215EF4CAF-A001','r6215EF4CAF_q01','Standard delivery',7,1.0,24.0,119.54);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A002','Weatherproof Chemical Metering Pump','Electrical Components','consu',247.14,167.3,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'P6215EF4CAF-A002','r6215EF4CAF_q02','Standard delivery',7,1.0,24.0,177.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A003','Powder-Coated Sensor Module','Maintenance Supplies','consu',353.08,214.41,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'P6215EF4CAF-A003','r6215EF4CAF_q03','Cross-dock',6,1.0,24.0,217.03);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A004','Cold-Rolled Meter Sensor Module','Seals and Gaskets','consu',236.71,135.9,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'P6215EF4CAF-A004','r6215EF4CAF_q04','Local pickup',4,1.0,24.0,137.9);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A005','Double-Row Membrane Element 4x40','Power Transmission','consu',269.94,143.12,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'P6215EF4CAF-A005','r6215EF4CAF_q05','Regional lane',3,1.0,24.0,143.52);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A006','High-Flow Meter Sensor Module','Electrical Components','consu',265.34,187.08,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'P6215EF4CAF-A006','r6215EF4CAF_q06','Standard delivery',8,1.0,24.0,202.0);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A007','Quick-Release Filter Cartridge 5um','Industrial Spare Parts','consu',403.15,277.45,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'P6215EF4CAF-A007','r6215EF4CAF_q07','Bulk shipment',8,1.0,24.0,275.69);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A008','Non-Magnetic Filter Cartridge 5um','Industrial Spare Parts','consu',315.16,213.9,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'P6215EF4CAF-A008','r6215EF4CAF_q08','Warehouse direct',6,1.0,24.0,212.12);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A009','High-Temp Cartridge 5um','Industrial Spare Parts','consu',182.82,103.17,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'P6215EF4CAF-A009','r6215EF4CAF_q09','Regional lane',4,1.0,24.0,104.94);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A010','Standard Housing FRP','Seals and Gaskets','consu',341.24,224.06,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'P6215EF4CAF-A010','r6215EF4CAF_q10','Standard delivery',3,1.0,24.0,226.64);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A011','Narrow-Body Metering Pump','Hardware Accessories','consu',272.96,160.57,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'P6215EF4CAF-A011','r6215EF4CAF_q11','Local pickup',6,1.0,24.0,165.3);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A012','Impact-Rated Housing Bracket Set','Seals and Gaskets','consu',186.04,103.19,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'P6215EF4CAF-A012','r6215EF4CAF_q12','Express route',7,1.0,24.0,103.74);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A013','Medical-Grade Meter Sensor Module','Fasteners and Fixings','consu',288.08,201.86,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'P6215EF4CAF-A013','r6215EF4CAF_q13','Warehouse direct',6,1.0,24.0,198.74);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A014','Sealed Cartridge 20in','Fasteners and Fixings','consu',203.96,143.3,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'P6215EF4CAF-A014','r6215EF4CAF_q14','Local pickup',3,1.0,24.0,151.49);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A015','High-Performance Valve Assembly','Electrical Components','consu',209.49,143.81,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'P6215EF4CAF-A015','r6215EF4CAF_q15','Standard delivery',7,1.0,24.0,149.33);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A016','Hardened Valve Assembly','Hardware Accessories','consu',413.12,274.95,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'P6215EF4CAF-A016','r6215EF4CAF_q16','Bulk shipment',3,1.0,24.0,287.86);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A017','Self-Lubricating Sleeve Set','Seals and Gaskets','consu',349.49,185.87,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'P6215EF4CAF-A017','r6215EF4CAF_q17','Express route',3,1.0,24.0,184.41);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A018','Low-Profile Housing FRP','Maintenance Supplies','consu',235.18,158.81,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'P6215EF4CAF-A018','r6215EF4CAF_q18','Regional lane',6,1.0,24.0,168.35);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A019','High-Torque Bracket Set','Mechanical Components','consu',188.44,107.08,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'P6215EF4CAF-A019','r6215EF4CAF_q19','Bulk shipment',6,1.0,24.0,104.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A020','Heavy-Duty Vessel Housing FRP','Seals and Gaskets','consu',229.72,129.23,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'P6215EF4CAF-A020','r6215EF4CAF_q20','Cross-dock',3,1.0,24.0,125.75);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A021','Tapered Housing FRP','Mechanical Components','consu',262.18,141.14,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'P6215EF4CAF-A021','r6215EF4CAF_q21','Standard delivery',5,1.0,24.0,134.98);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A022','Thermal-Guard Metering Pump','Pneumatic Components','consu',328.67,214.22,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'P6215EF4CAF-A022','r6215EF4CAF_q22','Cross-dock',7,1.0,24.0,220.71);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A023','Compact Sensor Module','Electrical Components','consu',311.92,210.1,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'P6215EF4CAF-A023','r6215EF4CAF_q23','Warehouse direct',6,1.0,24.0,204.91);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A024','Low-Friction Quartz Sleeve Set','Fasteners and Fixings','consu',390.6,203.64,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'P6215EF4CAF-A024','r6215EF4CAF_q24','Cross-dock',4,1.0,24.0,197.14);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A025','Spring-Loaded Cartridge 20in','Power Transmission','consu',196.09,135.68,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'P6215EF4CAF-A025','r6215EF4CAF_q25','Cross-dock',6,1.0,24.0,133.68);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A026','Wide-Body Carbon Cartridge 20in','Electrical Components','consu',406.73,233.86,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'P6215EF4CAF-A026','r6215EF4CAF_q26','Bulk shipment',7,1.0,24.0,236.87);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A027','Rapid-Lock Conductivity Sensor','Electrical Components','consu',381.71,258.36,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'P6215EF4CAF-A027','r6215EF4CAF_q27','Regional lane',6,1.0,24.0,246.55);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A028','Universal Bracket Set','Seals and Gaskets','consu',200.72,139.22,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'P6215EF4CAF-A028','r6215EF4CAF_q28','Local pickup',5,1.0,24.0,148.82);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A029','Lightweight Valve Assembly','Mechanical Components','consu',401.69,258.14,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'P6215EF4CAF-A029','r6215EF4CAF_q29','Local pickup',7,1.0,24.0,275.21);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A030','Threaded Cartridge 5um','Power Transmission','consu',232.39,162.01,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'P6215EF4CAF-A030','r6215EF4CAF_q30','Bulk shipment',5,1.0,24.0,156.68);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A031','Flanged Solenoid Valve Assembly','Pneumatic Components','consu',418.22,259.81,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'P6215EF4CAF-A031','r6215EF4CAF_q31','Local pickup',5,1.0,24.0,276.87);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A032','Cleanroom Solenoid Valve Assembly','Power Transmission','consu',185.17,120.65,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'P6215EF4CAF-A032','r6215EF4CAF_q32','Warehouse direct',8,1.0,24.0,119.35);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A033','Modular Bracket Set','Electrical Components','consu',352.28,184.01,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'P6215EF4CAF-A033','r6215EF4CAF_q33','Local pickup',8,1.0,24.0,183.88);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A034','Snap-Fit Vessel Housing FRP','Seals and Gaskets','consu',225.49,156.13,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'P6215EF4CAF-A034','r6215EF4CAF_q34','Bulk shipment',8,1.0,24.0,162.19);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A035','Food-Grade Cartridge 5um','Mechanical Components','consu',213.41,129.36,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'P6215EF4CAF-A035','r6215EF4CAF_q35','Express route',5,1.0,24.0,131.69);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A036','High-Cycle Solenoid Valve Assembly','Maintenance Supplies','consu',333.54,219.6,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'P6215EF4CAF-A036','r6215EF4CAF_q36','Warehouse direct',6,1.0,24.0,224.98);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A037','Precision Meter Sensor Module','Power Transmission','consu',335.79,228.33,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'P6215EF4CAF-A037','r6215EF4CAF_q37','Scheduled freight',3,1.0,24.0,245.59);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A038','UV-Stable Sleeve Set','Hardware Accessories','consu',291.18,161.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'P6215EF4CAF-A038','r6215EF4CAF_q38','Local pickup',6,1.0,24.0,172.61);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A039','Extended-Life Housing Bracket Set','Industrial Spare Parts','consu',269.21,142.24,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'P6215EF4CAF-A039','r6215EF4CAF_q39','Scheduled freight',5,1.0,24.0,138.33);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A040','Dual-Stage Sensor Module','Fasteners and Fixings','consu',288.98,157.49,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(57,'P6215EF4CAF-A040','r6215EF4CAF_q40','Bulk shipment',7,1.0,24.0,158.51);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A041','Single-Stage Housing Bracket Set','Power Transmission','consu',266.9,167.82,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(58,'P6215EF4CAF-A041','r6215EF4CAF_q41','Scheduled freight',5,1.0,24.0,171.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A042','Anti-Vibration TDS Conductivity Sensor','Industrial Spare Parts','consu',246.81,166.97,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(59,'P6215EF4CAF-A042','r6215EF4CAF_q42','Express route',4,1.0,24.0,159.8);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A043','Premium Sensor Module','Replacement Parts','consu',195.93,127.35,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(60,'P6215EF4CAF-A043','r6215EF4CAF_q43','Express route',7,1.0,24.0,125.95);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A044','Zero-Backlash Sensor Module','Mechanical Components','consu',416.99,282.47,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(61,'P6215EF4CAF-A044','r6215EF4CAF_q44','Standard delivery',7,1.0,24.0,300.23);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A045','Low-Flow Chemical Metering Pump','Maintenance Supplies','consu',247.87,167.05,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(62,'P6215EF4CAF-A045','r6215EF4CAF_q45','Local pickup',8,1.0,24.0,169.31);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A046','Commercial Membrane Element 4x40','Replacement Parts','consu',280.33,189.01,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(63,'P6215EF4CAF-A046','r6215EF4CAF_q46','Scheduled freight',4,1.0,24.0,182.42);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A047','Reinforced Sensor Module','Pneumatic Components','consu',237.13,155.29,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(64,'P6215EF4CAF-A047','r6215EF4CAF_q47','Cross-dock',6,1.0,24.0,166.14);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A048','Metric Cartridge 20in','Seals and Gaskets','consu',275.42,189.55,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(65,'P6215EF4CAF-A048','r6215EF4CAF_q48','Regional lane',6,1.0,24.0,189.44);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A049','Corrosion-Resistant Pump Assembly','Replacement Parts','consu',342.7,241.95,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(66,'P6215EF4CAF-A049','r6215EF4CAF_q49','Regional lane',3,1.0,24.0,238.21);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6215EF4CAF-A050','Low-Temp Gauge 0 100PSI','Replacement Parts','consu',306.08,209.7,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(67,'P6215EF4CAF-A050','r6215EF4CAF_q50','Warehouse direct',4,1.0,24.0,225.01);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'P43E89D45DC-SUB-02','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P43E89D45DC-WTR-ROM-101',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P43E89D45DC-WTR-PVH-102',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'P43E89D45DC-WTR-MSF-003','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P43E89D45DC-SUB-02',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P43E89D45DC-WTR-UVL-104',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P43E89D45DC-WTR-FMS-109',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'P6215EF4CAF-A022','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P6215EF4CAF-A020',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P6215EF4CAF-A047',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'P6215EF4CAF-A023','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'P6215EF4CAF-A050',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'P6215EF4CAF-A036','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P6215EF4CAF-A032',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'P6215EF4CAF-A014','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P6215EF4CAF-A043',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P6215EF4CAF-A039',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'P6215EF4CAF-A020','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'P6215EF4CAF-A016',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'P6215EF4CAF-A043','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P6215EF4CAF-A040',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'P6215EF4CAF-A034','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P6215EF4CAF-A005',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P6215EF4CAF-A046',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'P6215EF4CAF-A016','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P6215EF4CAF-A022',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(11,'P6215EF4CAF-A029','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'P6215EF4CAF-A030',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(12,'P6215EF4CAF-A001','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(12,'P6215EF4CAF-A012',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(12,'P6215EF4CAF-A011',1.0);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P43E89D45DC-WC02','Fabrication Cell 2',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P43E89D45DC-WC03','Precision Bench 3',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P43E89D45DC-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P43E89D45DC-WTR-FMS-109',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P43E89D45DC-WTR-MSF-003',NULL,80.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P43E89D45DC-WTR-PVH-102',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P43E89D45DC-WTR-ROM-101',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P43E89D45DC-WTR-UVL-104',NULL,16.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A001',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A002',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A003',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A004',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A005',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A006',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A007',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A008',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A009',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A010',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A011',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A012',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A013',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A014',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A015',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A016',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A017',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A018',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A019',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A020',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A021',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A022',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A023',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A024',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A025',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A026',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A027',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A028',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A029',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A030',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A031',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A032',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A033',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A034',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A035',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A036',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A037',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A038',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A039',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A040',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A041',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A042',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A043',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A044',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A045',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A046',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A047',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A048',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A049',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6215EF4CAF-A050',NULL,12.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'r43E89D45DC_c01','P43E89D45DC-WTR-MSF-003',16,8,61132.53,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'r43E89D45DC_c02','P43E89D45DC-WTR-MSF-003',20,8,73349.11,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'r43E89D45DC_c03','P43E89D45DC-WTR-MSF-003',17,10,65277.63,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'r43E89D45DC_c04','P43E89D45DC-WTR-MSF-003',16,11,58336.48,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'r43E89D45DC_c05','P43E89D45DC-WTR-MSF-003',14,12,52496.98,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'r43E89D45DC_c06','P43E89D45DC-WTR-MSF-003',20,12,74477.43,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'r43E89D45DC_c07','P43E89D45DC-WTR-MSF-003',19,12,73375.29,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'r43E89D45DC_c08','P43E89D45DC-WTR-MSF-003',14,13,53058.47,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(9,'r43E89D45DC_c09','P43E89D45DC-WTR-MSF-003',17,14,61426.34,NULL);
