-- agentic-labs/erp-bench scenario 2256: Wet Sprinkler System Package
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c01','Atlas Arena','customer',0,137642.85,NULL,NULL,'orders@atlasarena.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c02','Slate Productions','customer',0,123726.74,NULL,NULL,'orders@slateproductions.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c03','Pinnacle Hub','customer',0,101253.86,NULL,NULL,'orders@pinnaclehub.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c04','Terra Chambers','customer',0,93488.19,NULL,NULL,'orders@terrachambers.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c05','Keystone Academy','customer',0,106832.22,NULL,NULL,'orders@keystoneacademy.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c06','Osprey Partners','customer',0,175015.92,NULL,NULL,'orders@ospreypartners.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c07','Mosaic Practice','customer',0,104208.08,NULL,NULL,'orders@mosaicpractice.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c08','Riverdale Alliance','customer',0,173834.08,NULL,NULL,'orders@riverdalealliance.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c09','Ironside Interactive','customer',0,103967.05,NULL,NULL,'orders@ironsideinteractive.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c10','Compass Supply Co','customer',0,113439.87,NULL,NULL,'orders@compasssupplyco.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c11','Ember Office','customer',0,166644.81,NULL,NULL,'orders@emberoffice.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c12','Sterling Collective','customer',0,167168.31,NULL,NULL,'orders@sterlingcollective.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c13','Spire Conservatory','customer',0,125858.26,NULL,NULL,'orders@spireconservatory.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c14','Equinox Systems','customer',0,178291.94,NULL,NULL,'orders@equinoxsystems.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c15','Aurora Designs','customer',0,98059.95,NULL,NULL,'orders@auroradesigns.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c16','Baltic Research','customer',0,136650.68,NULL,NULL,'orders@balticresearch.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c17','Blaze Workshop','customer',0,175433.87,NULL,NULL,'orders@blazeworkshop.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c18','Crown Trading Co','customer',0,132246.91,NULL,NULL,'orders@crowntradingco.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c19','Grove Atelier','customer',0,103473.93,NULL,NULL,'orders@groveatelier.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c20','Cedar Architects','customer',0,122187.0,NULL,NULL,'orders@cedararchitects.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c21','Apex Archive','customer',0,143316.55,NULL,NULL,'orders@apexarchive.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c22','Vertex Institute','customer',0,133900.98,NULL,NULL,'orders@vertexinstitute.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c23','Jade Media','customer',0,101009.95,NULL,NULL,'orders@jademedia.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c24','Noble Pictures','customer',0,109418.23,NULL,NULL,'orders@noblepictures.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c25','Opal Forum','customer',0,160656.92,NULL,NULL,'orders@opalforum.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c26','Baseline Society','customer',0,167406.44,NULL,NULL,'orders@baselinesociety.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c27','Orbital Engineering','customer',0,173404.9,NULL,NULL,'orders@orbitalengineering.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c28','Fairview Clinics','customer',0,176319.95,NULL,NULL,'orders@fairviewclinics.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c29','Aether Studios South','customer',0,164910.64,NULL,NULL,'orders@aetherstudiossouth.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c30','Anvil Cooperative','customer',0,174934.25,NULL,NULL,'orders@anvilcooperative.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c31','Zenith Creative','customer',0,168891.48,NULL,NULL,'orders@zenithcreative.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r44B5187EB7_c32','Cardinal Outfitters','customer',0,177791.83,NULL,NULL,'orders@cardinaloutfitters.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p01','Scion Technologies Field Ops','customer',0,NULL,NULL,NULL,'contact@sciontechnologies.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p02','Alloy Operations Tooling Center','customer',0,NULL,NULL,NULL,'contact@alloyoperations.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p03','Granite Assembly Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@graniteassembly.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p04','Citadel Solutions Tooling Center','customer',0,NULL,NULL,NULL,'contact@citadelsolutions.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p05','Peak Services Quality Lab','customer',0,NULL,NULL,NULL,'contact@peakservices.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p06','Quantum Manufacturing Test Facility','customer',0,NULL,NULL,NULL,'contact@quantummanufacturing.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p07','Canton Services Test Facility','customer',0,NULL,NULL,NULL,'contact@cantonservices.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p08','Forge Production Test Facility','customer',0,NULL,NULL,NULL,'contact@forgeproduction.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p09','Bronze Production Site Logistics','customer',0,NULL,NULL,NULL,'contact@bronzeproduction.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p10','Cobalt Manufacturing R&D Workshop','customer',0,NULL,NULL,NULL,'contact@cobaltmanufacturing.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p11','Lumen Technologies Test Facility','customer',0,NULL,NULL,NULL,'contact@lumentechnologies.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p12','Ivory Production Test Facility','customer',0,NULL,NULL,NULL,'contact@ivoryproduction.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p13','Alpine Industries Tooling Center','customer',0,NULL,NULL,NULL,'contact@alpineindustries.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p14','Oxide Industries R&D Workshop','customer',0,NULL,NULL,NULL,'contact@oxideindustries.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p15','Marble Manufacturing Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@marblemanufacturing.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p16','Stonewall Operations Tooling Center','customer',0,NULL,NULL,NULL,'contact@stonewalloperations.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p17','Brookfield Technologies Prototype Shop','customer',0,NULL,NULL,NULL,'contact@brookfieldtechnologies.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p18','Aegis Industries Prototype Shop','customer',0,NULL,NULL,NULL,'contact@aegisindustries.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p19','Cipher Solutions HQ Procurement','customer',0,NULL,NULL,NULL,'contact@ciphersolutions.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p20','Lance Operations Prototype Shop','customer',0,NULL,NULL,NULL,'contact@lanceoperations.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p21','Coral Assembly Field Ops','customer',0,NULL,NULL,NULL,'contact@coralassembly.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p22','Flint Solutions Prototype Shop','customer',0,NULL,NULL,NULL,'contact@flintsolutions.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p23','Lattice Solutions Tooling Center','customer',0,NULL,NULL,NULL,'contact@latticesolutions.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p24','Nimbus Engineering R&D Workshop','customer',0,NULL,NULL,NULL,'contact@nimbusengineering.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p25','Axis Engineering Field Ops','customer',0,NULL,NULL,NULL,'contact@axisengineering.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p26','Catalyst Fabrication Field Ops','customer',0,NULL,NULL,NULL,'contact@catalystfabrication.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p27','Copper Operations Test Facility','customer',0,NULL,NULL,NULL,'contact@copperoperations.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p28','Borough Technologies Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@boroughtechnologies.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p29','Millbrook Solutions Prototype Shop','customer',0,NULL,NULL,NULL,'contact@millbrooksolutions.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p30','Quartz Engineering Tooling Center','customer',0,NULL,NULL,NULL,'contact@quartzengineering.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p31','Cascade Assembly HQ Procurement','customer',0,NULL,NULL,NULL,'contact@cascadeassembly.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p32','Ironwood Technologies Test Facility','customer',0,NULL,NULL,NULL,'contact@ironwoodtechnologies.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p33','Adjacent Customer 1 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer001.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p34','Adjacent Customer 2 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer002.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p35','Adjacent Customer 3 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer003.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p36','Adjacent Customer 4 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer004.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p37','Adjacent Customer 5 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer005.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p38','Adjacent Customer 6 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer006.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p39','Adjacent Customer 7 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer007.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p40','Adjacent Customer 8 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer008.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p41','Adjacent Customer 9 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer009.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p42','Adjacent Customer 10 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer010.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p43','Adjacent Customer 11 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer011.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p44','Adjacent Customer 12 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer012.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p45','Adjacent Customer 13 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer013.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p46','Adjacent Customer 14 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer014.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p47','Adjacent Customer 15 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer015.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p48','Adjacent Customer 16 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer016.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p49','Adjacent Customer 17 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer017.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0FB70F568D_p50','Adjacent Customer 18 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer018.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r44B5187EB7_q01','Metro Resources','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r44B5187EB7_q02','Eclipse Microfactory','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r44B5187EB7_q03','Circuit Transit','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r44B5187EB7_q04','Ridge Warehousing','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r44B5187EB7_q05','Chrome Importers','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r44B5187EB7_q06','Indigo Sourcing','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r44B5187EB7_q07','Ledger Distribution','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r44B5187EB7_q08','Bayshore Components','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r44B5187EB7_q09','Velocity Exporters','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r44B5187EB7_q10','Solace Haulage','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r44B5187EB7_q11','Bridgeway Assemblies','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r44B5187EB7_q12','Northbridge Networks','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r44B5187EB7_q13','Prism Carriers','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r44B5187EB7_q14','Clearwater Logistics','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r44B5187EB7_q15','Summit Operations','vendor',15,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r44B5187EB7_q16','Dune Procurement','vendor',16,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r44B5187EB7_q17','Drift Industries','vendor',17,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q01','Cosmo Procurement','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q02','Sentinel Carriers','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q03','Spectra Networks','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q04','Monarch Wholesale','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q05','Ashford Parts Co','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q06','Lakewood Networks','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q07','Titan Carriers','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q08','Spark Freight','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q09','Silverline Logistics','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q10','Sierra Resources','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q11','Sapphire Networks','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q12','Evergreen Sourcing','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q13','Arrow Parts Co','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q14','Globe Parts Co','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q15','Crest Wholesale','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q16','Steel Supply','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q17','Haven Resources','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q18','Conduit Parts Co','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q19','Oakmont Trading','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q20','Polar Components','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q21','Stratos Networks','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q22','Redstone Logistics','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q23','Beacon Carriers','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q24','Raven Distribution','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q25','Pacific Distribution','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q26','Horizon Carriers','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q27','Arbor Components','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q28','Pivot Sourcing','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q29','Crestview Distribution','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q30','Garnet Supply','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q31','Trident Transit','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q32','Helix Procurement','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q33','Arc Components','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q34','Echo Logistics','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q35','Thornton Logistics','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q36','Element Carriers','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q37','Vantage Wholesale','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q38','Westfield Procurement','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q39','Gateway Trading','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q40','Skyline Resources','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q41','Hartland Logistics','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q42','Nexus Parts Co','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q43','Flux Parts Co','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q44','Comet Wholesale','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q45','Trellis Parts Co','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q46','Matrix Materials','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q47','Meridian Materials','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q48','Ridgeline Resources','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q49','Onyx Procurement','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0FB70F568D_q50','Iron Trading','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P44B5187EB7-FIR-WSP-001','Wet Sprinkler System Package','Safety Systems','consu',5023.09,2615.38,'buy,manufacture',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'P44B5187EB7-FIR-WSP-001','r44B5187EB7_q01','Priority Shuttle lane (8d transit, 9-201 units)',8,9.0,201.0,3037.32);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'P44B5187EB7-FIR-WSP-001','r44B5187EB7_q02','Express Air lane (6d transit, 3-87 units)',6,3.0,87.0,4866.51);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'P44B5187EB7-FIR-WSP-001','r44B5187EB7_q03','Bulk Container lane (25d transit, 416-429 units)',25,416.0,429.0,1962.97);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'P44B5187EB7-FIR-WSP-001','r44B5187EB7_q04','Bulk Container lane (24d transit, 416-573 units)',24,416.0,573.0,1783.74);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'P44B5187EB7-FIR-WSP-001','r44B5187EB7_q05','Economy Ocean lane (20d transit, 9-19 units)',20,9.0,19.0,2600.65);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'P44B5187EB7-FIR-WSP-001','r44B5187EB7_q06','Regional Cross-Dock lane (11d transit, 4-4 units)',11,4.0,4.0,3266.07);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'P44B5187EB7-FIR-WSP-001','r44B5187EB7_q07','Hybrid Expedite lane (11d transit, 6-6 units)',11,6.0,6.0,3932.18);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P44B5187EB7-SUBA-02','Wet Sprinkler System Package Subassembly A','Safety Systems','consu',1406.47,92.52,'manufacture',NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P44B5187EB7-SUBB-02','Wet Sprinkler System Package Subassembly B','Safety Systems','consu',1406.47,300.43,'manufacture',NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P44B5187EB7-FIR-SHP-101','Sprinkler Head Pendant K5.6','Safety Systems','consu',17.54,7.23,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'P44B5187EB7-FIR-SHP-101','r44B5187EB7_q08','Rapid Works (2d)',2,8.0,1113.0,12.17);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'P44B5187EB7-FIR-SHP-101','r44B5187EB7_q09','Import Consolidator (4d)',4,46.0,99.0,7.23);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'P44B5187EB7-FIR-SHP-101','r44B5187EB7_q10','Domestic Supply (4d)',4,23.0,218.0,9.0);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'P44B5187EB7-FIR-SHP-101','r44B5187EB7_q11','Hybrid Fabricators (4d)',4,20.0,705.0,10.13);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P44B5187EB7-FIR-SHU-102','Sprinkler Head Upright K8.0','Safety Systems','consu',21.59,9.08,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'P44B5187EB7-FIR-SHU-102','r44B5187EB7_q12','Rapid Works (4d)',4,12.0,12.0,12.5);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'P44B5187EB7-FIR-SHU-102','r44B5187EB7_q13','Hybrid Fabricators (4d)',4,10.0,706.0,12.02);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'P44B5187EB7-FIR-SHU-102','r44B5187EB7_q14','Domestic Supply (4d)',4,12.0,1846.0,9.08);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P44B5187EB7-FIR-ACV-103','Alarm Check Valve Assembly 4in','Safety Systems','consu',410.49,228.58,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'P44B5187EB7-FIR-ACV-103','r44B5187EB7_q15','Rapid Works (4d)',4,10.0,74.0,273.17);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'P44B5187EB7-FIR-ACV-103','r44B5187EB7_q16','Domestic Supply (4d)',4,21.0,221.0,228.58);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'P44B5187EB7-FIR-ACV-103','r44B5187EB7_q17','Hybrid Fabricators (4d)',4,16.0,41.0,247.62);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A001','Adjustable Trim 6in','Pneumatic Components','consu',199.9,138.79,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'P0FB70F568D-A001','r0FB70F568D_q01','Warehouse direct',5,1.0,24.0,136.26);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A002','Lightweight Head Pendant K5.6','Maintenance Supplies','consu',199.77,141.84,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'P0FB70F568D-A002','r0FB70F568D_q02','Bulk shipment',7,1.0,24.0,135.52);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A003','Impact-Rated Department Connection Siamese','Replacement Parts','consu',338.74,180.99,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'P0FB70F568D-A003','r0FB70F568D_q03','Warehouse direct',7,1.0,24.0,172.89);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A004','Flanged Pendant K5.6','Mechanical Components','consu',412.83,288.27,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'P0FB70F568D-A004','r0FB70F568D_q04','Cross-dock',5,1.0,24.0,285.07);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A005','Metric Head Upright K8.0','Electrical Components','consu',253.06,139.94,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'P0FB70F568D-A005','r0FB70F568D_q05','Express route',4,1.0,24.0,135.22);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A006','Tapered Signal Trim 6in','Maintenance Supplies','consu',369.92,243.77,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'P0FB70F568D-A006','r0FB70F568D_q06','Express route',8,1.0,24.0,249.67);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A007','Industrial High Pressure','Industrial Spare Parts','consu',280.5,153.87,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'P0FB70F568D-A007','r0FB70F568D_q07','Regional lane',4,1.0,24.0,163.96);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A008','Thermal-Guard Valve 4in','Power Transmission','consu',257.04,183.22,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'P0FB70F568D-A008','r0FB70F568D_q08','Warehouse direct',8,1.0,24.0,192.9);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A009','Premium Valve 4in','Fasteners and Fixings','consu',225.5,124.63,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'P0FB70F568D-A009','r0FB70F568D_q09','Scheduled freight',7,1.0,24.0,129.55);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A010','Low-Flow Valve Assembly 4in','Electrical Components','consu',253.71,158.02,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'P0FB70F568D-A010','r0FB70F568D_q10','Cross-dock',4,1.0,24.0,165.49);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A011','Pressure-Balanced Pressure Switch Supervisory','Maintenance Supplies','consu',405.51,241.23,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'P0FB70F568D-A011','r0FB70F568D_q11','Local pickup',5,1.0,24.0,241.71);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A012','Stainless Valve Assembly 6in','Maintenance Supplies','consu',325.04,217.54,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'P0FB70F568D-A012','r0FB70F568D_q12','Warehouse direct',3,1.0,24.0,222.21);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A013','Zero-Backlash Cylinder 70L','Seals and Gaskets','consu',201.2,135.74,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'P0FB70F568D-A013','r0FB70F568D_q13','Bulk shipment',3,1.0,24.0,137.04);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A014','Single-Stage 45kg High Pressure','Replacement Parts','consu',269.99,171.46,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'P0FB70F568D-A014','r0FB70F568D_q14','Express route',6,1.0,24.0,177.98);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A015','Anti-Vibration Assembly 6in','Maintenance Supplies','consu',414.37,267.93,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'P0FB70F568D-A015','r0FB70F568D_q15','Local pickup',4,1.0,24.0,263.99);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A016','Low-Profile Department Connection Siamese','Power Transmission','consu',346.69,209.0,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'P0FB70F568D-A016','r0FB70F568D_q16','Warehouse direct',5,1.0,24.0,207.75);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A017','Standard Assembly 2in','Hardware Accessories','consu',307.26,179.45,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'P0FB70F568D-A017','r0FB70F568D_q17','Scheduled freight',5,1.0,24.0,177.9);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A018','UV-Stable High Pressure','Electrical Components','consu',205.88,147.15,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'P0FB70F568D-A018','r0FB70F568D_q18','Express route',7,1.0,24.0,145.32);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A019','Rapid-Lock Jockey Controller','Industrial Spare Parts','consu',187.27,126.33,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'P0FB70F568D-A019','r0FB70F568D_q19','Cross-dock',3,1.0,24.0,130.58);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A020','High-Flow Pump Jockey Controller','Maintenance Supplies','consu',229.23,150.99,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'P0FB70F568D-A020','r0FB70F568D_q20','Local pickup',5,1.0,24.0,157.91);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A021','Snap-Fit Signal Trim 6in','Industrial Spare Parts','consu',370.81,230.3,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'P0FB70F568D-A021','r0FB70F568D_q21','Bulk shipment',4,1.0,24.0,223.21);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A022','Cold-Rolled Pressure Switch Supervisory','Power Transmission','consu',293.24,205.99,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'P0FB70F568D-A022','r0FB70F568D_q22','Warehouse direct',3,1.0,24.0,212.79);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A023','Threaded Valve Assembly 6in','Power Transmission','consu',327.16,227.28,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'P0FB70F568D-A023','r0FB70F568D_q23','Cross-dock',3,1.0,24.0,228.08);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A024','Double-Row Pressure Switch Supervisory','Power Transmission','consu',223.87,128.29,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'P0FB70F568D-A024','r0FB70F568D_q24','Cross-dock',3,1.0,24.0,129.01);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A025','Dual-Stage Switch Supervisory','Seals and Gaskets','consu',377.2,241.71,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'P0FB70F568D-A025','r0FB70F568D_q25','Regional lane',7,1.0,24.0,245.4);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A026','Commercial Department Connection Siamese','Electrical Components','consu',402.87,239.4,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'P0FB70F568D-A026','r0FB70F568D_q26','Express route',7,1.0,24.0,242.15);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A027','Precision Connection Siamese','Seals and Gaskets','consu',282.8,169.1,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'P0FB70F568D-A027','r0FB70F568D_q27','Express route',7,1.0,24.0,166.28);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A028','Economy Switch Assembly 2in','Hardware Accessories','consu',417.28,284.73,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'P0FB70F568D-A028','r0FB70F568D_q28','Bulk shipment',4,1.0,24.0,290.27);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A029','High-Cycle Pendant K5.6','Replacement Parts','consu',362.56,237.77,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'P0FB70F568D-A029','r0FB70F568D_q29','Regional lane',7,1.0,24.0,241.96);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A030','Food-Grade Assembly 6in','Power Transmission','consu',303.36,161.79,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'P0FB70F568D-A030','r0FB70F568D_q30','Warehouse direct',4,1.0,24.0,166.79);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A031','Powder-Coated Valve 4in','Power Transmission','consu',255.75,178.88,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'P0FB70F568D-A031','r0FB70F568D_q31','Cross-dock',6,1.0,24.0,180.75);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A032','Hardened Valve Assembly 6in','Mechanical Components','consu',198.09,121.28,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'P0FB70F568D-A032','r0FB70F568D_q32','Warehouse direct',3,1.0,24.0,123.03);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A033','Quick-Release Assembly 6in','Mechanical Components','consu',387.87,226.99,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'P0FB70F568D-A033','r0FB70F568D_q33','Warehouse direct',5,1.0,24.0,240.06);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A034','Non-Magnetic Connection Siamese','Hardware Accessories','consu',354.82,229.91,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'P0FB70F568D-A034','r0FB70F568D_q34','Regional lane',8,1.0,24.0,237.74);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A035','Wide-Body Connection Siamese','Seals and Gaskets','consu',211.59,149.32,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'P0FB70F568D-A035','r0FB70F568D_q35','Cross-dock',4,1.0,24.0,152.81);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A036','Low-Noise Head Upright K8.0','Seals and Gaskets','consu',276.8,169.88,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'P0FB70F568D-A036','r0FB70F568D_q36','Bulk shipment',8,1.0,24.0,162.36);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A037','Anodized Valve Assembly 4in','Replacement Parts','consu',341.12,217.77,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'P0FB70F568D-A037','r0FB70F568D_q37','Express route',8,1.0,24.0,234.69);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A038','Reinforced Cylinder 70L','Replacement Parts','consu',236.09,139.87,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'P0FB70F568D-A038','r0FB70F568D_q38','Regional lane',6,1.0,24.0,149.49);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A039','Spring-Loaded Pendant K5.6','Seals and Gaskets','consu',258.24,183.93,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'P0FB70F568D-A039','r0FB70F568D_q39','Scheduled freight',7,1.0,24.0,176.31);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A040','Self-Lubricating Pressure Switch Supervisory','Industrial Spare Parts','consu',205.65,125.62,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(57,'P0FB70F568D-A040','r0FB70F568D_q40','Cross-dock',6,1.0,24.0,132.81);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A041','Cleanroom Pressure Switch Supervisory','Maintenance Supplies','consu',284.17,151.15,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(58,'P0FB70F568D-A041','r0FB70F568D_q41','Express route',8,1.0,24.0,159.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A042','Sealed Upright K8.0','Electrical Components','consu',318.21,199.59,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(59,'P0FB70F568D-A042','r0FB70F568D_q42','Regional lane',5,1.0,24.0,202.68);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A043','Modular Trim 6in','Maintenance Supplies','consu',205.52,110.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(60,'P0FB70F568D-A043','r0FB70F568D_q43','Bulk shipment',4,1.0,24.0,107.12);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A044','Universal Valve 4in','Industrial Spare Parts','consu',345.83,186.46,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(61,'P0FB70F568D-A044','r0FB70F568D_q44','Scheduled freight',7,1.0,24.0,186.39);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A045','Low-Friction Assembly 4in','Fasteners and Fixings','consu',400.61,267.79,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(62,'P0FB70F568D-A045','r0FB70F568D_q45','Scheduled freight',7,1.0,24.0,263.29);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A046','Medical-Grade Switch Supervisory','Replacement Parts','consu',364.46,255.2,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(63,'P0FB70F568D-A046','r0FB70F568D_q46','Express route',7,1.0,24.0,255.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A047','High-Torque Assembly 4in','Fasteners and Fixings','consu',211.15,120.54,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(64,'P0FB70F568D-A047','r0FB70F568D_q47','Standard delivery',8,1.0,24.0,125.76);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A048','Heat-Treated Valve 4in','Fasteners and Fixings','consu',291.52,164.35,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(65,'P0FB70F568D-A048','r0FB70F568D_q48','Cross-dock',7,1.0,24.0,161.57);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A049','High-Performance Department Connection Siamese','Fasteners and Fixings','consu',211.58,143.24,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(66,'P0FB70F568D-A049','r0FB70F568D_q49','Local pickup',5,1.0,24.0,150.24);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0FB70F568D-A050','Corrosion-Resistant Pump Jockey Controller','Replacement Parts','consu',348.94,205.75,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(67,'P0FB70F568D-A050','r0FB70F568D_q50','Express route',3,1.0,24.0,198.3);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'P44B5187EB7-SUBA-02','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P44B5187EB7-FIR-SHP-101',4.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P44B5187EB7-FIR-SHU-102',5.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'P44B5187EB7-SUBB-02','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P44B5187EB7-FIR-SHP-101',4.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P44B5187EB7-FIR-ACV-103',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'P44B5187EB7-FIR-WSP-001','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P44B5187EB7-SUBA-02',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P44B5187EB7-SUBB-02',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'P0FB70F568D-A027','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'P0FB70F568D-A033',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'P0FB70F568D-A031','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P0FB70F568D-A033',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P0FB70F568D-A050',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'P0FB70F568D-A011','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P0FB70F568D-A012',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'P0FB70F568D-A029','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'P0FB70F568D-A004',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'P0FB70F568D-A019',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'P0FB70F568D-A020','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P0FB70F568D-A049',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'P0FB70F568D-A050','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P0FB70F568D-A037',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P0FB70F568D-A019',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'P0FB70F568D-A039','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P0FB70F568D-A049',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(11,'P0FB70F568D-A049','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'P0FB70F568D-A017',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(12,'P0FB70F568D-A004','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(12,'P0FB70F568D-A030',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(13,'P0FB70F568D-A044','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(13,'P0FB70F568D-A050',3.0);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P44B5187EB7-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P44B5187EB7-WC02','Fabrication Cell 2',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P44B5187EB7-WC03','Precision Bench 3',0,0,NULL,NULL);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P44B5187EB7-FIR-ACV-103',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P44B5187EB7-FIR-SHP-101',NULL,40.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P44B5187EB7-FIR-SHU-102',NULL,44.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P44B5187EB7-FIR-WSP-001',NULL,333.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A001',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A002',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A003',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A004',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A005',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A006',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A007',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A008',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A009',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A010',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A011',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A012',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A013',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A014',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A015',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A016',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A017',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A018',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A019',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A020',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A021',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A022',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A023',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A024',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A025',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A026',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A027',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A028',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A029',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A030',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A031',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A032',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A033',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A034',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A035',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A036',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A037',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A038',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A039',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A040',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A041',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A042',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A043',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A044',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A045',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A046',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A047',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A048',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A049',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0FB70F568D-A050',NULL,8.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'r44B5187EB7_c01','P44B5187EB7-FIR-WSP-001',26,8,137642.85,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'r44B5187EB7_c02','P44B5187EB7-FIR-WSP-001',24,8,123726.74,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'r44B5187EB7_c03','P44B5187EB7-FIR-WSP-001',18,8,101253.86,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'r44B5187EB7_c04','P44B5187EB7-FIR-WSP-001',18,8,93488.19,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'r44B5187EB7_c05','P44B5187EB7-FIR-WSP-001',20,8,106832.22,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'r44B5187EB7_c06','P44B5187EB7-FIR-WSP-001',32,9,175015.92,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'r44B5187EB7_c07','P44B5187EB7-FIR-WSP-001',19,9,104208.08,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'r44B5187EB7_c08','P44B5187EB7-FIR-WSP-001',32,9,173834.08,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(9,'r44B5187EB7_c09','P44B5187EB7-FIR-WSP-001',20,9,103967.05,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(10,'r44B5187EB7_c10','P44B5187EB7-FIR-WSP-001',21,9,113439.87,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(11,'r44B5187EB7_c11','P44B5187EB7-FIR-WSP-001',32,9,166644.81,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(12,'r44B5187EB7_c12','P44B5187EB7-FIR-WSP-001',31,9,167168.31,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(13,'r44B5187EB7_c13','P44B5187EB7-FIR-WSP-001',23,10,125858.26,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(14,'r44B5187EB7_c14','P44B5187EB7-FIR-WSP-001',32,10,178291.94,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(15,'r44B5187EB7_c15','P44B5187EB7-FIR-WSP-001',18,10,98059.95,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(16,'r44B5187EB7_c16','P44B5187EB7-FIR-WSP-001',26,10,136650.68,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(17,'r44B5187EB7_c17','P44B5187EB7-FIR-WSP-001',32,10,175433.87,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(18,'r44B5187EB7_c18','P44B5187EB7-FIR-WSP-001',25,11,132246.91,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(19,'r44B5187EB7_c19','P44B5187EB7-FIR-WSP-001',19,11,103473.93,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(20,'r44B5187EB7_c20','P44B5187EB7-FIR-WSP-001',22,11,122187.0,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(21,'r44B5187EB7_c21','P44B5187EB7-FIR-WSP-001',26,11,143316.55,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(22,'r44B5187EB7_c22','P44B5187EB7-FIR-WSP-001',24,11,133900.98,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(23,'r44B5187EB7_c23','P44B5187EB7-FIR-WSP-001',19,12,101009.95,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(24,'r44B5187EB7_c24','P44B5187EB7-FIR-WSP-001',20,12,109418.23,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(25,'r44B5187EB7_c25','P44B5187EB7-FIR-WSP-001',29,12,160656.92,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(26,'r44B5187EB7_c26','P44B5187EB7-FIR-WSP-001',32,12,167406.44,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(27,'r44B5187EB7_c27','P44B5187EB7-FIR-WSP-001',32,12,173404.9,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(28,'r44B5187EB7_c28','P44B5187EB7-FIR-WSP-001',32,13,176319.95,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(29,'r44B5187EB7_c29','P44B5187EB7-FIR-WSP-001',32,13,164910.64,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(30,'r44B5187EB7_c30','P44B5187EB7-FIR-WSP-001',32,13,174934.25,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(31,'r44B5187EB7_c31','P44B5187EB7-FIR-WSP-001',32,13,168891.48,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(32,'r44B5187EB7_c32','P44B5187EB7-FIR-WSP-001',32,13,177791.83,'draft');
