-- agentic-labs/erp-bench scenario 2155: Low-Pressure Blower Package 25HP
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c01','Lakewood Trust','customer',0,213656.73,NULL,NULL,'orders@lakewoodtrust.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c02','Iron Academy','customer',0,196738.88,NULL,NULL,'orders@ironacademy.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c03','Spire Ventures','customer',0,272203.2,NULL,NULL,'orders@spireventures.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c04','Matrix Chambers','customer',0,221172.82,NULL,NULL,'orders@matrixchambers.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c05','Horizon Society','customer',0,205888.55,NULL,NULL,'orders@horizonsociety.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c06','Monarch Group','customer',0,212538.37,NULL,NULL,'orders@monarchgroup.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c07','Sterling Pavilion','customer',0,274831.94,NULL,NULL,'orders@sterlingpavilion.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c08','Trellis Atelier','customer',0,190625.39,NULL,NULL,'orders@trellisatelier.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c09','Beacon Cooperative','customer',0,284076.96,NULL,NULL,'orders@beaconcooperative.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c10','Westfield Research','customer',0,278213.13,NULL,NULL,'orders@westfieldresearch.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c11','Aether Theater','customer',0,223961.62,NULL,NULL,'orders@aethertheater.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c12','Velocity Analytics','customer',0,196585.33,NULL,NULL,'orders@velocityanalytics.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c13','Chrome Practice','customer',0,205091.44,NULL,NULL,'orders@chromepractice.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c14','Dune Studios South','customer',0,187286.19,NULL,NULL,'orders@dunestudiossouth.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c15','Thornton Designs','customer',0,217711.45,NULL,NULL,'orders@thorntondesigns.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c16','Fairview Observatory','customer',0,324307.22,NULL,NULL,'orders@fairviewobservatory.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c17','Crestview Media','customer',0,201422.2,NULL,NULL,'orders@crestviewmedia.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c18','Lumen Collective','customer',0,189907.05,NULL,NULL,'orders@lumencollective.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c19','Canton Greenhouse','customer',0,192633.25,NULL,NULL,'orders@cantongreenhouse.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c20','Helix Arena','customer',0,250131.27,NULL,NULL,'orders@helixarena.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c21','Bridgeway Clinics','customer',0,187713.99,NULL,NULL,'orders@bridgewayclinics.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c22','Element Institute','customer',0,236789.25,NULL,NULL,'orders@elementinstitute.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c23','Blaze Brands','customer',0,216749.66,NULL,NULL,'orders@blazebrands.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c24','Polar Publishing','customer',0,203353.22,NULL,NULL,'orders@polarpublishing.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c25','Noble Trading Co','customer',0,254909.18,NULL,NULL,'orders@nobletradingco.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c26','Evergreen Studios','customer',0,191015.21,NULL,NULL,'orders@evergreenstudios.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c27','Circuit Collective East','customer',0,323047.71,NULL,NULL,'orders@circuitcollectiveeast.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c28','Baltic Consortium','customer',0,252163.98,NULL,NULL,'orders@balticconsortium.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rB995C24EB6_c29','Hartland Reserve','customer',0,215524.38,NULL,NULL,'orders@hartlandreserve.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p01','Ironwood Manufacturing Test Facility','customer',0,NULL,NULL,NULL,'contact@ironwoodmanufacturing.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p02','Anvil Technologies Test Facility','customer',0,NULL,NULL,NULL,'contact@anviltechnologies.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p03','Northbridge Fabrication Tooling Center','customer',0,NULL,NULL,NULL,'contact@northbridgefabrication.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p04','Clearwater Services R&D Workshop','customer',0,NULL,NULL,NULL,'contact@clearwaterservices.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p05','Cosmo Fabrication R&D Workshop','customer',0,NULL,NULL,NULL,'contact@cosmofabrication.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p06','Summit Production Tooling Center','customer',0,NULL,NULL,NULL,'contact@summitproduction.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p07','Skyline Assembly Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@skylineassembly.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p08','Flint Operations Quality Lab','customer',0,NULL,NULL,NULL,'contact@flintoperations.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p09','Orbital Operations Site Logistics','customer',0,NULL,NULL,NULL,'contact@orbitaloperations.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p10','Haven Solutions Tooling Center','customer',0,NULL,NULL,NULL,'contact@havensolutions.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p11','Conduit Solutions Tooling Center','customer',0,NULL,NULL,NULL,'contact@conduitsolutions.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p12','Onyx Technologies Field Ops','customer',0,NULL,NULL,NULL,'contact@onyxtechnologies.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p13','Pinnacle Solutions Field Ops','customer',0,NULL,NULL,NULL,'contact@pinnaclesolutions.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p14','Sentinel Fabrication Tooling Center','customer',0,NULL,NULL,NULL,'contact@sentinelfabrication.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p15','Gateway Manufacturing Quality Lab','customer',0,NULL,NULL,NULL,'contact@gatewaymanufacturing.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p16','Crown Operations R&D Workshop','customer',0,NULL,NULL,NULL,'contact@crownoperations.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p17','Compass Engineering Field Ops','customer',0,NULL,NULL,NULL,'contact@compassengineering.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p18','Ridgeline Services Site Logistics','customer',0,NULL,NULL,NULL,'contact@ridgelineservices.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p19','Trident Operations Site Logistics','customer',0,NULL,NULL,NULL,'contact@tridentoperations.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p20','Brookfield Technologies R&D Workshop','customer',0,NULL,NULL,NULL,'contact@brookfieldtechnologies.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p21','Keystone Fabrication Tooling Center','customer',0,NULL,NULL,NULL,'contact@keystonefabrication.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p22','Aurora Solutions Field Ops','customer',0,NULL,NULL,NULL,'contact@aurorasolutions.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p23','Baseline Fabrication HQ Procurement','customer',0,NULL,NULL,NULL,'contact@baselinefabrication.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p24','Forge Manufacturing Field Ops','customer',0,NULL,NULL,NULL,'contact@forgemanufacturing.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p25','Aegis Technologies Site Logistics','customer',0,NULL,NULL,NULL,'contact@aegistechnologies.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p26','Prism Industries Tooling Center','customer',0,NULL,NULL,NULL,'contact@prismindustries.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p27','Ironside Production Field Ops','customer',0,NULL,NULL,NULL,'contact@ironsideproduction.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p28','Comet Industries Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@cometindustries.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p29','Bayshore Fabrication Site Logistics','customer',0,NULL,NULL,NULL,'contact@bayshorefabrication.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p30','Sapphire Fabrication Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@sapphirefabrication.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p31','Cipher Operations Prototype Shop','customer',0,NULL,NULL,NULL,'contact@cipheroperations.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p32','Mosaic Solutions Quality Lab','customer',0,NULL,NULL,NULL,'contact@mosaicsolutions.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p33','Quantum Fabrication Quality Lab','customer',0,NULL,NULL,NULL,'contact@quantumfabrication.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p34','Ridge Operations Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@ridgeoperations.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p35','Quartz Industries Prototype Shop','customer',0,NULL,NULL,NULL,'contact@quartzindustries.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p36','Adjacent Customer 1 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer001.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p37','Adjacent Customer 2 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer002.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p38','Adjacent Customer 3 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer003.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p39','Adjacent Customer 4 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer004.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p40','Adjacent Customer 5 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer005.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p41','Adjacent Customer 6 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer006.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p42','Adjacent Customer 7 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer007.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p43','Adjacent Customer 8 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer008.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p44','Adjacent Customer 9 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer009.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p45','Adjacent Customer 10 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer010.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p46','Adjacent Customer 11 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer011.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p47','Adjacent Customer 12 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer012.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p48','Adjacent Customer 13 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer013.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p49','Adjacent Customer 14 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer014.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0DC9DDA4F8_p50','Adjacent Customer 15 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer015.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB995C24EB6_q01','Slate Solutions','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB995C24EB6_q02','Cascade Transport','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB995C24EB6_q03','Garnet Supply','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB995C24EB6_q04','Ember Sourcing','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB995C24EB6_q05','Drift Wholesalers','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB995C24EB6_q06','Oxide Logistics','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB995C24EB6_q07','Ledger Networks','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB995C24EB6_q08','Arbor Materials','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB995C24EB6_q09','Indigo Partners','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB995C24EB6_q10','Metro Integrators','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB995C24EB6_q11','Meridian Assemblies','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB995C24EB6_q12','Equinox Merchants','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB995C24EB6_q13','Terra Movers','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB995C24EB6_q14','Spark Fabrication','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB995C24EB6_q15','Bronze Distribution','vendor',15,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB995C24EB6_q16','Titan Components','vendor',16,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rB995C24EB6_q17','Axis Microfactory','vendor',17,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q01','Grove Components','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q02','Solace Procurement','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q03','Raven Distribution','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q04','Redstone Networks','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q05','Arrow Freight','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q06','Ashford Sourcing','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q07','Marble Logistics','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q08','Opal Components','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q09','Jade Components','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q10','Eclipse Resources','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q11','Riverdale Resources','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q12','Silverline Networks','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q13','Steel Wholesale','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q14','Vertex Sourcing','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q15','Copper Resources','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q16','Borough Wholesale','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q17','Spectra Materials','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q18','Lattice Logistics','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q19','Citadel Sourcing','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q20','Apex Parts Co','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q21','Flux Carriers','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q22','Stonewall Procurement','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q23','Oakmont Wholesale','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q24','Crest Distribution','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q25','Osprey Networks','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q26','Pacific Materials','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q27','Alpine Materials','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q28','Nexus Carriers','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q29','Cobalt Transit','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q30','Nimbus Logistics','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q31','Lance Wholesale','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q32','Cardinal Supply','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q33','Cedar Wholesale','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q34','Echo Procurement','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q35','Millbrook Supply','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q36','Globe Freight','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q37','Scion Parts Co','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q38','Alloy Resources','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q39','Peak Resources','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q40','Stratos Trading','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q41','Atlas Sourcing','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q42','Pivot Materials','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q43','Coral Networks','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q44','Vantage Distribution','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q45','Sierra Trading','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q46','Arc Sourcing','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q47','Granite Distribution','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q48','Ivory Materials','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q49','Zenith Carriers','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0DC9DDA4F8_q50','Catalyst Supply','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PB995C24EB6-CMP-LPB-010','Low-Pressure Blower Package 25HP','Industrial Equipment','consu',10186.39,5536.08,'buy,manufacture',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'PB995C24EB6-CMP-LPB-010','rB995C24EB6_q01','Priority Shuttle lane (8d transit, 6-92 units)',8,6.0,92.0,7007.62);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'PB995C24EB6-CMP-LPB-010','rB995C24EB6_q02','Express Air lane (5d transit, 2-4 units)',5,2.0,4.0,10597.65);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'PB995C24EB6-CMP-LPB-010','rB995C24EB6_q03','Bulk Container lane (24d transit, 304-304 units)',24,304.0,304.0,3676.22);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'PB995C24EB6-CMP-LPB-010','rB995C24EB6_q04','Economy Ocean lane (19d transit, 10-15 units)',19,10.0,15.0,4869.89);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'PB995C24EB6-CMP-LPB-010','rB995C24EB6_q05','Microfactory Build-to-Order lane (7d transit, 5-34 units)',7,5.0,34.0,8862.32);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'PB995C24EB6-CMP-LPB-010','rB995C24EB6_q06','Air Charter lane (6d transit, 1-161 units)',6,1.0,161.0,11883.41);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'PB995C24EB6-CMP-LPB-010','rB995C24EB6_q07','Regional Cross-Dock lane (11d transit, 5-8 units)',11,5.0,8.0,5951.02);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PB995C24EB6-SUBA-01','Low-Pressure Blower Package 25HP Subassembly A','Industrial Equipment','consu',2852.19,220.79,'manufacture',NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PB995C24EB6-CMP-EDM-102','Electric Drive Motor 50HP TEFC','Industrial Equipment','consu',2823.5,1363.94,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'PB995C24EB6-CMP-EDM-102','rB995C24EB6_q08','Rapid Works (2d)',2,6.0,68.0,1821.11);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'PB995C24EB6-CMP-EDM-102','rB995C24EB6_q09','Hybrid Fabricators (6d)',6,12.0,72.0,2037.98);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'PB995C24EB6-CMP-EDM-102','rB995C24EB6_q10','Import Consolidator (6d)',6,43.0,54.0,1363.94);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PB995C24EB6-SUBB-02','Low-Pressure Blower Package 25HP Subassembly B','Industrial Equipment','consu',2852.19,200.72,'manufacture',NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PB995C24EB6-CMP-AOS-103','Air-Oil Separator Element','Industrial Equipment','consu',178.18,68.3,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'PB995C24EB6-CMP-AOS-103','rB995C24EB6_q11','Rapid Works (3d)',3,8.0,42.0,107.88);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'PB995C24EB6-CMP-AOS-103','rB995C24EB6_q12','Domestic Supply (3d)',3,25.0,69.0,87.77);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'PB995C24EB6-CMP-AOS-103','rB995C24EB6_q13','Import Consolidator (3d)',3,24.0,295.0,68.3);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PB995C24EB6-CMP-OFC-105','Oil Filter Cartridge','Industrial Equipment','consu',36.09,12.64,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'PB995C24EB6-CMP-OFC-105','rB995C24EB6_q14','Rapid Works (3d)',3,11.0,17.0,19.8);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'PB995C24EB6-CMP-OFC-105','rB995C24EB6_q15','Hybrid Fabricators (3d)',3,15.0,103.0,16.09);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'PB995C24EB6-CMP-OFC-105','rB995C24EB6_q16','Import Consolidator (3d)',3,34.0,201.0,12.64);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'PB995C24EB6-CMP-OFC-105','rB995C24EB6_q17','Domestic Supply (3d)',3,12.0,59.0,14.25);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A001','Sealed Receiver Tank 240Gal','Power Transmission','consu',228.87,133.07,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'P0DC9DDA4F8-A001','r0DC9DDA4F8_q01','Express route',7,1.0,24.0,127.12);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A002','Cleanroom Inverter Drive Unit','Electrical Components','consu',360.47,212.28,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'P0DC9DDA4F8-A002','r0DC9DDA4F8_q02','Express route',3,1.0,24.0,206.0);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A003','High-Cycle 50HP TEFC','Electrical Components','consu',338.51,214.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'P0DC9DDA4F8-A003','r0DC9DDA4F8_q03','Warehouse direct',6,1.0,24.0,230.66);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A004','Compact Screw Element 50HP','Power Transmission','consu',315.6,214.27,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'P0DC9DDA4F8-A004','r0DC9DDA4F8_q04','Regional lane',4,1.0,24.0,206.44);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A005','Food-Grade Heat Exchanger','Hardware Accessories','consu',307.4,180.44,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'P0DC9DDA4F8-A005','r0DC9DDA4F8_q05','Regional lane',4,1.0,24.0,181.06);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A006','Adjustable Aftercooler Heat Exchanger','Mechanical Components','consu',370.78,212.39,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'P0DC9DDA4F8-A006','r0DC9DDA4F8_q06','Express route',6,1.0,24.0,206.32);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A007','Low-Profile Heat Exchanger','Power Transmission','consu',313.41,199.99,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'P0DC9DDA4F8-A007','r0DC9DDA4F8_q07','Regional lane',4,1.0,24.0,211.02);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A008','Powder-Coated Blow Off Valve','Hardware Accessories','consu',358.81,218.16,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'P0DC9DDA4F8-A008','r0DC9DDA4F8_q08','Cross-dock',6,1.0,24.0,208.98);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A009','Double-Row Oil Separator Element','Maintenance Supplies','consu',335.6,187.86,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'P0DC9DDA4F8-A009','r0DC9DDA4F8_q09','Cross-dock',4,1.0,24.0,194.23);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A010','Narrow-Body Inverter Drive Unit','Industrial Spare Parts','consu',260.09,185.56,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'P0DC9DDA4F8-A010','r0DC9DDA4F8_q10','Local pickup',8,1.0,24.0,195.73);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A011','Premium Heat Exchanger','Replacement Parts','consu',220.86,126.03,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'P0DC9DDA4F8-A011','r0DC9DDA4F8_q11','Bulk shipment',7,1.0,24.0,120.96);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A012','Anti-Vibration Oil Filter Cartridge','Industrial Spare Parts','consu',195.36,128.14,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'P0DC9DDA4F8-A012','r0DC9DDA4F8_q12','Local pickup',3,1.0,24.0,127.97);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A013','Anodized Heat Exchanger','Fasteners and Fixings','consu',221.37,158.94,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'P0DC9DDA4F8-A013','r0DC9DDA4F8_q13','Bulk shipment',5,1.0,24.0,158.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A014','Spring-Loaded Inverter Drive Unit','Maintenance Supplies','consu',268.79,169.76,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'P0DC9DDA4F8-A014','r0DC9DDA4F8_q14','Warehouse direct',3,1.0,24.0,164.12);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A015','Low-Friction Oil Filter Cartridge','Fasteners and Fixings','consu',415.3,222.04,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'P0DC9DDA4F8-A015','r0DC9DDA4F8_q15','Local pickup',8,1.0,24.0,232.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A016','UV-Stable Off Valve','Fasteners and Fixings','consu',249.72,150.16,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'P0DC9DDA4F8-A016','r0DC9DDA4F8_q16','Scheduled freight',3,1.0,24.0,144.84);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A017','Heavy-Duty Oil Separator Element','Maintenance Supplies','consu',393.09,228.09,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'P0DC9DDA4F8-A017','r0DC9DDA4F8_q17','Express route',7,1.0,24.0,234.03);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A018','Corrosion-Resistant Minimum Pressure Valve','Industrial Spare Parts','consu',226.26,145.1,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'P0DC9DDA4F8-A018','r0DC9DDA4F8_q18','Cross-dock',3,1.0,24.0,152.86);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A019','Universal 50HP TEFC','Power Transmission','consu',210.41,145.53,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'P0DC9DDA4F8-A019','r0DC9DDA4F8_q19','Local pickup',7,1.0,24.0,150.62);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A020','High-Flow Screw Element 50HP','Electrical Components','consu',245.49,136.6,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'P0DC9DDA4F8-A020','r0DC9DDA4F8_q20','Local pickup',4,1.0,24.0,142.56);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A021','High-Torque Valve Assembly','Electrical Components','consu',274.17,175.96,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'P0DC9DDA4F8-A021','r0DC9DDA4F8_q21','Scheduled freight',8,1.0,24.0,187.55);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A022','Reinforced Tank 240Gal','Industrial Spare Parts','consu',394.84,281.1,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'P0DC9DDA4F8-A022','r0DC9DDA4F8_q22','Standard delivery',3,1.0,24.0,286.26);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A023','Extended-Life Valve Assembly','Seals and Gaskets','consu',294.01,181.69,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'P0DC9DDA4F8-A023','r0DC9DDA4F8_q23','Bulk shipment',5,1.0,24.0,189.52);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A024','Wide-Body Receiver Tank 240Gal','Maintenance Supplies','consu',292.59,209.11,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'P0DC9DDA4F8-A024','r0DC9DDA4F8_q24','Regional lane',3,1.0,24.0,219.3);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A025','Metric Off Valve','Hardware Accessories','consu',245.92,174.31,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'P0DC9DDA4F8-A025','r0DC9DDA4F8_q25','Express route',4,1.0,24.0,187.7);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A026','Precision Pressure Valve','Mechanical Components','consu',190.83,137.24,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'P0DC9DDA4F8-A026','r0DC9DDA4F8_q26','Regional lane',8,1.0,24.0,145.24);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A027','Non-Magnetic Heat Exchanger','Maintenance Supplies','consu',407.42,260.05,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'P0DC9DDA4F8-A027','r0DC9DDA4F8_q27','Local pickup',4,1.0,24.0,267.69);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A028','Low-Temp Screw Element 50HP','Fasteners and Fixings','consu',312.91,184.32,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'P0DC9DDA4F8-A028','r0DC9DDA4F8_q28','Cross-dock',4,1.0,24.0,192.86);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A029','Commercial Off Valve','Replacement Parts','consu',297.77,172.11,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'P0DC9DDA4F8-A029','r0DC9DDA4F8_q29','Bulk shipment',4,1.0,24.0,184.53);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A030','Pressure-Balanced Heat Exchanger','Electrical Components','consu',195.81,102.38,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'P0DC9DDA4F8-A030','r0DC9DDA4F8_q30','Regional lane',5,1.0,24.0,102.76);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A031','Modular Inlet Valve Assembly','Power Transmission','consu',250.45,154.84,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'P0DC9DDA4F8-A031','r0DC9DDA4F8_q31','Cross-dock',6,1.0,24.0,159.56);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A032','Weatherproof Separator Element','Fasteners and Fixings','consu',308.14,219.75,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'P0DC9DDA4F8-A032','r0DC9DDA4F8_q32','Bulk shipment',8,1.0,24.0,232.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A033','Industrial Pressure Valve','Mechanical Components','consu',355.25,208.02,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'P0DC9DDA4F8-A033','r0DC9DDA4F8_q33','Local pickup',5,1.0,24.0,216.03);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A034','Economy Pressure Valve','Fasteners and Fixings','consu',217.89,147.33,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'P0DC9DDA4F8-A034','r0DC9DDA4F8_q34','Express route',3,1.0,24.0,156.91);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A035','High-Temp Drive Unit','Replacement Parts','consu',221.7,119.94,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'P0DC9DDA4F8-A035','r0DC9DDA4F8_q35','Cross-dock',6,1.0,24.0,118.69);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A036','Self-Lubricating Minimum Pressure Valve','Industrial Spare Parts','consu',289.06,165.61,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'P0DC9DDA4F8-A036','r0DC9DDA4F8_q36','Bulk shipment',5,1.0,24.0,167.8);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A037','Rapid-Lock Filter Cartridge','Mechanical Components','consu',394.81,262.02,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'P0DC9DDA4F8-A037','r0DC9DDA4F8_q37','Warehouse direct',5,1.0,24.0,266.39);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A038','Impact-Rated Receiver Tank 240Gal','Replacement Parts','consu',266.57,177.6,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'P0DC9DDA4F8-A038','r0DC9DDA4F8_q38','Warehouse direct',5,1.0,24.0,179.88);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A039','Standard Air Filter Element','Hardware Accessories','consu',363.97,233.4,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'P0DC9DDA4F8-A039','r0DC9DDA4F8_q39','Standard delivery',4,1.0,24.0,227.84);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A040','Threaded Oil Separator Element','Seals and Gaskets','consu',213.47,117.51,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(57,'P0DC9DDA4F8-A040','r0DC9DDA4F8_q40','Bulk shipment',3,1.0,24.0,113.86);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A041','Thermal-Guard Filter Element','Maintenance Supplies','consu',322.69,226.31,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(58,'P0DC9DDA4F8-A041','r0DC9DDA4F8_q41','Regional lane',5,1.0,24.0,240.75);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A042','Stainless Filter Element','Electrical Components','consu',255.27,152.45,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(59,'P0DC9DDA4F8-A042','r0DC9DDA4F8_q42','Express route',4,1.0,24.0,156.87);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A043','Single-Stage Aftercooler Heat Exchanger','Electrical Components','consu',191.91,119.04,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(60,'P0DC9DDA4F8-A043','r0DC9DDA4F8_q43','Express route',6,1.0,24.0,121.03);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A044','Lightweight Oil Separator Element','Maintenance Supplies','consu',265.63,165.81,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(61,'P0DC9DDA4F8-A044','r0DC9DDA4F8_q44','Cross-dock',3,1.0,24.0,176.19);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A045','High-Performance 50HP TEFC','Pneumatic Components','consu',228.56,159.61,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(62,'P0DC9DDA4F8-A045','r0DC9DDA4F8_q45','Standard delivery',7,1.0,24.0,160.84);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A046','Tapered Heat Exchanger','Fasteners and Fixings','consu',417.18,271.3,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(63,'P0DC9DDA4F8-A046','r0DC9DDA4F8_q46','Bulk shipment',8,1.0,24.0,263.18);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A047','Hardened Controller Intellisys Module','Hardware Accessories','consu',270.88,156.83,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(64,'P0DC9DDA4F8-A047','r0DC9DDA4F8_q47','Local pickup',7,1.0,24.0,162.26);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A048','Snap-Fit Heat Exchanger','Pneumatic Components','consu',286.92,150.57,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(65,'P0DC9DDA4F8-A048','r0DC9DDA4F8_q48','Cross-dock',7,1.0,24.0,154.22);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A049','Low-Noise Element 50HP','Pneumatic Components','consu',311.77,178.34,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(66,'P0DC9DDA4F8-A049','r0DC9DDA4F8_q49','Local pickup',4,1.0,24.0,184.62);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0DC9DDA4F8-A050','Heat-Treated 50HP TEFC','Seals and Gaskets','consu',330.96,229.21,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(67,'P0DC9DDA4F8-A050','r0DC9DDA4F8_q50','Scheduled freight',4,1.0,24.0,245.16);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'PB995C24EB6-SUBB-02','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PB995C24EB6-CMP-AOS-103',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PB995C24EB6-CMP-OFC-105',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'PB995C24EB6-SUBA-01','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PB995C24EB6-SUBB-02',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'PB995C24EB6-CMP-LPB-010','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'PB995C24EB6-SUBA-01',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'PB995C24EB6-CMP-EDM-102',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'P0DC9DDA4F8-A027','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'P0DC9DDA4F8-A049',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'P0DC9DDA4F8-A024','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P0DC9DDA4F8-A045',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'P0DC9DDA4F8-A023','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P0DC9DDA4F8-A007',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P0DC9DDA4F8-A006',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'P0DC9DDA4F8-A043','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'P0DC9DDA4F8-A033',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'P0DC9DDA4F8-A009','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P0DC9DDA4F8-A048',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P0DC9DDA4F8-A036',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'P0DC9DDA4F8-A025','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P0DC9DDA4F8-A035',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'P0DC9DDA4F8-A016','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P0DC9DDA4F8-A033',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P0DC9DDA4F8-A022',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(11,'P0DC9DDA4F8-A045','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'P0DC9DDA4F8-A033',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(12,'P0DC9DDA4F8-A006','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(12,'P0DC9DDA4F8-A042',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(13,'P0DC9DDA4F8-A002','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(13,'P0DC9DDA4F8-A040',1.0);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PB995C24EB6-WC03','Precision Bench 3',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PB995C24EB6-WC02','Fabrication Cell 2',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PB995C24EB6-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PB995C24EB6-CMP-AOS-103',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PB995C24EB6-CMP-EDM-102',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PB995C24EB6-CMP-LPB-010',NULL,244.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PB995C24EB6-CMP-OFC-105',NULL,27.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A001',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A002',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A003',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A004',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A005',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A006',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A007',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A008',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A009',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A010',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A011',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A012',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A013',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A014',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A015',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A016',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A017',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A018',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A019',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A020',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A021',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A022',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A023',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A024',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A025',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A026',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A027',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A028',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A029',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A030',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A031',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A032',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A033',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A034',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A035',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A036',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A037',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A038',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A039',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A040',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A041',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A042',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A043',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A044',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A045',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A046',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A047',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A048',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A049',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0DC9DDA4F8-A050',NULL,6.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'rB995C24EB6_c01','PB995C24EB6-CMP-LPB-010',20,8,213656.73,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'rB995C24EB6_c02','PB995C24EB6-CMP-LPB-010',18,8,196738.88,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'rB995C24EB6_c03','PB995C24EB6-CMP-LPB-010',24,8,272203.2,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'rB995C24EB6_c04','PB995C24EB6-CMP-LPB-010',20,8,221172.82,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'rB995C24EB6_c05','PB995C24EB6-CMP-LPB-010',19,8,205888.55,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'rB995C24EB6_c06','PB995C24EB6-CMP-LPB-010',19,8,212538.37,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'rB995C24EB6_c07','PB995C24EB6-CMP-LPB-010',26,8,274831.94,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'rB995C24EB6_c08','PB995C24EB6-CMP-LPB-010',18,8,190625.39,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(9,'rB995C24EB6_c09','PB995C24EB6-CMP-LPB-010',25,9,284076.96,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(10,'rB995C24EB6_c10','PB995C24EB6-CMP-LPB-010',26,9,278213.13,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(11,'rB995C24EB6_c11','PB995C24EB6-CMP-LPB-010',20,9,223961.62,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(12,'rB995C24EB6_c12','PB995C24EB6-CMP-LPB-010',18,9,196585.33,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(13,'rB995C24EB6_c13','PB995C24EB6-CMP-LPB-010',19,10,205091.44,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(14,'rB995C24EB6_c14','PB995C24EB6-CMP-LPB-010',18,10,187286.19,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(15,'rB995C24EB6_c15','PB995C24EB6-CMP-LPB-010',20,10,217711.45,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(16,'rB995C24EB6_c16','PB995C24EB6-CMP-LPB-010',31,10,324307.22,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(17,'rB995C24EB6_c17','PB995C24EB6-CMP-LPB-010',18,11,201422.2,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(18,'rB995C24EB6_c18','PB995C24EB6-CMP-LPB-010',18,11,189907.05,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(19,'rB995C24EB6_c19','PB995C24EB6-CMP-LPB-010',18,11,192633.25,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(20,'rB995C24EB6_c20','PB995C24EB6-CMP-LPB-010',24,11,250131.27,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(21,'rB995C24EB6_c21','PB995C24EB6-CMP-LPB-010',18,11,187713.99,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(22,'rB995C24EB6_c22','PB995C24EB6-CMP-LPB-010',22,12,236789.25,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(23,'rB995C24EB6_c23','PB995C24EB6-CMP-LPB-010',19,12,216749.66,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(24,'rB995C24EB6_c24','PB995C24EB6-CMP-LPB-010',18,12,203353.22,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(25,'rB995C24EB6_c25','PB995C24EB6-CMP-LPB-010',23,12,254909.18,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(26,'rB995C24EB6_c26','PB995C24EB6-CMP-LPB-010',18,13,191015.21,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(27,'rB995C24EB6_c27','PB995C24EB6-CMP-LPB-010',30,13,323047.71,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(28,'rB995C24EB6_c28','PB995C24EB6-CMP-LPB-010',23,13,252163.98,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(29,'rB995C24EB6_c29','PB995C24EB6-CMP-LPB-010',19,13,215524.38,NULL);
