-- agentic-labs/erp-bench scenario 2085: Vertical Form-Fill-Seal Machine
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA349395F8D_c01','Crestview Architects','customer',0,516938.11,NULL,NULL,'orders@crestviewarchitects.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA349395F8D_c02','Silverline Cooperative','customer',0,738979.72,NULL,NULL,'orders@silverlinecooperative.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA349395F8D_c03','Crown Partners','customer',0,633044.38,NULL,NULL,'orders@crownpartners.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA349395F8D_c04','Spire Gallery','customer',0,574213.53,NULL,NULL,'orders@spiregallery.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA349395F8D_c05','Cedar Group','customer',0,960249.34,NULL,NULL,'orders@cedargroup.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA349395F8D_c06','Circuit Technologies','customer',0,513208.71,NULL,NULL,'orders@circuittechnologies.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA349395F8D_c07','Lumen Pictures','customer',0,792587.94,NULL,NULL,'orders@lumenpictures.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA349395F8D_c08','Evergreen Lyceum','customer',0,899169.91,NULL,NULL,'orders@evergreenlyceum.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p01','Stratos Operations R&D Workshop','customer',0,NULL,NULL,NULL,'contact@stratosoperations.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p02','Ledger Industries Tooling Center','customer',0,NULL,NULL,NULL,'contact@ledgerindustries.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p03','Ironwood Manufacturing Prototype Shop','customer',0,NULL,NULL,NULL,'contact@ironwoodmanufacturing.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p04','Drift Technologies Field Ops','customer',0,NULL,NULL,NULL,'contact@drifttechnologies.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p05','Matrix Production Site Logistics','customer',0,NULL,NULL,NULL,'contact@matrixproduction.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p06','Cascade Industries HQ Procurement','customer',0,NULL,NULL,NULL,'contact@cascadeindustries.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p07','Anvil Solutions Prototype Shop','customer',0,NULL,NULL,NULL,'contact@anvilsolutions.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p08','Bronze Services Field Ops','customer',0,NULL,NULL,NULL,'contact@bronzeservices.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p09','Riverdale Operations Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@riverdaleoperations.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p10','Westfield Technologies R&D Workshop','customer',0,NULL,NULL,NULL,'contact@westfieldtechnologies.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p11','Globe Fabrication Field Ops','customer',0,NULL,NULL,NULL,'contact@globefabrication.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p12','Onyx Services Site Logistics','customer',0,NULL,NULL,NULL,'contact@onyxservices.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p13','Velocity Operations Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@velocityoperations.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p14','Indigo Production Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@indigoproduction.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p15','Titan Industries Prototype Shop','customer',0,NULL,NULL,NULL,'contact@titanindustries.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p16','Hartland Fabrication Prototype Shop','customer',0,NULL,NULL,NULL,'contact@hartlandfabrication.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p17','Clearwater Assembly Field Ops','customer',0,NULL,NULL,NULL,'contact@clearwaterassembly.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p18','Polar Engineering HQ Procurement','customer',0,NULL,NULL,NULL,'contact@polarengineering.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p19','Slate Production Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@slateproduction.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p20','Orbital Operations Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@orbitaloperations.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p21','Noble Solutions Field Ops','customer',0,NULL,NULL,NULL,'contact@noblesolutions.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p22','Citadel Industries Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@citadelindustries.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p23','Vertex Solutions Tooling Center','customer',0,NULL,NULL,NULL,'contact@vertexsolutions.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p24','Vantage Manufacturing Prototype Shop','customer',0,NULL,NULL,NULL,'contact@vantagemanufacturing.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p25','Ember Fabrication Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@emberfabrication.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p26','Equinox Technologies Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@equinoxtechnologies.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p27','Aether Technologies Field Ops','customer',0,NULL,NULL,NULL,'contact@aethertechnologies.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p28','Compass Services Tooling Center','customer',0,NULL,NULL,NULL,'contact@compassservices.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p29','Meridian Technologies Quality Lab','customer',0,NULL,NULL,NULL,'contact@meridiantechnologies.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p30','Helix Assembly Quality Lab','customer',0,NULL,NULL,NULL,'contact@helixassembly.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p31','Baltic Solutions Test Facility','customer',0,NULL,NULL,NULL,'contact@balticsolutions.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p32','Cosmo Manufacturing R&D Workshop','customer',0,NULL,NULL,NULL,'contact@cosmomanufacturing.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p33','Bayshore Industries Test Facility','customer',0,NULL,NULL,NULL,'contact@bayshoreindustries.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p34','Lakewood Manufacturing Prototype Shop','customer',0,NULL,NULL,NULL,'contact@lakewoodmanufacturing.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p35','Sapphire Manufacturing Test Facility','customer',0,NULL,NULL,NULL,'contact@sapphiremanufacturing.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p36','Sierra Industries Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@sierraindustries.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p37','Alpine Solutions Prototype Shop','customer',0,NULL,NULL,NULL,'contact@alpinesolutions.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p38','Skyline Fabrication Test Facility','customer',0,NULL,NULL,NULL,'contact@skylinefabrication.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p39','Zenith Assembly R&D Workshop','customer',0,NULL,NULL,NULL,'contact@zenithassembly.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p40','Aegis Assembly Quality Lab','customer',0,NULL,NULL,NULL,'contact@aegisassembly.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p41','Oakmont Services Site Logistics','customer',0,NULL,NULL,NULL,'contact@oakmontservices.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p42','Comet Operations Field Ops','customer',0,NULL,NULL,NULL,'contact@cometoperations.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p43','Oxide Production R&D Workshop','customer',0,NULL,NULL,NULL,'contact@oxideproduction.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p44','Gateway Operations Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@gatewayoperations.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p45','Spectra Manufacturing Site Logistics','customer',0,NULL,NULL,NULL,'contact@spectramanufacturing.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p46','Adjacent Customer 1 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer001.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p47','Adjacent Customer 2 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer002.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p48','Adjacent Customer 3 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer003.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p49','Adjacent Customer 4 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer004.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF82AEB7700_p50','Adjacent Customer 5 Division','customer',0,NULL,NULL,NULL,'contact@adjacentcustomer005.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q01','Arc Conveyance','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q02','Brookfield Assemblies','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q03','Iron Transport','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q04','Nimbus Consolidators','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q05','Pinnacle Warehousing','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q06','Trellis Importers','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q07','Horizon Movers','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q08','Aurora Procurement','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q09','Marble Partners','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q10','Summit Depot','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q11','Pivot Packagers','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q12','Echo Freight','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q13','Catalyst Solutions','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q14','Lattice Distribution','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q15','Canton Supply','vendor',15,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q16','Ridgeline Forwarders','vendor',16,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q17','Coral Sourcing','vendor',17,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q18','Thornton Manufacturing','vendor',18,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q19','Element Resources','vendor',19,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q20','Flux Exporters','vendor',20,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q21','Quartz Integrators','vendor',21,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q22','Fairview Networks','vendor',22,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q23','Grove Fulfillment','vendor',23,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q24','Opal Operations','vendor',24,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q25','Alloy Fabrication','vendor',25,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q26','Ivory Transit','vendor',26,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q27','Ashford Warehouse','vendor',27,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA349395F8D_q28','Sentinel Logistics','vendor',28,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q01','Cobalt Networks','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q02','Mosaic Trading','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q03','Nexus Parts Co','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q04','Peak Materials','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q05','Flint Carriers','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q06','Forge Resources','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q07','Keystone Wholesale','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q08','Apex Carriers','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q09','Arrow Materials','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q10','Millbrook Trading','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q11','Steel Resources','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q12','Granite Trading','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q13','Haven Sourcing','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q14','Cipher Materials','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q15','Ridge Wholesale','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q16','Raven Supply','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q17','Lance Resources','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q18','Sterling Transit','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q19','Prism Procurement','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q20','Terra Logistics','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q21','Cardinal Transit','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q22','Jade Components','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q23','Trident Parts Co','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q24','Quantum Parts Co','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q25','Blaze Distribution','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q26','Northbridge Resources','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q27','Eclipse Resources','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q28','Metro Distribution','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q29','Chrome Sourcing','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q30','Dune Sourcing','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q31','Spark Parts Co','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q32','Baseline Supply','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q33','Borough Resources','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q34','Crest Transit','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q35','Conduit Wholesale','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q36','Arbor Freight','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q37','Axis Carriers','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q38','Copper Freight','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q39','Solace Materials','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q40','Pacific Logistics','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q41','Beacon Networks','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q42','Garnet Logistics','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q43','Redstone Sourcing','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q44','Scion Freight','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q45','Bridgeway Trading','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q46','Ironside Freight','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q47','Monarch Wholesale','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q48','Osprey Materials','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q49','Atlas Carriers','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF82AEB7700_q50','Stonewall Parts Co','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA349395F8D-PKG-VFF-006','Vertical Form-Fill-Seal Machine','Material Handling Equipment','consu',32982.62,18246.99,'buy,manufacture',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'PA349395F8D-PKG-VFF-006','rA349395F8D_q01','Priority Shuttle lane (8d transit, 6-14 units)',8,6.0,14.0,21824.52);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'PA349395F8D-PKG-VFF-006','rA349395F8D_q02','Express Air lane (7d transit, 1-1 units)',7,1.0,1.0,26563.38);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'PA349395F8D-PKG-VFF-006','rA349395F8D_q03','Bulk Container lane (20d transit, 80-85 units)',20,80.0,85.0,12272.19);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'PA349395F8D-PKG-VFF-006','rA349395F8D_q04','Microfactory Build-to-Order lane (6d transit, 2-29 units)',6,2.0,29.0,26578.74);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'PA349395F8D-PKG-VFF-006','rA349395F8D_q05','Bulk Container lane (20d transit, 80-91 units)',20,80.0,91.0,14415.7);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA349395F8D-PKG-GAN-112','Glue Applicator Nozzle Set','Material Handling Equipment','consu',66.36,27.15,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'PA349395F8D-PKG-GAN-112','rA349395F8D_q06','Rapid Works (2d)',2,12.0,28.0,45.09);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'PA349395F8D-PKG-GAN-112','rA349395F8D_q07','Hybrid Fabricators (2d)',2,20.0,28.0,34.25);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'PA349395F8D-PKG-GAN-112','rA349395F8D_q08','Import Consolidator (2d)',2,39.0,212.0,27.15);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA349395F8D-PKG-LDA-114','Label Dispenser Assembly','Material Handling Equipment','consu',272.77,129.51,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'PA349395F8D-PKG-LDA-114','rA349395F8D_q09','Rapid Works (2d)',2,7.0,30.0,200.21);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'PA349395F8D-PKG-LDA-114','rA349395F8D_q10','Hybrid Fabricators (2d)',2,18.0,33.0,148.47);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'PA349395F8D-PKG-LDA-114','rA349395F8D_q11','Domestic Supply (2d)',2,26.0,39.0,156.23);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'PA349395F8D-PKG-LDA-114','rA349395F8D_q12','Import Consolidator (2d)',2,31.0,59.0,129.51);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA349395F8D-PKG-SHM-115','Strapping Head Module','Material Handling Equipment','consu',390.97,154.27,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'PA349395F8D-PKG-SHM-115','rA349395F8D_q13','Rapid Works (2d)',2,12.0,18.0,213.79);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'PA349395F8D-PKG-SHM-115','rA349395F8D_q14','Domestic Supply (2d)',2,21.0,44.0,192.63);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'PA349395F8D-PKG-SHM-115','rA349395F8D_q15','Import Consolidator (2d)',2,36.0,45.0,154.27);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA349395F8D-PKG-EWA-116','Encoder Wheel Assembly','Material Handling Equipment','consu',116.63,50.68,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'PA349395F8D-PKG-EWA-116','rA349395F8D_q16','Rapid Works (2d)',2,6.0,14.0,71.62);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'PA349395F8D-PKG-EWA-116','rA349395F8D_q17','Hybrid Fabricators (2d)',2,9.0,10.0,55.12);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'PA349395F8D-PKG-EWA-116','rA349395F8D_q18','Domestic Supply (2d)',2,27.0,47.0,50.68);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA349395F8D-PKG-QCD-117','Quick-Change Die Set','Material Handling Equipment','consu',247.34,105.08,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'PA349395F8D-PKG-QCD-117','rA349395F8D_q19','Rapid Works (2d)',2,12.0,90.0,169.85);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'PA349395F8D-PKG-QCD-117','rA349395F8D_q20','Domestic Supply (2d)',2,21.0,95.0,135.4);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'PA349395F8D-PKG-QCD-117','rA349395F8D_q21','Hybrid Fabricators (2d)',2,8.0,38.0,126.75);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'PA349395F8D-PKG-QCD-117','rA349395F8D_q22','Import Consolidator (2d)',2,32.0,110.0,105.08);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA349395F8D-PKG-RDA-121','Reject Diverter Arm','Material Handling Equipment','consu',198.68,98.62,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'PA349395F8D-PKG-RDA-121','rA349395F8D_q23','Rapid Works (2d)',2,5.0,9.0,130.52);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'PA349395F8D-PKG-RDA-121','rA349395F8D_q24','Import Consolidator (2d)',2,38.0,42.0,98.62);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'PA349395F8D-PKG-RDA-121','rA349395F8D_q25','Domestic Supply (2d)',2,25.0,26.0,116.27);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA349395F8D-PKG-FTA-123','Forming Tube Assembly','Material Handling Equipment','consu',273.63,122.74,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'PA349395F8D-PKG-FTA-123','rA349395F8D_q26','Rapid Works (2d)',2,10.0,36.0,221.44);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'PA349395F8D-PKG-FTA-123','rA349395F8D_q27','Hybrid Fabricators (2d)',2,20.0,53.0,181.75);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'PA349395F8D-PKG-FTA-123','rA349395F8D_q28','Import Consolidator (2d)',2,48.0,61.0,122.74);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A001','Low-Noise Section 12in','Seals and Gaskets','consu',404.16,268.43,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'PF82AEB7700-A001','rF82AEB7700_q01','Regional lane',8,1.0,24.0,287.81);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A002','Tapered Panel 10in','Fasteners and Fixings','consu',412.08,234.11,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'PF82AEB7700-A002','rF82AEB7700_q02','Regional lane',7,1.0,24.0,249.16);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A003','Powder-Coated Cylinder Assembly','Fasteners and Fixings','consu',204.26,126.94,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'PF82AEB7700-A003','rF82AEB7700_q03','Express route',3,1.0,24.0,126.97);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A004','Self-Lubricating Pneumatic Cylinder Assembly','Industrial Spare Parts','consu',400.38,274.93,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'PF82AEB7700-A004','rF82AEB7700_q04','Regional lane',8,1.0,24.0,293.82);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A005','High-Flow Belt Section 12in','Power Transmission','consu',348.48,250.43,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'PF82AEB7700-A005','rF82AEB7700_q05','Warehouse direct',4,1.0,24.0,261.92);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A006','Heat-Treated Pump Assembly','Hardware Accessories','consu',274.14,180.02,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'PF82AEB7700-A006','rF82AEB7700_q06','Scheduled freight',6,1.0,24.0,189.5);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A007','Low-Profile HMI Panel 10in','Mechanical Components','consu',191.76,120.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'PF82AEB7700-A007','rF82AEB7700_q07','Regional lane',8,1.0,24.0,120.37);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A008','Pressure-Balanced Motor 2kW','Maintenance Supplies','consu',301.44,171.14,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'PF82AEB7700-A008','rF82AEB7700_q08','Cross-dock',8,1.0,24.0,171.1);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A009','Anodized Roll Holder Spindle','Pneumatic Components','consu',192.6,121.71,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'PF82AEB7700-A009','rF82AEB7700_q09','Scheduled freight',5,1.0,24.0,128.22);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A010','Cleanroom Applicator Nozzle Set','Replacement Parts','consu',251.28,139.47,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'PF82AEB7700-A010','rF82AEB7700_q10','Warehouse direct',5,1.0,24.0,141.58);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A011','Adjustable Jaw Assembly','Mechanical Components','consu',383.02,208.27,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'PF82AEB7700-A011','rF82AEB7700_q11','Warehouse direct',3,1.0,24.0,205.22);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A012','Spring-Loaded Applicator Nozzle Set','Maintenance Supplies','consu',201.83,137.88,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'PF82AEB7700-A012','rF82AEB7700_q12','Cross-dock',3,1.0,24.0,142.28);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A013','Double-Row Motor 2kW','Industrial Spare Parts','consu',225.74,133.9,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'PF82AEB7700-A013','rF82AEB7700_q13','Regional lane',7,1.0,24.0,136.78);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A014','Precision Holder Spindle','Maintenance Supplies','consu',290.88,176.45,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'PF82AEB7700-A014','rF82AEB7700_q14','Regional lane',5,1.0,24.0,180.0);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A015','Dual-Stage Sealing Jaw Assembly','Seals and Gaskets','consu',292.38,200.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'PF82AEB7700-A015','rF82AEB7700_q15','Warehouse direct',5,1.0,24.0,190.59);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A016','Threaded Light Curtain Pair','Replacement Parts','consu',205.29,109.63,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'PF82AEB7700-A016','rF82AEB7700_q16','Standard delivery',8,1.0,24.0,113.67);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A017','Wide-Body Pulley Kit','Replacement Parts','consu',400.86,248.47,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'PF82AEB7700-A017','rF82AEB7700_q17','Regional lane',4,1.0,24.0,259.48);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A018','Stainless Belt Section 12in','Maintenance Supplies','consu',370.64,203.87,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'PF82AEB7700-A018','rF82AEB7700_q18','Bulk shipment',8,1.0,24.0,199.4);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A019','Modular Photoelectric Sensor Set','Maintenance Supplies','consu',343.63,193.44,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'PF82AEB7700-A019','rF82AEB7700_q19','Express route',6,1.0,24.0,202.97);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A020','Hardened Section 12in','Pneumatic Components','consu',282.19,188.6,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'PF82AEB7700-A020','rF82AEB7700_q20','Bulk shipment',5,1.0,24.0,198.86);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A021','Universal Roll Holder Spindle','Maintenance Supplies','consu',357.54,219.87,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'PF82AEB7700-A021','rF82AEB7700_q21','Scheduled freight',4,1.0,24.0,219.75);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A022','Impact-Rated Belt Section 12in','Maintenance Supplies','consu',230.27,152.55,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'PF82AEB7700-A022','rF82AEB7700_q22','Warehouse direct',4,1.0,24.0,150.54);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A023','Narrow-Body Applicator Nozzle Set','Hardware Accessories','consu',185.68,114.45,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'PF82AEB7700-A023','rF82AEB7700_q23','Bulk shipment',8,1.0,24.0,116.61);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A024','UV-Stable Pneumatic Cylinder Assembly','Replacement Parts','consu',396.82,206.89,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'PF82AEB7700-A024','rF82AEB7700_q24','Cross-dock',7,1.0,24.0,215.17);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A025','Rapid-Lock HMI Panel 10in','Power Transmission','consu',391.85,238.96,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'PF82AEB7700-A025','rF82AEB7700_q25','Bulk shipment',8,1.0,24.0,255.61);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A026','Low-Flow and Pulley Kit','Electrical Components','consu',299.44,164.53,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'PF82AEB7700-A026','rF82AEB7700_q26','Standard delivery',3,1.0,24.0,161.37);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A027','Heavy-Duty Photoelectric Sensor Set','Maintenance Supplies','consu',224.7,140.73,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'PF82AEB7700-A027','rF82AEB7700_q27','Standard delivery',7,1.0,24.0,135.27);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A028','Extended-Life Jaw Assembly','Industrial Spare Parts','consu',244.26,171.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'PF82AEB7700-A028','rF82AEB7700_q28','Standard delivery',5,1.0,24.0,172.08);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A029','Medical-Grade Controller Module','Mechanical Components','consu',303.56,188.76,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(57,'PF82AEB7700-A029','rF82AEB7700_q29','Warehouse direct',6,1.0,24.0,193.87);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A030','High-Torque PLC Controller Module','Industrial Spare Parts','consu',228.79,134.75,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(58,'PF82AEB7700-A030','rF82AEB7700_q30','Scheduled freight',7,1.0,24.0,134.26);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A031','Low-Temp Photoelectric Sensor Set','Mechanical Components','consu',192.28,117.21,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(59,'PF82AEB7700-A031','rF82AEB7700_q31','Warehouse direct',8,1.0,24.0,122.92);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A032','Corrosion-Resistant Section 12in','Electrical Components','consu',265.39,180.87,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(60,'PF82AEB7700-A032','rF82AEB7700_q32','Express route',6,1.0,24.0,177.46);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A033','High-Performance HMI Panel 10in','Fasteners and Fixings','consu',346.71,239.9,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(61,'PF82AEB7700-A033','rF82AEB7700_q33','Express route',4,1.0,24.0,253.51);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A034','Metric Vacuum Pump Assembly','Industrial Spare Parts','consu',293.75,159.6,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(62,'PF82AEB7700-A034','rF82AEB7700_q34','Regional lane',8,1.0,24.0,169.44);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A035','Flanged Jaw Assembly','Replacement Parts','consu',234.37,141.18,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(63,'PF82AEB7700-A035','rF82AEB7700_q35','Bulk shipment',5,1.0,24.0,140.42);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A036','Snap-Fit Drive Motor 2kW','Electrical Components','consu',261.46,149.92,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(64,'PF82AEB7700-A036','rF82AEB7700_q36','Scheduled freight',6,1.0,24.0,147.04);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A037','High-Cycle and Pulley Kit','Pneumatic Components','consu',199.13,129.34,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(65,'PF82AEB7700-A037','rF82AEB7700_q37','Scheduled freight',6,1.0,24.0,133.46);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A038','Compact Light Curtain Pair','Seals and Gaskets','consu',339.78,243.4,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(66,'PF82AEB7700-A038','rF82AEB7700_q38','Regional lane',4,1.0,24.0,251.4);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A039','Cold-Rolled Sealing Jaw Assembly','Industrial Spare Parts','consu',323.53,216.35,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(67,'PF82AEB7700-A039','rF82AEB7700_q39','Bulk shipment',8,1.0,24.0,211.04);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A040','High-Temp Controller Module','Power Transmission','consu',217.53,133.71,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(68,'PF82AEB7700-A040','rF82AEB7700_q40','Bulk shipment',7,1.0,24.0,129.01);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A041','Commercial and Pulley Kit','Seals and Gaskets','consu',332.7,173.91,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(69,'PF82AEB7700-A041','rF82AEB7700_q41','Scheduled freight',6,1.0,24.0,178.07);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A042','Single-Stage Sensor Set','Power Transmission','consu',264.0,155.13,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(70,'PF82AEB7700-A042','rF82AEB7700_q42','Standard delivery',7,1.0,24.0,147.87);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A043','Zero-Backlash Vacuum Pump Assembly','Power Transmission','consu',277.96,165.43,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(71,'PF82AEB7700-A043','rF82AEB7700_q43','Express route',7,1.0,24.0,176.66);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A044','Sealed Curtain Pair','Mechanical Components','consu',213.5,151.76,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(72,'PF82AEB7700-A044','rF82AEB7700_q44','Bulk shipment',6,1.0,24.0,153.39);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A045','Reinforced Drive Motor 2kW','Replacement Parts','consu',354.02,226.96,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(73,'PF82AEB7700-A045','rF82AEB7700_q45','Standard delivery',8,1.0,24.0,238.94);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A046','Economy Cylinder Assembly','Pneumatic Components','consu',245.51,174.79,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(74,'PF82AEB7700-A046','rF82AEB7700_q46','Bulk shipment',7,1.0,24.0,173.54);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A047','Thermal-Guard Belt Section 12in','Power Transmission','consu',325.67,203.45,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(75,'PF82AEB7700-A047','rF82AEB7700_q47','Local pickup',6,1.0,24.0,218.08);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A048','Quick-Release Photoelectric Sensor Set','Fasteners and Fixings','consu',321.62,199.9,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(76,'PF82AEB7700-A048','rF82AEB7700_q48','Regional lane',3,1.0,24.0,204.31);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A049','Anti-Vibration Section 12in','Mechanical Components','consu',347.86,188.81,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(77,'PF82AEB7700-A049','rF82AEB7700_q49','Bulk shipment',4,1.0,24.0,179.71);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF82AEB7700-A050','Food-Grade Curtain Pair','Replacement Parts','consu',403.72,274.16,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(78,'PF82AEB7700-A050','rF82AEB7700_q50','Express route',3,1.0,24.0,282.68);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'PA349395F8D-PKG-VFF-006','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PA349395F8D-PKG-GAN-112',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PA349395F8D-PKG-LDA-114',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PA349395F8D-PKG-SHM-115',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PA349395F8D-PKG-EWA-116',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PA349395F8D-PKG-QCD-117',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PA349395F8D-PKG-RDA-121',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PA349395F8D-PKG-FTA-123',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'PF82AEB7700-A015','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PF82AEB7700-A043',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'PF82AEB7700-A037','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'PF82AEB7700-A006',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'PF82AEB7700-A031',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'PF82AEB7700-A013','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'PF82AEB7700-A049',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'PF82AEB7700-A030',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'PF82AEB7700-A044','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'PF82AEB7700-A035',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'PF82AEB7700-A005','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'PF82AEB7700-A018',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'PF82AEB7700-A038','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'PF82AEB7700-A050',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'PF82AEB7700-A033','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'PF82AEB7700-A025',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'PF82AEB7700-A048',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'PF82AEB7700-A049','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'PF82AEB7700-A030',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'PF82AEB7700-A039',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'PF82AEB7700-A020','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'PF82AEB7700-A036',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(11,'PF82AEB7700-A026','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'PF82AEB7700-A027',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'PF82AEB7700-A001',3.0);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PA349395F8D-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PA349395F8D-WC02','Fabrication Cell 2',0,0,NULL,NULL);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA349395F8D-PKG-EWA-116',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA349395F8D-PKG-FTA-123',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA349395F8D-PKG-GAN-112',NULL,18.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA349395F8D-PKG-LDA-114',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA349395F8D-PKG-QCD-117',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA349395F8D-PKG-RDA-121',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA349395F8D-PKG-SHM-115',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA349395F8D-PKG-VFF-006',NULL,71.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A001',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A002',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A003',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A004',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A005',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A006',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A007',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A008',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A009',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A010',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A011',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A012',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A013',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A014',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A015',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A016',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A017',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A018',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A019',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A020',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A021',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A022',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A023',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A024',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A025',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A026',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A027',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A028',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A029',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A030',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A031',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A032',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A033',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A034',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A035',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A036',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A037',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A038',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A039',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A040',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A041',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A042',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A043',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A044',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A045',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A046',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A047',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A048',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A049',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF82AEB7700-A050',NULL,4.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'rA349395F8D_c01','PA349395F8D-PKG-VFF-006',15,8,516938.11,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'rA349395F8D_c02','PA349395F8D-PKG-VFF-006',21,9,738979.72,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'rA349395F8D_c03','PA349395F8D-PKG-VFF-006',18,10,633044.38,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'rA349395F8D_c04','PA349395F8D-PKG-VFF-006',17,11,574213.53,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'rA349395F8D_c05','PA349395F8D-PKG-VFF-006',26,12,960249.34,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'rA349395F8D_c06','PA349395F8D-PKG-VFF-006',15,13,513208.71,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'rA349395F8D_c07','PA349395F8D-PKG-VFF-006',22,13,792587.94,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'rA349395F8D_c08','PA349395F8D-PKG-VFF-006',26,14,899169.91,NULL);
