-- agentic-labs/erp-bench scenario 2015: Co-Location Cage Rack 42U
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r14661E7E55_c01','Beacon Observatory','customer',0,9393.79,NULL,NULL,'orders@beaconobservatory.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r14661E7E55_c02','Riverdale Trading Co','customer',0,19120.66,NULL,NULL,'orders@riverdaletradingco.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r14661E7E55_c03','Titan Holdings','customer',0,9480.42,NULL,NULL,'orders@titanholdings.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r14661E7E55_c04','Cascade Technologies','customer',0,12809.9,NULL,NULL,'orders@cascadetechnologies.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p01','Orbital Technologies Test Facility','customer',0,NULL,NULL,NULL,'contact@orbitaltechnologies.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p02','Meridian Services Field Ops','customer',0,NULL,NULL,NULL,'contact@meridianservices.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p03','Coral Fabrication HQ Procurement','customer',0,NULL,NULL,NULL,'contact@coralfabrication.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p04','Solace Services Field Ops','customer',0,NULL,NULL,NULL,'contact@solaceservices.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p05','Dune Manufacturing Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@dunemanufacturing.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p06','Raven Industries Field Ops','customer',0,NULL,NULL,NULL,'contact@ravenindustries.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p07','Garnet Manufacturing Tooling Center','customer',0,NULL,NULL,NULL,'contact@garnetmanufacturing.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p08','Arc Manufacturing Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@arcmanufacturing.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p09','Stratos Operations Field Ops','customer',0,NULL,NULL,NULL,'contact@stratosoperations.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p10','Baseline Fabrication Field Ops','customer',0,NULL,NULL,NULL,'contact@baselinefabrication.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p11','Globe Engineering Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@globeengineering.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p12','Crest Industries Tooling Center','customer',0,NULL,NULL,NULL,'contact@crestindustries.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p13','Canton Engineering Test Facility','customer',0,NULL,NULL,NULL,'contact@cantonengineering.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p14','Brookfield Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@brookfieldassembly.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p15','Peak Industries Field Ops','customer',0,NULL,NULL,NULL,'contact@peakindustries.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p16','Ridge Operations Field Ops','customer',0,NULL,NULL,NULL,'contact@ridgeoperations.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p17','Pivot Production Quality Lab','customer',0,NULL,NULL,NULL,'contact@pivotproduction.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p18','Arrow Fabrication Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@arrowfabrication.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p19','Cedar Assembly Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@cedarassembly.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p20','Apex Solutions Quality Lab','customer',0,NULL,NULL,NULL,'contact@apexsolutions.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p21','Prism Engineering Field Ops','customer',0,NULL,NULL,NULL,'contact@prismengineering.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p22','Anvil Fabrication Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@anvilfabrication.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p23','Spectra Assembly R&D Workshop','customer',0,NULL,NULL,NULL,'contact@spectraassembly.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p24','Forge Engineering Site Logistics','customer',0,NULL,NULL,NULL,'contact@forgeengineering.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p25','Axis Engineering HQ Procurement','customer',0,NULL,NULL,NULL,'contact@axisengineering.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p26','Cipher Solutions Quality Lab','customer',0,NULL,NULL,NULL,'contact@ciphersolutions.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p27','Fairview Services Site Logistics','customer',0,NULL,NULL,NULL,'contact@fairviewservices.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p28','Nimbus Solutions R&D Workshop','customer',0,NULL,NULL,NULL,'contact@nimbussolutions.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p29','Zenith Fabrication Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@zenithfabrication.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p30','Polar Operations Tooling Center','customer',0,NULL,NULL,NULL,'contact@polaroperations.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p31','Scion Engineering Test Facility','customer',0,NULL,NULL,NULL,'contact@scionengineering.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p32','Marble Assembly Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@marbleassembly.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p33','Spire Production R&D Workshop','customer',0,NULL,NULL,NULL,'contact@spireproduction.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p34','Summit Production Tooling Center','customer',0,NULL,NULL,NULL,'contact@summitproduction.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p35','Ivory Manufacturing HQ Procurement','customer',0,NULL,NULL,NULL,'contact@ivorymanufacturing.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p36','Flux Assembly Test Facility','customer',0,NULL,NULL,NULL,'contact@fluxassembly.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p37','Trident Production Tooling Center','customer',0,NULL,NULL,NULL,'contact@tridentproduction.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p38','Cosmo Manufacturing Prototype Shop','customer',0,NULL,NULL,NULL,'contact@cosmomanufacturing.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p39','Ember Services Prototype Shop','customer',0,NULL,NULL,NULL,'contact@emberservices.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p40','Drift Technologies Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@drifttechnologies.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p41','Ironwood Operations Tooling Center','customer',0,NULL,NULL,NULL,'contact@ironwoodoperations.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p42','Thornton Production Tooling Center','customer',0,NULL,NULL,NULL,'contact@thorntonproduction.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p43','Lakewood Engineering Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@lakewoodengineering.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p44','Cardinal Manufacturing Field Ops','customer',0,NULL,NULL,NULL,'contact@cardinalmanufacturing.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p45','Conduit Manufacturing Quality Lab','customer',0,NULL,NULL,NULL,'contact@conduitmanufacturing.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p46','Arbor Fabrication Prototype Shop','customer',0,NULL,NULL,NULL,'contact@arborfabrication.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p47','Element Solutions Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@elementsolutions.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p48','Equinox Industries Field Ops','customer',0,NULL,NULL,NULL,'contact@equinoxindustries.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p49','Silverline Engineering Test Facility','customer',0,NULL,NULL,NULL,'contact@silverlineengineering.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r6DEB139AB4_p50','Lumen Solutions Field Ops','customer',0,NULL,NULL,NULL,'contact@lumensolutions.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r14661E7E55_q01','Terra Microfactory','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r14661E7E55_q02','Ashford Wholesalers','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r14661E7E55_q03','Skyline Provisions','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q01','Citadel Parts Co','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q02','Quantum Components','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q03','Jade Parts Co','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q04','Haven Logistics','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q05','Crestview Components','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q06','Comet Materials','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q07','Aether Wholesale','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q08','Baltic Parts Co','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q09','Catalyst Transit','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q10','Gateway Supply','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q11','Quartz Procurement','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q12','Mosaic Networks','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q13','Compass Resources','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q14','Evergreen Wholesale','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q15','Helix Trading','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q16','Metro Distribution','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q17','Oakmont Freight','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q18','Grove Components','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q19','Blaze Networks','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q20','Borough Freight','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q21','Vantage Carriers','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q22','Cobalt Procurement','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q23','Ledger Materials','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q24','Pacific Transit','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q25','Vertex Components','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q26','Lance Procurement','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q27','Echo Logistics','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q28','Velocity Trading','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q29','Keystone Supply','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q30','Monarch Freight','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q31','Matrix Materials','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q32','Ironside Transit','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q33','Stonewall Materials','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q34','Sterling Procurement','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q35','Circuit Resources','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q36','Hartland Components','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q37','Horizon Freight','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q38','Eclipse Trading','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q39','Granite Materials','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q40','Chrome Networks','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q41','Westfield Resources','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q42','Clearwater Procurement','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q43','Spark Networks','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q44','Onyx Logistics','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q45','Atlas Supply','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q46','Steel Components','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q47','Lattice Components','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q48','Bridgeway Materials','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q49','Opal Freight','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r6DEB139AB4_q50','Oxide Transit','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P14661E7E55-SRK-CLR-009','Co-Location Cage Rack 42U','Data Center Equipment','consu',2937.05,1650.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'P14661E7E55-SRK-CLR-009','r14661E7E55_q01','Priority Shuttle lane (7d transit, 13-15 units)',7,13.0,15.0,2113.79);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'P14661E7E55-SRK-CLR-009','r14661E7E55_q02','Express Air lane (6d transit, 5-15 units)',6,5.0,15.0,2875.84);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'P14661E7E55-SRK-CLR-009','r14661E7E55_q03','Regional Cross-Dock lane (12d transit, 9-12 units)',12,9.0,12.0,1988.87);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A001','Low-Temp Panel Cover','Electrical Components','consu',338.41,211.93,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'P6DEB139AB4-A001','r6DEB139AB4_q01','Bulk shipment',4,1.0,24.0,210.4);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A002','Economy Mounting Rails Set','Electrical Components','consu',196.11,117.97,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'P6DEB139AB4-A002','r6DEB139AB4_q02','Regional lane',8,1.0,24.0,113.79);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A003','Corrosion-Resistant Caster Wheel Assembly','Hardware Accessories','consu',308.32,193.28,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'P6DEB139AB4-A003','r6DEB139AB4_q03','Regional lane',6,1.0,24.0,185.88);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A004','Powder-Coated Side Panel Cover','Replacement Parts','consu',385.98,263.27,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'P6DEB139AB4-A004','r6DEB139AB4_q04','Local pickup',5,1.0,24.0,280.0);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A005','High-Flow Cooling Fan Module','Mechanical Components','consu',327.0,220.88,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'P6DEB139AB4-A005','r6DEB139AB4_q05','Warehouse direct',3,1.0,24.0,224.8);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A006','Industrial Panel Cover','Mechanical Components','consu',277.18,192.38,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'P6DEB139AB4-A006','r6DEB139AB4_q06','Standard delivery',4,1.0,24.0,191.73);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A007','Flanged Steel Chassis Frame','Seals and Gaskets','consu',260.96,183.47,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'P6DEB139AB4-A007','r6DEB139AB4_q07','Local pickup',4,1.0,24.0,186.32);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A008','Modular Cable Manager','Industrial Spare Parts','consu',255.11,152.07,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'P6DEB139AB4-A008','r6DEB139AB4_q08','Cross-dock',7,1.0,24.0,161.6);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A009','Non-Magnetic Blanking Panel Set','Industrial Spare Parts','consu',374.55,201.77,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'P6DEB139AB4-A009','r6DEB139AB4_q09','Local pickup',7,1.0,24.0,210.34);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A010','Self-Lubricating Bracket Assembly','Industrial Spare Parts','consu',212.51,147.4,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'P6DEB139AB4-A010','r6DEB139AB4_q10','Warehouse direct',6,1.0,24.0,147.82);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A011','Metric Bracket Assembly','Fasteners and Fixings','consu',335.37,177.33,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'P6DEB139AB4-A011','r6DEB139AB4_q11','Standard delivery',8,1.0,24.0,179.73);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A012','Premium Steel Chassis Frame','Industrial Spare Parts','consu',219.49,120.85,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'P6DEB139AB4-A012','r6DEB139AB4_q12','Scheduled freight',4,1.0,24.0,118.73);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A013','Heat-Treated Rails Set','Industrial Spare Parts','consu',354.02,222.24,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'P6DEB139AB4-A013','r6DEB139AB4_q13','Standard delivery',3,1.0,24.0,223.97);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A014','Compact PDU Bracket Assembly','Pneumatic Components','consu',203.13,124.93,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'P6DEB139AB4-A014','r6DEB139AB4_q14','Regional lane',4,1.0,24.0,119.27);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A015','High-Cycle Fan Module','Seals and Gaskets','consu',364.25,226.33,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'P6DEB139AB4-A015','r6DEB139AB4_q15','Regional lane',5,1.0,24.0,217.84);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A016','Spring-Loaded Front Door Panel','Electrical Components','consu',277.75,170.83,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'P6DEB139AB4-A016','r6DEB139AB4_q16','Express route',7,1.0,24.0,170.73);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A017','UV-Stable Panel Cover','Mechanical Components','consu',270.12,140.47,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'P6DEB139AB4-A017','r6DEB139AB4_q17','Cross-dock',8,1.0,24.0,140.15);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A018','Commercial Blanking Panel Set','Fasteners and Fixings','consu',378.39,243.58,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'P6DEB139AB4-A018','r6DEB139AB4_q18','Standard delivery',3,1.0,24.0,250.49);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A019','Impact-Rated Rails Set','Replacement Parts','consu',196.12,116.57,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'P6DEB139AB4-A019','r6DEB139AB4_q19','Express route',8,1.0,24.0,122.25);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A020','Lightweight Mounting Rails Set','Replacement Parts','consu',267.58,177.55,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'P6DEB139AB4-A020','r6DEB139AB4_q20','Bulk shipment',8,1.0,24.0,170.44);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A021','Anodized Cooling Fan Module','Electrical Components','consu',355.9,205.57,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'P6DEB139AB4-A021','r6DEB139AB4_q21','Scheduled freight',3,1.0,24.0,219.03);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A022','Cold-Rolled Rails Set','Seals and Gaskets','consu',337.39,212.1,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'P6DEB139AB4-A022','r6DEB139AB4_q22','Warehouse direct',3,1.0,24.0,214.42);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A023','High-Temp Cable Manager','Hardware Accessories','consu',351.52,219.49,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'P6DEB139AB4-A023','r6DEB139AB4_q23','Bulk shipment',8,1.0,24.0,230.64);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A024','Hardened Steel Chassis Frame','Seals and Gaskets','consu',283.8,157.63,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'P6DEB139AB4-A024','r6DEB139AB4_q24','Cross-dock',4,1.0,24.0,156.7);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A025','Low-Noise Fan Module','Seals and Gaskets','consu',314.73,166.33,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'P6DEB139AB4-A025','r6DEB139AB4_q25','Bulk shipment',8,1.0,24.0,177.81);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A026','Thermal-Guard Steel Chassis Frame','Hardware Accessories','consu',241.44,161.99,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'P6DEB139AB4-A026','r6DEB139AB4_q26','Local pickup',4,1.0,24.0,159.71);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A027','Stainless Mounting Rails Set','Power Transmission','consu',317.76,207.96,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'P6DEB139AB4-A027','r6DEB139AB4_q27','Standard delivery',5,1.0,24.0,198.46);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A028','Adjustable Door Panel','Maintenance Supplies','consu',354.74,211.8,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'P6DEB139AB4-A028','r6DEB139AB4_q28','Express route',5,1.0,24.0,220.15);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A029','Standard Rails Set','Power Transmission','consu',289.56,173.13,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'P6DEB139AB4-A029','r6DEB139AB4_q29','Scheduled freight',8,1.0,24.0,167.64);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A030','High-Performance Door Panel','Replacement Parts','consu',295.49,177.93,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'P6DEB139AB4-A030','r6DEB139AB4_q30','Standard delivery',6,1.0,24.0,183.48);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A031','Extended-Life Rails Set','Mechanical Components','consu',270.22,141.81,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'P6DEB139AB4-A031','r6DEB139AB4_q31','Scheduled freight',3,1.0,24.0,147.62);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A032','High-Torque Lock Assembly','Power Transmission','consu',187.28,116.58,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'P6DEB139AB4-A032','r6DEB139AB4_q32','Local pickup',7,1.0,24.0,117.61);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A033','Threaded Panel Set','Fasteners and Fixings','consu',286.72,168.5,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'P6DEB139AB4-A033','r6DEB139AB4_q33','Warehouse direct',6,1.0,24.0,162.63);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A034','Low-Flow Rails Set','Electrical Components','consu',296.91,164.91,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'P6DEB139AB4-A034','r6DEB139AB4_q34','Bulk shipment',7,1.0,24.0,165.19);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A035','Rapid-Lock Steel Chassis Frame','Maintenance Supplies','consu',371.74,261.09,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'P6DEB139AB4-A035','r6DEB139AB4_q35','Cross-dock',8,1.0,24.0,255.7);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A036','Cleanroom Panel Set','Industrial Spare Parts','consu',301.26,203.05,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'P6DEB139AB4-A036','r6DEB139AB4_q36','Standard delivery',5,1.0,24.0,202.35);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A037','Sealed Cooling Fan Module','Mechanical Components','consu',395.01,257.96,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'P6DEB139AB4-A037','r6DEB139AB4_q37','Express route',4,1.0,24.0,270.08);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A038','Narrow-Body Steel Chassis Frame','Electrical Components','consu',318.15,220.81,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'P6DEB139AB4-A038','r6DEB139AB4_q38','Bulk shipment',3,1.0,24.0,215.7);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A039','Pressure-Balanced Cable Management Kit','Power Transmission','consu',295.82,175.83,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'P6DEB139AB4-A039','r6DEB139AB4_q39','Local pickup',8,1.0,24.0,187.68);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A040','Single-Stage Panel Cover','Seals and Gaskets','consu',279.45,152.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'P6DEB139AB4-A040','r6DEB139AB4_q40','Warehouse direct',8,1.0,24.0,151.34);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A041','Anti-Vibration Blanking Panel Set','Hardware Accessories','consu',339.64,238.84,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'P6DEB139AB4-A041','r6DEB139AB4_q41','Bulk shipment',6,1.0,24.0,248.77);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A042','Weatherproof Door Panel','Hardware Accessories','consu',277.15,154.19,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'P6DEB139AB4-A042','r6DEB139AB4_q42','Local pickup',3,1.0,24.0,156.0);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A043','Zero-Backlash Vertical Cable Manager','Mechanical Components','consu',249.26,148.84,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'P6DEB139AB4-A043','r6DEB139AB4_q43','Standard delivery',5,1.0,24.0,141.93);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A044','Universal Cable Manager','Seals and Gaskets','consu',279.91,179.24,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'P6DEB139AB4-A044','r6DEB139AB4_q44','Regional lane',4,1.0,24.0,184.27);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A045','Reinforced Caster Wheel Assembly','Replacement Parts','consu',371.13,232.5,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'P6DEB139AB4-A045','r6DEB139AB4_q45','Local pickup',5,1.0,24.0,246.94);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A046','Medical-Grade Side Panel Cover','Hardware Accessories','consu',368.47,261.3,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'P6DEB139AB4-A046','r6DEB139AB4_q46','Express route',8,1.0,24.0,265.24);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A047','Precision Panel Cover','Electrical Components','consu',412.92,259.06,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'P6DEB139AB4-A047','r6DEB139AB4_q47','Scheduled freight',3,1.0,24.0,271.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A048','Tapered Management Kit','Mechanical Components','consu',182.42,125.2,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'P6DEB139AB4-A048','r6DEB139AB4_q48','Bulk shipment',8,1.0,24.0,120.37);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A049','Dual-Stage Panel Cover','Electrical Components','consu',282.15,179.17,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'P6DEB139AB4-A049','r6DEB139AB4_q49','Scheduled freight',4,1.0,24.0,178.99);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P6DEB139AB4-A050','Double-Row PDU Bracket Assembly','Mechanical Components','consu',320.2,202.16,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'P6DEB139AB4-A050','r6DEB139AB4_q50','Scheduled freight',6,1.0,24.0,203.72);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'P6DEB139AB4-A027','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P6DEB139AB4-A047',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'P6DEB139AB4-A044','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P6DEB139AB4-A045',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P6DEB139AB4-A039',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'P6DEB139AB4-A013','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P6DEB139AB4-A025',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'P6DEB139AB4-A029','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'P6DEB139AB4-A016',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'P6DEB139AB4-A009',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'P6DEB139AB4-A002','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P6DEB139AB4-A040',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P6DEB139AB4-A038',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'P6DEB139AB4-A016','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P6DEB139AB4-A046',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'P6DEB139AB4-A015','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'P6DEB139AB4-A020',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'P6DEB139AB4-A004','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P6DEB139AB4-A026',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P6DEB139AB4-A048',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'P6DEB139AB4-A032','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P6DEB139AB4-A027',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'P6DEB139AB4-A011','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P6DEB139AB4-A002',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P6DEB139AB4-A020',2.0);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P14661E7E55-SRK-CLR-009',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A001',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A002',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A003',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A004',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A005',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A006',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A007',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A008',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A009',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A010',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A011',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A012',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A013',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A014',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A015',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A016',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A017',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A018',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A019',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A020',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A021',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A022',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A023',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A024',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A025',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A026',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A027',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A028',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A029',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A030',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A031',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A032',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A033',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A034',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A035',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A036',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A037',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A038',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A039',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A040',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A041',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A042',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A043',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A044',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A045',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A046',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A047',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A048',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A049',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P6DEB139AB4-A050',NULL,5.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'r14661E7E55_c01','P14661E7E55-SRK-CLR-009',3,7,9393.79,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'r14661E7E55_c02','P14661E7E55-SRK-CLR-009',6,7,19120.66,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'r14661E7E55_c03','P14661E7E55-SRK-CLR-009',3,8,9480.42,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'r14661E7E55_c04','P14661E7E55-SRK-CLR-009',4,9,12809.9,NULL);
