-- agentic-labs/erp-bench scenario 2233: Carport Solar Canopy Module
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0BA0BC3DDB_c01','Granite Sciences','customer',0,47632.74,NULL,NULL,'orders@granitesciences.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0BA0BC3DDB_c02','Sentinel Enterprises','customer',0,75957.79,NULL,NULL,'orders@sentinelenterprises.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0BA0BC3DDB_c03','Summit Workspaces','customer',0,57131.12,NULL,NULL,'orders@summitworkspaces.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0BA0BC3DDB_c04','Apex Foundry','customer',0,57245.91,NULL,NULL,'orders@apexfoundry.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0BA0BC3DDB_c05','Sterling Publishing','customer',0,103381.74,NULL,NULL,'orders@sterlingpublishing.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0BA0BC3DDB_c06','Northbridge Academy','customer',0,71555.14,NULL,NULL,'orders@northbridgeacademy.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0BA0BC3DDB_c07','Aurora Observatory','customer',0,73534.49,NULL,NULL,'orders@auroraobservatory.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0BA0BC3DDB_c08','Quartz Media','customer',0,79487.92,NULL,NULL,'orders@quartzmedia.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0BA0BC3DDB_c09','Redstone Forum','customer',0,68485.91,NULL,NULL,'orders@redstoneforum.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r0BA0BC3DDB_c10','Fairview Studios North','customer',0,56175.59,NULL,NULL,'orders@fairviewstudiosnorth.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p01','Millbrook Production Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@millbrookproduction.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p02','Polar Technologies Prototype Shop','customer',0,NULL,NULL,NULL,'contact@polartechnologies.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p03','Alloy Solutions Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@alloysolutions.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p04','Coral Services HQ Procurement','customer',0,NULL,NULL,NULL,'contact@coralservices.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p05','Velocity Engineering Test Facility','customer',0,NULL,NULL,NULL,'contact@velocityengineering.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p06','Ashford Technologies Tooling Center','customer',0,NULL,NULL,NULL,'contact@ashfordtechnologies.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p07','Spire Assembly Tooling Center','customer',0,NULL,NULL,NULL,'contact@spireassembly.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p08','Ironside Engineering Tooling Center','customer',0,NULL,NULL,NULL,'contact@ironsideengineering.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p09','Conduit Operations Site Logistics','customer',0,NULL,NULL,NULL,'contact@conduitoperations.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p10','Circuit Solutions Quality Lab','customer',0,NULL,NULL,NULL,'contact@circuitsolutions.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p11','Pacific Solutions Quality Lab','customer',0,NULL,NULL,NULL,'contact@pacificsolutions.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p12','Metro Technologies Test Facility','customer',0,NULL,NULL,NULL,'contact@metrotechnologies.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p13','Copper Services Quality Lab','customer',0,NULL,NULL,NULL,'contact@copperservices.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p14','Ironwood Production Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@ironwoodproduction.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p15','Cardinal Engineering Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@cardinalengineering.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p16','Chrome Engineering Tooling Center','customer',0,NULL,NULL,NULL,'contact@chromeengineering.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p17','Lumen Technologies Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@lumentechnologies.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p18','Citadel Fabrication R&D Workshop','customer',0,NULL,NULL,NULL,'contact@citadelfabrication.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p19','Hartland Fabrication Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@hartlandfabrication.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p20','Jade Solutions Test Facility','customer',0,NULL,NULL,NULL,'contact@jadesolutions.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p21','Ivory Services Prototype Shop','customer',0,NULL,NULL,NULL,'contact@ivoryservices.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p22','Stonewall Operations R&D Workshop','customer',0,NULL,NULL,NULL,'contact@stonewalloperations.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p23','Horizon Engineering HQ Procurement','customer',0,NULL,NULL,NULL,'contact@horizonengineering.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p24','Nimbus Assembly Tooling Center','customer',0,NULL,NULL,NULL,'contact@nimbusassembly.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p25','Vertex Industries HQ Procurement','customer',0,NULL,NULL,NULL,'contact@vertexindustries.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p26','Meridian Fabrication Prototype Shop','customer',0,NULL,NULL,NULL,'contact@meridianfabrication.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p27','Keystone Engineering Test Facility','customer',0,NULL,NULL,NULL,'contact@keystoneengineering.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p28','Flux Solutions HQ Procurement','customer',0,NULL,NULL,NULL,'contact@fluxsolutions.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p29','Crestview Manufacturing Site Logistics','customer',0,NULL,NULL,NULL,'contact@crestviewmanufacturing.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p30','Riverdale Production Quality Lab','customer',0,NULL,NULL,NULL,'contact@riverdaleproduction.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p31','Matrix Production Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@matrixproduction.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p32','Compass Technologies Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@compasstechnologies.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p33','Bayshore Industries Tooling Center','customer',0,NULL,NULL,NULL,'contact@bayshoreindustries.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p34','Oakmont Industries R&D Workshop','customer',0,NULL,NULL,NULL,'contact@oakmontindustries.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p35','Globe Technologies R&D Workshop','customer',0,NULL,NULL,NULL,'contact@globetechnologies.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p36','Canton Technologies HQ Procurement','customer',0,NULL,NULL,NULL,'contact@cantontechnologies.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p37','Alpine Production Site Logistics','customer',0,NULL,NULL,NULL,'contact@alpineproduction.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p38','Ridge Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@ridgeassembly.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p39','Eclipse Services Prototype Shop','customer',0,NULL,NULL,NULL,'contact@eclipseservices.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p40','Titan Industries Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@titanindustries.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p41','Axis Solutions HQ Procurement','customer',0,NULL,NULL,NULL,'contact@axissolutions.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p42','Orbital Solutions R&D Workshop','customer',0,NULL,NULL,NULL,'contact@orbitalsolutions.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p43','Borough Operations Quality Lab','customer',0,NULL,NULL,NULL,'contact@boroughoperations.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p44','Baltic Fabrication HQ Procurement','customer',0,NULL,NULL,NULL,'contact@balticfabrication.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p45','Gateway Technologies HQ Procurement','customer',0,NULL,NULL,NULL,'contact@gatewaytechnologies.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p46','Brookfield Engineering R&D Workshop','customer',0,NULL,NULL,NULL,'contact@brookfieldengineering.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p47','Equinox Industries HQ Procurement','customer',0,NULL,NULL,NULL,'contact@equinoxindustries.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p48','Scion Engineering Field Ops','customer',0,NULL,NULL,NULL,'contact@scionengineering.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p49','Sapphire Engineering R&D Workshop','customer',0,NULL,NULL,NULL,'contact@sapphireengineering.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r18E7321DD8_p50','Atlas Operations Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@atlasoperations.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0BA0BC3DDB_q01','Pivot Wholesalers','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0BA0BC3DDB_q02','Onyx Consolidators','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0BA0BC3DDB_q03','Quantum Materials','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0BA0BC3DDB_q04','Crown Solutions','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0BA0BC3DDB_q05','Ledger Transit','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0BA0BC3DDB_q06','Trellis Merchants','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0BA0BC3DDB_q07','Helix Depot','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0BA0BC3DDB_q08','Grove Shipping','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0BA0BC3DDB_q09','Lattice Networks','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0BA0BC3DDB_q10','Opal Conveyance','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0BA0BC3DDB_q11','Marble Fabrication','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0BA0BC3DDB_q12','Blaze Assemblies','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0BA0BC3DDB_q13','Terra Movers','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0BA0BC3DDB_q14','Ridgeline Haulage','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0BA0BC3DDB_q15','Element Sourcing','vendor',15,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0BA0BC3DDB_q16','Drift Integrators','vendor',16,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0BA0BC3DDB_q17','Ember Commodities','vendor',17,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0BA0BC3DDB_q18','Arc Forwarders','vendor',18,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r0BA0BC3DDB_q19','Lance Distribution','vendor',19,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q01','Cascade Carriers','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q02','Arbor Networks','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q03','Steel Wholesale','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q04','Beacon Materials','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q05','Oxide Sourcing','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q06','Spectra Components','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q07','Evergreen Logistics','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q08','Spark Logistics','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q09','Noble Resources','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q10','Mosaic Logistics','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q11','Slate Carriers','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q12','Bridgeway Wholesale','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q13','Echo Distribution','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q14','Nexus Networks','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q15','Forge Logistics','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q16','Comet Parts Co','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q17','Aether Trading','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q18','Thornton Trading','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q19','Cedar Components','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q20','Prism Materials','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q21','Solace Components','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q22','Sierra Resources','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q23','Dune Resources','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q24','Baseline Carriers','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q25','Osprey Logistics','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q26','Anvil Carriers','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q27','Garnet Supply','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q28','Monarch Distribution','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q29','Indigo Transit','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q30','Silverline Trading','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q31','Flint Procurement','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q32','Trident Logistics','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q33','Skyline Sourcing','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q34','Aegis Logistics','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q35','Westfield Networks','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q36','Lakewood Components','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q37','Arrow Supply','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q38','Raven Networks','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q39','Zenith Trading','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q40','Catalyst Logistics','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q41','Haven Logistics','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q42','Peak Supply','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q43','Cobalt Carriers','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q44','Iron Supply','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q45','Crest Networks','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q46','Stratos Components','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q47','Cosmo Parts Co','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q48','Clearwater Logistics','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q49','Cipher Sourcing','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r18E7321DD8_q50','Bronze Wholesale','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0BA0BC3DDB-SOL-CSC-007','Carport Solar Canopy Module','Power Equipment','consu',3926.56,2067.34,'buy,manufacture',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'P0BA0BC3DDB-SOL-CSC-007','r0BA0BC3DDB_q01','Priority Shuttle lane (9d transit, 13-26 units)',9,13.0,26.0,2181.85);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'P0BA0BC3DDB-SOL-CSC-007','r0BA0BC3DDB_q02','Express Air lane (5d transit, 2-2 units)',5,2.0,2.0,3496.91);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'P0BA0BC3DDB-SOL-CSC-007','r0BA0BC3DDB_q03','Economy Ocean lane (20d transit, 8-8 units)',20,8.0,8.0,1615.32);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'P0BA0BC3DDB-SOL-CSC-007','r0BA0BC3DDB_q04','Air Charter lane (5d transit, 2-2 units)',5,2.0,2.0,3729.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0BA0BC3DDB-RESMOD-02','Carport Solar Canopy Module Restricted Module','Power Equipment','consu',1099.44,43.74,'manufacture',NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0BA0BC3DDB-SOL-ECF-122','Edge Clamp Fastener Pack','Power Equipment','consu',10.27,3.35,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'P0BA0BC3DDB-SOL-ECF-122','r0BA0BC3DDB_q05','Rapid Works (3d)',3,7.0,311.0,5.27);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'P0BA0BC3DDB-SOL-ECF-122','r0BA0BC3DDB_q06','Hybrid Fabricators (6d)',6,14.0,16.0,4.23);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'P0BA0BC3DDB-SOL-ECF-122','r0BA0BC3DDB_q07','Domestic Supply (6d)',6,14.0,145.0,3.38);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'P0BA0BC3DDB-SOL-ECF-122','r0BA0BC3DDB_q08','Import Consolidator (6d)',6,44.0,97.0,3.35);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0BA0BC3DDB-SOL-SPD-124','Surge Protection Device DC','Power Equipment','consu',69.64,31.93,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'P0BA0BC3DDB-SOL-SPD-124','r0BA0BC3DDB_q09','Rapid Works (4d)',4,8.0,11.0,36.17);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'P0BA0BC3DDB-SOL-SPD-124','r0BA0BC3DDB_q10','Domestic Supply (5d)',5,27.0,62.0,31.93);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'P0BA0BC3DDB-SOL-SPD-124','r0BA0BC3DDB_q11','Hybrid Fabricators (6d)',6,19.0,61.0,34.72);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0BA0BC3DDB-SOL-RHB-111','Roof Hook Mounting Bracket','Power Equipment','consu',15.3,5.88,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'P0BA0BC3DDB-SOL-RHB-111','r0BA0BC3DDB_q12','Rapid Works (4d)',4,6.0,33.0,7.3);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'P0BA0BC3DDB-SOL-RHB-111','r0BA0BC3DDB_q13','Import Consolidator (4d)',4,48.0,159.0,5.88);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'P0BA0BC3DDB-SOL-RHB-111','r0BA0BC3DDB_q14','Domestic Supply (4d)',4,15.0,45.0,7.37);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'P0BA0BC3DDB-SOL-RHB-111','r0BA0BC3DDB_q15','Hybrid Fabricators (4d)',4,17.0,389.0,7.4);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P0BA0BC3DDB-SOL-CTR-119','Cable Tray Solar Raceway','Power Equipment','consu',21.51,8.24,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'P0BA0BC3DDB-SOL-CTR-119','r0BA0BC3DDB_q16','Rapid Works (4d)',4,4.0,22.0,10.95);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'P0BA0BC3DDB-SOL-CTR-119','r0BA0BC3DDB_q17','Hybrid Fabricators (4d)',4,16.0,16.0,10.27);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'P0BA0BC3DDB-SOL-CTR-119','r0BA0BC3DDB_q18','Domestic Supply (4d)',4,21.0,30.0,10.16);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'P0BA0BC3DDB-SOL-CTR-119','r0BA0BC3DDB_q19','Import Consolidator (4d)',4,42.0,62.0,8.24);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A001','Extended-Life Cable Set','Industrial Spare Parts','consu',358.29,214.96,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'P18E7321DD8-A001','r18E7321DD8_q01','Local pickup',7,1.0,24.0,229.24);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A002','Precision Bypass Diodes','Mechanical Components','consu',275.1,146.66,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'P18E7321DD8-A002','r18E7321DD8_q02','Cross-dock',8,1.0,24.0,145.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A003','Universal Connector Cable Set','Fasteners and Fixings','consu',413.76,260.27,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'P18E7321DD8-A003','r18E7321DD8_q03','Standard delivery',4,1.0,24.0,269.8);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A004','Flanged Glass Front Sheet','Replacement Parts','consu',341.36,240.51,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'P18E7321DD8-A004','r18E7321DD8_q04','Warehouse direct',7,1.0,24.0,257.88);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A005','Snap-Fit Front Sheet','Maintenance Supplies','consu',285.56,179.44,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'P18E7321DD8-A005','r18E7321DD8_q05','Warehouse direct',6,1.0,24.0,192.86);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A006','Metric Screw Foundation Pile','Seals and Gaskets','consu',232.25,137.44,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'P18E7321DD8-A006','r18E7321DD8_q06','Regional lane',8,1.0,24.0,143.61);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A007','Stainless Inverter 5kW','Maintenance Supplies','consu',322.57,200.58,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'P18E7321DD8-A007','r18E7321DD8_q07','Bulk shipment',7,1.0,24.0,201.91);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A008','Sealed Frame Extrusion Set','Mechanical Components','consu',264.0,174.46,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'P18E7321DD8-A008','r18E7321DD8_q08','Standard delivery',3,1.0,24.0,168.53);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A009','Standard Hook Mounting Bracket','Pneumatic Components','consu',235.92,165.14,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'P18E7321DD8-A009','r18E7321DD8_q09','Express route',7,1.0,24.0,165.29);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A010','Low-Flow Frame Extrusion Set','Seals and Gaskets','consu',244.5,135.96,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'P18E7321DD8-A010','r18E7321DD8_q10','Standard delivery',3,1.0,24.0,138.17);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A011','Medical-Grade Screw Foundation Pile','Power Transmission','consu',332.11,209.06,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'P18E7321DD8-A011','r18E7321DD8_q11','Standard delivery',6,1.0,24.0,222.95);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A012','Modular Film Roll','Industrial Spare Parts','consu',334.16,192.98,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'P18E7321DD8-A012','r18E7321DD8_q12','Express route',4,1.0,24.0,187.34);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A013','Zero-Backlash Screw Foundation Pile','Seals and Gaskets','consu',240.18,164.47,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'P18E7321DD8-A013','r18E7321DD8_q13','Regional lane',6,1.0,24.0,157.92);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A014','Single-Stage with Bypass Diodes','Industrial Spare Parts','consu',276.37,196.62,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'P18E7321DD8-A014','r18E7321DD8_q14','Bulk shipment',5,1.0,24.0,200.91);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A015','Spring-Loaded Glass Front Sheet','Seals and Gaskets','consu',213.45,116.2,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'P18E7321DD8-A015','r18E7321DD8_q15','Standard delivery',4,1.0,24.0,122.49);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A016','Corrosion-Resistant Inverter Module','Seals and Gaskets','consu',263.1,165.57,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'P18E7321DD8-A016','r18E7321DD8_q16','Regional lane',3,1.0,24.0,175.56);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A017','Heat-Treated Hook Mounting Bracket','Maintenance Supplies','consu',339.45,236.49,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'P18E7321DD8-A017','r18E7321DD8_q17','Warehouse direct',4,1.0,24.0,226.6);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A018','Low-Temp Protective Film','Industrial Spare Parts','consu',245.49,174.54,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'P18E7321DD8-A018','r18E7321DD8_q18','Bulk shipment',8,1.0,24.0,179.86);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A019','Adjustable Micro Inverter Module','Industrial Spare Parts','consu',271.44,147.15,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'P18E7321DD8-A019','r18E7321DD8_q19','Cross-dock',5,1.0,24.0,142.03);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A020','Self-Lubricating Micro Inverter Module','Seals and Gaskets','consu',203.51,134.16,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'P18E7321DD8-A020','r18E7321DD8_q20','Warehouse direct',4,1.0,24.0,141.57);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A021','Lightweight T Slot 4m','Hardware Accessories','consu',253.95,174.13,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'P18E7321DD8-A021','r18E7321DD8_q21','Warehouse direct',3,1.0,24.0,171.26);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A022','Economy Backsheet Protective Film','Power Transmission','consu',330.05,189.47,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'P18E7321DD8-A022','r18E7321DD8_q22','Warehouse direct',5,1.0,24.0,184.21);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A023','High-Torque Mounting Bracket','Maintenance Supplies','consu',300.12,158.36,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'P18E7321DD8-A023','r18E7321DD8_q23','Warehouse direct',4,1.0,24.0,168.13);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A024','High-Performance Slot 4m','Hardware Accessories','consu',302.35,212.63,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'P18E7321DD8-A024','r18E7321DD8_q24','Express route',4,1.0,24.0,209.64);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A025','Thermal-Guard T Slot 4m','Mechanical Components','consu',200.34,129.11,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'P18E7321DD8-A025','r18E7321DD8_q25','Scheduled freight',3,1.0,24.0,136.04);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A026','Narrow-Body Foundation Pile','Seals and Gaskets','consu',344.99,187.54,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'P18E7321DD8-A026','r18E7321DD8_q26','Standard delivery',6,1.0,24.0,187.57);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A027','Food-Grade Cell String Set','Mechanical Components','consu',245.02,151.95,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'P18E7321DD8-A027','r18E7321DD8_q27','Regional lane',8,1.0,24.0,152.57);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A028','Heavy-Duty Encapsulant Film Roll','Maintenance Supplies','consu',374.09,209.4,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'P18E7321DD8-A028','r18E7321DD8_q28','Bulk shipment',7,1.0,24.0,201.76);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A029','High-Cycle Cell String Set','Industrial Spare Parts','consu',357.23,245.13,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'P18E7321DD8-A029','r18E7321DD8_q29','Scheduled freight',8,1.0,24.0,237.34);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A030','Pressure-Balanced T Slot 4m','Power Transmission','consu',341.02,228.64,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'P18E7321DD8-A030','r18E7321DD8_q30','Regional lane',4,1.0,24.0,223.3);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A031','Industrial String Set','Pneumatic Components','consu',398.58,215.48,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'P18E7321DD8-A031','r18E7321DD8_q31','Standard delivery',8,1.0,24.0,206.09);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A032','Non-Magnetic Encapsulant Film Roll','Fasteners and Fixings','consu',341.28,241.61,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'P18E7321DD8-A032','r18E7321DD8_q32','Express route',4,1.0,24.0,258.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A033','High-Temp Bypass Diodes','Power Transmission','consu',391.45,265.82,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'P18E7321DD8-A033','r18E7321DD8_q33','Warehouse direct',4,1.0,24.0,284.19);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A034','Anodized Micro Inverter Module','Industrial Spare Parts','consu',233.97,162.59,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'P18E7321DD8-A034','r18E7321DD8_q34','Regional lane',4,1.0,24.0,155.17);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A035','Hardened Screw Foundation Pile','Fasteners and Fixings','consu',414.15,261.08,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'P18E7321DD8-A035','r18E7321DD8_q35','Regional lane',3,1.0,24.0,258.26);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A036','Threaded Bypass Diodes','Industrial Spare Parts','consu',326.63,206.39,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'P18E7321DD8-A036','r18E7321DD8_q36','Express route',8,1.0,24.0,196.23);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A037','Rapid-Lock Encapsulant Film Roll','Seals and Gaskets','consu',343.03,231.91,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'P18E7321DD8-A037','r18E7321DD8_q37','Cross-dock',8,1.0,24.0,247.82);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A038','Tapered Mounting Bracket','Industrial Spare Parts','consu',273.46,174.54,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(57,'P18E7321DD8-A038','r18E7321DD8_q38','Local pickup',3,1.0,24.0,175.84);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A039','Compact Cell String Set','Mechanical Components','consu',312.28,195.48,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(58,'P18E7321DD8-A039','r18E7321DD8_q39','Regional lane',5,1.0,24.0,202.47);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A040','Low-Friction Cable Set','Power Transmission','consu',300.36,201.94,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(59,'P18E7321DD8-A040','r18E7321DD8_q40','Standard delivery',5,1.0,24.0,193.67);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A041','Cold-Rolled String Set','Seals and Gaskets','consu',371.0,242.77,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(60,'P18E7321DD8-A041','r18E7321DD8_q41','Express route',7,1.0,24.0,261.19);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A042','Double-Row Protective Film','Hardware Accessories','consu',409.04,284.6,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(61,'P18E7321DD8-A042','r18E7321DD8_q42','Express route',6,1.0,24.0,271.7);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A043','Weatherproof Film Roll','Hardware Accessories','consu',290.45,184.27,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(62,'P18E7321DD8-A043','r18E7321DD8_q43','Standard delivery',6,1.0,24.0,177.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A044','High-Flow Encapsulant Film Roll','Mechanical Components','consu',378.01,204.12,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(63,'P18E7321DD8-A044','r18E7321DD8_q44','Cross-dock',5,1.0,24.0,212.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A045','Premium Backsheet Protective Film','Industrial Spare Parts','consu',260.46,174.27,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(64,'P18E7321DD8-A045','r18E7321DD8_q45','Local pickup',7,1.0,24.0,169.08);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A046','UV-Stable Film Roll','Replacement Parts','consu',228.63,162.52,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(65,'P18E7321DD8-A046','r18E7321DD8_q46','Cross-dock',8,1.0,24.0,154.53);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A047','Powder-Coated Hook Mounting Bracket','Hardware Accessories','consu',208.78,114.62,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(66,'P18E7321DD8-A047','r18E7321DD8_q47','Standard delivery',6,1.0,24.0,111.98);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A048','Reinforced Mounting Bracket','Fasteners and Fixings','consu',396.97,222.21,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(67,'P18E7321DD8-A048','r18E7321DD8_q48','Standard delivery',6,1.0,24.0,215.02);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A049','Wide-Body Protective Film','Mechanical Components','consu',330.22,201.68,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(68,'P18E7321DD8-A049','r18E7321DD8_q49','Express route',7,1.0,24.0,210.54);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P18E7321DD8-A050','Cleanroom Screw Foundation Pile','Pneumatic Components','consu',392.17,253.09,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(69,'P18E7321DD8-A050','r18E7321DD8_q50','Regional lane',6,1.0,24.0,248.75);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'P0BA0BC3DDB-RESMOD-02','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P0BA0BC3DDB-SOL-RHB-111',5.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P0BA0BC3DDB-SOL-CTR-119',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'P0BA0BC3DDB-SOL-CSC-007','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P0BA0BC3DDB-RESMOD-02',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P0BA0BC3DDB-SOL-ECF-122',4.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P0BA0BC3DDB-SOL-SPD-124',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'P18E7321DD8-A008','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P18E7321DD8-A035',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P18E7321DD8-A011',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'P18E7321DD8-A022','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'P18E7321DD8-A021',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'P18E7321DD8-A029','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P18E7321DD8-A047',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P18E7321DD8-A037',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'P18E7321DD8-A035','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P18E7321DD8-A041',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P18E7321DD8-A031',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'P18E7321DD8-A045','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'P18E7321DD8-A019',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'P18E7321DD8-A028','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P18E7321DD8-A013',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P18E7321DD8-A010',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'P18E7321DD8-A007','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P18E7321DD8-A035',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'P18E7321DD8-A034','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P18E7321DD8-A013',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P18E7321DD8-A035',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(11,'P18E7321DD8-A021','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'P18E7321DD8-A005',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'P18E7321DD8-A010',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(12,'P18E7321DD8-A001','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(12,'P18E7321DD8-A006',2.0);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P0BA0BC3DDB-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P0BA0BC3DDB-WC02','Fabrication Cell 2',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P0BA0BC3DDB-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0BA0BC3DDB-SOL-CSC-007',NULL,36.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0BA0BC3DDB-SOL-CTR-119',NULL,28.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0BA0BC3DDB-SOL-ECF-122',NULL,28.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0BA0BC3DDB-SOL-RHB-111',NULL,40.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P0BA0BC3DDB-SOL-SPD-124',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A001',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A002',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A003',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A004',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A005',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A006',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A007',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A008',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A009',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A010',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A011',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A012',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A013',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A014',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A015',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A016',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A017',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A018',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A019',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A020',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A021',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A022',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A023',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A024',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A025',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A026',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A027',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A028',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A029',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A030',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A031',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A032',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A033',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A034',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A035',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A036',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A037',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A038',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A039',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A040',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A041',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A042',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A043',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A044',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A045',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A046',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A047',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A048',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A049',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P18E7321DD8-A050',NULL,14.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'r0BA0BC3DDB_c01','P0BA0BC3DDB-SOL-CSC-007',14,8,47632.74,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'r0BA0BC3DDB_c02','P0BA0BC3DDB-SOL-CSC-007',18,9,75957.79,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'r0BA0BC3DDB_c03','P0BA0BC3DDB-SOL-CSC-007',14,9,57131.12,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'r0BA0BC3DDB_c04','P0BA0BC3DDB-SOL-CSC-007',14,10,57245.91,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'r0BA0BC3DDB_c05','P0BA0BC3DDB-SOL-CSC-007',25,10,103381.74,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'r0BA0BC3DDB_c06','P0BA0BC3DDB-SOL-CSC-007',17,11,71555.14,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'r0BA0BC3DDB_c07','P0BA0BC3DDB-SOL-CSC-007',18,11,73534.49,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'r0BA0BC3DDB_c08','P0BA0BC3DDB-SOL-CSC-007',19,12,79487.92,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(9,'r0BA0BC3DDB_c09','P0BA0BC3DDB-SOL-CSC-007',17,12,68485.91,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(10,'r0BA0BC3DDB_c10','P0BA0BC3DDB-SOL-CSC-007',14,13,56175.59,'draft');
