-- agentic-labs/erp-bench scenario 2242: Landing Door Assembly Center-Open
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF8BEF50511_c01','Arrow Council','customer',0,61490.83,NULL,NULL,'orders@arrowcouncil.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF8BEF50511_c02','Copper Productions','customer',0,111963.96,NULL,NULL,'orders@copperproductions.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF8BEF50511_c03','Mosaic Architects','customer',0,79807.06,NULL,NULL,'orders@mosaicarchitects.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF8BEF50511_c04','Ridgeline Manufactory','customer',0,77807.61,NULL,NULL,'orders@ridgelinemanufactory.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF8BEF50511_c05','Jade Workshop','customer',0,107432.57,NULL,NULL,'orders@jadeworkshop.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF8BEF50511_c06','Aether Academy','customer',0,67991.56,NULL,NULL,'orders@aetheracademy.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF8BEF50511_c07','Equinox Technologies','customer',0,76028.34,NULL,NULL,'orders@equinoxtechnologies.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF8BEF50511_c08','Flux Studios North','customer',0,97011.32,NULL,NULL,'orders@fluxstudiosnorth.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rF8BEF50511_c09','Garnet Designs','customer',0,72307.05,NULL,NULL,'orders@garnetdesigns.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p01','Cardinal Technologies Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@cardinaltechnologies.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p02','Ridge Operations Quality Lab','customer',0,NULL,NULL,NULL,'contact@ridgeoperations.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p03','Comet Services Test Facility','customer',0,NULL,NULL,NULL,'contact@cometservices.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p04','Spectra Fabrication Field Ops','customer',0,NULL,NULL,NULL,'contact@spectrafabrication.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p05','Keystone Fabrication Field Ops','customer',0,NULL,NULL,NULL,'contact@keystonefabrication.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p06','Stonewall Industries Field Ops','customer',0,NULL,NULL,NULL,'contact@stonewallindustries.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p07','Lumen Manufacturing Tooling Center','customer',0,NULL,NULL,NULL,'contact@lumenmanufacturing.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p08','Bayshore Technologies Field Ops','customer',0,NULL,NULL,NULL,'contact@bayshoretechnologies.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p09','Peak Services Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@peakservices.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p10','Monarch Solutions Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@monarchsolutions.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p11','Granite Engineering Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@graniteengineering.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p12','Cipher Assembly Site Logistics','customer',0,NULL,NULL,NULL,'contact@cipherassembly.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p13','Blaze Assembly Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@blazeassembly.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p14','Terra Engineering Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@terraengineering.logistics.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p15','Gateway Solutions Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@gatewaysolutions.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p16','Ironwood Fabrication Tooling Center','customer',0,NULL,NULL,NULL,'contact@ironwoodfabrication.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p17','Nexus Production Test Facility','customer',0,NULL,NULL,NULL,'contact@nexusproduction.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p18','Echo Industries Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@echoindustries.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p19','Indigo Assembly Tooling Center','customer',0,NULL,NULL,NULL,'contact@indigoassembly.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p20','Crown Manufacturing Test Facility','customer',0,NULL,NULL,NULL,'contact@crownmanufacturing.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p21','Oakmont Engineering HQ Procurement','customer',0,NULL,NULL,NULL,'contact@oakmontengineering.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p22','Baseline Engineering Prototype Shop','customer',0,NULL,NULL,NULL,'contact@baselineengineering.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p23','Coral Manufacturing Test Facility','customer',0,NULL,NULL,NULL,'contact@coralmanufacturing.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p24','Aegis Industries Prototype Shop','customer',0,NULL,NULL,NULL,'contact@aegisindustries.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p25','Ember Services Test Facility','customer',0,NULL,NULL,NULL,'contact@emberservices.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p26','Beacon Production HQ Procurement','customer',0,NULL,NULL,NULL,'contact@beaconproduction.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p27','Lattice Solutions Site Logistics','customer',0,NULL,NULL,NULL,'contact@latticesolutions.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p28','Ledger Services Quality Lab','customer',0,NULL,NULL,NULL,'contact@ledgerservices.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p29','Onyx Production Site Logistics','customer',0,NULL,NULL,NULL,'contact@onyxproduction.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p30','Ashford Fabrication Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@ashfordfabrication.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p31','Forge Technologies Prototype Shop','customer',0,NULL,NULL,NULL,'contact@forgetechnologies.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p32','Silverline Assembly Site Logistics','customer',0,NULL,NULL,NULL,'contact@silverlineassembly.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p33','Conduit Assembly Quality Lab','customer',0,NULL,NULL,NULL,'contact@conduitassembly.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p34','Sapphire Operations Tooling Center','customer',0,NULL,NULL,NULL,'contact@sapphireoperations.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p35','Prism Technologies Prototype Shop','customer',0,NULL,NULL,NULL,'contact@prismtechnologies.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p36','Vantage Industries R&D Workshop','customer',0,NULL,NULL,NULL,'contact@vantageindustries.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p37','Chrome Engineering R&D Workshop','customer',0,NULL,NULL,NULL,'contact@chromeengineering.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p38','Bridgeway Engineering Site Logistics','customer',0,NULL,NULL,NULL,'contact@bridgewayengineering.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p39','Metro Services Prototype Shop','customer',0,NULL,NULL,NULL,'contact@metroservices.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p40','Alloy Assembly HQ Procurement','customer',0,NULL,NULL,NULL,'contact@alloyassembly.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p41','Northbridge Engineering R&D Workshop','customer',0,NULL,NULL,NULL,'contact@northbridgeengineering.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p42','Horizon Technologies R&D Workshop','customer',0,NULL,NULL,NULL,'contact@horizontechnologies.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p43','Atlas Industries HQ Procurement','customer',0,NULL,NULL,NULL,'contact@atlasindustries.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p44','Meridian Fabrication Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@meridianfabrication.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p45','Pacific Operations Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@pacificoperations.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p46','Spark Manufacturing Field Ops','customer',0,NULL,NULL,NULL,'contact@sparkmanufacturing.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p47','Titan Production Prototype Shop','customer',0,NULL,NULL,NULL,'contact@titanproduction.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p48','Cascade Technologies HQ Procurement','customer',0,NULL,NULL,NULL,'contact@cascadetechnologies.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p49','Polar Manufacturing Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@polarmanufacturing.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rA7ECE1BB36_p50','Borough Fabrication Quality Lab','customer',0,NULL,NULL,NULL,'contact@boroughfabrication.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF8BEF50511_q01','Opal Importers','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF8BEF50511_q02','Element Logistics','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF8BEF50511_q03','Quartz Fulfillment','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF8BEF50511_q04','Citadel Components','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF8BEF50511_q05','Arc Holdings','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF8BEF50511_q06','Canton Freight','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF8BEF50511_q07','Brookfield Integrators','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF8BEF50511_q08','Haven Consolidators','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF8BEF50511_q09','Clearwater Supply','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF8BEF50511_q10','Globe Warehousing','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF8BEF50511_q11','Helix Carriers','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF8BEF50511_q12','Pivot Depot','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF8BEF50511_q13','Lakewood Conveyance','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF8BEF50511_q14','Orbital Shipping','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF8BEF50511_q15','Evergreen Industries','vendor',15,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF8BEF50511_q16','Dune Assemblies','vendor',16,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF8BEF50511_q17','Solace Fabrication','vendor',17,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rF8BEF50511_q18','Slate Exporters','vendor',18,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q01','Cosmo Resources','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q02','Marble Carriers','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q03','Redstone Networks','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q04','Cedar Procurement','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q05','Trellis Carriers','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q06','Summit Transit','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q07','Velocity Resources','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q08','Sierra Distribution','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q09','Thornton Procurement','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q10','Anvil Resources','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q11','Circuit Transit','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q12','Ivory Parts Co','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q13','Flint Carriers','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q14','Alpine Carriers','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q15','Westfield Carriers','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q16','Apex Parts Co','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q17','Iron Logistics','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q18','Oxide Logistics','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q19','Bronze Parts Co','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q20','Steel Materials','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q21','Matrix Supply','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q22','Quantum Wholesale','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q23','Ironside Networks','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q24','Catalyst Wholesale','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q25','Skyline Wholesale','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q26','Pinnacle Supply','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q27','Sterling Supply','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q28','Trident Resources','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q29','Cobalt Networks','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q30','Raven Supply','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q31','Axis Parts Co','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q32','Eclipse Sourcing','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q33','Vertex Distribution','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q34','Crestview Distribution','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q35','Osprey Transit','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q36','Fairview Trading','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q37','Riverdale Trading','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q38','Crest Supply','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q39','Baltic Transit','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q40','Lance Freight','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q41','Drift Components','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q42','Zenith Wholesale','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q43','Aurora Materials','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q44','Grove Networks','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q45','Noble Carriers','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q46','Compass Carriers','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q47','Stratos Transit','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q48','Nimbus Logistics','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q49','Spire Networks','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rA7ECE1BB36_q50','Arbor Transit','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF8BEF50511-ELV-LDA-220','Landing Door Assembly Center-Open','Building Systems','consu',4104.74,2424.12,'buy,manufacture',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'PF8BEF50511-ELV-LDA-220','rF8BEF50511_q01','Priority Shuttle lane (8d transit, 12-52 units)',8,12.0,52.0,2381.61);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'PF8BEF50511-ELV-LDA-220','rF8BEF50511_q02','Express Air lane (5d transit, 2-2 units)',5,2.0,2.0,3632.47);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'PF8BEF50511-ELV-LDA-220','rF8BEF50511_q03','Bulk Container lane (25d transit, 85-89 units)',25,85.0,89.0,1351.19);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'PF8BEF50511-ELV-LDA-220','rF8BEF50511_q04','Bulk Container lane (24d transit, 85-86 units)',24,85.0,86.0,1159.77);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'PF8BEF50511-ELV-LDA-220','rF8BEF50511_q05','Hybrid Expedite lane (14d transit, 9-15 units)',14,9.0,15.0,3006.18);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF8BEF50511-SUB-02','Landing Door Assembly Center-Open Subassembly','Building Systems','consu',1234.2,822.8,'manufacture',NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF8BEF50511-ELV-GOV-007','Overspeed Governor Assembly','Building Systems','consu',756.93,381.55,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'PF8BEF50511-ELV-GOV-007','rF8BEF50511_q06','Rapid Works (3d)',3,5.0,23.0,623.33);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'PF8BEF50511-ELV-GOV-007','rF8BEF50511_q07','Domestic Supply (6d)',6,14.0,15.0,388.97);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'PF8BEF50511-ELV-GOV-007','rF8BEF50511_q08','Import Consolidator (6d)',6,37.0,63.0,381.55);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF8BEF50511-ELV-INS-010','Car Top Inspection Box','Building Systems','consu',300.42,130.78,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'PF8BEF50511-ELV-INS-010','rF8BEF50511_q09','Rapid Works (4d)',4,10.0,16.0,195.79);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'PF8BEF50511-ELV-INS-010','rF8BEF50511_q10','Import Consolidator (6d)',6,24.0,58.0,130.78);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'PF8BEF50511-ELV-INS-010','rF8BEF50511_q11','Domestic Supply (4d)',4,21.0,63.0,153.54);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'PF8BEF50511-ELV-INS-010','rF8BEF50511_q12','Hybrid Fabricators (4d)',4,12.0,49.0,172.88);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF8BEF50511-ELV-SHV-002','Deflector Sheave Assembly','Building Systems','consu',689.95,329.78,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'PF8BEF50511-ELV-SHV-002','rF8BEF50511_q13','Rapid Works (3d)',3,12.0,20.0,523.94);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'PF8BEF50511-ELV-SHV-002','rF8BEF50511_q14','Hybrid Fabricators (4d)',4,13.0,31.0,468.43);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'PF8BEF50511-ELV-SHV-002','rF8BEF50511_q15','Import Consolidator (4d)',4,31.0,42.0,329.78);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PF8BEF50511-ELV-ENC-003','Incremental Shaft Encoder','Building Systems','consu',314.57,154.82,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'PF8BEF50511-ELV-ENC-003','rF8BEF50511_q16','Rapid Works (3d)',3,5.0,52.0,237.72);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'PF8BEF50511-ELV-ENC-003','rF8BEF50511_q17','Domestic Supply (4d)',4,14.0,108.0,195.71);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'PF8BEF50511-ELV-ENC-003','rF8BEF50511_q18','Import Consolidator (4d)',4,30.0,70.0,154.82);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A001','High-Torque Push Button Module','Replacement Parts','consu',255.23,173.52,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'PA7ECE1BB36-A001','rA7ECE1BB36_q01','Standard delivery',8,1.0,24.0,171.24);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A002','Quick-Release Traction Motor','Industrial Spare Parts','consu',363.9,191.16,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'PA7ECE1BB36-A002','rA7ECE1BB36_q02','Cross-dock',8,1.0,24.0,185.01);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A003','Non-Magnetic Traction Motor','Hardware Accessories','consu',239.36,156.82,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'PA7ECE1BB36-A003','rA7ECE1BB36_q03','Warehouse direct',5,1.0,24.0,156.63);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A004','Hardened Panel Stainless','Power Transmission','consu',203.66,137.27,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'PA7ECE1BB36-A004','rA7ECE1BB36_q04','Scheduled freight',8,1.0,24.0,142.64);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A005','High-Performance Door Panel Stainless','Hardware Accessories','consu',324.92,172.98,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'PA7ECE1BB36-A005','rA7ECE1BB36_q05','Cross-dock',3,1.0,24.0,177.78);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A006','Single-Stage Deflector Sheave Assembly','Electrical Components','consu',266.03,151.41,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'PA7ECE1BB36-A006','rA7ECE1BB36_q06','Warehouse direct',8,1.0,24.0,161.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A007','Commercial Overspeed Governor Assembly','Replacement Parts','consu',223.79,127.69,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'PA7ECE1BB36-A007','rA7ECE1BB36_q07','Local pickup',4,1.0,24.0,123.95);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A008','Anti-Vibration Panel Stainless','Hardware Accessories','consu',316.82,220.61,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'PA7ECE1BB36-A008','rA7ECE1BB36_q08','Express route',6,1.0,24.0,226.63);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A009','Low-Friction Inspection Box','Seals and Gaskets','consu',227.6,126.21,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'PA7ECE1BB36-A009','rA7ECE1BB36_q09','Express route',3,1.0,24.0,121.51);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A010','Metric Top Inspection Box','Electrical Components','consu',333.02,180.44,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'PA7ECE1BB36-A010','rA7ECE1BB36_q10','Express route',4,1.0,24.0,189.54);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A011','Self-Lubricating Door Panel Stainless','Hardware Accessories','consu',319.12,217.23,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'PA7ECE1BB36-A011','rA7ECE1BB36_q11','Cross-dock',5,1.0,24.0,207.87);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A012','Modular Door Panel Stainless','Seals and Gaskets','consu',204.58,124.94,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'PA7ECE1BB36-A012','rA7ECE1BB36_q12','Standard delivery',8,1.0,24.0,124.49);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A013','Weatherproof Drive Kit','Electrical Components','consu',349.34,233.82,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'PA7ECE1BB36-A013','rA7ECE1BB36_q13','Cross-dock',8,1.0,24.0,233.26);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A014','Compact Drive Kit','Industrial Spare Parts','consu',224.54,119.29,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'PA7ECE1BB36-A014','rA7ECE1BB36_q14','Express route',3,1.0,24.0,127.38);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A015','High-Flow Shaft Encoder','Electrical Components','consu',190.91,108.73,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'PA7ECE1BB36-A015','rA7ECE1BB36_q15','Cross-dock',6,1.0,24.0,105.76);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A016','Reinforced Drive Kit','Maintenance Supplies','consu',227.09,134.99,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'PA7ECE1BB36-A016','rA7ECE1BB36_q16','Cross-dock',6,1.0,24.0,128.43);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A017','Thermal-Guard Rope Set 12mm','Mechanical Components','consu',359.21,253.2,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'PA7ECE1BB36-A017','rA7ECE1BB36_q17','Bulk shipment',6,1.0,24.0,250.83);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A018','Rapid-Lock Gear Set','Power Transmission','consu',292.49,163.47,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'PA7ECE1BB36-A018','rA7ECE1BB36_q18','Local pickup',7,1.0,24.0,171.91);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A019','Impact-Rated Electromagnetic Guide Shoe','Replacement Parts','consu',318.02,214.67,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'PA7ECE1BB36-A019','rA7ECE1BB36_q19','Standard delivery',7,1.0,24.0,225.72);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A020','Universal Drive Kit','Fasteners and Fixings','consu',205.74,143.57,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'PA7ECE1BB36-A020','rA7ECE1BB36_q20','Regional lane',5,1.0,24.0,154.8);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A021','High-Cycle Door Panel Stainless','Power Transmission','consu',307.99,184.47,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'PA7ECE1BB36-A021','rA7ECE1BB36_q21','Bulk shipment',8,1.0,24.0,182.34);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A022','Snap-Fit Ceiling Panel','Pneumatic Components','consu',338.3,209.01,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'PA7ECE1BB36-A022','rA7ECE1BB36_q22','Cross-dock',6,1.0,24.0,200.72);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A023','Low-Flow Belt Drive Kit','Replacement Parts','consu',302.19,159.79,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'PA7ECE1BB36-A023','rA7ECE1BB36_q23','Cross-dock',6,1.0,24.0,159.37);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A024','Wide-Body Push Button Module','Power Transmission','consu',419.9,247.53,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'PA7ECE1BB36-A024','rA7ECE1BB36_q24','Express route',3,1.0,24.0,235.54);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A025','Adjustable Gear Set','Maintenance Supplies','consu',261.83,179.18,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'PA7ECE1BB36-A025','rA7ECE1BB36_q25','Standard delivery',5,1.0,24.0,174.42);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A026','Medical-Grade Overspeed Governor Assembly','Electrical Components','consu',285.3,154.73,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'PA7ECE1BB36-A026','rA7ECE1BB36_q26','Regional lane',4,1.0,24.0,156.57);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A027','Heavy-Duty Belt Drive Kit','Seals and Gaskets','consu',309.68,181.85,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'PA7ECE1BB36-A027','rA7ECE1BB36_q27','Regional lane',7,1.0,24.0,187.49);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A028','High-Temp Belt Drive Kit','Replacement Parts','consu',361.91,228.8,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'PA7ECE1BB36-A028','rA7ECE1BB36_q28','Local pickup',7,1.0,24.0,230.48);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A029','Spring-Loaded Guide Shoe','Fasteners and Fixings','consu',196.15,128.72,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'PA7ECE1BB36-A029','rA7ECE1BB36_q29','Warehouse direct',5,1.0,24.0,137.76);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A030','Cold-Rolled Door Panel Stainless','Seals and Gaskets','consu',285.42,203.77,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'PA7ECE1BB36-A030','rA7ECE1BB36_q30','Express route',4,1.0,24.0,210.12);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A031','Narrow-Body Set 12mm','Mechanical Components','consu',309.51,216.81,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'PA7ECE1BB36-A031','rA7ECE1BB36_q31','Scheduled freight',3,1.0,24.0,218.8);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A032','Low-Temp Guide Shoe','Maintenance Supplies','consu',249.85,130.45,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'PA7ECE1BB36-A032','rA7ECE1BB36_q32','Regional lane',8,1.0,24.0,130.25);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A033','Low-Noise Electromagnetic Guide Shoe','Replacement Parts','consu',323.22,209.41,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'PA7ECE1BB36-A033','rA7ECE1BB36_q33','Warehouse direct',3,1.0,24.0,205.52);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A034','Standard Drive Kit','Seals and Gaskets','consu',267.06,178.3,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'PA7ECE1BB36-A034','rA7ECE1BB36_q34','Regional lane',7,1.0,24.0,188.06);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A035','Economy Electromagnetic Guide Shoe','Maintenance Supplies','consu',297.8,199.61,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'PA7ECE1BB36-A035','rA7ECE1BB36_q35','Bulk shipment',3,1.0,24.0,209.06);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A036','Lightweight Shaft Encoder','Seals and Gaskets','consu',264.58,183.1,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'PA7ECE1BB36-A036','rA7ECE1BB36_q36','Warehouse direct',8,1.0,24.0,191.47);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A037','Zero-Backlash Shaft Encoder','Mechanical Components','consu',244.35,144.58,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'PA7ECE1BB36-A037','rA7ECE1BB36_q37','Cross-dock',3,1.0,24.0,146.64);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A038','Flanged Shaft Encoder','Electrical Components','consu',357.06,205.7,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'PA7ECE1BB36-A038','rA7ECE1BB36_q38','Scheduled freight',8,1.0,24.0,209.7);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A039','Precision Guide Shoe','Hardware Accessories','consu',227.53,139.75,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(57,'PA7ECE1BB36-A039','rA7ECE1BB36_q39','Local pickup',3,1.0,24.0,137.44);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A040','Extended-Life Belt Drive Kit','Pneumatic Components','consu',316.63,192.07,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(58,'PA7ECE1BB36-A040','rA7ECE1BB36_q40','Standard delivery',6,1.0,24.0,183.74);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A041','Low-Profile Governor Assembly','Power Transmission','consu',268.79,177.3,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(59,'PA7ECE1BB36-A041','rA7ECE1BB36_q41','Bulk shipment',7,1.0,24.0,174.91);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A042','Stainless LED Ceiling Panel','Mechanical Components','consu',320.44,183.3,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(60,'PA7ECE1BB36-A042','rA7ECE1BB36_q42','Regional lane',4,1.0,24.0,181.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A043','Food-Grade Set 12mm','Power Transmission','consu',297.3,200.35,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(61,'PA7ECE1BB36-A043','rA7ECE1BB36_q43','Warehouse direct',6,1.0,24.0,215.35);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A044','Cleanroom Deflector Sheave Assembly','Electrical Components','consu',373.04,217.83,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(62,'PA7ECE1BB36-A044','rA7ECE1BB36_q44','Local pickup',7,1.0,24.0,221.22);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A045','Premium Button Module','Maintenance Supplies','consu',273.05,163.06,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(63,'PA7ECE1BB36-A045','rA7ECE1BB36_q45','Express route',5,1.0,24.0,159.93);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A046','Dual-Stage Traction Motor','Hardware Accessories','consu',361.37,239.64,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(64,'PA7ECE1BB36-A046','rA7ECE1BB36_q46','Express route',3,1.0,24.0,255.45);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A047','Tapered Safety Gear Set','Fasteners and Fixings','consu',358.66,187.89,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(65,'PA7ECE1BB36-A047','rA7ECE1BB36_q47','Standard delivery',6,1.0,24.0,179.28);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A048','UV-Stable Governor Assembly','Industrial Spare Parts','consu',197.08,124.36,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(66,'PA7ECE1BB36-A048','rA7ECE1BB36_q48','Bulk shipment',4,1.0,24.0,119.72);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A049','Industrial Set 12mm','Pneumatic Components','consu',300.52,215.21,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(67,'PA7ECE1BB36-A049','rA7ECE1BB36_q49','Express route',4,1.0,24.0,219.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PA7ECE1BB36-A050','Heat-Treated Door Panel Stainless','Power Transmission','consu',264.45,174.59,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(68,'PA7ECE1BB36-A050','rA7ECE1BB36_q50','Regional lane',8,1.0,24.0,170.6);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'PF8BEF50511-SUB-02','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PF8BEF50511-ELV-SHV-002',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PF8BEF50511-ELV-ENC-003',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'PF8BEF50511-ELV-LDA-220','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PF8BEF50511-SUB-02',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PF8BEF50511-ELV-GOV-007',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PF8BEF50511-ELV-INS-010',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'PA7ECE1BB36-A041','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'PA7ECE1BB36-A015',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'PA7ECE1BB36-A050','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'PA7ECE1BB36-A046',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'PA7ECE1BB36-A031',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'PA7ECE1BB36-A048','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'PA7ECE1BB36-A049',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'PA7ECE1BB36-A035','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'PA7ECE1BB36-A008',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'PA7ECE1BB36-A014','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'PA7ECE1BB36-A003',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'PA7ECE1BB36-A015','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'PA7ECE1BB36-A014',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'PA7ECE1BB36-A003','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'PA7ECE1BB36-A041',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'PA7ECE1BB36-A044','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'PA7ECE1BB36-A033',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'PA7ECE1BB36-A030',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(11,'PA7ECE1BB36-A049','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'PA7ECE1BB36-A041',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(12,'PA7ECE1BB36-A005','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(12,'PA7ECE1BB36-A028',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(12,'PA7ECE1BB36-A037',2.0);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PF8BEF50511-WC02','Fabrication Cell 2',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PF8BEF50511-WC03','Precision Bench 3',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PF8BEF50511-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('PF8BEF50511-WC03','Precision Bench 3',0,0,NULL,NULL);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF8BEF50511-ELV-ENC-003',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF8BEF50511-ELV-GOV-007',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF8BEF50511-ELV-INS-010',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF8BEF50511-ELV-LDA-220',NULL,76.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PF8BEF50511-ELV-SHV-002',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A001',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A002',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A003',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A004',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A005',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A006',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A007',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A008',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A009',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A010',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A011',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A012',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A013',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A014',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A015',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A016',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A017',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A018',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A019',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A020',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A021',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A022',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A023',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A024',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A025',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A026',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A027',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A028',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A029',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A030',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A031',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A032',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A033',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A034',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A035',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A036',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A037',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A038',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A039',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A040',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A041',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A042',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A043',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A044',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A045',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A046',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A047',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A048',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A049',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PA7ECE1BB36-A050',NULL,12.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'rF8BEF50511_c01','PF8BEF50511-ELV-LDA-220',14,8,61490.83,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'rF8BEF50511_c02','PF8BEF50511-ELV-LDA-220',25,9,111963.96,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'rF8BEF50511_c03','PF8BEF50511-ELV-LDA-220',18,10,79807.06,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'rF8BEF50511_c04','PF8BEF50511-ELV-LDA-220',18,10,77807.61,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'rF8BEF50511_c05','PF8BEF50511-ELV-LDA-220',25,12,107432.57,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'rF8BEF50511_c06','PF8BEF50511-ELV-LDA-220',15,12,67991.56,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'rF8BEF50511_c07','PF8BEF50511-ELV-LDA-220',17,13,76028.34,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'rF8BEF50511_c08','PF8BEF50511-ELV-LDA-220',22,13,97011.32,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(9,'rF8BEF50511_c09','PF8BEF50511-ELV-LDA-220',17,14,72307.05,NULL);
