-- agentic-labs/erp-bench scenario 2055: Split System Heat Pump 5-Ton
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r236D3035F4_c01','Monarch Interactive','customer',0,100345.78,NULL,NULL,'orders@monarchinteractive.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r236D3035F4_c02','Thornton Sciences','customer',0,95541.91,NULL,NULL,'orders@thorntonsciences.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r236D3035F4_c03','Keystone Reserve','customer',0,107975.67,NULL,NULL,'orders@keystonereserve.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r236D3035F4_c04','Ivory Solutions Group','customer',0,76153.25,NULL,NULL,'orders@ivorysolutionsgroup.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r236D3035F4_c05','Ashford Brands','customer',0,78458.75,NULL,NULL,'orders@ashfordbrands.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r236D3035F4_c06','Spectra Workspaces','customer',0,107224.93,NULL,NULL,'orders@spectraworkspaces.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r236D3035F4_c07','Grove Architects','customer',0,143375.85,NULL,NULL,'orders@grovearchitects.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r236D3035F4_c08','Horizon Supply Co','customer',0,136440.1,NULL,NULL,'orders@horizonsupplyco.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r236D3035F4_c09','Circuit Trust','customer',0,142904.56,NULL,NULL,'orders@circuittrust.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p01','Drift Technologies Site Logistics','customer',0,NULL,NULL,NULL,'contact@drifttechnologies.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p02','Baseline Solutions Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@baselinesolutions.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p03','Sterling Services Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@sterlingservices.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p04','Ridgeline Services R&D Workshop','customer',0,NULL,NULL,NULL,'contact@ridgelineservices.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p05','Aegis Operations Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@aegisoperations.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p06','Raven Fabrication Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@ravenfabrication.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p07','Gateway Solutions Field Ops','customer',0,NULL,NULL,NULL,'contact@gatewaysolutions.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p08','Jade Fabrication Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@jadefabrication.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p09','Sentinel Operations HQ Procurement','customer',0,NULL,NULL,NULL,'contact@sentineloperations.warehouse.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p10','Anvil Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@anvilassembly.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p11','Eclipse Engineering Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@eclipseengineering.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p12','Globe Technologies R&D Workshop','customer',0,NULL,NULL,NULL,'contact@globetechnologies.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p13','Silverline Production HQ Procurement','customer',0,NULL,NULL,NULL,'contact@silverlineproduction.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p14','Cascade Services Quality Lab','customer',0,NULL,NULL,NULL,'contact@cascadeservices.ops-mail.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p15','Millbrook Fabrication Quality Lab','customer',0,NULL,NULL,NULL,'contact@millbrookfabrication.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p16','Atlas Manufacturing R&D Workshop','customer',0,NULL,NULL,NULL,'contact@atlasmanufacturing.logistics.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p17','Bridgeway Production Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@bridgewayproduction.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p18','Slate Production Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@slateproduction.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p19','Crown Operations Test Facility','customer',0,NULL,NULL,NULL,'contact@crownoperations.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p20','Crestview Technologies Test Facility','customer',0,NULL,NULL,NULL,'contact@crestviewtechnologies.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p21','Iron Services Prototype Shop','customer',0,NULL,NULL,NULL,'contact@ironservices.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p22','Alloy Assembly Quality Lab','customer',0,NULL,NULL,NULL,'contact@alloyassembly.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p23','Forge Operations Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@forgeoperations.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p24','Zenith Manufacturing Site Logistics','customer',0,NULL,NULL,NULL,'contact@zenithmanufacturing.procurement.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p25','Bronze Engineering Site Logistics','customer',0,NULL,NULL,NULL,'contact@bronzeengineering.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p26','Vertex Services Quality Lab','customer',0,NULL,NULL,NULL,'contact@vertexservices.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p27','Chrome Production Field Ops','customer',0,NULL,NULL,NULL,'contact@chromeproduction.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p28','Velocity Manufacturing Site Logistics','customer',0,NULL,NULL,NULL,'contact@velocitymanufacturing.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p29','Vantage Industries Site Logistics','customer',0,NULL,NULL,NULL,'contact@vantageindustries.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p30','Marble Production Field Ops','customer',0,NULL,NULL,NULL,'contact@marbleproduction.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p31','Polar Solutions Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@polarsolutions.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p32','Aether Solutions HQ Procurement','customer',0,NULL,NULL,NULL,'contact@aethersolutions.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p33','Granite Assembly Test Facility','customer',0,NULL,NULL,NULL,'contact@graniteassembly.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p34','Sapphire Engineering Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@sapphireengineering.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p35','Brookfield Services Field Ops','customer',0,NULL,NULL,NULL,'contact@brookfieldservices.procurement.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p36','Citadel Manufacturing Tooling Center','customer',0,NULL,NULL,NULL,'contact@citadelmanufacturing.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p37','Coral Manufacturing Quality Lab','customer',0,NULL,NULL,NULL,'contact@coralmanufacturing.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p38','Flux Fabrication R&D Workshop','customer',0,NULL,NULL,NULL,'contact@fluxfabrication.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p39','Osprey Technologies Tooling Center','customer',0,NULL,NULL,NULL,'contact@ospreytechnologies.supply-chain.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p40','Apex Operations Test Facility','customer',0,NULL,NULL,NULL,'contact@apexoperations.supply-chain.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p41','Element Assembly Tooling Center','customer',0,NULL,NULL,NULL,'contact@elementassembly.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p42','Matrix Manufacturing Test Facility','customer',0,NULL,NULL,NULL,'contact@matrixmanufacturing.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p43','Compass Manufacturing Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@compassmanufacturing.sourcing.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p44','Quartz Industries Field Ops','customer',0,NULL,NULL,NULL,'contact@quartzindustries.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p45','Lance Industries Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@lanceindustries.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p46','Cipher Industries Test Facility','customer',0,NULL,NULL,NULL,'contact@cipherindustries.supply-chain.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p47','Echo Industries Test Facility','customer',0,NULL,NULL,NULL,'contact@echoindustries.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p48','Opal Industries Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@opalindustries.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p49','Ironside Engineering Field Ops','customer',0,NULL,NULL,NULL,'contact@ironsideengineering.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('rAABAFB4335_p50','Northbridge Manufacturing Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@northbridgemanufacturing.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r236D3035F4_q01','Spark Components','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r236D3035F4_q02','Quantum Fabrication','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r236D3035F4_q03','Spire Warehouse','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r236D3035F4_q04','Haven Transport','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r236D3035F4_q05','Blaze Provisions','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r236D3035F4_q06','Scion Holdings','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q01','Oakmont Trading','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q02','Bayshore Networks','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q03','Lumen Networks','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q04','Beacon Logistics','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q05','Ridge Resources','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q06','Crest Logistics','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q07','Nimbus Procurement','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q08','Conduit Trading','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q09','Stonewall Components','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q10','Ledger Transit','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q11','Arc Materials','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q12','Axis Networks','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q13','Titan Distribution','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q14','Mosaic Procurement','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q15','Pivot Distribution','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q16','Lakewood Transit','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q17','Cobalt Supply','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q18','Summit Supply','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q19','Pacific Resources','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q20','Ember Components','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q21','Clearwater Transit','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q22','Steel Materials','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q23','Indigo Distribution','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q24','Garnet Wholesale','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q25','Dune Networks','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q26','Skyline Components','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q27','Alpine Materials','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q28','Stratos Trading','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q29','Lattice Transit','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q30','Copper Supply','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q31','Trident Parts Co','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q32','Meridian Sourcing','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q33','Pinnacle Components','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q34','Evergreen Trading','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q35','Fairview Procurement','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q36','Trellis Materials','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q37','Flint Networks','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q38','Cosmo Trading','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q39','Arbor Wholesale','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q40','Comet Sourcing','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q41','Cedar Sourcing','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q42','Ironwood Sourcing','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q43','Riverdale Sourcing','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q44','Sierra Carriers','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q45','Solace Sourcing','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q46','Prism Wholesale','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q47','Canton Components','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q48','Noble Parts Co','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q49','Terra Networks','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('rAABAFB4335_q50','Borough Resources','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P236D3035F4-HVC-SHP-002','Split System Heat Pump 5-Ton','Building Systems','consu',5085.5,3226.99,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'P236D3035F4-HVC-SHP-002','r236D3035F4_q01','Priority Shuttle lane (9d transit, 7-28 units)',9,7.0,28.0,3125.72);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'P236D3035F4-HVC-SHP-002','r236D3035F4_q02','Express Air lane (8d transit, 1-13 units)',8,1.0,13.0,3881.65);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'P236D3035F4-HVC-SHP-002','r236D3035F4_q03','Bulk Container lane (24d transit, 90-107 units)',24,90.0,107.0,1663.97);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'P236D3035F4-HVC-SHP-002','r236D3035F4_q04','Microfactory Build-to-Order lane (9d transit, 6-30 units)',9,6.0,30.0,4030.22);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'P236D3035F4-HVC-SHP-002','r236D3035F4_q05','Regional Cross-Dock lane (12d transit, 8-43 units)',12,8.0,43.0,2676.29);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'P236D3035F4-HVC-SHP-002','r236D3035F4_q06','Hybrid Expedite lane (12d transit, 9-10 units)',12,9.0,10.0,3604.01);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A001','Standard Coil Assembly','Electrical Components','consu',338.61,204.52,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'PAABAFB4335-A001','rAABAFB4335_q01','Standard delivery',3,1.0,24.0,209.59);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A002','Precision Coil Assembly','Fasteners and Fixings','consu',315.47,181.15,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'PAABAFB4335-A002','rAABAFB4335_q02','Express route',5,1.0,24.0,193.19);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A003','Low-Friction Scroll Compressor 10HP','Power Transmission','consu',350.99,188.55,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'PAABAFB4335-A003','rAABAFB4335_q03','Standard delivery',8,1.0,24.0,194.97);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A004','Extended-Life Drive Module','Hardware Accessories','consu',314.33,203.12,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'PAABAFB4335-A004','rAABAFB4335_q04','Regional lane',8,1.0,24.0,213.92);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A005','Self-Lubricating Condensate Drain Pan','Pneumatic Components','consu',351.77,251.74,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'PAABAFB4335-A005','rAABAFB4335_q05','Bulk shipment',6,1.0,24.0,260.82);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A006','High-Cycle Condenser Coil Assembly','Mechanical Components','consu',339.84,226.86,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'PAABAFB4335-A006','rAABAFB4335_q06','Scheduled freight',3,1.0,24.0,233.03);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A007','Compact Motor Assembly','Fasteners and Fixings','consu',322.89,231.28,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'PAABAFB4335-A007','rAABAFB4335_q07','Local pickup',6,1.0,24.0,239.42);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A008','Rapid-Lock Drive Module','Electrical Components','consu',265.96,170.93,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'PAABAFB4335-A008','rAABAFB4335_q08','Warehouse direct',6,1.0,24.0,183.8);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A009','Industrial Coil Assembly','Replacement Parts','consu',212.09,115.46,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'PAABAFB4335-A009','rAABAFB4335_q09','Express route',5,1.0,24.0,111.75);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A010','Snap-Fit Condensate Drain Pan','Replacement Parts','consu',346.43,199.06,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'PAABAFB4335-A010','rAABAFB4335_q10','Bulk shipment',4,1.0,24.0,198.99);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A011','High-Flow Plate Pack','Industrial Spare Parts','consu',189.5,115.15,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'PAABAFB4335-A011','rAABAFB4335_q11','Warehouse direct',5,1.0,24.0,114.81);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A012','Low-Flow Condensate Drain Pan','Fasteners and Fixings','consu',379.19,200.36,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'PAABAFB4335-A012','rAABAFB4335_q12','Warehouse direct',3,1.0,24.0,210.86);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A013','Anodized Electronic Control Board','Seals and Gaskets','consu',229.06,142.67,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'PAABAFB4335-A013','rAABAFB4335_q13','Warehouse direct',3,1.0,24.0,138.36);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A014','Double-Row Evaporator Coil Assembly','Seals and Gaskets','consu',266.03,184.52,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'PAABAFB4335-A014','rAABAFB4335_q14','Warehouse direct',8,1.0,24.0,196.99);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A015','Low-Profile Expansion Valve','Pneumatic Components','consu',266.13,189.5,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'PAABAFB4335-A015','rAABAFB4335_q15','Express route',6,1.0,24.0,194.17);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A016','Pressure-Balanced Evaporator Coil Assembly','Fasteners and Fixings','consu',281.21,192.12,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'PAABAFB4335-A016','rAABAFB4335_q16','Warehouse direct',5,1.0,24.0,194.06);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A017','Quick-Release Scroll Compressor 10HP','Power Transmission','consu',185.48,119.95,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'PAABAFB4335-A017','rAABAFB4335_q17','Local pickup',8,1.0,24.0,120.72);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A018','High-Torque Drive Module','Industrial Spare Parts','consu',367.35,237.89,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'PAABAFB4335-A018','rAABAFB4335_q18','Standard delivery',6,1.0,24.0,240.04);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A019','Spring-Loaded Reversing Valve Assembly','Maintenance Supplies','consu',305.0,159.57,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'PAABAFB4335-A019','rAABAFB4335_q19','Standard delivery',4,1.0,24.0,152.12);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A020','Low-Temp Drain Pan','Power Transmission','consu',212.72,125.15,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'PAABAFB4335-A020','rAABAFB4335_q20','Standard delivery',5,1.0,24.0,120.87);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A021','Metric Compressor 10HP','Electrical Components','consu',375.06,257.4,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'PAABAFB4335-A021','rAABAFB4335_q21','Warehouse direct',4,1.0,24.0,261.69);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A022','Premium Housing Panel Set','Pneumatic Components','consu',310.23,222.48,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'PAABAFB4335-A022','rAABAFB4335_q22','Express route',8,1.0,24.0,234.53);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A023','Flanged Housing Panel Set','Electrical Components','consu',322.49,208.55,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'PAABAFB4335-A023','rAABAFB4335_q23','Standard delivery',7,1.0,24.0,217.27);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A024','High-Temp Line Set 25ft','Mechanical Components','consu',334.12,229.61,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'PAABAFB4335-A024','rAABAFB4335_q24','Scheduled freight',8,1.0,24.0,241.95);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A025','UV-Stable Line Set 25ft','Seals and Gaskets','consu',315.66,216.92,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'PAABAFB4335-A025','rAABAFB4335_q25','Cross-dock',6,1.0,24.0,231.43);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A026','Medical-Grade Condenser Coil Assembly','Electrical Components','consu',207.65,140.28,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'PAABAFB4335-A026','rAABAFB4335_q26','Warehouse direct',5,1.0,24.0,137.3);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A027','Corrosion-Resistant Electronic Control Board','Pneumatic Components','consu',343.03,233.69,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'PAABAFB4335-A027','rAABAFB4335_q27','Local pickup',6,1.0,24.0,230.71);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A028','Impact-Rated Speed Drive Module','Hardware Accessories','consu',204.35,143.25,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'PAABAFB4335-A028','rAABAFB4335_q28','Warehouse direct',4,1.0,24.0,153.96);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A029','Narrow-Body Thermostatic Expansion Valve','Power Transmission','consu',371.69,233.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'PAABAFB4335-A029','rAABAFB4335_q29','Cross-dock',8,1.0,24.0,241.97);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A030','Powder-Coated Set 25ft','Power Transmission','consu',318.02,220.53,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'PAABAFB4335-A030','rAABAFB4335_q30','Standard delivery',7,1.0,24.0,229.14);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A031','Wide-Body Control Board','Mechanical Components','consu',205.53,140.55,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'PAABAFB4335-A031','rAABAFB4335_q31','Warehouse direct',4,1.0,24.0,142.59);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A032','Food-Grade Scroll Compressor 10HP','Maintenance Supplies','consu',388.71,277.67,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'PAABAFB4335-A032','rAABAFB4335_q32','Cross-dock',6,1.0,24.0,275.99);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A033','Commercial Scroll Compressor 10HP','Replacement Parts','consu',400.15,255.48,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'PAABAFB4335-A033','rAABAFB4335_q33','Local pickup',5,1.0,24.0,274.46);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A034','Reinforced Reversing Valve Assembly','Hardware Accessories','consu',192.35,129.4,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'PAABAFB4335-A034','rAABAFB4335_q34','Cross-dock',5,1.0,24.0,130.97);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A035','Sealed Scroll Compressor 10HP','Hardware Accessories','consu',343.63,222.14,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'PAABAFB4335-A035','rAABAFB4335_q35','Warehouse direct',6,1.0,24.0,225.43);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A036','Heat-Treated Exchanger Plate Pack','Mechanical Components','consu',213.05,111.33,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'PAABAFB4335-A036','rAABAFB4335_q36','Regional lane',3,1.0,24.0,117.56);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A037','Anti-Vibration Plate Pack','Fasteners and Fixings','consu',376.39,250.26,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'PAABAFB4335-A037','rAABAFB4335_q37','Local pickup',5,1.0,24.0,264.28);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A038','Cleanroom Exchanger Plate Pack','Maintenance Supplies','consu',230.38,162.55,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'PAABAFB4335-A038','rAABAFB4335_q38','Express route',6,1.0,24.0,158.95);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A039','Zero-Backlash Drive Module','Mechanical Components','consu',358.29,257.22,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'PAABAFB4335-A039','rAABAFB4335_q39','Cross-dock',5,1.0,24.0,248.71);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A040','Tapered Drive Module','Industrial Spare Parts','consu',391.36,249.35,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'PAABAFB4335-A040','rAABAFB4335_q40','Bulk shipment',4,1.0,24.0,249.95);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A041','Adjustable Evaporator Coil Assembly','Electrical Components','consu',347.03,217.24,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'PAABAFB4335-A041','rAABAFB4335_q41','Warehouse direct',8,1.0,24.0,208.36);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A042','Cold-Rolled Blower Motor Assembly','Replacement Parts','consu',241.76,136.67,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'PAABAFB4335-A042','rAABAFB4335_q42','Express route',3,1.0,24.0,141.26);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A043','Single-Stage Drive Module','Industrial Spare Parts','consu',202.82,117.5,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'PAABAFB4335-A043','rAABAFB4335_q43','Express route',4,1.0,24.0,121.04);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A044','Modular Exchanger Plate Pack','Industrial Spare Parts','consu',414.42,268.81,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'PAABAFB4335-A044','rAABAFB4335_q44','Express route',5,1.0,24.0,266.06);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A045','Heavy-Duty Filter Media Pack','Maintenance Supplies','consu',371.6,232.24,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'PAABAFB4335-A045','rAABAFB4335_q45','Regional lane',4,1.0,24.0,222.0);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A046','Lightweight Line Set 25ft','Electrical Components','consu',289.44,183.71,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'PAABAFB4335-A046','rAABAFB4335_q46','Express route',4,1.0,24.0,198.24);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A047','Hardened Motor Assembly','Hardware Accessories','consu',309.53,215.72,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'PAABAFB4335-A047','rAABAFB4335_q47','Express route',5,1.0,24.0,221.54);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A048','Stainless Electronic Control Board','Power Transmission','consu',238.58,124.41,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'PAABAFB4335-A048','rAABAFB4335_q48','Bulk shipment',3,1.0,24.0,133.2);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A049','Thermal-Guard Compressor 10HP','Maintenance Supplies','consu',405.13,237.73,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'PAABAFB4335-A049','rAABAFB4335_q49','Cross-dock',6,1.0,24.0,243.27);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('PAABAFB4335-A050','Low-Noise Panel Set','Replacement Parts','consu',371.99,218.98,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'PAABAFB4335-A050','rAABAFB4335_q50','Regional lane',6,1.0,24.0,225.35);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'PAABAFB4335-A020','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PAABAFB4335-A019',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'PAABAFB4335-A028',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'PAABAFB4335-A048','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'PAABAFB4335-A031',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'PAABAFB4335-A032','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'PAABAFB4335-A045',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'PAABAFB4335-A050','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'PAABAFB4335-A024',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'PAABAFB4335-A026',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'PAABAFB4335-A009','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'PAABAFB4335-A027',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'PAABAFB4335-A023',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'PAABAFB4335-A012','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'PAABAFB4335-A047',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'PAABAFB4335-A023',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'PAABAFB4335-A023','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'PAABAFB4335-A050',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'PAABAFB4335-A024',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'PAABAFB4335-A015','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'PAABAFB4335-A022',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'PAABAFB4335-A027',2.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'PAABAFB4335-A006','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'PAABAFB4335-A021',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'PAABAFB4335-A030','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'PAABAFB4335-A028',3.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'PAABAFB4335-A041',1.0);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P236D3035F4-HVC-SHP-002',NULL,78.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A001',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A002',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A003',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A004',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A005',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A006',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A007',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A008',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A009',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A010',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A011',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A012',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A013',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A014',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A015',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A016',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A017',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A018',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A019',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A020',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A021',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A022',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A023',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A024',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A025',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A026',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A027',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A028',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A029',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A030',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A031',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A032',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A033',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A034',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A035',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A036',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A037',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A038',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A039',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A040',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A041',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A042',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A043',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A044',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A045',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A046',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A047',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A048',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A049',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('PAABAFB4335-A050',NULL,13.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'r236D3035F4_c01','P236D3035F4-HVC-SHP-002',18,9,100345.78,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'r236D3035F4_c02','P236D3035F4-HVC-SHP-002',18,9,95541.91,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'r236D3035F4_c03','P236D3035F4-HVC-SHP-002',19,10,107975.67,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'r236D3035F4_c04','P236D3035F4-HVC-SHP-002',14,10,76153.25,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'r236D3035F4_c05','P236D3035F4-HVC-SHP-002',15,11,78458.75,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'r236D3035F4_c06','P236D3035F4-HVC-SHP-002',19,12,107224.93,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'r236D3035F4_c07','P236D3035F4-HVC-SHP-002',26,12,143375.85,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'r236D3035F4_c08','P236D3035F4-HVC-SHP-002',25,12,136440.1,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(9,'r236D3035F4_c09','P236D3035F4-HVC-SHP-002',26,13,142904.56,NULL);
