-- agentic-labs/erp-bench scenario 2216: Labeling Applicator System
-- Seeded verbatim from the source scenario_data.json. SIMULATION ONLY.

INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r22B8FDBB6B_c01','Northbridge Studios East','customer',0,114112.83,NULL,NULL,'orders@northbridgestudioseast.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r22B8FDBB6B_c02','Terra Partners','customer',0,147849.8,NULL,NULL,'orders@terrapartners.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r22B8FDBB6B_c03','Spire Society','customer',0,177622.51,NULL,NULL,'orders@spiresociety.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r22B8FDBB6B_c04','Lakewood Dynamics','customer',0,138307.83,NULL,NULL,'orders@lakewooddynamics.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r22B8FDBB6B_c05','Trellis Designs','customer',0,157717.95,NULL,NULL,'orders@trellisdesigns.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r22B8FDBB6B_c06','Fairview Clinics','customer',0,151142.57,NULL,NULL,'orders@fairviewclinics.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r22B8FDBB6B_c07','Oxide Exchange','customer',0,212008.03,NULL,NULL,'orders@oxideexchange.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r22B8FDBB6B_c08','Vantage Alliance','customer',0,183089.13,NULL,NULL,'orders@vantagealliance.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r22B8FDBB6B_c09','Haven Lyceum','customer',0,234947.0,NULL,NULL,'orders@havenlyceum.io',NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p01','Drift Production Tooling Center','customer',0,NULL,NULL,NULL,'contact@driftproduction.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p02','Ironwood Manufacturing R&D Workshop','customer',0,NULL,NULL,NULL,'contact@ironwoodmanufacturing.sourcing.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p03','Alloy Operations R&D Workshop','customer',0,NULL,NULL,NULL,'contact@alloyoperations.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p04','Spectra Services Site Logistics','customer',0,NULL,NULL,NULL,'contact@spectraservices.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p05','Marble Engineering Prototype Shop','customer',0,NULL,NULL,NULL,'contact@marbleengineering.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p06','Cascade Technologies Field Ops','customer',0,NULL,NULL,NULL,'contact@cascadetechnologies.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p07','Keystone Production HQ Procurement','customer',0,NULL,NULL,NULL,'contact@keystoneproduction.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p08','Baseline Solutions Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@baselinesolutions.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p09','Crown Technologies Site Logistics','customer',0,NULL,NULL,NULL,'contact@crowntechnologies.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p10','Gateway Technologies Test Facility','customer',0,NULL,NULL,NULL,'contact@gatewaytechnologies.warehouse.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p11','Polar Engineering Quality Lab','customer',0,NULL,NULL,NULL,'contact@polarengineering.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p12','Canton Assembly Site Logistics','customer',0,NULL,NULL,NULL,'contact@cantonassembly.sourcing.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p13','Chrome Industries Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@chromeindustries.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p14','Quartz Operations Site Logistics','customer',0,NULL,NULL,NULL,'contact@quartzoperations.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p15','Sapphire Assembly Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@sapphireassembly.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p16','Eclipse Technologies Field Ops','customer',0,NULL,NULL,NULL,'contact@eclipsetechnologies.procurement.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p17','Raven Solutions Field Ops','customer',0,NULL,NULL,NULL,'contact@ravensolutions.supply-chain.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p18','Crestview Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@crestviewassembly.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p19','Ledger Manufacturing R&D Workshop','customer',0,NULL,NULL,NULL,'contact@ledgermanufacturing.sourcing.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p20','Scion Industries Prototype Shop','customer',0,NULL,NULL,NULL,'contact@scionindustries.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p21','Trident Fabrication Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@tridentfabrication.procurement.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p22','Zenith Operations Test Facility','customer',0,NULL,NULL,NULL,'contact@zenithoperations.warehouse.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p23','Ridge Operations R&D Workshop','customer',0,NULL,NULL,NULL,'contact@ridgeoperations.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p24','Garnet Services Site Logistics','customer',0,NULL,NULL,NULL,'contact@garnetservices.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p25','Apex Production Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@apexproduction.procurement.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p26','Indigo Operations R&D Workshop','customer',0,NULL,NULL,NULL,'contact@indigooperations.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p27','Ivory Fabrication Site Logistics','customer',0,NULL,NULL,NULL,'contact@ivoryfabrication.supply-chain.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p28','Cardinal Production Site Logistics','customer',0,NULL,NULL,NULL,'contact@cardinalproduction.sourcing.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p29','Westfield Services Prototype Shop','customer',0,NULL,NULL,NULL,'contact@westfieldservices.logistics.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p30','Lance Manufacturing R&D Workshop','customer',0,NULL,NULL,NULL,'contact@lancemanufacturing.ops-mail.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p31','Flint Production Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@flintproduction.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p32','Arbor Assembly Quality Lab','customer',0,NULL,NULL,NULL,'contact@arborassembly.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p33','Stratos Assembly Prototype Shop','customer',0,NULL,NULL,NULL,'contact@stratosassembly.procurement.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p34','Skyline Production R&D Workshop','customer',0,NULL,NULL,NULL,'contact@skylineproduction.logistics.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p35','Matrix Technologies Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@matrixtechnologies.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p36','Echo Services R&D Workshop','customer',0,NULL,NULL,NULL,'contact@echoservices.supply-chain.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p37','Horizon Industries Prototype Shop','customer',0,NULL,NULL,NULL,'contact@horizonindustries.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p38','Steel Manufacturing Tooling Center','customer',0,NULL,NULL,NULL,'contact@steelmanufacturing.sourcing.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p39','Riverdale Assembly R&D Workshop','customer',0,NULL,NULL,NULL,'contact@riverdaleassembly.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p40','Pacific Industries Tooling Center','customer',0,NULL,NULL,NULL,'contact@pacificindustries.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p41','Pinnacle Engineering Quality Lab','customer',0,NULL,NULL,NULL,'contact@pinnacleengineering.ops-mail.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p42','Bronze Assembly R&D Workshop','customer',0,NULL,NULL,NULL,'contact@bronzeassembly.warehouse.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p43','Monarch Operations Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@monarchoperations.ops-mail.example','Operating division account.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p44','Arc Solutions Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@arcsolutions.ops-mail.example','Regional distribution hub.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p45','Blaze Assembly Warehouse Ops','customer',0,NULL,NULL,NULL,'contact@blazeassembly.logistics.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p46','Prism Solutions Prototype Shop','customer',0,NULL,NULL,NULL,'contact@prismsolutions.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p47','Aegis Services HQ Procurement','customer',0,NULL,NULL,NULL,'contact@aegisservices.ops-mail.example','Preferred payment net-30.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p48','Cosmo Assembly Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@cosmoassembly.logistics.example','Maintenance contract on file.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p49','Copper Services Plant Maintenance','customer',0,NULL,NULL,NULL,'contact@copperservices.warehouse.example','');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,budget_dollars,credit_limit,payment_term,email,comment) VALUES('r9B59255BE3_p50','Globe Solutions Test Facility','customer',0,NULL,NULL,NULL,'contact@globesolutions.warehouse.example','Recurring quarterly orders.');
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q01','Cipher Procurement','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q02','Quantum Microfactory','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q03','Catalyst Importers','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q04','Sterling Conveyance','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q05','Sentinel Partners','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q06','Dune Shipping','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q07','Crest Supply','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q08','Peak Distributors','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q09','Millbrook Networks','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q10','Compass Consolidators','vendor',10,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q11','Summit Transit','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q12','Alpine Warehouse','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q13','Baltic Movers','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q14','Iron Merchants','vendor',14,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q15','Jade Integrators','vendor',15,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q16','Opal Forwarders','vendor',16,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q17','Velocity Industries','vendor',17,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q18','Axis Wholesalers','vendor',18,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q19','Conduit Manufacturing','vendor',19,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q20','Onyx Commodities','vendor',20,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r22B8FDBB6B_q21','Silverline Transport','vendor',21,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q01','Bridgeway Trading','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q02','Solace Parts Co','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q03','Granite Sourcing','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q04','Orbital Distribution','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q05','Aurora Sourcing','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q06','Arrow Distribution','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q07','Sierra Components','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q08','Osprey Parts Co','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q09','Pivot Carriers','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q10','Lumen Transit','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q11','Element Carriers','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q12','Flux Resources','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q13','Brookfield Trading','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q14','Hartland Logistics','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q15','Ember Wholesale','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q16','Anvil Trading','vendor',3,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q17','Helix Wholesale','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q18','Spark Logistics','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q19','Ironside Logistics','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q20','Nimbus Materials','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q21','Grove Sourcing','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q22','Ashford Resources','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q23','Coral Logistics','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q24','Borough Transit','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q25','Lattice Procurement','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q26','Cedar Materials','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q27','Circuit Parts Co','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q28','Nexus Supply','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q29','Citadel Trading','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q30','Comet Carriers','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q31','Cobalt Distribution','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q32','Bayshore Resources','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q33','Metro Freight','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q34','Titan Parts Co','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q35','Evergreen Transit','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q36','Equinox Trading','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q37','Noble Carriers','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q38','Forge Distribution','vendor',1,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q39','Clearwater Trading','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q40','Atlas Components','vendor',13,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q41','Slate Distribution','vendor',4,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q42','Ridgeline Supply','vendor',11,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q43','Mosaic Materials','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q44','Thornton Materials','vendor',8,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q45','Stonewall Freight','vendor',12,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q46','Oakmont Freight','vendor',9,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q47','Vertex Freight','vendor',2,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q48','Beacon Wholesale','vendor',5,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q49','Redstone Trading','vendor',6,NULL);
INSERT OR REPLACE INTO erpb_partners(ref,name,kind,supplier_rank,comment) VALUES('r9B59255BE3_q50','Meridian Procurement','vendor',7,NULL);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P22B8FDBB6B-PKG-LAS-007','Labeling Applicator System','Material Handling Equipment','consu',9417.62,6091.02,'buy,manufacture',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(1,'P22B8FDBB6B-PKG-LAS-007','r22B8FDBB6B_q01','Priority Shuttle lane (8d transit, 10-45 units)',8,10.0,45.0,5358.6);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(2,'P22B8FDBB6B-PKG-LAS-007','r22B8FDBB6B_q02','Express Air lane (7d transit, 2-16 units)',7,2.0,16.0,6465.11);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(3,'P22B8FDBB6B-PKG-LAS-007','r22B8FDBB6B_q03','Bulk Container lane (21d transit, 76-76 units)',21,76.0,76.0,2792.72);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(4,'P22B8FDBB6B-PKG-LAS-007','r22B8FDBB6B_q04','Regional Cross-Dock lane (17d transit, 4-6 units)',17,4.0,6.0,5506.94);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(5,'P22B8FDBB6B-PKG-LAS-007','r22B8FDBB6B_q05','Scheduled Freight lane (20d transit, 7-33 units)',20,7.0,33.0,4438.95);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P22B8FDBB6B-PKG-FRS-106','Film Roll Holder Spindle','Material Handling Equipment','consu',220.39,97.73,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(6,'P22B8FDBB6B-PKG-FRS-106','r22B8FDBB6B_q06','Rapid Works (2d)',2,7.0,29.0,153.05);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(7,'P22B8FDBB6B-PKG-FRS-106','r22B8FDBB6B_q07','Import Consolidator (2d)',2,39.0,72.0,97.73);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(8,'P22B8FDBB6B-PKG-FRS-106','r22B8FDBB6B_q08','Domestic Supply (2d)',2,13.0,36.0,128.36);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(9,'P22B8FDBB6B-PKG-FRS-106','r22B8FDBB6B_q09','Hybrid Fabricators (2d)',2,12.0,12.0,158.3);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P22B8FDBB6B-PKG-PES-108','Photoelectric Sensor Set','Material Handling Equipment','consu',96.56,35.71,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(10,'P22B8FDBB6B-PKG-PES-108','r22B8FDBB6B_q10','Rapid Works (2d)',2,12.0,155.0,46.69);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(11,'P22B8FDBB6B-PKG-PES-108','r22B8FDBB6B_q11','Import Consolidator (2d)',2,29.0,251.0,35.71);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(12,'P22B8FDBB6B-PKG-PES-108','r22B8FDBB6B_q12','Hybrid Fabricators (2d)',2,8.0,98.0,51.25);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P22B8FDBB6B-PKG-PGR-119','Product Guide Rail Set','Material Handling Equipment','consu',56.59,25.26,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(13,'P22B8FDBB6B-PKG-PGR-119','r22B8FDBB6B_q13','Rapid Works (2d)',2,8.0,51.0,33.21);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(14,'P22B8FDBB6B-PKG-PGR-119','r22B8FDBB6B_q14','Hybrid Fabricators (2d)',2,10.0,20.0,35.46);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(15,'P22B8FDBB6B-PKG-PGR-119','r22B8FDBB6B_q15','Import Consolidator (2d)',2,37.0,95.0,25.26);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P22B8FDBB6B-PKG-FTA-123','Forming Tube Assembly','Material Handling Equipment','consu',276.18,162.29,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(16,'P22B8FDBB6B-PKG-FTA-123','r22B8FDBB6B_q16','Rapid Works (2d)',2,7.0,46.0,193.93);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(17,'P22B8FDBB6B-PKG-FTA-123','r22B8FDBB6B_q17','Domestic Supply (2d)',2,16.0,19.0,192.28);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(18,'P22B8FDBB6B-PKG-FTA-123','r22B8FDBB6B_q18','Hybrid Fabricators (2d)',2,16.0,21.0,162.29);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P22B8FDBB6B-PKG-TBR-129','Turntable Bearing Ring','Material Handling Equipment','consu',214.22,97.37,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(19,'P22B8FDBB6B-PKG-TBR-129','r22B8FDBB6B_q19','Rapid Works (2d)',2,5.0,22.0,155.27);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(20,'P22B8FDBB6B-PKG-TBR-129','r22B8FDBB6B_q20','Import Consolidator (2d)',2,24.0,47.0,97.37);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(21,'P22B8FDBB6B-PKG-TBR-129','r22B8FDBB6B_q21','Domestic Supply (2d)',2,18.0,28.0,127.73);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A001','Threaded Drive Motor 2kW','Maintenance Supplies','consu',345.61,241.44,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(22,'P9B59255BE3-A001','r9B59255BE3_q01','Local pickup',4,1.0,24.0,256.25);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A002','Thermal-Guard Section 12in','Seals and Gaskets','consu',313.9,196.95,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(23,'P9B59255BE3-A002','r9B59255BE3_q02','Cross-dock',5,1.0,24.0,195.78);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A003','Low-Temp Photoelectric Sensor Set','Seals and Gaskets','consu',346.87,183.16,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(24,'P9B59255BE3-A003','r9B59255BE3_q03','Warehouse direct',8,1.0,24.0,180.76);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A004','Spring-Loaded Drive Motor 2kW','Power Transmission','consu',214.01,119.41,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(25,'P9B59255BE3-A004','r9B59255BE3_q04','Bulk shipment',8,1.0,24.0,115.1);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A005','High-Temp Controller Module','Replacement Parts','consu',260.28,149.69,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(26,'P9B59255BE3-A005','r9B59255BE3_q05','Regional lane',6,1.0,24.0,149.0);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A006','Non-Magnetic Photoelectric Sensor Set','Industrial Spare Parts','consu',398.63,224.02,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(27,'P9B59255BE3-A006','r9B59255BE3_q06','Regional lane',6,1.0,24.0,217.95);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A007','Anti-Vibration PLC Controller Module','Replacement Parts','consu',265.2,154.78,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(28,'P9B59255BE3-A007','r9B59255BE3_q07','Standard delivery',8,1.0,24.0,164.08);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A008','High-Torque Section 12in','Maintenance Supplies','consu',223.97,132.42,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(29,'P9B59255BE3-A008','r9B59255BE3_q08','Local pickup',3,1.0,24.0,135.32);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A009','Metric Sealing Jaw Assembly','Mechanical Components','consu',371.71,259.15,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(30,'P9B59255BE3-A009','r9B59255BE3_q09','Standard delivery',3,1.0,24.0,269.41);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A010','Low-Noise PLC Controller Module','Mechanical Components','consu',409.08,222.52,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(31,'P9B59255BE3-A010','r9B59255BE3_q10','Scheduled freight',6,1.0,24.0,227.27);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A011','Reinforced Photoelectric Sensor Set','Industrial Spare Parts','consu',286.3,160.43,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(32,'P9B59255BE3-A011','r9B59255BE3_q11','Express route',6,1.0,24.0,155.34);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A012','Food-Grade Pump Assembly','Mechanical Components','consu',364.81,229.41,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(33,'P9B59255BE3-A012','r9B59255BE3_q12','Cross-dock',5,1.0,24.0,230.77);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A013','Cold-Rolled Light Curtain Pair','Electrical Components','consu',320.8,180.79,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(34,'P9B59255BE3-A013','r9B59255BE3_q13','Local pickup',6,1.0,24.0,175.56);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A014','Dual-Stage Jaw Assembly','Mechanical Components','consu',402.06,274.92,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(35,'P9B59255BE3-A014','r9B59255BE3_q14','Express route',6,1.0,24.0,282.08);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A015','Industrial Vacuum Pump Assembly','Pneumatic Components','consu',242.7,161.29,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(36,'P9B59255BE3-A015','r9B59255BE3_q15','Local pickup',3,1.0,24.0,155.94);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A016','Impact-Rated Belt Section 12in','Hardware Accessories','consu',181.59,116.13,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(37,'P9B59255BE3-A016','r9B59255BE3_q16','Express route',7,1.0,24.0,123.79);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A017','Lightweight Sensor Set','Pneumatic Components','consu',252.24,160.27,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(38,'P9B59255BE3-A017','r9B59255BE3_q17','Cross-dock',6,1.0,24.0,158.1);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A018','Medical-Grade Applicator Nozzle Set','Fasteners and Fixings','consu',187.49,130.53,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(39,'P9B59255BE3-A018','r9B59255BE3_q18','Standard delivery',5,1.0,24.0,140.03);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A019','Low-Friction PLC Controller Module','Mechanical Components','consu',334.52,181.92,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(40,'P9B59255BE3-A019','r9B59255BE3_q19','Scheduled freight',3,1.0,24.0,184.65);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A020','Weatherproof Photoelectric Sensor Set','Industrial Spare Parts','consu',238.09,170.94,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(41,'P9B59255BE3-A020','r9B59255BE3_q20','Scheduled freight',3,1.0,24.0,183.19);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A021','Cleanroom PLC Controller Module','Industrial Spare Parts','consu',316.9,173.76,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(42,'P9B59255BE3-A021','r9B59255BE3_q21','Standard delivery',5,1.0,24.0,175.52);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A022','Low-Profile Panel 10in','Industrial Spare Parts','consu',193.92,104.05,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(43,'P9B59255BE3-A022','r9B59255BE3_q22','Local pickup',4,1.0,24.0,105.7);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A023','Rapid-Lock Pulley Kit','Seals and Gaskets','consu',219.65,117.02,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(44,'P9B59255BE3-A023','r9B59255BE3_q23','Cross-dock',5,1.0,24.0,118.71);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A024','Quick-Release Jaw Assembly','Pneumatic Components','consu',415.47,216.88,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(45,'P9B59255BE3-A024','r9B59255BE3_q24','Standard delivery',8,1.0,24.0,217.78);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A025','Modular Curtain Pair','Fasteners and Fixings','consu',313.22,183.36,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(46,'P9B59255BE3-A025','r9B59255BE3_q25','Cross-dock',8,1.0,24.0,178.22);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A026','Pressure-Balanced Light Curtain Pair','Hardware Accessories','consu',188.45,127.71,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(47,'P9B59255BE3-A026','r9B59255BE3_q26','Bulk shipment',6,1.0,24.0,126.62);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A027','Commercial Light Curtain Pair','Fasteners and Fixings','consu',187.87,129.96,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(48,'P9B59255BE3-A027','r9B59255BE3_q27','Express route',4,1.0,24.0,130.16);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A028','Premium Pneumatic Cylinder Assembly','Pneumatic Components','consu',244.05,145.48,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(49,'P9B59255BE3-A028','r9B59255BE3_q28','Regional lane',8,1.0,24.0,147.4);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A029','Snap-Fit Sealing Jaw Assembly','Replacement Parts','consu',275.05,156.1,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(50,'P9B59255BE3-A029','r9B59255BE3_q29','Express route',3,1.0,24.0,153.61);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A030','Double-Row Drive Motor 2kW','Replacement Parts','consu',213.72,143.07,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(51,'P9B59255BE3-A030','r9B59255BE3_q30','Express route',5,1.0,24.0,138.2);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A031','Standard HMI Panel 10in','Maintenance Supplies','consu',248.72,135.21,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(52,'P9B59255BE3-A031','r9B59255BE3_q31','Regional lane',4,1.0,24.0,141.74);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A032','Anodized Panel 10in','Fasteners and Fixings','consu',216.11,134.44,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(53,'P9B59255BE3-A032','r9B59255BE3_q32','Bulk shipment',6,1.0,24.0,137.85);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A033','Tapered Vacuum Pump Assembly','Power Transmission','consu',329.8,231.88,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(54,'P9B59255BE3-A033','r9B59255BE3_q33','Bulk shipment',3,1.0,24.0,236.96);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A034','Extended-Life PLC Controller Module','Seals and Gaskets','consu',388.02,267.3,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(55,'P9B59255BE3-A034','r9B59255BE3_q34','Warehouse direct',8,1.0,24.0,254.6);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A035','Heavy-Duty Curtain Pair','Power Transmission','consu',409.07,255.68,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(56,'P9B59255BE3-A035','r9B59255BE3_q35','Regional lane',8,1.0,24.0,261.54);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A036','Flanged Pulley Kit','Maintenance Supplies','consu',187.42,134.06,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(57,'P9B59255BE3-A036','r9B59255BE3_q36','Scheduled freight',3,1.0,24.0,141.8);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A037','Zero-Backlash Panel 10in','Replacement Parts','consu',419.14,282.1,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(58,'P9B59255BE3-A037','r9B59255BE3_q37','Local pickup',7,1.0,24.0,268.7);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A038','Narrow-Body Jaw Assembly','Industrial Spare Parts','consu',346.3,228.81,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(59,'P9B59255BE3-A038','r9B59255BE3_q38','Local pickup',5,1.0,24.0,232.64);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A039','Sealed Jaw Assembly','Maintenance Supplies','consu',348.75,222.24,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(60,'P9B59255BE3-A039','r9B59255BE3_q39','Scheduled freight',5,1.0,24.0,216.49);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A040','Adjustable Nozzle Set','Industrial Spare Parts','consu',297.38,164.4,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(61,'P9B59255BE3-A040','r9B59255BE3_q40','Cross-dock',3,1.0,24.0,157.96);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A041','Single-Stage Sensor Set','Maintenance Supplies','consu',222.74,145.58,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(62,'P9B59255BE3-A041','r9B59255BE3_q41','Cross-dock',4,1.0,24.0,144.27);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A042','UV-Stable Panel 10in','Industrial Spare Parts','consu',190.24,118.17,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(63,'P9B59255BE3-A042','r9B59255BE3_q42','Regional lane',5,1.0,24.0,123.43);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A043','High-Performance Belt Section 12in','Pneumatic Components','consu',221.07,155.73,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(64,'P9B59255BE3-A043','r9B59255BE3_q43','Bulk shipment',6,1.0,24.0,167.18);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A044','Self-Lubricating Holder Spindle','Hardware Accessories','consu',412.92,273.87,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(65,'P9B59255BE3-A044','r9B59255BE3_q44','Local pickup',8,1.0,24.0,272.03);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A045','Wide-Body Motor 2kW','Industrial Spare Parts','consu',214.28,150.74,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(66,'P9B59255BE3-A045','r9B59255BE3_q45','Bulk shipment',6,1.0,24.0,147.33);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A046','Low-Flow Roll Holder Spindle','Replacement Parts','consu',419.2,272.87,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(67,'P9B59255BE3-A046','r9B59255BE3_q46','Regional lane',3,1.0,24.0,278.26);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A047','Hardened Roll Holder Spindle','Power Transmission','consu',204.45,140.27,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(68,'P9B59255BE3-A047','r9B59255BE3_q47','Bulk shipment',3,1.0,24.0,144.42);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A048','Universal Sealing Jaw Assembly','Power Transmission','consu',315.33,212.68,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(69,'P9B59255BE3-A048','r9B59255BE3_q48','Bulk shipment',5,1.0,24.0,226.31);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A049','Stainless Sensor Set','Mechanical Components','consu',392.72,257.08,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(70,'P9B59255BE3-A049','r9B59255BE3_q49','Cross-dock',5,1.0,24.0,260.63);
INSERT OR REPLACE INTO erpb_products(code,name,category,type,list_price,standard_price,routes,comment) VALUES('P9B59255BE3-A050','Powder-Coated Photoelectric Sensor Set','Replacement Parts','consu',311.86,198.76,'buy',NULL);
INSERT INTO erpb_vendor_offers(id,product_code,partner_ref,name,delay,min_qty,max_qty,price) VALUES(71,'P9B59255BE3-A050','r9B59255BE3_q50','Express route',7,1.0,24.0,209.87);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(1,'P22B8FDBB6B-PKG-LAS-007','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P22B8FDBB6B-PKG-FRS-106',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P22B8FDBB6B-PKG-PES-108',4.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P22B8FDBB6B-PKG-PGR-119',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P22B8FDBB6B-PKG-FTA-123',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(1,'P22B8FDBB6B-PKG-TBR-129',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(2,'P9B59255BE3-A003','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P9B59255BE3-A049',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(2,'P9B59255BE3-A027',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(3,'P9B59255BE3-A041','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P9B59255BE3-A016',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(3,'P9B59255BE3-A037',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(4,'P9B59255BE3-A025','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'P9B59255BE3-A014',2.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(4,'P9B59255BE3-A006',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(5,'P9B59255BE3-A005','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(5,'P9B59255BE3-A039',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(6,'P9B59255BE3-A043','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P9B59255BE3-A007',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(6,'P9B59255BE3-A028',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(7,'P9B59255BE3-A034','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(7,'P9B59255BE3-A027',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(8,'P9B59255BE3-A042','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(8,'P9B59255BE3-A013',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(9,'P9B59255BE3-A044','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(9,'P9B59255BE3-A012',1.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(10,'P9B59255BE3-A013','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P9B59255BE3-A041',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(10,'P9B59255BE3-A027',3.0);
INSERT INTO erpb_boms(id,product_code,type,quantity,warehouse_code) VALUES(11,'P9B59255BE3-A032','normal',1.0,NULL);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'P9B59255BE3-A041',1.0);
INSERT INTO erpb_bom_components(bom_id,component_code,quantity) VALUES(11,'P9B59255BE3-A002',1.0);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P22B8FDBB6B-WC01','Assembly Line 1',0,0,NULL,NULL);
INSERT OR REPLACE INTO erpb_workcenters(code,name,capacity_per_day,cost_per_hour,warehouse_code,comment) VALUES('P22B8FDBB6B-WC02','Fabrication Cell 2',0,0,NULL,NULL);
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P22B8FDBB6B-PKG-FRS-106',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P22B8FDBB6B-PKG-FTA-123',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P22B8FDBB6B-PKG-LAS-007',NULL,70.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P22B8FDBB6B-PKG-PES-108',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P22B8FDBB6B-PKG-PGR-119',NULL,19.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P22B8FDBB6B-PKG-TBR-129',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A001',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A002',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A003',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A004',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A005',NULL,14.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A006',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A007',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A008',NULL,9.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A009',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A010',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A011',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A012',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A013',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A014',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A015',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A016',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A017',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A018',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A019',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A020',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A021',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A022',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A023',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A024',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A025',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A026',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A027',NULL,4.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A028',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A029',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A030',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A031',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A032',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A033',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A034',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A035',NULL,6.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A036',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A037',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A038',NULL,11.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A039',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A040',NULL,13.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A041',NULL,7.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A042',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A043',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A044',NULL,8.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A045',NULL,10.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A046',NULL,15.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A047',NULL,5.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A048',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A049',NULL,12.0,'stock');
INSERT INTO erpb_stock(product_code,warehouse_code,quantity,location_type) VALUES('P9B59255BE3-A050',NULL,4.0,'stock');

INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(1,'r22B8FDBB6B_c01','P22B8FDBB6B-PKG-LAS-007',14,8,114112.83,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(2,'r22B8FDBB6B_c02','P22B8FDBB6B-PKG-LAS-007',15,10,147849.8,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(3,'r22B8FDBB6B_c03','P22B8FDBB6B-PKG-LAS-007',17,11,177622.51,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(4,'r22B8FDBB6B_c04','P22B8FDBB6B-PKG-LAS-007',14,11,138307.83,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(5,'r22B8FDBB6B_c05','P22B8FDBB6B-PKG-LAS-007',15,13,157717.95,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(6,'r22B8FDBB6B_c06','P22B8FDBB6B-PKG-LAS-007',15,13,151142.57,'draft');
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(7,'r22B8FDBB6B_c07','P22B8FDBB6B-PKG-LAS-007',21,13,212008.03,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(8,'r22B8FDBB6B_c08','P22B8FDBB6B-PKG-LAS-007',19,14,183089.13,NULL);
INSERT INTO erpb_demand(id,partner_ref,product_code,units,due_days,budget_cap,seeded_order_state) VALUES(9,'r22B8FDBB6B_c09','P22B8FDBB6B-PKG-LAS-007',23,14,234947.0,NULL);
